openapi: 3.1.0
info:
  title: PI_21047
  version: '202604'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: c7b88c733e93fe4ee423d52cffa2cd8f312574ea
components:
  schemas:
    PI_21047:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_21047__stammdaten'
        transaktionsdaten:
          $ref: '#/components/schemas/PI_21047__transaktionsdaten'
      required:
        - stammdaten
        - transaktionsdaten
    PI_21047__stammdaten:
      type: object
      properties:
        STATUSMITTEILUNG:
          type: array
          items:
            $ref: '#/components/schemas/PI_21047__stammdaten__STATUSMITTEILUNG'
      required:
        - STATUSMITTEILUNG
    PI_21047__stammdaten__STATUSMITTEILUNG:
      type: object
      properties:
        auftragsstatus:
          $ref: '../../../bo4e/fields/bo/Statusmitteilung/auftragsstatus.yaml#/components/schemas/auftragsstatus'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z43
        positionsdaten:
          type: array
          items:
            $ref: '#/components/schemas/PI_21047__stammdaten__STATUSMITTEILUNG__positionsdaten'
        statusObjekt:
          $ref: '../../../bo4e/fields/bo/Statusmitteilung/statusObjekt.yaml#/components/schemas/statusObjekt'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z43
      required:
        - auftragsstatus
        - positionsdaten
        - statusObjekt
    PI_21047__stammdaten__STATUSMITTEILUNG__positionsdaten:
      type: object
      properties:
        allgemeineInformationen:
          $ref: '#/components/schemas/PI_21047__stammdaten__STATUSMITTEILUNG__positionsdaten__allgemeineInformationen'
        positionsnummer:
          $ref: '../../../bo4e/fields/com/StatusmitteilungPosition/positionsnummer.yaml#/components/schemas/positionsnummer'
          x-edifact-segment:
            - SG14.CNI
      required:
        - allgemeineInformationen
        - positionsnummer
    PI_21047__stammdaten__STATUSMITTEILUNG__positionsdaten__allgemeineInformationen:
      type: object
      properties:
        info1:
          $ref: '../../../bo4e/fields/com/AllgemeineInformationen/info1.yaml#/components/schemas/info1'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z43.SG25.GID.FTX+ACB
        info2:
          $ref: '../../../bo4e/fields/com/AllgemeineInformationen/info2.yaml#/components/schemas/info2'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z43.SG25.GID.FTX+ACB
        info3:
          $ref: '../../../bo4e/fields/com/AllgemeineInformationen/info3.yaml#/components/schemas/info3'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z43.SG25.GID.FTX+ACB
        info4:
          $ref: '../../../bo4e/fields/com/AllgemeineInformationen/info4.yaml#/components/schemas/info4'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z43.SG25.GID.FTX+ACB
        info5:
          $ref: '../../../bo4e/fields/com/AllgemeineInformationen/info5.yaml#/components/schemas/info5'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z43.SG25.GID.FTX+ACB
      required:
        - info1
        - info2
        - info3
        - info4
        - info5
    PI_21047__transaktionsdaten:
      type: object
      properties:
        absender:
          $ref: '#/components/schemas/PI_21047__transaktionsdaten__absender'
        antwortstatus:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/antwortstatus.yaml#/components/schemas/antwortstatus'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z43
        antwortstatusCodeliste:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/antwortstatusCodeliste.yaml#/components/schemas/antwortstatusCodeliste'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z43
        dokumentennummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/dokumentennummer.yaml#/components/schemas/dokumentennummer'
          x-edifact-segment:
            - BGM+Z33
        empfaenger:
          $ref: '#/components/schemas/PI_21047__transaktionsdaten__empfaenger'
        nachrichtendatum:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtendatum.yaml#/components/schemas/nachrichtendatum'
          x-edifact-segment:
            - DTM+137
        nachrichtenreferenznummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtenreferenznummer.yaml#/components/schemas/nachrichtenreferenznummer'
          x-edifact-segment:
            - UNH
        pruefidentifikator:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/pruefidentifikator.yaml#/components/schemas/pruefidentifikator'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z43.RFF+Z13
        sendungsposition:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/sendungsposition.yaml#/components/schemas/sendungsposition'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z43.SG25.GID
        vorgangsreferenznummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/vorgangsreferenznummer.yaml#/components/schemas/vorgangsreferenznummer'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z43.RFF+ACW
      required:
        - absender
        - antwortstatus
        - antwortstatusCodeliste
        - dokumentennummer
        - empfaenger
        - nachrichtendatum
        - nachrichtenreferenznummer
        - pruefidentifikator
        - sendungsposition
        - vorgangsreferenznummer
    PI_21047__transaktionsdaten__absender:
      type: object
      properties:
        ansprechpartner:
          $ref: '#/components/schemas/PI_21047__transaktionsdaten__absender__ansprechpartner'
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG1.NAD+MS
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG1.NAD+MS
      required:
        - ansprechpartner
        - rollencodenummer
        - rollencodetyp
    PI_21047__transaktionsdaten__absender__ansprechpartner:
      type: object
      properties:
        eMailAdresse:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/eMailAdresse.yaml#/components/schemas/eMailAdresse'
          x-edifact-segment:
            - 'SG1.NAD+MS.SG2.CTA+IC.COM+[EM|FX|TE|AJ|AL]'
        nachname:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/nachname.yaml#/components/schemas/nachname'
          x-edifact-segment:
            - SG1.NAD+MS.SG2.CTA+IC
        rufnummern:
          type: array
          items:
            $ref: '#/components/schemas/PI_21047__transaktionsdaten__absender__ansprechpartner__rufnummern'
      required:
        - eMailAdresse
        - nachname
        - rufnummern
    PI_21047__transaktionsdaten__absender__ansprechpartner__rufnummern:
      type: object
      properties:
        nummerntyp:
          $ref: '../../../bo4e/fields/com/Rufnummer/nummerntyp.yaml#/components/schemas/nummerntyp'
          x-edifact-segment:
            - 'SG1.NAD+MS.SG2.CTA+IC.COM+[EM|FX|TE|AJ|AL]'
        rufnummer:
          $ref: '../../../bo4e/fields/com/Rufnummer/rufnummer.yaml#/components/schemas/rufnummer'
          x-edifact-segment:
            - 'SG1.NAD+MS.SG2.CTA+IC.COM+[EM|FX|TE|AJ|AL]'
      required:
        - nummerntyp
        - rufnummer
    PI_21047__transaktionsdaten__empfaenger:
      type: object
      properties:
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG1.NAD+MR
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG1.NAD+MR
      required:
        - rollencodenummer
        - rollencodetyp
