openapi: 3.1.0
info:
  title: '[MSB] START_VERSAND_ANF_STORNO'
  version: '202610'
  x-bpmn-source-sha: aa74db2c
  x-bo4e-schema-version: 1.7.1
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    '[MSB] START_VERSAND_ANF_STORNO':
      type: object
      required:
      - masterData
      - transactionData
      - additionalData
      properties:
        transactionData:
          type: object
          required:
          - sender
          - receiver
          - freeText
          - category
          - sector
          - processReferenceNumber
          properties:
            sender:
              type: object
              properties:
                roleCodeNumber:
                  $ref: ../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
            receiver:
              type: object
              properties:
                roleCodeNumber:
                  $ref: ../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
            freeText:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/freeText.yaml#/components/schemas/freeText
            category:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/category.yaml#/components/schemas/category
            sector:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/sector.yaml#/components/schemas/sector
            processReferenceNumber:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/processReferenceNumber.yaml#/components/schemas/processReferenceNumber
            verificationIdentifier:
              description: Wird dynamisch im Event-Prozess ermittelt (Sparte + Transaktionsgrund + Empfänger-Marktrolle). Ein vom Sender mitgegebener Wert wird ignoriert. Im Topic mögliche Prüfis — 55022.
              examples:
              - '55022'
        additionalData:
          type: object
          required:
          - processId
          - eventname
          properties:
            processId:
              type: string
            eventname:
              type: string
              const: START_VERSAND_ANF_STORNO
              default: START_DISPATCH_REQUEST_CANCELLATION
      x-pending-pruefis:
      - '55022'
