openapi: 3.1.0
info:
  title: PI_19015
  version: '202604'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_19015:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_19015__masterData'
      required:
      - masterData
    PI_19015__masterData:
      type: object
      properties:
        ORDER:
          type: array
          items:
            $ref: '#/components/schemas/PI_19015__masterData__ORDER'
      required:
      - ORDER
    PI_19015__masterData__ORDER:
      type: object
      properties:
        deliveryAddressOldDevices:
          $ref: '#/components/schemas/PI_19015__masterData__ORDER__deliveryAddressOldDevices'
      required:
      - deliveryAddressOldDevices
    PI_19015__masterData__ORDER__deliveryAddressOldDevices:
      type: object
      properties:
        salutation:
          $ref: ../../../bo4e-en/fields/bo/BusinessPartner/salutation.yaml#/components/schemas/salutation
          x-edifact-segment:
          - SG3.NAD+Z22
        commercialClassification:
          $ref: ../../../bo4e-en/fields/bo/BusinessPartner/commercialClassification.yaml#/components/schemas/commercialClassification
          x-edifact-segment:
          - SG3.NAD+Z22
        name1:
          $ref: ../../../bo4e-en/fields/bo/BusinessPartner/name1.yaml#/components/schemas/name1
          x-edifact-segment:
          - SG3.NAD+Z22
        name2:
          $ref: ../../../bo4e-en/fields/bo/BusinessPartner/name2.yaml#/components/schemas/name2
          x-edifact-segment:
          - SG3.NAD+Z22
        name3:
          $ref: ../../../bo4e-en/fields/bo/BusinessPartner/name3.yaml#/components/schemas/name3
          x-edifact-segment:
          - SG3.NAD+Z22
        name4:
          $ref: ../../../bo4e-en/fields/bo/BusinessPartner/name4.yaml#/components/schemas/name4
          x-edifact-segment:
          - SG3.NAD+Z22
        partnerAddress:
          $ref: '#/components/schemas/PI_19015__masterData__ORDER__deliveryAddressOldDevices__partnerAddress'
      required:
      - salutation
      - commercialClassification
      - name1
      - name2
      - name3
      - name4
      - partnerAddress
    PI_19015__masterData__ORDER__deliveryAddressOldDevices__partnerAddress:
      type: object
      properties:
        houseNumber:
          $ref: ../../../bo4e-en/fields/com/Address/houseNumber.yaml#/components/schemas/houseNumber
          x-edifact-segment:
          - SG3.NAD+Z22
        countryCode:
          $ref: ../../../bo4e-en/fields/com/Address/countryCode.yaml#/components/schemas/countryCode
          x-edifact-segment:
          - SG3.NAD+Z22
        city:
          $ref: ../../../bo4e-en/fields/com/Address/city.yaml#/components/schemas/city
          x-edifact-segment:
          - SG3.NAD+Z22
        district:
          $ref: ../../../bo4e-en/fields/com/Address/district.yaml#/components/schemas/district
          x-edifact-segment:
          - SG3.NAD+Z22
        poBox:
          $ref: ../../../bo4e-en/fields/com/Address/poBox.yaml#/components/schemas/poBox
          x-edifact-segment:
          - SG3.NAD+Z22
        postalCode:
          $ref: ../../../bo4e-en/fields/com/Address/postalCode.yaml#/components/schemas/postalCode
          x-edifact-segment:
          - SG3.NAD+Z22
        street:
          $ref: ../../../bo4e-en/fields/com/Address/street.yaml#/components/schemas/street
          x-edifact-segment:
          - SG3.NAD+Z22
      required:
      - houseNumber
      - countryCode
      - city
      - district
      - poBox
      - postalCode
      - street
