openapi: 3.1.0
info:
  title: PI_25008
  version: '202510'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_25008:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_25008__stammdaten'
        transaktionsdaten:
          $ref: '#/components/schemas/PI_25008__transaktionsdaten'
      required:
        - stammdaten
        - transaktionsdaten
    PI_25008__stammdaten:
      type: object
      properties:
        SCHALTZEITDEFINITION:
          type: array
          items:
            $ref: '#/components/schemas/PI_25008__stammdaten__SCHALTZEITDEFINITION'
      required:
        - SCHALTZEITDEFINITION
    PI_25008__stammdaten__SCHALTZEITDEFINITION:
      type: object
      properties:
        beginndatum:
          $ref: '../../../bo4e/fields/bo/Schaltzeitdefinition/beginndatum.yaml#/components/schemas/beginndatum'
          x-edifact-segment:
            - SG5.IDE+24.DTM+Z34
        code:
          $ref: '../../../bo4e/fields/bo/Schaltzeitdefinition/code.yaml#/components/schemas/code'
          x-edifact-segment:
            - SG5.IDE+24.LOC+Z09
        endedatum:
          $ref: '../../../bo4e/fields/bo/Schaltzeitdefinition/endedatum.yaml#/components/schemas/endedatum'
          x-edifact-segment:
            - SG5.IDE+24.DTM+Z35
        schaltzeiten:
          type: array
          items:
            $ref: '#/components/schemas/PI_25008__stammdaten__SCHALTZEITDEFINITION__schaltzeiten'
        version:
          $ref: '../../../bo4e/fields/bo/Schaltzeitdefinition/version.yaml#/components/schemas/version'
          x-edifact-segment:
            - SG5.IDE+24.DTM+293
      required:
        - beginndatum
        - code
        - schaltzeiten
        - version
    PI_25008__stammdaten__SCHALTZEITDEFINITION__schaltzeiten:
      type: object
      properties:
        aenderungszeitpunkt:
          $ref: '../../../bo4e/fields/com/Schaltzeit/aenderungszeitpunkt.yaml#/components/schemas/aenderungszeitpunkt'
          x-edifact-segment:
            - SG5.IDE+24.SG8.SEQ+Z73.DTM+Z44
        haeufigkeit:
          $ref: '../../../bo4e/fields/com/Schaltzeit/haeufigkeit.yaml#/components/schemas/haeufigkeit'
          x-edifact-segment:
            - SG5.IDE+24.SG8.SEQ+Z73.DTM+Z44
        schalthandlung:
          $ref: '../../../bo4e/fields/com/Schaltzeit/schalthandlung.yaml#/components/schemas/schalthandlung'
          x-edifact-segment:
            - SG5.IDE+24.SG8.SEQ+Z73.SG9.CCI+Z58
      required:
        - aenderungszeitpunkt
        - haeufigkeit
        - schalthandlung
    PI_25008__transaktionsdaten:
      type: object
      properties:
        absender:
          $ref: '#/components/schemas/PI_25008__transaktionsdaten__absender'
        anfrageReferenz:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/anfrageReferenz.yaml#/components/schemas/anfrageReferenz'
          x-edifact-segment:
            - SG5.IDE+24.SG6.RFF+AGI
        dokumentennummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/dokumentennummer.yaml#/components/schemas/dokumentennummer'
          x-edifact-segment:
            - BGM+Z80
        empfaenger:
          $ref: '#/components/schemas/PI_25008__transaktionsdaten__empfaenger'
        nachrichtendatum:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtendatum.yaml#/components/schemas/nachrichtendatum'
          x-edifact-segment:
            - DTM+137
        nachrichtenreferenznummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtenreferenznummer.yaml#/components/schemas/nachrichtenreferenznummer'
          x-edifact-segment:
            - UNH
        pruefidentifikator:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/pruefidentifikator.yaml#/components/schemas/pruefidentifikator'
          x-edifact-segment:
            - SG5.IDE+24.SG6.RFF+Z13
        vorgangsnummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/vorgangsnummer.yaml#/components/schemas/vorgangsnummer'
          x-edifact-segment:
            - SG5.IDE+24
      required:
        - absender
        - anfrageReferenz
        - dokumentennummer
        - empfaenger
        - nachrichtendatum
        - nachrichtenreferenznummer
        - pruefidentifikator
        - vorgangsnummer
    PI_25008__transaktionsdaten__absender:
      type: object
      properties:
        ansprechpartner:
          $ref: '#/components/schemas/PI_25008__transaktionsdaten__absender__ansprechpartner'
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+MS
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+MS
      required:
        - ansprechpartner
        - rollencodenummer
        - rollencodetyp
    PI_25008__transaktionsdaten__absender__ansprechpartner:
      type: object
      properties:
        eMailAdresse:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/eMailAdresse.yaml#/components/schemas/eMailAdresse'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG3.CTA+IC.COM+[EM|FX|TE|AJ|AL]'
        nachname:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/nachname.yaml#/components/schemas/nachname'
          x-edifact-segment:
            - SG2.NAD+MS.SG3.CTA+IC
        rufnummern:
          type: array
          items:
            $ref: '#/components/schemas/PI_25008__transaktionsdaten__absender__ansprechpartner__rufnummern'
      required:
        - eMailAdresse
        - nachname
        - rufnummern
    PI_25008__transaktionsdaten__absender__ansprechpartner__rufnummern:
      type: object
      properties:
        nummerntyp:
          $ref: '../../../bo4e/fields/com/Rufnummer/nummerntyp.yaml#/components/schemas/nummerntyp'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG3.CTA+IC.COM+[EM|FX|TE|AJ|AL]'
        rufnummer:
          $ref: '../../../bo4e/fields/com/Rufnummer/rufnummer.yaml#/components/schemas/rufnummer'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG3.CTA+IC.COM+[EM|FX|TE|AJ|AL]'
      required:
        - nummerntyp
        - rufnummer
    PI_25008__transaktionsdaten__empfaenger:
      type: object
      properties:
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+MR
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+MR
      required:
        - rollencodenummer
        - rollencodetyp
