openapi: 3.1.0
info:
  title: PI_13017
  version: '202504'
  x-bo4e-schema-version: 1.6.5
  x-bo4e-schema-sha: 95f07d974cf2dc738ca248b258d6589025614cb0
  x-templater-sha: 6e98aaa8818d7b01b16786b130d743ea57fa960a
components:
  schemas:
    PI_13017:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_13017__stammdaten'
      required:
        - stammdaten
    PI_13017__stammdaten:
      type: object
      properties:
        ENERGIEMENGE:
          type: array
          items:
            $ref: '#/components/schemas/PI_13017__stammdaten__ENERGIEMENGE'
        ZAEHLER:
          type: array
          items:
            $ref: '#/components/schemas/PI_13017__stammdaten__ZAEHLER'
      required:
        - ENERGIEMENGE
        - ZAEHLER
    PI_13017__stammdaten__ENERGIEMENGE:
      type: object
      properties:
        konfiguration:
          $ref: '../../../bo4e/fields/bo/Energiemenge/konfiguration.yaml#/components/schemas/konfiguration'
          x-edifact-segment:
            - SG5.NAD+DP.SG6.LOC+172
            - SG5.NAD+DP.SG6.LOC+172.SG7.RFF+AGK
        lokationsId:
          $ref: '../../../bo4e/fields/bo/Energiemenge/lokationsId.yaml#/components/schemas/lokationsId'
          x-edifact-segment:
            - SG5.NAD+DP.SG6.LOC+172
      required:
        - konfiguration
        - lokationsId
    PI_13017__stammdaten__ZAEHLER:
      type: object
      properties:
        zaehlernummer:
          $ref: '../../../bo4e/fields/bo/Zaehler/zaehlernummer.yaml#/components/schemas/zaehlernummer'
          x-edifact-segment:
            - SG5.NAD+DP.SG6.LOC+172.SG7.RFF+MG
      required:
        - zaehlernummer
