openapi: 3.1.0
info:
  title: '[LF] START_ANFRAGE_STAMMDATEN_MALO'
  version: '202604'
  x-bpmn-source-sha: 3a7c8fc1
  x-bo4e-schema-version: 1.7.1
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    '[LF] START_ANFRAGE_STAMMDATEN_MALO':
      type: object
      required:
        - stammdaten
        - transaktionsdaten
        - zusatzdaten
      properties:
        stammdaten:
          oneOf:
            - $ref: ../../event-bauteil/202604/ORDERS/PI_17101.yaml#/components/schemas/PI_17101__stammdaten
        transaktionsdaten:
          type: object
          required:
            - absender
            - empfaenger
            - kategorie
            - sparte
          properties:
            absender:
              type: object
              properties:
                rollencodenummer:
                  $ref: ../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer
            empfaenger:
              type: object
              properties:
                rollencodenummer:
                  $ref: ../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer
            kategorie:
              $ref: ../../bo4e/fields/cdoc/Transaktionsdaten/kategorie.yaml#/components/schemas/kategorie
            sparte:
              $ref: ../../bo4e/fields/cdoc/Transaktionsdaten/sparte.yaml#/components/schemas/sparte
            pruefidentifikator:
              description: Wird dynamisch im Event-Prozess ermittelt (Sparte + Transaktionsgrund + Empfänger-Marktrolle). Ein vom Sender mitgegebener Wert wird ignoriert. Im Topic mögliche Prüfis — 17101.
              examples:
                - '17101'
        zusatzdaten:
          type: object
          required:
            - prozessId
            - eventname
          properties:
            prozessId:
              type: string
            eventname:
              type: string
              const: START_ANFRAGE_STAMMDATEN_MALO
              default: START_ANFRAGE_STAMMDATEN_MALO
