openapi: 3.1.0
info:
  title: '[LF] START_BESTELLUNG_STDAE_MALO_AN_MSB'
  version: '202604'
  x-bpmn-source-sha: '36717036'
  x-bo4e-schema-version: 1.6.5
  x-templater-sha: 6e98aaa8818d7b01b16786b130d743ea57fa960a
components:
  schemas:
    '[LF] START_BESTELLUNG_STDAE_MALO_AN_MSB':
      type: object
      required:
      - stammdaten
      - transaktionsdaten
      - zusatzdaten
      properties:
        stammdaten:
          oneOf:
          - $ref: ../../event-bauteil/202604/UTILMD/PI_55655.yaml#/components/schemas/PI_55655__stammdaten
        transaktionsdaten:
          allOf:
          - $ref: ../../bo4e/cdoc/Transaktionsdaten.yaml#/components/schemas/Transaktionsdaten
          - type: object
            required:
            - absender
            - empfaenger
            - kategorie
            - sparte
            - transaktionsgrund
            - transaktionsgrundergaenzung
            properties:
              pruefidentifikator:
                description: Wird dynamisch im Event-Prozess ermittelt (Sparte + Transaktionsgrund + Empfänger-Marktrolle). Ein vom Sender mitgegebener Wert wird ignoriert. Im Topic mögliche Prüfis — 55655.
                examples:
                - '55655'
        zusatzdaten:
          type: object
          required:
          - prozessId
          - eventname
          properties:
            prozessId:
              type: string
            eventname:
              type: string
              const: START_BESTELLUNG_STDAE_MALO_AN_MSB
              default: START_BESTELLUNG_STDAE_MALO_AN_MSB
