openapi: 3.1.0
info:
  title: '[LF] START_LIEFERENDE'
  version: '202604'
  x-bpmn-source-sha: 3a7c8fc1
  x-bo4e-schema-version: 1.7.0
  x-templater-sha: 39ae45d481e5cc3d4d7aae328a23a9751236156a
components:
  schemas:
    '[LF] START_LIEFERENDE':
      type: object
      required:
        - stammdaten
        - transaktionsdaten
        - zusatzdaten
      properties:
        stammdaten:
          oneOf:
            - $ref: ../../event-bauteil/202604/UTILMD_GAS/PI_44004.yaml#/components/schemas/PI_44004__stammdaten
            - $ref: ../../event-bauteil/202604/UTILMD/PI_55004.yaml#/components/schemas/PI_55004__stammdaten
        transaktionsdaten:
          type: object
          required:
            - absender
            - empfaenger
            - freitext
            - kategorie
            - sparte
            - transaktionsgrund
            - transaktionsgrundergaenzung
          properties:
            absender:
              type: object
              properties:
                rollencodenummer:
                  $ref: ../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer
            empfaenger:
              type: object
              properties:
                marktrolle:
                  $ref: ../../bo4e/fields/bo/Marktteilnehmer/marktrolle.yaml#/components/schemas/marktrolle
                rollencodenummer:
                  $ref: ../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer
            freitext:
              $ref: ../../bo4e/fields/cdoc/Transaktionsdaten/freitext.yaml#/components/schemas/freitext
            kategorie:
              $ref: ../../bo4e/fields/cdoc/Transaktionsdaten/kategorie.yaml#/components/schemas/kategorie
            sparte:
              $ref: ../../bo4e/fields/cdoc/Transaktionsdaten/sparte.yaml#/components/schemas/sparte
            transaktionsgrund:
              $ref: ../../bo4e/fields/cdoc/Transaktionsdaten/transaktionsgrund.yaml#/components/schemas/transaktionsgrund
            transaktionsgrundergaenzung:
              $ref: ../../bo4e/fields/cdoc/Transaktionsdaten/transaktionsgrundergaenzung.yaml#/components/schemas/transaktionsgrundergaenzung
            pruefidentifikator:
              description: Wird dynamisch im Event-Prozess ermittelt (Sparte + Transaktionsgrund + Empfänger-Marktrolle). Ein vom Sender mitgegebener Wert wird ignoriert. Im Topic mögliche Prüfis — 44004, 55004.
              examples:
                - '44004'
                - '55004'
        zusatzdaten:
          type: object
          required:
            - prozessId
            - eventname
          properties:
            prozessId:
              type: string
            eventname:
              type: string
              const: START_LIEFERENDE
              default: START_LIEFERENDE
