openapi: 3.1.0
info:
  title: PI_55691
  version: '202604'
  x-bo4e-schema-version: 1.6.8
  x-bo4e-schema-sha: b84d59c01638e348fe912e388cf7b7a25ab9937f
  x-templater-sha: ce089a840512efbac03c3b3e949ad6e8b7215947
components:
  schemas:
    PI_55691:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55691__stammdaten'
      required:
        - stammdaten
    PI_55691__stammdaten:
      type: object
      properties:
        MARKTLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_55691__stammdaten__MARKTLOKATION'
        VERWENDUNGSZEITRAUM:
          type: array
          items:
            $ref: '#/components/schemas/PI_55691__stammdaten__VERWENDUNGSZEITRAUM'
      required:
        - MARKTLOKATION
        - VERWENDUNGSZEITRAUM
    PI_55691__stammdaten__MARKTLOKATION:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Marktlokation/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z01
        marktlokationsId:
          $ref: '../../../bo4e/fields/bo/Marktlokation/marktlokationsId.yaml#/components/schemas/marktlokationsId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z16
        paketId:
          $ref: '../../../bo4e/fields/bo/Marktlokation/paketId.yaml#/components/schemas/paketId'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+Z67
      required:
        - datenqualitaet
        - marktlokationsId
        - paketId
    PI_55691__stammdaten__VERWENDUNGSZEITRAUM:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53]'
        verwendungAb:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungAb.yaml#/components/schemas/verwendungAb'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53].DTM+Z25'
      required:
        - datenqualitaet
        - verwendungAb
