openapi: 3.1.0
info:
  title: PI_55177
  version: '202604'
  x-bo4e-schema-version: 1.6.5
  x-bo4e-schema-sha: 95f07d974cf2dc738ca248b258d6589025614cb0
  x-templater-sha: 6e98aaa8818d7b01b16786b130d743ea57fa960a
components:
  schemas:
    PI_55177:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55177__stammdaten'
      required:
        - stammdaten
    PI_55177__stammdaten:
      type: object
      properties:
        LOKATIONSBUENDEL:
          type: array
          items:
            $ref: '#/components/schemas/PI_55177__stammdaten__LOKATIONSBUENDEL'
        MARKTLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_55177__stammdaten__MARKTLOKATION'
        MESSLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_55177__stammdaten__MESSLOKATION'
        NETZLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_55177__stammdaten__NETZLOKATION'
        STEUERBARE_RESSOURCE:
          type: array
          items:
            $ref: '#/components/schemas/PI_55177__stammdaten__STEUERBARE_RESSOURCE'
        TECHNISCHE_RESSOURCE:
          type: array
          items:
            $ref: '#/components/schemas/PI_55177__stammdaten__TECHNISCHE_RESSOURCE'
        VERWENDUNGSZEITRAUM:
          type: array
          items:
            $ref: '#/components/schemas/PI_55177__stammdaten__VERWENDUNGSZEITRAUM'
      required:
        - LOKATIONSBUENDEL
        - MARKTLOKATION
        - MESSLOKATION
        - NETZLOKATION
        - STEUERBARE_RESSOURCE
        - TECHNISCHE_RESSOURCE
        - VERWENDUNGSZEITRAUM
    PI_55177__stammdaten__LOKATIONSBUENDEL:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Lokationsbuendel/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZC7|ZC8]'
            - 'SG4.IDE+24.SG8.SEQ+[ZC9|ZD0]'
        gueltigkeitszeitraum:
          $ref: '#/components/schemas/PI_55177__stammdaten__LOKATIONSBUENDEL__gueltigkeitszeitraum'
        lokationsbuendelNummer:
          $ref: '../../../bo4e/fields/bo/Lokationsbuendel/lokationsbuendelNummer.yaml#/components/schemas/lokationsbuendelNummer'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZC7|ZC8].RFF+[Z31|Z39]'
        lokationsbuendelstrukturId:
          $ref: '../../../bo4e/fields/bo/Lokationsbuendel/lokationsbuendelstrukturId.yaml#/components/schemas/lokationsbuendelstrukturId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZC7|ZC8].RFF+[Z31|Z39]'
        standardisierteLokationsbuendelstruktur:
          $ref: '../../../bo4e/fields/bo/Lokationsbuendel/standardisierteLokationsbuendelstruktur.yaml#/components/schemas/standardisierteLokationsbuendelstruktur'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZC7|ZC8].RFF+[Z31|Z39]'
        zuordnungObjectcode:
          type: array
          items:
            $ref: '#/components/schemas/PI_55177__stammdaten__LOKATIONSBUENDEL__zuordnungObjectcode'
      required:
        - datenqualitaet
        - gueltigkeitszeitraum
        - lokationsbuendelNummer
        - lokationsbuendelstrukturId
        - standardisierteLokationsbuendelstruktur
        - zuordnungObjectcode
    PI_55177__stammdaten__LOKATIONSBUENDEL__gueltigkeitszeitraum:
      type: object
      properties:
        zeitraumId:
          $ref: '../../../bo4e/fields/com/Zeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZC7|ZC8]'
            - 'SG4.IDE+24.SG8.SEQ+[ZC9|ZD0]'
      required:
        - zeitraumId
    PI_55177__stammdaten__LOKATIONSBUENDEL__zuordnungObjectcode:
      type: object
      properties:
        objectcode:
          type: array
          items:
            $ref: '#/components/schemas/PI_55177__stammdaten__LOKATIONSBUENDEL__zuordnungObjectcode__objectcode'
        referenzLokationsId:
          $ref: '../../../bo4e/fields/com/ZuordnungObjectcode/referenzLokationsId.yaml#/components/schemas/referenzLokationsId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZC9|ZD0].RFF+[Z32|Z18|Z19|Z37]'
        referenzLokationsTyp:
          $ref: '../../../bo4e/fields/com/ZuordnungObjectcode/referenzLokationsTyp.yaml#/components/schemas/referenzLokationsTyp'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZC9|ZD0].RFF+[Z32|Z18|Z19|Z37]'
        referenzMarktlokationTechnischeRessource:
          $ref: '../../../bo4e/fields/com/ZuordnungObjectcode/referenzMarktlokationTechnischeRessource.yaml#/components/schemas/referenzMarktlokationTechnischeRessource'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZC9|ZD0].RFF+Z16'
        vorgelagerteLokationId:
          $ref: '../../../bo4e/fields/com/ZuordnungObjectcode/vorgelagerteLokationId.yaml#/components/schemas/vorgelagerteLokationId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZC9|ZD0].RFF+[Z34|Z35]'
        vorgelagerteLokationTyp:
          $ref: '../../../bo4e/fields/com/ZuordnungObjectcode/vorgelagerteLokationTyp.yaml#/components/schemas/vorgelagerteLokationTyp'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZC9|ZD0].RFF+[Z34|Z35]'
      required:
        - objectcode
        - referenzLokationsId
        - referenzLokationsTyp
    PI_55177__stammdaten__LOKATIONSBUENDEL__zuordnungObjectcode__objectcode:
      type: object
      properties:
        lokationsbuendelNummer:
          $ref: '../../../bo4e/fields/com/Objectcode/lokationsbuendelNummer.yaml#/components/schemas/lokationsbuendelNummer'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZC9|ZD0].RFF+Z33'
        objectcode:
          $ref: '../../../bo4e/fields/com/Objectcode/objectcode.yaml#/components/schemas/objectcode'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZC9|ZD0].RFF+Z33'
      required:
        - lokationsbuendelNummer
        - objectcode
    PI_55177__stammdaten__MARKTLOKATION:
      type: object
      properties:
        gueltigkeitszeitraum:
          $ref: '#/components/schemas/PI_55177__stammdaten__MARKTLOKATION__gueltigkeitszeitraum'
        marktlokationsId:
          $ref: '../../../bo4e/fields/bo/Marktlokation/marktlokationsId.yaml#/components/schemas/marktlokationsId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z16
            - SG4.IDE+24.SG5.LOC+Z22
      required:
        - gueltigkeitszeitraum
        - marktlokationsId
    PI_55177__stammdaten__MARKTLOKATION__gueltigkeitszeitraum:
      type: object
      properties:
        zeitraumId:
          $ref: '../../../bo4e/fields/com/Zeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z16
            - SG4.IDE+24.SG5.LOC+Z22
      required:
        - zeitraumId
    PI_55177__stammdaten__MESSLOKATION:
      type: object
      properties:
        gueltigkeitszeitraum:
          $ref: '#/components/schemas/PI_55177__stammdaten__MESSLOKATION__gueltigkeitszeitraum'
        messlokationsId:
          $ref: '../../../bo4e/fields/bo/Messlokation/messlokationsId.yaml#/components/schemas/messlokationsId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z17
      required:
        - gueltigkeitszeitraum
        - messlokationsId
    PI_55177__stammdaten__MESSLOKATION__gueltigkeitszeitraum:
      type: object
      properties:
        zeitraumId:
          $ref: '../../../bo4e/fields/com/Zeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z17
      required:
        - zeitraumId
    PI_55177__stammdaten__NETZLOKATION:
      type: object
      properties:
        gueltigkeitszeitraum:
          $ref: '#/components/schemas/PI_55177__stammdaten__NETZLOKATION__gueltigkeitszeitraum'
        netzlokationsId:
          $ref: '../../../bo4e/fields/bo/Netzlokation/netzlokationsId.yaml#/components/schemas/netzlokationsId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z18
      required:
        - gueltigkeitszeitraum
        - netzlokationsId
    PI_55177__stammdaten__NETZLOKATION__gueltigkeitszeitraum:
      type: object
      properties:
        zeitraumId:
          $ref: '../../../bo4e/fields/com/Zeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z18
      required:
        - zeitraumId
    PI_55177__stammdaten__STEUERBARE_RESSOURCE:
      type: object
      properties:
        gueltigkeitszeitraum:
          $ref: '#/components/schemas/PI_55177__stammdaten__STEUERBARE_RESSOURCE__gueltigkeitszeitraum'
        ressourcenId:
          $ref: '../../../bo4e/fields/bo/SteuerbareRessource/ressourcenId.yaml#/components/schemas/ressourcenId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z19
      required:
        - gueltigkeitszeitraum
        - ressourcenId
    PI_55177__stammdaten__STEUERBARE_RESSOURCE__gueltigkeitszeitraum:
      type: object
      properties:
        zeitraumId:
          $ref: '../../../bo4e/fields/com/Zeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z19
      required:
        - zeitraumId
    PI_55177__stammdaten__TECHNISCHE_RESSOURCE:
      type: object
      properties:
        gueltigkeitszeitraum:
          $ref: '#/components/schemas/PI_55177__stammdaten__TECHNISCHE_RESSOURCE__gueltigkeitszeitraum'
        ressourcenId:
          $ref: '../../../bo4e/fields/bo/TechnischeRessource/ressourcenId.yaml#/components/schemas/ressourcenId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z20
      required:
        - gueltigkeitszeitraum
        - ressourcenId
    PI_55177__stammdaten__TECHNISCHE_RESSOURCE__gueltigkeitszeitraum:
      type: object
      properties:
        zeitraumId:
          $ref: '../../../bo4e/fields/com/Zeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z20
      required:
        - zeitraumId
    PI_55177__stammdaten__VERWENDUNGSZEITRAUM:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55]'
        verwendungAb:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungAb.yaml#/components/schemas/verwendungAb'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55].DTM+Z25'
        verwendungBis:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungBis.yaml#/components/schemas/verwendungBis'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55].DTM+Z26'
        zeitraumId:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55]'
      required:
        - verwendungAb
