openapi: 3.1.0
info:
  title: PI_55625
  version: '202604'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: 39ae45d481e5cc3d4d7aae328a23a9751236156a
components:
  schemas:
    PI_55625:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55625__stammdaten'
      required:
        - stammdaten
    PI_55625__stammdaten:
      type: object
      properties:
        TRANCHE:
          type: array
          items:
            $ref: '#/components/schemas/PI_55625__stammdaten__TRANCHE'
        VERWENDUNGSZEITRAUM:
          type: array
          items:
            $ref: '#/components/schemas/PI_55625__stammdaten__VERWENDUNGSZEITRAUM'
      required:
        - TRANCHE
        - VERWENDUNGSZEITRAUM
    PI_55625__stammdaten__TRANCHE:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Tranche/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z94|Z95]'
        gueltigkeitszeitraum:
          $ref: '#/components/schemas/PI_55625__stammdaten__TRANCHE__gueltigkeitszeitraum'
        tranchenId:
          $ref: '../../../bo4e/fields/bo/Tranche/tranchenId.yaml#/components/schemas/tranchenId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z21
        verguetungEmpfaenger:
          $ref: '../../../bo4e/fields/bo/Tranche/verguetungEmpfaenger.yaml#/components/schemas/verguetungEmpfaenger'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z94|Z95].SG10.CCI+++Z89.CAV'
      required:
        - datenqualitaet
        - gueltigkeitszeitraum
        - tranchenId
        - verguetungEmpfaenger
    PI_55625__stammdaten__TRANCHE__gueltigkeitszeitraum:
      type: object
      properties:
        zeitraumId:
          $ref: '../../../bo4e/fields/com/Zeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z94|Z95]'
      required:
        - zeitraumId
    PI_55625__stammdaten__VERWENDUNGSZEITRAUM:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55]'
        verwendungAb:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungAb.yaml#/components/schemas/verwendungAb'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55].DTM+Z25'
        verwendungBis:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungBis.yaml#/components/schemas/verwendungBis'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55].DTM+Z26'
        zeitraumId:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55]'
      required:
        - datenqualitaet
        - verwendungAb
        - zeitraumId
