openapi: 3.1.0
info:
  title: PI_55661
  version: '202604'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_55661:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55661__stammdaten'
      required:
        - stammdaten
    PI_55661__stammdaten:
      type: object
      properties:
        STEUERBARE_RESSOURCE:
          type: array
          items:
            $ref: '#/components/schemas/PI_55661__stammdaten__STEUERBARE_RESSOURCE'
        VERWENDUNGSZEITRAUM:
          type: array
          items:
            $ref: '#/components/schemas/PI_55661__stammdaten__VERWENDUNGSZEITRAUM'
      required:
        - STEUERBARE_RESSOURCE
        - VERWENDUNGSZEITRAUM
    PI_55661__stammdaten__STEUERBARE_RESSOURCE:
      type: object
      properties:
        auftraggebenderMarktpartner:
          $ref: '#/components/schemas/PI_55661__stammdaten__STEUERBARE_RESSOURCE__auftraggebenderMarktpartner'
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/SteuerbareRessource/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z61
            - SG4.IDE+24.SG8.SEQ+Z62
        gueltigkeitszeitraum:
          $ref: '#/components/schemas/PI_55661__stammdaten__STEUERBARE_RESSOURCE__gueltigkeitszeitraum'
        konfigurationsprodukt:
          $ref: '../../../bo4e/fields/bo/SteuerbareRessource/konfigurationsprodukt.yaml#/components/schemas/konfigurationsprodukt'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z61.PIA+5
        produktdatenRelevanteRolle:
          $ref: '../../../bo4e/fields/bo/SteuerbareRessource/produktdatenRelevanteRolle.yaml#/components/schemas/produktdatenRelevanteRolle'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+Z61.SG10.CCI+++[ZA7|ZA8]'
        ressourcenId:
          $ref: '../../../bo4e/fields/bo/SteuerbareRessource/ressourcenId.yaml#/components/schemas/ressourcenId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z19
        steuerkanal:
          $ref: '../../../bo4e/fields/bo/SteuerbareRessource/steuerkanal.yaml#/components/schemas/steuerkanal'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z62.SG10.CCI+Z49.CAV+ZF2
        zugeordneteDefinition:
          $ref: '#/components/schemas/PI_55661__stammdaten__STEUERBARE_RESSOURCE__zugeordneteDefinition'
      required:
        - auftraggebenderMarktpartner
        - datenqualitaet
        - gueltigkeitszeitraum
        - konfigurationsprodukt
        - produktdatenRelevanteRolle
        - ressourcenId
        - steuerkanal
        - zugeordneteDefinition
    PI_55661__stammdaten__STEUERBARE_RESSOURCE__auftraggebenderMarktpartner:
      type: object
      properties:
        marktrolle:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/marktrolle.yaml#/components/schemas/marktrolle'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+Z61.SG10.CCI+++ZB3.CAV+[Z88|Z89]'
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+Z61.SG10.CCI+++ZB3.CAV+[Z88|Z89]'
      required:
        - marktrolle
        - rollencodenummer
    PI_55661__stammdaten__STEUERBARE_RESSOURCE__gueltigkeitszeitraum:
      type: object
      properties:
        zeitraumId:
          $ref: '../../../bo4e/fields/com/Zeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z61
            - SG4.IDE+24.SG8.SEQ+Z62
      required:
        - zeitraumId
    PI_55661__stammdaten__STEUERBARE_RESSOURCE__zugeordneteDefinition:
      type: object
      properties:
        leistungskurvendefinition:
          $ref: '../../../bo4e/fields/com/ZugeordneteDefinition/leistungskurvendefinition.yaml#/components/schemas/leistungskurvendefinition'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+Z61.SG10.CCI+[Z52|Z53]'
        schaltzeitdefinition:
          $ref: '../../../bo4e/fields/com/ZugeordneteDefinition/schaltzeitdefinition.yaml#/components/schemas/schaltzeitdefinition'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+Z61.SG10.CCI+[Z52|Z53]'
      required:
        - leistungskurvendefinition
        - schaltzeitdefinition
    PI_55661__stammdaten__VERWENDUNGSZEITRAUM:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53]'
        verwendungAb:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungAb.yaml#/components/schemas/verwendungAb'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53].DTM+Z25'
        verwendungBis:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungBis.yaml#/components/schemas/verwendungBis'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53].DTM+Z26'
        zeitraumId:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53]'
      required:
        - datenqualitaet
        - verwendungAb
        - zeitraumId
