openapi: 3.1.0
info:
  title: PI_55627
  version: '202604'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: 39ae45d481e5cc3d4d7aae328a23a9751236156a
components:
  schemas:
    PI_55627:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55627__stammdaten'
      required:
        - stammdaten
    PI_55627__stammdaten:
      type: object
      properties:
        NETZLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_55627__stammdaten__NETZLOKATION'
        VERWENDUNGSZEITRAUM:
          type: array
          items:
            $ref: '#/components/schemas/PI_55627__stammdaten__VERWENDUNGSZEITRAUM'
      required:
        - NETZLOKATION
        - VERWENDUNGSZEITRAUM
    PI_55627__stammdaten__NETZLOKATION:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Netzlokation/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z51
        gueltigkeitszeitraum:
          $ref: '#/components/schemas/PI_55627__stammdaten__NETZLOKATION__gueltigkeitszeitraum'
        marktrollen:
          type: array
          items:
            $ref: '#/components/schemas/PI_55627__stammdaten__NETZLOKATION__marktrollen'
        netzlokationsId:
          $ref: '../../../bo4e/fields/bo/Netzlokation/netzlokationsId.yaml#/components/schemas/netzlokationsId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z18
      required:
        - datenqualitaet
        - gueltigkeitszeitraum
        - marktrollen
        - netzlokationsId
    PI_55627__stammdaten__NETZLOKATION__gueltigkeitszeitraum:
      type: object
      properties:
        zeitraumId:
          $ref: '../../../bo4e/fields/com/Zeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z51
      required:
        - zeitraumId
    PI_55627__stammdaten__NETZLOKATION__marktrollen:
      type: object
      properties:
        marktrolle:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/marktrolle.yaml#/components/schemas/marktrolle'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z51.SG10.CCI+++ZB3.CAV+Z91
        messstellenbetreiberEigenschaft:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/messstellenbetreiberEigenschaft.yaml#/components/schemas/messstellenbetreiberEigenschaft'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z51.SG10.CCI+++ZB3.CAV+Z91
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z51.SG10.CCI+++ZB3.CAV+Z91
      required:
        - marktrolle
        - messstellenbetreiberEigenschaft
        - rollencodenummer
    PI_55627__stammdaten__VERWENDUNGSZEITRAUM:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53]'
        verwendungAb:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungAb.yaml#/components/schemas/verwendungAb'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53].DTM+Z25'
        verwendungBis:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungBis.yaml#/components/schemas/verwendungBis'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53].DTM+Z26'
        zeitraumId:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53]'
      required:
        - datenqualitaet
        - verwendungAb
        - zeitraumId
