openapi: 3.1.0
info:
  title: PI_55664
  version: '202604'
  x-bo4e-schema-version: 1.6.5
  x-bo4e-schema-sha: 95f07d974cf2dc738ca248b258d6589025614cb0
  x-templater-sha: 6e98aaa8818d7b01b16786b130d743ea57fa960a
components:
  schemas:
    PI_55664:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55664__stammdaten'
      required:
        - stammdaten
    PI_55664__stammdaten:
      type: object
      properties:
        NETZLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_55664__stammdaten__NETZLOKATION'
        VERWENDUNGSZEITRAUM:
          type: array
          items:
            $ref: '#/components/schemas/PI_55664__stammdaten__VERWENDUNGSZEITRAUM'
      required:
        - NETZLOKATION
        - VERWENDUNGSZEITRAUM
    PI_55664__stammdaten__NETZLOKATION:
      type: object
      properties:
        auftraggebenderMarktpartner:
          $ref: '#/components/schemas/PI_55664__stammdaten__NETZLOKATION__auftraggebenderMarktpartner'
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Netzlokation/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZA7|ZA8]'
            - 'SG4.IDE+24.SG8.SEQ+[ZA9|ZB0]'
            - 'SG4.IDE+24.SG8.SEQ+[ZG8|ZG9]'
        gueltigkeitszeitraum:
          $ref: '#/components/schemas/PI_55664__stammdaten__NETZLOKATION__gueltigkeitszeitraum'
        keinKonfigurationsprodukt:
          $ref: '../../../bo4e/fields/bo/Netzlokation/keinKonfigurationsprodukt.yaml#/components/schemas/keinKonfigurationsprodukt'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZG8|ZG9].SG10.CCI+11'
        konfigurationsprodukt:
          $ref: '../../../bo4e/fields/bo/Netzlokation/konfigurationsprodukt.yaml#/components/schemas/konfigurationsprodukt'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZG8|ZG9].PIA+5'
        leistungskurvendefinition:
          $ref: '../../../bo4e/fields/bo/Netzlokation/leistungskurvendefinition.yaml#/components/schemas/leistungskurvendefinition'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZG8|ZG9].SG10.CCI+Z53'
        netzlokationsId:
          $ref: '../../../bo4e/fields/bo/Netzlokation/netzlokationsId.yaml#/components/schemas/netzlokationsId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z18
        produktdatenRelevanteRolle:
          $ref: '../../../bo4e/fields/bo/Netzlokation/produktdatenRelevanteRolle.yaml#/components/schemas/produktdatenRelevanteRolle'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZG8|ZG9].SG10.CCI+++ZA7'
        steuerkanal:
          $ref: '../../../bo4e/fields/bo/Netzlokation/steuerkanal.yaml#/components/schemas/steuerkanal'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZA9|ZB0].SG10.CCI+Z49'
        zaehlwerke:
          type: array
          items:
            $ref: '#/components/schemas/PI_55664__stammdaten__NETZLOKATION__zaehlwerke'
      required:
        - auftraggebenderMarktpartner
        - datenqualitaet
        - gueltigkeitszeitraum
        - keinKonfigurationsprodukt
        - leistungskurvendefinition
        - netzlokationsId
        - produktdatenRelevanteRolle
        - steuerkanal
        - zaehlwerke
    PI_55664__stammdaten__NETZLOKATION__auftraggebenderMarktpartner:
      type: object
      properties:
        marktrolle:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/marktrolle.yaml#/components/schemas/marktrolle'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZG8|ZG9].SG10.CCI+++ZB3.CAV+[Z88|Z89]'
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZG8|ZG9].SG10.CCI+++ZB3.CAV+[Z88|Z89]'
      required:
        - marktrolle
        - rollencodenummer
    PI_55664__stammdaten__NETZLOKATION__gueltigkeitszeitraum:
      type: object
      properties:
        zeitraumId:
          $ref: '../../../bo4e/fields/com/Zeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZA7|ZA8]'
            - 'SG4.IDE+24.SG8.SEQ+[ZA9|ZB0]'
            - 'SG4.IDE+24.SG8.SEQ+[ZG8|ZG9]'
      required:
        - zeitraumId
    PI_55664__stammdaten__NETZLOKATION__zaehlwerke:
      type: object
      properties:
        obisKennzahl:
          $ref: '../../../bo4e/fields/com/Zaehlwerk/obisKennzahl.yaml#/components/schemas/obisKennzahl'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZA7|ZA8].PIA+5'
        verwendungszwecke:
          type: array
          items:
            $ref: '#/components/schemas/PI_55664__stammdaten__NETZLOKATION__zaehlwerke__verwendungszwecke'
      required:
        - obisKennzahl
        - verwendungszwecke
    PI_55664__stammdaten__NETZLOKATION__zaehlwerke__verwendungszwecke:
      type: object
      properties:
        marktrolle:
          $ref: '../../../bo4e/fields/com/Verwendungszweck/marktrolle.yaml#/components/schemas/marktrolle'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZA7|ZA8].SG10.CCI+++ZA7.CAV'
            - 'SG4.IDE+24.SG8.SEQ+[ZA7|ZA8].SG10.CCI+++ZA8.CAV'
        zweck:
          $ref: '../../../bo4e/fields/com/Verwendungszweck/zweck.yaml#/components/schemas/zweck'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZA7|ZA8].SG10.CCI+++ZA7.CAV'
            - 'SG4.IDE+24.SG8.SEQ+[ZA7|ZA8].SG10.CCI+++ZA8.CAV'
      required:
        - marktrolle
        - zweck
    PI_55664__stammdaten__VERWENDUNGSZEITRAUM:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48]'
        verwendungAb:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungAb.yaml#/components/schemas/verwendungAb'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48].DTM+Z25'
        verwendungBis:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungBis.yaml#/components/schemas/verwendungBis'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48].DTM+Z26'
        zeitraumId:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48]'
      required:
        - datenqualitaet
        - verwendungAb
        - zeitraumId
