openapi: 3.1.0
info:
  title: PI_55667
  version: '202604'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: c7b88c733e93fe4ee423d52cffa2cd8f312574ea
components:
  schemas:
    PI_55667:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55667__stammdaten'
      required:
        - stammdaten
    PI_55667__stammdaten:
      type: object
      properties:
        TRANCHE:
          type: array
          items:
            $ref: '#/components/schemas/PI_55667__stammdaten__TRANCHE'
        VERWENDUNGSZEITRAUM:
          type: array
          items:
            $ref: '#/components/schemas/PI_55667__stammdaten__VERWENDUNGSZEITRAUM'
      required:
        - TRANCHE
        - VERWENDUNGSZEITRAUM
    PI_55667__stammdaten__TRANCHE:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Tranche/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z99|ZA0]'
        gueltigkeitszeitraum:
          $ref: '#/components/schemas/PI_55667__stammdaten__TRANCHE__gueltigkeitszeitraum'
        tranchenId:
          $ref: '../../../bo4e/fields/bo/Tranche/tranchenId.yaml#/components/schemas/tranchenId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z21
        zaehlwerke:
          type: array
          items:
            $ref: '#/components/schemas/PI_55667__stammdaten__TRANCHE__zaehlwerke'
      required:
        - datenqualitaet
        - gueltigkeitszeitraum
        - tranchenId
        - zaehlwerke
    PI_55667__stammdaten__TRANCHE__gueltigkeitszeitraum:
      type: object
      properties:
        zeitraumId:
          $ref: '../../../bo4e/fields/com/Zeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z99|ZA0]'
      required:
        - zeitraumId
    PI_55667__stammdaten__TRANCHE__zaehlwerke:
      type: object
      properties:
        obisKennzahl:
          $ref: '../../../bo4e/fields/com/Zaehlwerk/obisKennzahl.yaml#/components/schemas/obisKennzahl'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z99|ZA0].PIA+5'
        verwendungszwecke:
          type: array
          items:
            $ref: '#/components/schemas/PI_55667__stammdaten__TRANCHE__zaehlwerke__verwendungszwecke'
      required:
        - obisKennzahl
        - verwendungszwecke
    PI_55667__stammdaten__TRANCHE__zaehlwerke__verwendungszwecke:
      type: object
      properties:
        marktrolle:
          $ref: '../../../bo4e/fields/com/Verwendungszweck/marktrolle.yaml#/components/schemas/marktrolle'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z99|ZA0].SG10.CCI+++ZA7.CAV'
            - 'SG4.IDE+24.SG8.SEQ+[Z99|ZA0].SG10.CCI+++ZA8.CAV'
        zweck:
          $ref: '../../../bo4e/fields/com/Verwendungszweck/zweck.yaml#/components/schemas/zweck'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z99|ZA0].SG10.CCI+++ZA7.CAV'
            - 'SG4.IDE+24.SG8.SEQ+[Z99|ZA0].SG10.CCI+++ZA8.CAV'
      required:
        - marktrolle
        - zweck
    PI_55667__stammdaten__VERWENDUNGSZEITRAUM:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55]'
        verwendungAb:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungAb.yaml#/components/schemas/verwendungAb'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55].DTM+Z25'
        verwendungBis:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungBis.yaml#/components/schemas/verwendungBis'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55].DTM+Z26'
        zeitraumId:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55]'
      required:
        - datenqualitaet
        - verwendungAb
        - zeitraumId
