openapi: 3.1.0
info:
  title: PI_55670
  version: '202604'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_55670:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55670__stammdaten'
      required:
        - stammdaten
    PI_55670__stammdaten:
      type: object
      properties:
        BILANZIERUNG:
          type: array
          items:
            $ref: '#/components/schemas/PI_55670__stammdaten__BILANZIERUNG'
        MARKTLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_55670__stammdaten__MARKTLOKATION'
        TRANCHE:
          type: array
          items:
            $ref: '#/components/schemas/PI_55670__stammdaten__TRANCHE'
        VERWENDUNGSZEITRAUM:
          type: array
          items:
            $ref: '#/components/schemas/PI_55670__stammdaten__VERWENDUNGSZEITRAUM'
      required:
        - BILANZIERUNG
        - MARKTLOKATION
        - TRANCHE
        - VERWENDUNGSZEITRAUM
    PI_55670__stammdaten__BILANZIERUNG:
      type: object
      properties:
        bilanzkreis:
          $ref: '../../../bo4e/fields/bo/Bilanzierung/bilanzkreis.yaml#/components/schemas/bilanzkreis'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+Z19
            - SG4.IDE+24.SG8.SEQ+Z98.SG10.CCI+Z19
        zeitreihentyp:
          $ref: '../../../bo4e/fields/bo/Bilanzierung/zeitreihentyp.yaml#/components/schemas/zeitreihentyp'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+15++Z21.CAV
            - SG4.IDE+24.SG8.SEQ+Z98.SG10.CCI+15++Z21.CAV
      required:
        - bilanzkreis
        - zeitreihentyp
    PI_55670__stammdaten__MARKTLOKATION:
      type: object
      properties:
        bilanzierungsgebiet:
          $ref: '../../../bo4e/fields/bo/Marktlokation/bilanzierungsgebiet.yaml#/components/schemas/bilanzierungsgebiet'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+Z20
            - SG4.IDE+24.SG8.SEQ+Z98.SG10.CCI+Z20
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Marktlokation/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z01
            - SG4.IDE+24.SG8.SEQ+Z98
        gueltigkeitszeitraum:
          $ref: '#/components/schemas/PI_55670__stammdaten__MARKTLOKATION__gueltigkeitszeitraum'
        marktlokationsId:
          $ref: '../../../bo4e/fields/bo/Marktlokation/marktlokationsId.yaml#/components/schemas/marktlokationsId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z16
        marktrollen:
          type: array
          items:
            $ref: '#/components/schemas/PI_55670__stammdaten__MARKTLOKATION__marktrollen'
      required:
        - bilanzierungsgebiet
        - datenqualitaet
        - gueltigkeitszeitraum
        - marktlokationsId
    PI_55670__stammdaten__MARKTLOKATION__gueltigkeitszeitraum:
      type: object
      properties:
        zeitraumId:
          $ref: '../../../bo4e/fields/com/Zeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z01
      required:
        - zeitraumId
    PI_55670__stammdaten__MARKTLOKATION__marktrollen:
      type: object
      properties:
        marktrolle:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/marktrolle.yaml#/components/schemas/marktrolle'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+++ZB3.CAV+Z89
            - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+++ZB3.CAV+Z91
            - SG4.IDE+24.SG8.SEQ+Z98.SG10.CCI+++ZB3.CAV+Z89
            - SG4.IDE+24.SG8.SEQ+Z98.SG10.CCI+++ZB3.CAV+Z91
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+++ZB3.CAV+Z89
            - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+++ZB3.CAV+Z91
            - SG4.IDE+24.SG8.SEQ+Z98.SG10.CCI+++ZB3.CAV+Z89
            - SG4.IDE+24.SG8.SEQ+Z98.SG10.CCI+++ZB3.CAV+Z91
    PI_55670__stammdaten__TRANCHE:
      type: object
      properties:
        bilanzkreis:
          $ref: '../../../bo4e/fields/bo/Tranche/bilanzkreis.yaml#/components/schemas/bilanzkreis'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z15.SG10.CCI+Z19
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Tranche/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z15
        gueltigkeitszeitraum:
          $ref: '#/components/schemas/PI_55670__stammdaten__TRANCHE__gueltigkeitszeitraum'
        marktrollen:
          type: array
          items:
            $ref: '#/components/schemas/PI_55670__stammdaten__TRANCHE__marktrollen'
        tranchenId:
          $ref: '../../../bo4e/fields/bo/Tranche/tranchenId.yaml#/components/schemas/tranchenId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z21
            - SG4.IDE+24.SG8.SEQ+Z15.RFF+Z20
      required:
        - bilanzkreis
        - datenqualitaet
        - gueltigkeitszeitraum
        - marktrollen
        - tranchenId
    PI_55670__stammdaten__TRANCHE__gueltigkeitszeitraum:
      type: object
      properties:
        zeitraumId:
          $ref: '../../../bo4e/fields/com/Zeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z15
      required:
        - zeitraumId
    PI_55670__stammdaten__TRANCHE__marktrollen:
      type: object
      properties:
        marktrolle:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/marktrolle.yaml#/components/schemas/marktrolle'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z15.SG10.CCI+++ZB3.CAV+Z89
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z15.SG10.CCI+++ZB3.CAV+Z89
      required:
        - marktrolle
        - rollencodenummer
    PI_55670__stammdaten__VERWENDUNGSZEITRAUM:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53]'
        verwendungAb:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungAb.yaml#/components/schemas/verwendungAb'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53].DTM+Z25'
        verwendungBis:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungBis.yaml#/components/schemas/verwendungBis'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53].DTM+Z26'
        zeitraumId:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53]'
      required:
        - datenqualitaet
        - verwendungAb
        - zeitraumId
