openapi: 3.1.0
info:
  title: PI_55220
  version: '202604'
  x-bo4e-schema-version: 1.6.8
  x-bo4e-schema-sha: b84d59c01638e348fe912e388cf7b7a25ab9937f
  x-templater-sha: ce089a840512efbac03c3b3e949ad6e8b7215947
components:
  schemas:
    PI_55220:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55220__stammdaten'
      required:
        - stammdaten
    PI_55220__stammdaten:
      type: object
      properties:
        BILANZIERUNG:
          type: array
          items:
            $ref: '#/components/schemas/PI_55220__stammdaten__BILANZIERUNG'
        MARKTLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_55220__stammdaten__MARKTLOKATION'
        NETZNUTZUNGSVERTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_55220__stammdaten__NETZNUTZUNGSVERTRAG'
        VERWENDUNGSZEITRAUM:
          type: array
          items:
            $ref: '#/components/schemas/PI_55220__stammdaten__VERWENDUNGSZEITRAUM'
      required:
        - BILANZIERUNG
        - MARKTLOKATION
        - NETZNUTZUNGSVERTRAG
        - VERWENDUNGSZEITRAUM
    PI_55220__stammdaten__BILANZIERUNG:
      type: object
      properties:
        verbrauchsaufteilung:
          $ref: '#/components/schemas/PI_55220__stammdaten__BILANZIERUNG__verbrauchsaufteilung'
      required:
        - verbrauchsaufteilung
    PI_55220__stammdaten__BILANZIERUNG__verbrauchsaufteilung:
      type: object
      properties:
        einheit:
          $ref: '../../../bo4e/fields/com/Menge/einheit.yaml#/components/schemas/einheit'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z80|Z81].SG10.CCI+++E17.CAV+Z22'
        wert:
          $ref: '../../../bo4e/fields/com/Menge/wert.yaml#/components/schemas/wert'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z80|Z81].SG10.CCI+++E17.CAV+Z22'
      required:
        - einheit
        - wert
    PI_55220__stammdaten__MARKTLOKATION:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Marktlokation/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z51|Z52]'
            - 'SG4.IDE+24.SG8.SEQ+[Z80|Z81]'
            - 'SG4.IDE+24.SG8.SEQ+[Z82|Z83|Z96|Z97]'
        gueltigkeitszeitraum:
          $ref: '#/components/schemas/PI_55220__stammdaten__MARKTLOKATION__gueltigkeitszeitraum'
        marktlokationsId:
          $ref: '../../../bo4e/fields/bo/Marktlokation/marktlokationsId.yaml#/components/schemas/marktlokationsId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z16
        netzbetreiberCodeNr:
          $ref: '../../../bo4e/fields/bo/Marktlokation/netzbetreiberCodeNr.yaml#/components/schemas/netzbetreiberCodeNr'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z82|Z83|Z96|Z97].SG10.CCI+++ZB3.CAV+Z88'
        netznutzungsabrechnungsdaten:
          type: array
          items:
            $ref: '#/components/schemas/PI_55220__stammdaten__MARKTLOKATION__netznutzungsabrechnungsdaten'
      required:
        - datenqualitaet
        - gueltigkeitszeitraum
        - marktlokationsId
        - netzbetreiberCodeNr
        - netznutzungsabrechnungsdaten
    PI_55220__stammdaten__MARKTLOKATION__gueltigkeitszeitraum:
      type: object
      properties:
        zeitraumId:
          $ref: '../../../bo4e/fields/com/Zeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z51|Z52]'
            - 'SG4.IDE+24.SG8.SEQ+[Z80|Z81]'
            - 'SG4.IDE+24.SG8.SEQ+[Z82|Z83|Z96|Z97]'
      required:
        - zeitraumId
    PI_55220__stammdaten__MARKTLOKATION__netznutzungsabrechnungsdaten:
      type: object
      properties:
        abschlag:
          $ref: '../../../bo4e/fields/com/Netznutzungsabrechnungsdaten/abschlag.yaml#/components/schemas/abschlag'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z82|Z83|Z96|Z97].SG9.QTY'
        anzahl:
          $ref: '../../../bo4e/fields/com/Netznutzungsabrechnungsdaten/anzahl.yaml#/components/schemas/anzahl'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z82|Z83|Z96|Z97].SG9.QTY+Z38'
        artikelId:
          $ref: '../../../bo4e/fields/com/Netznutzungsabrechnungsdaten/artikelId.yaml#/components/schemas/artikelId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z82|Z83|Z96|Z97].PIA+Z02'
        artikelIdTyp:
          $ref: '../../../bo4e/fields/com/Netznutzungsabrechnungsdaten/artikelIdTyp.yaml#/components/schemas/artikelIdTyp'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z82|Z83|Z96|Z97].PIA+Z02'
        gemeinderabatt:
          $ref: '../../../bo4e/fields/com/Netznutzungsabrechnungsdaten/gemeinderabatt.yaml#/components/schemas/gemeinderabatt'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z82|Z83|Z96|Z97].SG9.QTY'
            - 'SG4.IDE+24.SG8.SEQ+[Z82|Z83|Z96|Z97].SG9.QTY+Z16'
        preisSingulaereBetriebsmittel:
          $ref: '#/components/schemas/PI_55220__stammdaten__MARKTLOKATION__netznutzungsabrechnungsdaten__preisSingulaereBetriebsmittel'
        singulaereBetriebsmittel:
          $ref: '#/components/schemas/PI_55220__stammdaten__MARKTLOKATION__netznutzungsabrechnungsdaten__singulaereBetriebsmittel'
        zaehlzeiten:
          $ref: '#/components/schemas/PI_55220__stammdaten__MARKTLOKATION__netznutzungsabrechnungsdaten__zaehlzeiten'
        zuschlag:
          $ref: '../../../bo4e/fields/com/Netznutzungsabrechnungsdaten/zuschlag.yaml#/components/schemas/zuschlag'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z82|Z83|Z96|Z97].SG9.QTY'
      required:
        - abschlag
        - anzahl
        - artikelId
        - artikelIdTyp
        - gemeinderabatt
        - preisSingulaereBetriebsmittel
        - singulaereBetriebsmittel
        - zaehlzeiten
        - zuschlag
    PI_55220__stammdaten__MARKTLOKATION__netznutzungsabrechnungsdaten__preisSingulaereBetriebsmittel:
      type: object
      properties:
        wert:
          $ref: '../../../bo4e/fields/com/Preis/wert.yaml#/components/schemas/wert'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z82|Z83|Z96|Z97].SG10.CCI+Z44+ZD8'
      required:
        - wert
    PI_55220__stammdaten__MARKTLOKATION__netznutzungsabrechnungsdaten__singulaereBetriebsmittel:
      type: object
      properties:
        wert:
          $ref: '../../../bo4e/fields/com/Menge/wert.yaml#/components/schemas/wert'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z82|Z83|Z96|Z97].SG9.QTY+Z33'
      required:
        - wert
    PI_55220__stammdaten__MARKTLOKATION__netznutzungsabrechnungsdaten__zaehlzeiten:
      type: object
      properties:
        register:
          $ref: '../../../bo4e/fields/com/Zaehlzeitregister/register.yaml#/components/schemas/register'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z82|Z83|Z96|Z97].SG10.CCI+Z38'
        zaehlzeitDefinition:
          $ref: '../../../bo4e/fields/com/Zaehlzeitregister/zaehlzeitDefinition.yaml#/components/schemas/zaehlzeitDefinition'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z82|Z83|Z96|Z97].SG10.CCI+Z39'
      required:
        - register
        - zaehlzeitDefinition
    PI_55220__stammdaten__NETZNUTZUNGSVERTRAG:
      type: object
      properties:
        vertragskonditionen:
          $ref: '#/components/schemas/PI_55220__stammdaten__NETZNUTZUNGSVERTRAG__vertragskonditionen'
      required:
        - vertragskonditionen
    PI_55220__stammdaten__NETZNUTZUNGSVERTRAG__vertragskonditionen:
      type: object
      properties:
        naechstenetznutzungsabrechnung:
          $ref: '../../../bo4e/fields/com/Vertragskonditionen/naechstenetznutzungsabrechnung.yaml#/components/schemas/naechstenetznutzungsabrechnung'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z51|Z52].DTM+Z09'
        netznutzungsabrechnung:
          $ref: '#/components/schemas/PI_55220__stammdaten__NETZNUTZUNGSVERTRAG__vertragskonditionen__netznutzungsabrechnung'
        netznutzungsabrechnungIntervall:
          $ref: '../../../bo4e/fields/com/Vertragskonditionen/netznutzungsabrechnungIntervall.yaml#/components/schemas/netznutzungsabrechnungIntervall'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z51|Z52].DTM+Z22'
        netznutzungsabrechnungsgrundlage:
          $ref: '../../../bo4e/fields/com/Vertragskonditionen/netznutzungsabrechnungsgrundlage.yaml#/components/schemas/netznutzungsabrechnungsgrundlage'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z80|Z81].SG10.CCI+++Z88.CAV+ZA7'
        netznutzungsvertrag:
          $ref: '../../../bo4e/fields/com/Vertragskonditionen/netznutzungsvertrag.yaml#/components/schemas/netznutzungsvertrag'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z80|Z81].SG10.CCI+++Z88.CAV+Z74'
        netznutzungszahler:
          $ref: '../../../bo4e/fields/com/Vertragskonditionen/netznutzungszahler.yaml#/components/schemas/netznutzungszahler'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[Z80|Z81].SG10.CCI+++Z88.CAV+Z73'
      required:
        - netznutzungsabrechnungsgrundlage
        - netznutzungsvertrag
        - netznutzungszahler
    PI_55220__stammdaten__NETZNUTZUNGSVERTRAG__vertragskonditionen__netznutzungsabrechnung:
      type: object
      properties:
        abrechnungsZeitraum:
          $ref: '../../../bo4e/fields/com/Zeitraum/abrechnungsZeitraum.yaml#/components/schemas/abrechnungsZeitraum'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z51|Z52].DTM+Z21'
    PI_55220__stammdaten__VERWENDUNGSZEITRAUM:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55]'
        verwendungAb:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungAb.yaml#/components/schemas/verwendungAb'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55].DTM+Z25'
        verwendungBis:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungBis.yaml#/components/schemas/verwendungBis'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55].DTM+Z26'
        zeitraumId:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55]'
      required:
        - datenqualitaet
        - verwendungAb
        - zeitraumId
