openapi: 3.1.0
info:
  title: PI_55017
  version: '202604'
  x-bo4e-schema-version: 1.6.5
  x-bo4e-schema-sha: 95f07d974cf2dc738ca248b258d6589025614cb0
  x-templater-sha: 6e98aaa8818d7b01b16786b130d743ea57fa960a
components:
  schemas:
    PI_55017:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55017__stammdaten'
      required:
        - stammdaten
    PI_55017__stammdaten:
      type: object
      properties:
        BILANZIERUNG:
          type: array
          items:
            $ref: '#/components/schemas/PI_55017__stammdaten__BILANZIERUNG'
        NETZNUTZUNGSVERTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_55017__stammdaten__NETZNUTZUNGSVERTRAG'
      required:
        - BILANZIERUNG
    PI_55017__stammdaten__BILANZIERUNG:
      type: object
      properties:
        vorjahresverbrauch:
          $ref: '#/components/schemas/PI_55017__stammdaten__BILANZIERUNG__vorjahresverbrauch'
      required:
        - vorjahresverbrauch
    PI_55017__stammdaten__BILANZIERUNG__vorjahresverbrauch:
      type: object
      properties:
        einheit:
          $ref: '../../../bo4e/fields/com/Menge/einheit.yaml#/components/schemas/einheit'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z01.SG9.QTY+Z09
        wert:
          $ref: '../../../bo4e/fields/com/Menge/wert.yaml#/components/schemas/wert'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z01.SG9.QTY+Z09
      required:
        - einheit
        - wert
    PI_55017__stammdaten__NETZNUTZUNGSVERTRAG:
      type: object
      properties:
        vertragsende:
          $ref: '../../../bo4e/fields/bo/Vertrag/vertragsende.yaml#/components/schemas/vertragsende'
          x-edifact-segment:
            - SG4.IDE+24.DTM+93
