openapi: 3.1.0
info:
  title: PI_19003
  version: '202610'
  x-bo4e-schema-version: 1.7.4
  x-bo4e-schema-sha: 1732e948753541a9b641ca98f3d8ff189d994263
  x-templater-sha: 392a2eb2993418f8a5be64578c22568416e2d551
components:
  schemas:
    PI_19003:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_19003__masterData'
      required:
      - masterData
    PI_19003__masterData:
      type: object
      properties:
        ORDER:
          type: array
          items:
            $ref: '#/components/schemas/PI_19003__masterData__ORDER'
      required:
      - ORDER
    PI_19003__masterData__ORDER:
      type: object
      properties:
        postponedDeregistrationDate:
          $ref: ../../../bo4e-en/fields/bo/Order/postponedDeregistrationDate.yaml#/components/schemas/postponedDeregistrationDate
          x-edifact-segment:
          - DTM+Z02
      required:
      - postponedDeregistrationDate
