openapi: 3.1.0
info:
  title: PI_19003
  version: '202510'
  x-bo4e-schema-version: 1.7.4
  x-bo4e-schema-sha: 1732e948753541a9b641ca98f3d8ff189d994263
  x-templater-sha: 20c434c98f1808f1b10ab64bdf7a7a96d42aa7ee
components:
  schemas:
    PI_19003:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_19003__stammdaten'
      required:
        - stammdaten
    PI_19003__stammdaten:
      type: object
      properties:
        AUFTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_19003__stammdaten__AUFTRAG'
      required:
        - AUFTRAG
    PI_19003__stammdaten__AUFTRAG:
      type: object
      properties:
        verschobenerAbmeldetermin:
          $ref: '../../../bo4e/fields/bo/Auftrag/verschobenerAbmeldetermin.yaml#/components/schemas/verschobenerAbmeldetermin'
          x-edifact-segment:
            - DTM+Z02
      required:
        - verschobenerAbmeldetermin
