openapi: 3.1.0
info:
  title: PI_19004
  version: '202604'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: c7b88c733e93fe4ee423d52cffa2cd8f312574ea
components:
  schemas:
    PI_19004:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_19004__stammdaten'
      required:
        - stammdaten
    PI_19004__stammdaten:
      type: object
      properties:
        AUFTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_19004__stammdaten__AUFTRAG'
      required:
        - AUFTRAG
    PI_19004__stammdaten__AUFTRAG:
      type: object
      properties:
        verschobenerAbmeldetermin:
          $ref: '../../../bo4e/fields/bo/Auftrag/verschobenerAbmeldetermin.yaml#/components/schemas/verschobenerAbmeldetermin'
          x-edifact-segment:
            - DTM+Z02
      required:
        - verschobenerAbmeldetermin
