openapi: 3.1.0
info:
  title: PI_19009
  version: '202604'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_19009:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_19009__stammdaten'
      required:
        - stammdaten
    PI_19009__stammdaten:
      type: object
      properties:
        ANFRAGE:
          type: array
          items:
            $ref: '#/components/schemas/PI_19009__stammdaten__ANFRAGE'
        AUFTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_19009__stammdaten__AUFTRAG'
      required:
        - ANFRAGE
        - AUFTRAG
    PI_19009__stammdaten__ANFRAGE:
      type: object
      properties:
        abonnement:
          $ref: '../../../bo4e/fields/bo/Anfrage/abonnement.yaml#/components/schemas/abonnement'
          x-edifact-segment:
            - IMD++Z02
        anfragekategorie:
          $ref: '../../../bo4e/fields/bo/Anfrage/anfragekategorie.yaml#/components/schemas/anfragekategorie'
          x-edifact-segment:
            - BGM+Z29
      required:
        - abonnement
        - anfragekategorie
    PI_19009__stammdaten__AUFTRAG:
      type: object
      properties:
        ausfuehrungsdatum:
          $ref: '../../../bo4e/fields/bo/Auftrag/ausfuehrungsdatum.yaml#/components/schemas/ausfuehrungsdatum'
          x-edifact-segment:
            - DTM+203
      required:
        - ausfuehrungsdatum
