openapi: 3.1.0
info:
  title: PI_17130
  version: '202510'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: c7b88c733e93fe4ee423d52cffa2cd8f312574ea
components:
  schemas:
    PI_17130:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_17130__stammdaten'
      required:
        - stammdaten
    PI_17130__stammdaten:
      type: object
      properties:
        ANFRAGE:
          type: array
          items:
            $ref: '#/components/schemas/PI_17130__stammdaten__ANFRAGE'
        AUFTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_17130__stammdaten__AUFTRAG'
        WERTE_NACH_TYP2:
          type: array
          items:
            $ref: '#/components/schemas/PI_17130__stammdaten__WERTE_NACH_TYP2'
      required:
        - ANFRAGE
        - WERTE_NACH_TYP2
    PI_17130__stammdaten__ANFRAGE:
      type: object
      properties:
        lokationsId:
          $ref: '../../../bo4e/fields/bo/Anfrage/lokationsId.yaml#/components/schemas/lokationsId'
          x-edifact-segment:
            - SG2.NAD+DP.LOC+172
      required:
        - lokationsId
    PI_17130__stammdaten__AUFTRAG:
      type: object
      properties:
        ausfuehrungsdatum:
          $ref: '../../../bo4e/fields/bo/Auftrag/ausfuehrungsdatum.yaml#/components/schemas/ausfuehrungsdatum'
          x-edifact-segment:
            - DTM+203
    PI_17130__stammdaten__WERTE_NACH_TYP2:
      type: object
      properties:
        aenderungsmoeglichkeitKonfiguration:
          $ref: '../../../bo4e/fields/bo/WerteNachTyp2/aenderungsmoeglichkeitKonfiguration.yaml#/components/schemas/aenderungsmoeglichkeitKonfiguration'
          x-edifact-segment:
            - SG29.LIN+Z68.SG30.CCI+Z54
        aussteller:
          $ref: '#/components/schemas/PI_17130__stammdaten__WERTE_NACH_TYP2__aussteller'
        messprodukt:
          $ref: '../../../bo4e/fields/bo/WerteNachTyp2/messprodukt.yaml#/components/schemas/messprodukt'
          x-edifact-segment:
            - SG29.LIN+Z67.PIA+5
            - SG29.LIN+Z68.PIA+5
        schwellwerte:
          type: array
          items:
            $ref: '#/components/schemas/PI_17130__stammdaten__WERTE_NACH_TYP2__schwellwerte'
        zertifikatsNutzer:
          $ref: '#/components/schemas/PI_17130__stammdaten__WERTE_NACH_TYP2__zertifikatsNutzer'
        zieladresse:
          $ref: '#/components/schemas/PI_17130__stammdaten__WERTE_NACH_TYP2__zieladresse'
      required:
        - aenderungsmoeglichkeitKonfiguration
        - aussteller
        - messprodukt
        - schwellwerte
        - zertifikatsNutzer
        - zieladresse
    PI_17130__stammdaten__WERTE_NACH_TYP2__aussteller:
      type: object
      properties:
        aussteller1:
          $ref: '../../../bo4e/fields/com/Aussteller/aussteller1.yaml#/components/schemas/aussteller1'
          x-edifact-segment:
            - SG29.LIN+Z68.FTX+Z24
        aussteller2:
          $ref: '../../../bo4e/fields/com/Aussteller/aussteller2.yaml#/components/schemas/aussteller2'
          x-edifact-segment:
            - SG29.LIN+Z68.FTX+Z24
        aussteller3:
          $ref: '../../../bo4e/fields/com/Aussteller/aussteller3.yaml#/components/schemas/aussteller3'
          x-edifact-segment:
            - SG29.LIN+Z68.FTX+Z24
        aussteller4:
          $ref: '../../../bo4e/fields/com/Aussteller/aussteller4.yaml#/components/schemas/aussteller4'
          x-edifact-segment:
            - SG29.LIN+Z68.FTX+Z24
        aussteller5:
          $ref: '../../../bo4e/fields/com/Aussteller/aussteller5.yaml#/components/schemas/aussteller5'
          x-edifact-segment:
            - SG29.LIN+Z68.FTX+Z24
      required:
        - aussteller1
        - aussteller2
        - aussteller3
        - aussteller4
        - aussteller5
    PI_17130__stammdaten__WERTE_NACH_TYP2__schwellwerte:
      type: object
      properties:
        konfigurationsprodukt:
          $ref: '../../../bo4e/fields/com/Schwellwert/konfigurationsprodukt.yaml#/components/schemas/konfigurationsprodukt'
          x-edifact-segment:
            - SG29.LIN+Z68.SG30.CCI+Z60
        obererSchwellwert:
          $ref: '../../../bo4e/fields/com/Schwellwert/obererSchwellwert.yaml#/components/schemas/obererSchwellwert'
          x-edifact-segment:
            - SG29.LIN+Z68.SG30.CCI+Z60
        untererSchwellwert:
          $ref: '../../../bo4e/fields/com/Schwellwert/untererSchwellwert.yaml#/components/schemas/untererSchwellwert'
          x-edifact-segment:
            - SG29.LIN+Z68.SG30.CCI+Z60
      required:
        - konfigurationsprodukt
        - obererSchwellwert
        - untererSchwellwert
    PI_17130__stammdaten__WERTE_NACH_TYP2__zertifikatsNutzer:
      type: object
      properties:
        zertifikatsNutzer1:
          $ref: '../../../bo4e/fields/com/ZertifikatsNutzer/zertifikatsNutzer1.yaml#/components/schemas/zertifikatsNutzer1'
          x-edifact-segment:
            - SG29.LIN+Z68.FTX+Z23
        zertifikatsNutzer2:
          $ref: '../../../bo4e/fields/com/ZertifikatsNutzer/zertifikatsNutzer2.yaml#/components/schemas/zertifikatsNutzer2'
          x-edifact-segment:
            - SG29.LIN+Z68.FTX+Z23
        zertifikatsNutzer3:
          $ref: '../../../bo4e/fields/com/ZertifikatsNutzer/zertifikatsNutzer3.yaml#/components/schemas/zertifikatsNutzer3'
          x-edifact-segment:
            - SG29.LIN+Z68.FTX+Z23
        zertifikatsNutzer4:
          $ref: '../../../bo4e/fields/com/ZertifikatsNutzer/zertifikatsNutzer4.yaml#/components/schemas/zertifikatsNutzer4'
          x-edifact-segment:
            - SG29.LIN+Z68.FTX+Z23
        zertifikatsNutzer5:
          $ref: '../../../bo4e/fields/com/ZertifikatsNutzer/zertifikatsNutzer5.yaml#/components/schemas/zertifikatsNutzer5'
          x-edifact-segment:
            - SG29.LIN+Z68.FTX+Z23
      required:
        - zertifikatsNutzer1
        - zertifikatsNutzer2
        - zertifikatsNutzer3
        - zertifikatsNutzer4
        - zertifikatsNutzer5
    PI_17130__stammdaten__WERTE_NACH_TYP2__zieladresse:
      type: object
      properties:
        zieladresse1:
          $ref: '../../../bo4e/fields/com/Zieladresse/zieladresse1.yaml#/components/schemas/zieladresse1'
          x-edifact-segment:
            - SG29.LIN+Z68.FTX+Z17
        zieladresse2:
          $ref: '../../../bo4e/fields/com/Zieladresse/zieladresse2.yaml#/components/schemas/zieladresse2'
          x-edifact-segment:
            - SG29.LIN+Z68.FTX+Z17
        zieladresse3:
          $ref: '../../../bo4e/fields/com/Zieladresse/zieladresse3.yaml#/components/schemas/zieladresse3'
          x-edifact-segment:
            - SG29.LIN+Z68.FTX+Z17
        zieladresse4:
          $ref: '../../../bo4e/fields/com/Zieladresse/zieladresse4.yaml#/components/schemas/zieladresse4'
          x-edifact-segment:
            - SG29.LIN+Z68.FTX+Z17
        zieladresse5:
          $ref: '../../../bo4e/fields/com/Zieladresse/zieladresse5.yaml#/components/schemas/zieladresse5'
          x-edifact-segment:
            - SG29.LIN+Z68.FTX+Z17
      required:
        - zieladresse1
        - zieladresse2
        - zieladresse3
        - zieladresse4
        - zieladresse5
