openapi: 3.1.0
info:
  title: PI_17135
  version: '202510'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: 39ae45d481e5cc3d4d7aae328a23a9751236156a
components:
  schemas:
    PI_17135:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_17135__stammdaten'
      required:
        - stammdaten
    PI_17135__stammdaten:
      type: object
      properties:
        ANFRAGE:
          type: array
          items:
            $ref: '#/components/schemas/PI_17135__stammdaten__ANFRAGE'
        AUFTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_17135__stammdaten__AUFTRAG'
        MARKTLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_17135__stammdaten__MARKTLOKATION'
        MESSLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_17135__stammdaten__MESSLOKATION'
        TRANCHE:
          type: array
          items:
            $ref: '#/components/schemas/PI_17135__stammdaten__TRANCHE'
      required:
        - ANFRAGE
        - AUFTRAG
        - MARKTLOKATION
        - MESSLOKATION
        - TRANCHE
    PI_17135__stammdaten__ANFRAGE:
      type: object
      properties:
        anfragetyp:
          $ref: '../../../bo4e/fields/bo/Anfrage/anfragetyp.yaml#/components/schemas/anfragetyp'
          x-edifact-segment:
            - 'IMD++[Z66|Z67]'
        lokationsId:
          $ref: '../../../bo4e/fields/bo/Anfrage/lokationsId.yaml#/components/schemas/lokationsId'
          x-edifact-segment:
            - SG2.NAD+DP.LOC+172
      required:
        - lokationsId
    PI_17135__stammdaten__AUFTRAG:
      type: object
      properties:
        ausfuehrungsdatum:
          $ref: '../../../bo4e/fields/bo/Auftrag/ausfuehrungsdatum.yaml#/components/schemas/ausfuehrungsdatum'
          x-edifact-segment:
            - DTM+203
        positionsdaten:
          type: array
          items:
            $ref: '#/components/schemas/PI_17135__stammdaten__AUFTRAG__positionsdaten'
      required:
        - ausfuehrungsdatum
        - positionsdaten
    PI_17135__stammdaten__AUFTRAG__positionsdaten:
      type: object
      properties:
        positionsnummer:
          $ref: '../../../bo4e/fields/com/AuftragPosition/positionsnummer.yaml#/components/schemas/positionsnummer'
          x-edifact-segment:
            - SG29.LIN++Z19
      required:
        - positionsnummer
    PI_17135__stammdaten__MARKTLOKATION:
      type: object
      properties:
        marktlokationsId:
          $ref: '../../../bo4e/fields/bo/Marktlokation/marktlokationsId.yaml#/components/schemas/marktlokationsId'
          x-edifact-segment:
            - SG2.NAD+DEB.SG3.RFF+Z59
            - SG2.NAD+DP.SG3.RFF+Z18
            - SG2.NAD+DP.SG3.RFF+Z59
            - SG2.NAD+SU.SG3.RFF+Z18
            - SG2.NAD+SU.SG3.RFF+Z59
        marktrollen:
          type: array
          items:
            $ref: '#/components/schemas/PI_17135__stammdaten__MARKTLOKATION__marktrollen'
      required:
        - marktlokationsId
        - marktrollen
    PI_17135__stammdaten__MARKTLOKATION__marktrollen:
      type: object
      properties:
        marktrolle:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/marktrolle.yaml#/components/schemas/marktrolle'
          x-edifact-segment:
            - SG2.NAD+DEB
            - SG2.NAD+SU
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+DEB
            - SG2.NAD+SU
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+DEB
            - SG2.NAD+SU
        weiterverpflichtet:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/weiterverpflichtet.yaml#/components/schemas/weiterverpflichtet'
          x-edifact-segment:
            - SG2.NAD+DEB
            - SG2.NAD+SU
      required:
        - marktrolle
        - rollencodenummer
        - rollencodetyp
        - weiterverpflichtet
    PI_17135__stammdaten__MESSLOKATION:
      type: object
      properties:
        zaehlwerke:
          type: array
          items:
            $ref: '#/components/schemas/PI_17135__stammdaten__MESSLOKATION__zaehlwerke'
      required:
        - zaehlwerke
    PI_17135__stammdaten__MESSLOKATION__zaehlwerke:
      type: object
      properties:
        messprodukt:
          $ref: '../../../bo4e/fields/com/Zaehlwerk/messprodukt.yaml#/components/schemas/messprodukt'
          x-edifact-segment:
            - SG29.LIN++Z19.PIA+5
        zaehlzeiten:
          $ref: '#/components/schemas/PI_17135__stammdaten__MESSLOKATION__zaehlwerke__zaehlzeiten'
      required:
        - messprodukt
        - zaehlzeiten
    PI_17135__stammdaten__MESSLOKATION__zaehlwerke__zaehlzeiten:
      type: object
      properties:
        zaehlzeitDefinition:
          $ref: '../../../bo4e/fields/com/Zaehlzeitregister/zaehlzeitDefinition.yaml#/components/schemas/zaehlzeitDefinition'
          x-edifact-segment:
            - 'SG29.LIN++Z19.SG30.CCI+[Z39|Z41]'
      required:
        - zaehlzeitDefinition
    PI_17135__stammdaten__TRANCHE:
      type: object
      properties:
        marktrollen:
          type: array
          items:
            $ref: '#/components/schemas/PI_17135__stammdaten__TRANCHE__marktrollen'
        tranchenId:
          $ref: '../../../bo4e/fields/bo/Tranche/tranchenId.yaml#/components/schemas/tranchenId'
          x-edifact-segment:
            - SG2.NAD+DP.SG3.RFF+Z20
            - SG2.NAD+SU.SG3.RFF+Z20
      required:
        - marktrollen
        - tranchenId
    PI_17135__stammdaten__TRANCHE__marktrollen:
      type: object
      properties:
        marktrolle:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/marktrolle.yaml#/components/schemas/marktrolle'
          x-edifact-segment:
            - SG2.NAD+SU
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+SU
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+SU
      required:
        - marktrolle
        - rollencodenummer
        - rollencodetyp
