openapi: 3.1.0
info:
  title: PI_17103
  version: '202510'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_17103:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_17103__stammdaten'
      required:
        - stammdaten
    PI_17103__stammdaten:
      type: object
      properties:
        ANFRAGE:
          type: array
          items:
            $ref: '#/components/schemas/PI_17103__stammdaten__ANFRAGE'
        AUFTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_17103__stammdaten__AUFTRAG'
      required:
        - ANFRAGE
        - AUFTRAG
    PI_17103__stammdaten__ANFRAGE:
      type: object
      properties:
        anfragekategorie:
          $ref: '../../../bo4e/fields/bo/Anfrage/anfragekategorie.yaml#/components/schemas/anfragekategorie'
          x-edifact-segment:
            - BGM+7
        anfragetyp:
          $ref: '../../../bo4e/fields/bo/Anfrage/anfragetyp.yaml#/components/schemas/anfragetyp'
          x-edifact-segment:
            - IMD++Z10
        lokationsId:
          $ref: '../../../bo4e/fields/bo/Anfrage/lokationsId.yaml#/components/schemas/lokationsId'
          x-edifact-segment:
            - SG2.NAD+DP.LOC+172
      required:
        - anfragekategorie
        - anfragetyp
        - lokationsId
    PI_17103__stammdaten__AUFTRAG:
      type: object
      properties:
        positionsdaten:
          type: array
          items:
            $ref: '#/components/schemas/PI_17103__stammdaten__AUFTRAG__positionsdaten'
      required:
        - positionsdaten
    PI_17103__stammdaten__AUFTRAG__positionsdaten:
      type: object
      properties:
        enddatum:
          $ref: '../../../bo4e/fields/com/AuftragPosition/enddatum.yaml#/components/schemas/enddatum'
          x-edifact-segment:
            - SG29.LIN.DTM+164
        startdatum:
          $ref: '../../../bo4e/fields/com/AuftragPosition/startdatum.yaml#/components/schemas/startdatum'
          x-edifact-segment:
            - SG29.LIN.DTM+163
      required:
        - enddatum
        - startdatum
