openapi: 3.1.0
info:
  title: PI_17122
  version: '202510'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_17122:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_17122__stammdaten'
      required:
        - stammdaten
    PI_17122__stammdaten:
      type: object
      properties:
        AUFTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_17122__stammdaten__AUFTRAG'
        LEISTUNGSKURVENDEFINITION:
          type: array
          items:
            $ref: '#/components/schemas/PI_17122__stammdaten__LEISTUNGSKURVENDEFINITION'
        REKLAMATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_17122__stammdaten__REKLAMATION'
        SCHALTZEITDEFINITION:
          type: array
          items:
            $ref: '#/components/schemas/PI_17122__stammdaten__SCHALTZEITDEFINITION'
        ZAEHLZEITDEFINITION:
          type: array
          items:
            $ref: '#/components/schemas/PI_17122__stammdaten__ZAEHLZEITDEFINITION'
      required:
        - AUFTRAG
        - LEISTUNGSKURVENDEFINITION
        - REKLAMATION
        - SCHALTZEITDEFINITION
        - ZAEHLZEITDEFINITION
    PI_17122__stammdaten__AUFTRAG:
      type: object
      properties:
        positionsdaten:
          type: array
          items:
            $ref: '#/components/schemas/PI_17122__stammdaten__AUFTRAG__positionsdaten'
      required:
        - positionsdaten
    PI_17122__stammdaten__AUFTRAG__positionsdaten:
      type: object
      properties:
        definitionsTyp:
          $ref: '../../../bo4e/fields/com/AuftragPosition/definitionsTyp.yaml#/components/schemas/definitionsTyp'
          x-edifact-segment:
            - SG29.LIN
        positionsnummer:
          $ref: '../../../bo4e/fields/com/AuftragPosition/positionsnummer.yaml#/components/schemas/positionsnummer'
          x-edifact-segment:
            - SG29.LIN
      required:
        - definitionsTyp
        - positionsnummer
    PI_17122__stammdaten__LEISTUNGSKURVENDEFINITION:
      type: object
      properties:
        leistungskurven:
          type: array
          items:
            $ref: '#/components/schemas/PI_17122__stammdaten__LEISTUNGSKURVENDEFINITION__leistungskurven'
      required:
        - leistungskurven
    PI_17122__stammdaten__LEISTUNGSKURVENDEFINITION__leistungskurven:
      type: object
      properties:
        code:
          $ref: '../../../bo4e/fields/com/Leistungskurve/code.yaml#/components/schemas/code'
          x-edifact-segment:
            - SG29.LIN.SG30.CCI+Z52
      required:
        - code
    PI_17122__stammdaten__REKLAMATION:
      type: object
      properties:
        reklamationsgrund:
          $ref: '../../../bo4e/fields/bo/Reklamation/reklamationsgrund.yaml#/components/schemas/reklamationsgrund'
          x-edifact-segment:
            - 'SG29.LIN.FTX+[Z07|Z08|Z09|Z10]'
        reklamationsgrundBemerkung:
          $ref: '#/components/schemas/PI_17122__stammdaten__REKLAMATION__reklamationsgrundBemerkung'
      required:
        - reklamationsgrund
        - reklamationsgrundBemerkung
    PI_17122__stammdaten__REKLAMATION__reklamationsgrundBemerkung:
      type: object
      properties:
        bemerkung1:
          $ref: '../../../bo4e/fields/com/ReklamationsgrundBemerkung/bemerkung1.yaml#/components/schemas/bemerkung1'
          x-edifact-segment:
            - 'SG29.LIN.FTX+[Z07|Z08|Z09|Z10]'
        bemerkung2:
          $ref: '../../../bo4e/fields/com/ReklamationsgrundBemerkung/bemerkung2.yaml#/components/schemas/bemerkung2'
          x-edifact-segment:
            - 'SG29.LIN.FTX+[Z07|Z08|Z09|Z10]'
        bemerkung3:
          $ref: '../../../bo4e/fields/com/ReklamationsgrundBemerkung/bemerkung3.yaml#/components/schemas/bemerkung3'
          x-edifact-segment:
            - 'SG29.LIN.FTX+[Z07|Z08|Z09|Z10]'
        bemerkung4:
          $ref: '../../../bo4e/fields/com/ReklamationsgrundBemerkung/bemerkung4.yaml#/components/schemas/bemerkung4'
          x-edifact-segment:
            - 'SG29.LIN.FTX+[Z07|Z08|Z09|Z10]'
        bemerkung5:
          $ref: '../../../bo4e/fields/com/ReklamationsgrundBemerkung/bemerkung5.yaml#/components/schemas/bemerkung5'
          x-edifact-segment:
            - 'SG29.LIN.FTX+[Z07|Z08|Z09|Z10]'
      required:
        - bemerkung1
        - bemerkung2
        - bemerkung3
        - bemerkung4
        - bemerkung5
    PI_17122__stammdaten__SCHALTZEITDEFINITION:
      type: object
      properties:
        schaltzeiten:
          type: array
          items:
            $ref: '#/components/schemas/PI_17122__stammdaten__SCHALTZEITDEFINITION__schaltzeiten'
      required:
        - schaltzeiten
    PI_17122__stammdaten__SCHALTZEITDEFINITION__schaltzeiten:
      type: object
      properties:
        code:
          $ref: '../../../bo4e/fields/com/Schaltzeit/code.yaml#/components/schemas/code'
          x-edifact-segment:
            - SG29.LIN.SG30.CCI+Z52
      required:
        - code
    PI_17122__stammdaten__ZAEHLZEITDEFINITION:
      type: object
      properties:
        zaehlzeiten:
          type: array
          items:
            $ref: '#/components/schemas/PI_17122__stammdaten__ZAEHLZEITDEFINITION__zaehlzeiten'
      required:
        - zaehlzeiten
    PI_17122__stammdaten__ZAEHLZEITDEFINITION__zaehlzeiten:
      type: object
      properties:
        code:
          $ref: '../../../bo4e/fields/com/Zaehlzeit/code.yaml#/components/schemas/code'
          x-edifact-segment:
            - SG29.LIN.SG30.CCI
      required:
        - code
