openapi: 3.1.0
info:
  title: PI_17121
  version: '202510'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: 39ae45d481e5cc3d4d7aae328a23a9751236156a
components:
  schemas:
    PI_17121:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_17121__stammdaten'
      required:
        - stammdaten
    PI_17121__stammdaten:
      type: object
      properties:
        ANFRAGE:
          type: array
          items:
            $ref: '#/components/schemas/PI_17121__stammdaten__ANFRAGE'
        AUFTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_17121__stammdaten__AUFTRAG'
        MARKTLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_17121__stammdaten__MARKTLOKATION'
        MESSLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_17121__stammdaten__MESSLOKATION'
        NETZLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_17121__stammdaten__NETZLOKATION'
        TRANCHE:
          type: array
          items:
            $ref: '#/components/schemas/PI_17121__stammdaten__TRANCHE'
      required:
        - ANFRAGE
        - AUFTRAG
        - MARKTLOKATION
        - MESSLOKATION
        - NETZLOKATION
        - TRANCHE
    PI_17121__stammdaten__ANFRAGE:
      type: object
      properties:
        energierichtung:
          $ref: '../../../bo4e/fields/bo/Anfrage/energierichtung.yaml#/components/schemas/energierichtung'
          x-edifact-segment:
            - IMD++Z14
        lokationsId:
          $ref: '../../../bo4e/fields/bo/Anfrage/lokationsId.yaml#/components/schemas/lokationsId'
          x-edifact-segment:
            - SG2.NAD+DP.LOC+172
      required:
        - energierichtung
        - lokationsId
    PI_17121__stammdaten__AUFTRAG:
      type: object
      properties:
        ausfuehrungsdatum:
          $ref: '../../../bo4e/fields/bo/Auftrag/ausfuehrungsdatum.yaml#/components/schemas/ausfuehrungsdatum'
          x-edifact-segment:
            - DTM+203
        positionsdaten:
          type: array
          items:
            $ref: '#/components/schemas/PI_17121__stammdaten__AUFTRAG__positionsdaten'
      required:
        - ausfuehrungsdatum
        - positionsdaten
    PI_17121__stammdaten__AUFTRAG__positionsdaten:
      type: object
      properties:
        positionsnummer:
          $ref: '../../../bo4e/fields/com/AuftragPosition/positionsnummer.yaml#/components/schemas/positionsnummer'
          x-edifact-segment:
            - SG29.LIN+Z16
            - SG29.LIN+Z19
            - SG29.LIN+Z54
            - SG29.LIN+Z55
      required:
        - positionsnummer
    PI_17121__stammdaten__MARKTLOKATION:
      type: object
      properties:
        zaehlwerke:
          type: array
          items:
            $ref: '#/components/schemas/PI_17121__stammdaten__MARKTLOKATION__zaehlwerke'
      required:
        - zaehlwerke
    PI_17121__stammdaten__MARKTLOKATION__zaehlwerke:
      type: object
      properties:
        messprodukt:
          $ref: '../../../bo4e/fields/com/Zaehlwerk/messprodukt.yaml#/components/schemas/messprodukt'
          x-edifact-segment:
            - SG29.LIN+Z54.PIA+5
        verwendungszwecke:
          type: array
          items:
            $ref: '#/components/schemas/PI_17121__stammdaten__MARKTLOKATION__zaehlwerke__verwendungszwecke'
        zaehlzeiten:
          $ref: '#/components/schemas/PI_17121__stammdaten__MARKTLOKATION__zaehlwerke__zaehlzeiten'
      required:
        - messprodukt
        - verwendungszwecke
        - zaehlzeiten
    PI_17121__stammdaten__MARKTLOKATION__zaehlwerke__verwendungszwecke:
      type: object
      properties:
        marktrolle:
          $ref: '../../../bo4e/fields/com/Verwendungszweck/marktrolle.yaml#/components/schemas/marktrolle'
          x-edifact-segment:
            - SG29.LIN+Z54.SG30.CCI+ZA7.CAV
            - SG29.LIN+Z54.SG30.CCI+ZA8.CAV
            - SG29.LIN+Z54.SG30.CCI+ZA9.CAV
        zweck:
          $ref: '../../../bo4e/fields/com/Verwendungszweck/zweck.yaml#/components/schemas/zweck'
          x-edifact-segment:
            - SG29.LIN+Z54.SG30.CCI+ZA7.CAV
            - SG29.LIN+Z54.SG30.CCI+ZA8.CAV
            - SG29.LIN+Z54.SG30.CCI+ZA9.CAV
      required:
        - marktrolle
        - zweck
    PI_17121__stammdaten__MARKTLOKATION__zaehlwerke__zaehlzeiten:
      type: object
      properties:
        zaehlzeitDefinition:
          $ref: '../../../bo4e/fields/com/Zaehlzeitregister/zaehlzeitDefinition.yaml#/components/schemas/zaehlzeitDefinition'
          x-edifact-segment:
            - 'SG29.LIN+Z54.SG30.CCI+[Z39|Z41]'
      required:
        - zaehlzeitDefinition
    PI_17121__stammdaten__MESSLOKATION:
      type: object
      properties:
        messlokationsId:
          $ref: '../../../bo4e/fields/bo/Messlokation/messlokationsId.yaml#/components/schemas/messlokationsId'
          x-edifact-segment:
            - SG29.LIN+Z19.SG34.RFF+Z19
        zaehlwerke:
          type: array
          items:
            $ref: '#/components/schemas/PI_17121__stammdaten__MESSLOKATION__zaehlwerke'
      required:
        - messlokationsId
        - zaehlwerke
    PI_17121__stammdaten__MESSLOKATION__zaehlwerke:
      type: object
      properties:
        messprodukt:
          $ref: '../../../bo4e/fields/com/Zaehlwerk/messprodukt.yaml#/components/schemas/messprodukt'
          x-edifact-segment:
            - SG29.LIN+Z19.PIA+5
        notwendigkeitZweiteMessung:
          $ref: '../../../bo4e/fields/com/Zaehlwerk/notwendigkeitZweiteMessung.yaml#/components/schemas/notwendigkeitZweiteMessung'
          x-edifact-segment:
            - SG29.LIN+Z19.SG30.CCI+Z35.CAV+ZC9
        werteuebermittlungVerwendungszweck:
          $ref: '../../../bo4e/fields/com/Zaehlwerk/werteuebermittlungVerwendungszweck.yaml#/components/schemas/werteuebermittlungVerwendungszweck'
          x-edifact-segment:
            - SG29.LIN+Z19.SG30.CCI+Z35.CAV+Z88
        zaehlzeiten:
          $ref: '#/components/schemas/PI_17121__stammdaten__MESSLOKATION__zaehlwerke__zaehlzeiten'
      required:
        - messprodukt
        - notwendigkeitZweiteMessung
        - werteuebermittlungVerwendungszweck
        - zaehlzeiten
    PI_17121__stammdaten__MESSLOKATION__zaehlwerke__zaehlzeiten:
      type: object
      properties:
        zaehlzeitDefinition:
          $ref: '../../../bo4e/fields/com/Zaehlzeitregister/zaehlzeitDefinition.yaml#/components/schemas/zaehlzeitDefinition'
          x-edifact-segment:
            - 'SG29.LIN+Z19.SG30.CCI+[Z39|Z41]'
      required:
        - zaehlzeitDefinition
    PI_17121__stammdaten__NETZLOKATION:
      type: object
      properties:
        zaehlwerke:
          type: array
          items:
            $ref: '#/components/schemas/PI_17121__stammdaten__NETZLOKATION__zaehlwerke'
      required:
        - zaehlwerke
    PI_17121__stammdaten__NETZLOKATION__zaehlwerke:
      type: object
      properties:
        messprodukt:
          $ref: '../../../bo4e/fields/com/Zaehlwerk/messprodukt.yaml#/components/schemas/messprodukt'
          x-edifact-segment:
            - SG29.LIN+Z55.PIA+5
        verwendungszwecke:
          type: array
          items:
            $ref: '#/components/schemas/PI_17121__stammdaten__NETZLOKATION__zaehlwerke__verwendungszwecke'
      required:
        - messprodukt
        - verwendungszwecke
    PI_17121__stammdaten__NETZLOKATION__zaehlwerke__verwendungszwecke:
      type: object
      properties:
        marktrolle:
          $ref: '../../../bo4e/fields/com/Verwendungszweck/marktrolle.yaml#/components/schemas/marktrolle'
          x-edifact-segment:
            - SG29.LIN+Z55.SG30.CCI+ZA7.CAV
            - SG29.LIN+Z55.SG30.CCI+ZA8.CAV
        zweck:
          $ref: '../../../bo4e/fields/com/Verwendungszweck/zweck.yaml#/components/schemas/zweck'
          x-edifact-segment:
            - SG29.LIN+Z55.SG30.CCI+ZA7.CAV
            - SG29.LIN+Z55.SG30.CCI+ZA8.CAV
      required:
        - marktrolle
        - zweck
    PI_17121__stammdaten__TRANCHE:
      type: object
      properties:
        tranchenId:
          $ref: '../../../bo4e/fields/bo/Tranche/tranchenId.yaml#/components/schemas/tranchenId'
          x-edifact-segment:
            - SG29.LIN+Z16.SG34.RFF+Z20
        zaehlwerke:
          type: array
          items:
            $ref: '#/components/schemas/PI_17121__stammdaten__TRANCHE__zaehlwerke'
      required:
        - tranchenId
        - zaehlwerke
    PI_17121__stammdaten__TRANCHE__zaehlwerke:
      type: object
      properties:
        messprodukt:
          $ref: '../../../bo4e/fields/com/Zaehlwerk/messprodukt.yaml#/components/schemas/messprodukt'
          x-edifact-segment:
            - SG29.LIN+Z16.PIA+5
        verwendungszwecke:
          type: array
          items:
            $ref: '#/components/schemas/PI_17121__stammdaten__TRANCHE__zaehlwerke__verwendungszwecke'
      required:
        - messprodukt
        - verwendungszwecke
    PI_17121__stammdaten__TRANCHE__zaehlwerke__verwendungszwecke:
      type: object
      properties:
        marktrolle:
          $ref: '../../../bo4e/fields/com/Verwendungszweck/marktrolle.yaml#/components/schemas/marktrolle'
          x-edifact-segment:
            - SG29.LIN+Z16.SG30.CCI+ZA7.CAV
            - SG29.LIN+Z16.SG30.CCI+ZA8.CAV
            - SG29.LIN+Z16.SG30.CCI+ZA9.CAV
        zweck:
          $ref: '../../../bo4e/fields/com/Verwendungszweck/zweck.yaml#/components/schemas/zweck'
          x-edifact-segment:
            - SG29.LIN+Z16.SG30.CCI+ZA7.CAV
            - SG29.LIN+Z16.SG30.CCI+ZA8.CAV
            - SG29.LIN+Z16.SG30.CCI+ZA9.CAV
      required:
        - marktrolle
        - zweck
