openapi: 3.1.0
info:
  title: PI_55003
  version: '202610'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_55003:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_55003__masterData'
      required:
      - masterData
    PI_55003__masterData:
      type: object
      properties:
        MARKET_LOCATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_55003__masterData__MARKET_LOCATION'
      required:
      - MARKET_LOCATION
    PI_55003__masterData__MARKET_LOCATION:
      type: object
      properties:
        requiredProductPackage:
          type: array
          items:
            $ref: '#/components/schemas/PI_55003__masterData__MARKET_LOCATION__requiredProductPackage'
      required:
      - requiredProductPackage
    PI_55003__masterData__MARKET_LOCATION__requiredProductPackage:
      type: object
      properties:
        product:
          type: array
          items:
            $ref: '#/components/schemas/PI_55003__masterData__MARKET_LOCATION__requiredProductPackage__product'
        productPackageId:
          $ref: ../../../bo4e-en/fields/com/ProductPackage/productPackageId.yaml#/components/schemas/productPackageId
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z79
      required:
      - product
      - productPackageId
    PI_55003__masterData__MARKET_LOCATION__requiredProductPackage__product:
      type: object
      properties:
        productCode:
          $ref: ../../../bo4e-en/fields/com/Product/productCode.yaml#/components/schemas/productCode
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z79.PIA+5
      required:
      - productCode
