openapi: 3.1.0
info:
  title: PI_21043
  version: '202510'
  x-bo4e-schema-version: 1.7.4
  x-bo4e-schema-sha: 1732e948753541a9b641ca98f3d8ff189d994263
  x-templater-sha: 392a2eb2993418f8a5be64578c22568416e2d551
components:
  schemas:
    PI_21043:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_21043__masterData'
      required:
      - masterData
    PI_21043__masterData:
      type: object
      properties:
        STATUS_NOTIFICATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_21043__masterData__STATUS_NOTIFICATION'
      required:
      - STATUS_NOTIFICATION
    PI_21043__masterData__STATUS_NOTIFICATION:
      type: object
      properties:
        orderStatus:
          $ref: ../../../bo4e-en/fields/bo/StatusNotification/orderStatus.yaml#/components/schemas/orderStatus
          x-edifact-segment:
          - SG14.CNI.SG15.STS+Z21
        positionData:
          type: array
          items:
            $ref: '#/components/schemas/PI_21043__masterData__STATUS_NOTIFICATION__positionData'
      required:
      - orderStatus
      - positionData
    PI_21043__masterData__STATUS_NOTIFICATION__positionData:
      type: object
      properties:
        generalInformation:
          $ref: '#/components/schemas/PI_21043__masterData__STATUS_NOTIFICATION__positionData__generalInformation'
        positionNumber:
          $ref: ../../../bo4e-en/fields/com/StatusNotificationPosition/positionNumber.yaml#/components/schemas/positionNumber
          x-edifact-segment:
          - SG14.CNI
        statusChangeTimestamp:
          $ref: ../../../bo4e-en/fields/com/StatusNotificationPosition/statusChangeTimestamp.yaml#/components/schemas/statusChangeTimestamp
          x-edifact-segment:
          - SG14.CNI.SG15.STS+Z21.DTM+334
      required:
      - generalInformation
      - positionNumber
      - statusChangeTimestamp
    PI_21043__masterData__STATUS_NOTIFICATION__positionData__generalInformation:
      type: object
      properties:
        info1:
          $ref: ../../../bo4e-en/fields/com/GeneralInformation/info1.yaml#/components/schemas/info1
          x-edifact-segment:
          - SG14.CNI.SG15.STS+Z21.SG25.GID.FTX+ACB
        info2:
          $ref: ../../../bo4e-en/fields/com/GeneralInformation/info2.yaml#/components/schemas/info2
          x-edifact-segment:
          - SG14.CNI.SG15.STS+Z21.SG25.GID.FTX+ACB
        info3:
          $ref: ../../../bo4e-en/fields/com/GeneralInformation/info3.yaml#/components/schemas/info3
          x-edifact-segment:
          - SG14.CNI.SG15.STS+Z21.SG25.GID.FTX+ACB
        info4:
          $ref: ../../../bo4e-en/fields/com/GeneralInformation/info4.yaml#/components/schemas/info4
          x-edifact-segment:
          - SG14.CNI.SG15.STS+Z21.SG25.GID.FTX+ACB
        info5:
          $ref: ../../../bo4e-en/fields/com/GeneralInformation/info5.yaml#/components/schemas/info5
          x-edifact-segment:
          - SG14.CNI.SG15.STS+Z21.SG25.GID.FTX+ACB
      required:
      - info1
      - info2
      - info3
      - info4
      - info5
