openapi: 3.1.0
info:
  title: PI_44017
  version: '202604'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: 39ae45d481e5cc3d4d7aae328a23a9751236156a
components:
  schemas:
    PI_44017:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_44017__stammdaten'
        transaktionsdaten:
          $ref: '#/components/schemas/PI_44017__transaktionsdaten'
      required:
        - stammdaten
        - transaktionsdaten
    PI_44017__stammdaten:
      type: object
      properties:
        BILANZIERUNG:
          type: array
          items:
            $ref: '#/components/schemas/PI_44017__stammdaten__BILANZIERUNG'
        ENERGIELIEFERVERTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_44017__stammdaten__ENERGIELIEFERVERTRAG'
        MARKTLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_44017__stammdaten__MARKTLOKATION'
        NETZNUTZUNGSVERTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_44017__stammdaten__NETZNUTZUNGSVERTRAG'
      required:
        - BILANZIERUNG
        - ENERGIELIEFERVERTRAG
        - MARKTLOKATION
    PI_44017__stammdaten__BILANZIERUNG:
      type: object
      properties:
        vorjahresverbrauch:
          $ref: '#/components/schemas/PI_44017__stammdaten__BILANZIERUNG__vorjahresverbrauch'
      required:
        - vorjahresverbrauch
    PI_44017__stammdaten__BILANZIERUNG__vorjahresverbrauch:
      type: object
      properties:
        einheit:
          $ref: '../../../bo4e/fields/com/Menge/einheit.yaml#/components/schemas/einheit'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z01.SG9.QTY+Z09
        wert:
          $ref: '../../../bo4e/fields/com/Menge/wert.yaml#/components/schemas/wert'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z01.SG9.QTY+Z09
      required:
        - einheit
        - wert
    PI_44017__stammdaten__ENERGIELIEFERVERTRAG:
      type: object
      properties:
        vertragspartner2:
          type: array
          items:
            $ref: '#/components/schemas/PI_44017__stammdaten__ENERGIELIEFERVERTRAG__vertragspartner2'
      required:
        - vertragspartner2
    PI_44017__stammdaten__ENERGIELIEFERVERTRAG__vertragspartner2:
      type: object
      properties:
        anrede:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/anrede.yaml#/components/schemas/anrede'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z09
        externeReferenzen:
          type: array
          items:
            $ref: '#/components/schemas/PI_44017__stammdaten__ENERGIELIEFERVERTRAG__vertragspartner2__externeReferenzen'
        gewerbekennzeichnung:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/gewerbekennzeichnung.yaml#/components/schemas/gewerbekennzeichnung'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z09
        name1:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name1.yaml#/components/schemas/name1'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z09
        name2:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name2.yaml#/components/schemas/name2'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z09
        name3:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name3.yaml#/components/schemas/name3'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z09
        name4:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name4.yaml#/components/schemas/name4'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z09
      required:
        - anrede
        - gewerbekennzeichnung
        - name1
        - name2
        - name3
        - name4
    PI_44017__stammdaten__ENERGIELIEFERVERTRAG__vertragspartner2__externeReferenzen:
      type: object
      properties:
        exRefName:
          $ref: '../../../bo4e/fields/com/ExterneReferenz/exRefName.yaml#/components/schemas/exRefName'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z09.RFF+Z01
        exRefWert:
          $ref: '../../../bo4e/fields/com/ExterneReferenz/exRefWert.yaml#/components/schemas/exRefWert'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z09.RFF+Z01
    PI_44017__stammdaten__MARKTLOKATION:
      type: object
      properties:
        lokationsadresse:
          $ref: '#/components/schemas/PI_44017__stammdaten__MARKTLOKATION__lokationsadresse'
        marktlokationsId:
          $ref: '../../../bo4e/fields/bo/Marktlokation/marktlokationsId.yaml#/components/schemas/marktlokationsId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+172
      required:
        - lokationsadresse
        - marktlokationsId
    PI_44017__stammdaten__MARKTLOKATION__lokationsadresse:
      type: object
      properties:
        hausnummer:
          $ref: '../../../bo4e/fields/com/Adresse/hausnummer.yaml#/components/schemas/hausnummer'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+DP
        landescode:
          $ref: '../../../bo4e/fields/com/Adresse/landescode.yaml#/components/schemas/landescode'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+DP
        ort:
          $ref: '../../../bo4e/fields/com/Adresse/ort.yaml#/components/schemas/ort'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+DP
        ortsteil:
          $ref: '../../../bo4e/fields/com/Adresse/ortsteil.yaml#/components/schemas/ortsteil'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+DP
        postfach:
          $ref: '../../../bo4e/fields/com/Adresse/postfach.yaml#/components/schemas/postfach'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+DP
        postleitzahl:
          $ref: '../../../bo4e/fields/com/Adresse/postleitzahl.yaml#/components/schemas/postleitzahl'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+DP
        strasse:
          $ref: '../../../bo4e/fields/com/Adresse/strasse.yaml#/components/schemas/strasse'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+DP
        zusatzInformation:
          $ref: '#/components/schemas/PI_44017__stammdaten__MARKTLOKATION__lokationsadresse__zusatzInformation'
      required:
        - hausnummer
        - landescode
        - ort
        - ortsteil
        - postfach
        - postleitzahl
        - strasse
        - zusatzInformation
    PI_44017__stammdaten__MARKTLOKATION__lokationsadresse__zusatzInformation:
      type: object
      properties:
        zusatz1:
          $ref: '../../../bo4e/fields/com/AdresszusatzInformation/zusatz1.yaml#/components/schemas/zusatz1'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+DP
        zusatz2:
          $ref: '../../../bo4e/fields/com/AdresszusatzInformation/zusatz2.yaml#/components/schemas/zusatz2'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+DP
        zusatz3:
          $ref: '../../../bo4e/fields/com/AdresszusatzInformation/zusatz3.yaml#/components/schemas/zusatz3'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+DP
        zusatz4:
          $ref: '../../../bo4e/fields/com/AdresszusatzInformation/zusatz4.yaml#/components/schemas/zusatz4'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+DP
        zusatz5:
          $ref: '../../../bo4e/fields/com/AdresszusatzInformation/zusatz5.yaml#/components/schemas/zusatz5'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+DP
      required:
        - zusatz1
        - zusatz2
        - zusatz3
        - zusatz4
        - zusatz5
    PI_44017__stammdaten__NETZNUTZUNGSVERTRAG:
      type: object
      properties:
        vertragsende:
          $ref: '../../../bo4e/fields/bo/Vertrag/vertragsende.yaml#/components/schemas/vertragsende'
          x-edifact-segment:
            - SG4.IDE+24.DTM+93
    PI_44017__transaktionsdaten:
      type: object
      properties:
        absender:
          $ref: '#/components/schemas/PI_44017__transaktionsdaten__absender'
        anfragereferenznummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/anfragereferenznummer.yaml#/components/schemas/anfragereferenznummer'
          x-edifact-segment:
            - SG4.IDE+24.SG6.RFF+TN
        antwortstatus:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/antwortstatus.yaml#/components/schemas/antwortstatus'
          x-edifact-segment:
            - SG4.IDE+24.STS+E01
        antwortstatusCodeliste:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/antwortstatusCodeliste.yaml#/components/schemas/antwortstatusCodeliste'
          x-edifact-segment:
            - SG4.IDE+24.STS+E01
        dokumentennummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/dokumentennummer.yaml#/components/schemas/dokumentennummer'
          x-edifact-segment:
            - BGM+E35
        empfaenger:
          $ref: '#/components/schemas/PI_44017__transaktionsdaten__empfaenger'
        endezumtermin:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/endezumtermin.yaml#/components/schemas/endezumtermin'
          x-edifact-segment:
            - SG4.IDE+24.DTM+471
        freitext:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/freitext.yaml#/components/schemas/freitext'
          x-edifact-segment:
            - SG4.IDE+24.FTX+ACB
        kategorie:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/kategorie.yaml#/components/schemas/kategorie'
          x-edifact-segment:
            - BGM+E35
        nachrichtendatum:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtendatum.yaml#/components/schemas/nachrichtendatum'
          x-edifact-segment:
            - DTM+137
        nachrichtenreferenznummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtenreferenznummer.yaml#/components/schemas/nachrichtenreferenznummer'
          x-edifact-segment:
            - UNH
        pruefidentifikator:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/pruefidentifikator.yaml#/components/schemas/pruefidentifikator'
          x-edifact-segment:
            - SG4.IDE+24.SG6.RFF+Z13
        transaktionsgrund:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/transaktionsgrund.yaml#/components/schemas/transaktionsgrund'
          x-edifact-segment:
            - SG4.IDE+24.STS+7
        vertragsende:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/vertragsende.yaml#/components/schemas/vertragsende'
          x-edifact-segment:
            - SG4.IDE+24.DTM+93
        vorgangsnummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/vorgangsnummer.yaml#/components/schemas/vorgangsnummer'
          x-edifact-segment:
            - SG4.IDE+24
      required:
        - absender
        - anfragereferenznummer
        - antwortstatus
        - antwortstatusCodeliste
        - dokumentennummer
        - empfaenger
        - kategorie
        - nachrichtendatum
        - nachrichtenreferenznummer
        - pruefidentifikator
        - transaktionsgrund
        - vorgangsnummer
    PI_44017__transaktionsdaten__absender:
      type: object
      properties:
        ansprechpartner:
          $ref: '#/components/schemas/PI_44017__transaktionsdaten__absender__ansprechpartner'
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+MS
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+MS
      required:
        - ansprechpartner
        - rollencodenummer
        - rollencodetyp
    PI_44017__transaktionsdaten__absender__ansprechpartner:
      type: object
      properties:
        eMailAdresse:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/eMailAdresse.yaml#/components/schemas/eMailAdresse'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]'
        nachname:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/nachname.yaml#/components/schemas/nachname'
          x-edifact-segment:
            - SG2.NAD+MS.SG3.CTA
        rufnummern:
          type: array
          items:
            $ref: '#/components/schemas/PI_44017__transaktionsdaten__absender__ansprechpartner__rufnummern'
      required:
        - eMailAdresse
        - nachname
        - rufnummern
    PI_44017__transaktionsdaten__absender__ansprechpartner__rufnummern:
      type: object
      properties:
        nummerntyp:
          $ref: '../../../bo4e/fields/com/Rufnummer/nummerntyp.yaml#/components/schemas/nummerntyp'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]'
        rufnummer:
          $ref: '../../../bo4e/fields/com/Rufnummer/rufnummer.yaml#/components/schemas/rufnummer'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]'
      required:
        - nummerntyp
        - rufnummer
    PI_44017__transaktionsdaten__empfaenger:
      type: object
      properties:
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+MR
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+MR
      required:
        - rollencodenummer
        - rollencodetyp
