openapi: 3.1.0
info:
  title: PI_44018
  version: '202604'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: 39ae45d481e5cc3d4d7aae328a23a9751236156a
components:
  schemas:
    PI_44018:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_44018__stammdaten'
        transaktionsdaten:
          $ref: '#/components/schemas/PI_44018__transaktionsdaten'
      required:
        - stammdaten
        - transaktionsdaten
    PI_44018__stammdaten:
      type: object
      properties:
        ENERGIELIEFERVERTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_44018__stammdaten__ENERGIELIEFERVERTRAG'
        MARKTLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_44018__stammdaten__MARKTLOKATION'
      required:
        - MARKTLOKATION
    PI_44018__stammdaten__ENERGIELIEFERVERTRAG:
      type: object
      properties:
        vertragskonditionen:
          $ref: '#/components/schemas/PI_44018__stammdaten__ENERGIELIEFERVERTRAG__vertragskonditionen'
    PI_44018__stammdaten__ENERGIELIEFERVERTRAG__vertragskonditionen:
      type: object
      properties:
        kuendigungsfrist:
          $ref: '#/components/schemas/PI_44018__stammdaten__ENERGIELIEFERVERTRAG__vertragskonditionen__kuendigungsfrist'
        kuendigungstermin:
          $ref: '../../../bo4e/fields/com/Vertragskonditionen/kuendigungstermin.yaml#/components/schemas/kuendigungstermin'
          x-edifact-segment:
            - SG4.IDE+24.DTM+Z10
    PI_44018__stammdaten__ENERGIELIEFERVERTRAG__vertragskonditionen__kuendigungsfrist:
      type: object
      properties:
        zeitraumText:
          $ref: '../../../bo4e/fields/com/Zeitraum/zeitraumText.yaml#/components/schemas/zeitraumText'
          x-edifact-segment:
            - SG4.IDE+24.DTM+Z01
    PI_44018__stammdaten__MARKTLOKATION:
      type: object
      properties:
        marktlokationsId:
          $ref: '../../../bo4e/fields/bo/Marktlokation/marktlokationsId.yaml#/components/schemas/marktlokationsId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+172
      required:
        - marktlokationsId
    PI_44018__transaktionsdaten:
      type: object
      properties:
        absender:
          $ref: '#/components/schemas/PI_44018__transaktionsdaten__absender'
        anfragereferenznummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/anfragereferenznummer.yaml#/components/schemas/anfragereferenznummer'
          x-edifact-segment:
            - SG4.IDE+24.SG6.RFF+TN
        antwortstatus:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/antwortstatus.yaml#/components/schemas/antwortstatus'
          x-edifact-segment:
            - SG4.IDE+24.STS+E01
        antwortstatusCodeliste:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/antwortstatusCodeliste.yaml#/components/schemas/antwortstatusCodeliste'
          x-edifact-segment:
            - SG4.IDE+24.STS+E01
        datumKuendigungKd:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/datumKuendigungKd.yaml#/components/schemas/datumKuendigungKd'
          x-edifact-segment:
            - 'SG4.IDE+24.DTM+[Z05|Z06]'
        datumKuendigungLf:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/datumKuendigungLf.yaml#/components/schemas/datumKuendigungLf'
          x-edifact-segment:
            - 'SG4.IDE+24.DTM+[Z05|Z06]'
        dokumentennummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/dokumentennummer.yaml#/components/schemas/dokumentennummer'
          x-edifact-segment:
            - BGM+E35
        empfaenger:
          $ref: '#/components/schemas/PI_44018__transaktionsdaten__empfaenger'
        freitext:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/freitext.yaml#/components/schemas/freitext'
          x-edifact-segment:
            - SG4.IDE+24.FTX+ACB
        gueltigAb:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/gueltigAb.yaml#/components/schemas/gueltigAb'
          x-edifact-segment:
            - SG4.IDE+24.DTM+157
        kategorie:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/kategorie.yaml#/components/schemas/kategorie'
          x-edifact-segment:
            - BGM+E35
        nachrichtendatum:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtendatum.yaml#/components/schemas/nachrichtendatum'
          x-edifact-segment:
            - DTM+137
        nachrichtenreferenznummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtenreferenznummer.yaml#/components/schemas/nachrichtenreferenznummer'
          x-edifact-segment:
            - UNH
        pruefidentifikator:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/pruefidentifikator.yaml#/components/schemas/pruefidentifikator'
          x-edifact-segment:
            - SG4.IDE+24.SG6.RFF+Z13
        transaktionsgrund:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/transaktionsgrund.yaml#/components/schemas/transaktionsgrund'
          x-edifact-segment:
            - SG4.IDE+24.STS+7
        vorgangsnummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/vorgangsnummer.yaml#/components/schemas/vorgangsnummer'
          x-edifact-segment:
            - SG4.IDE+24
      required:
        - absender
        - anfragereferenznummer
        - antwortstatus
        - antwortstatusCodeliste
        - dokumentennummer
        - empfaenger
        - kategorie
        - nachrichtendatum
        - nachrichtenreferenznummer
        - pruefidentifikator
        - transaktionsgrund
        - vorgangsnummer
    PI_44018__transaktionsdaten__absender:
      type: object
      properties:
        ansprechpartner:
          $ref: '#/components/schemas/PI_44018__transaktionsdaten__absender__ansprechpartner'
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+MS
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+MS
      required:
        - ansprechpartner
        - rollencodenummer
        - rollencodetyp
    PI_44018__transaktionsdaten__absender__ansprechpartner:
      type: object
      properties:
        eMailAdresse:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/eMailAdresse.yaml#/components/schemas/eMailAdresse'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]'
        nachname:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/nachname.yaml#/components/schemas/nachname'
          x-edifact-segment:
            - SG2.NAD+MS.SG3.CTA
        rufnummern:
          type: array
          items:
            $ref: '#/components/schemas/PI_44018__transaktionsdaten__absender__ansprechpartner__rufnummern'
      required:
        - eMailAdresse
        - nachname
        - rufnummern
    PI_44018__transaktionsdaten__absender__ansprechpartner__rufnummern:
      type: object
      properties:
        nummerntyp:
          $ref: '../../../bo4e/fields/com/Rufnummer/nummerntyp.yaml#/components/schemas/nummerntyp'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]'
        rufnummer:
          $ref: '../../../bo4e/fields/com/Rufnummer/rufnummer.yaml#/components/schemas/rufnummer'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]'
      required:
        - nummerntyp
        - rufnummer
    PI_44018__transaktionsdaten__empfaenger:
      type: object
      properties:
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+MR
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+MR
      required:
        - rollencodenummer
        - rollencodetyp
