openapi: 3.1.0
info:
  title: '[LF] START_BESTELLUNG_STDAE_MELO_AN_MSB'
  version: '202510'
  x-bpmn-source-sha: 4f5b2ff0
  x-bo4e-schema-version: 1.7.0
  x-templater-sha: c7b88c733e93fe4ee423d52cffa2cd8f312574ea
components:
  schemas:
    '[LF] START_BESTELLUNG_STDAE_MELO_AN_MSB':
      type: object
      required:
        - stammdaten
        - transaktionsdaten
        - zusatzdaten
      properties:
        stammdaten:
          oneOf:
            - $ref: ../../event-bauteil/202510/UTILMD/PI_55658.yaml#/components/schemas/PI_55658__stammdaten
        transaktionsdaten:
          type: object
          required:
            - absender
            - empfaenger
            - kategorie
            - sparte
            - transaktionsgrund
          properties:
            absender:
              type: object
              properties:
                rollencodenummer:
                  $ref: ../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer
            empfaenger:
              type: object
              properties:
                rollencodenummer:
                  $ref: ../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer
            kategorie:
              $ref: ../../bo4e/fields/cdoc/Transaktionsdaten/kategorie.yaml#/components/schemas/kategorie
            sparte:
              $ref: ../../bo4e/fields/cdoc/Transaktionsdaten/sparte.yaml#/components/schemas/sparte
            transaktionsgrund:
              $ref: ../../bo4e/fields/cdoc/Transaktionsdaten/transaktionsgrund.yaml#/components/schemas/transaktionsgrund
            pruefidentifikator:
              description: Wird dynamisch im Event-Prozess ermittelt (Sparte + Transaktionsgrund + Empfänger-Marktrolle). Ein vom Sender mitgegebener Wert wird ignoriert. Im Topic mögliche Prüfis — 55658.
              examples:
                - '55658'
        zusatzdaten:
          type: object
          required:
            - prozessId
            - eventname
          properties:
            prozessId:
              type: string
            eventname:
              type: string
              const: START_BESTELLUNG_STDAE_MELO_AN_MSB
              default: START_BESTELLUNG_STDAE_MELO_AN_MSB
