openapi: 3.1.0
info:
  title: '[NB] START_UEBERSICHT_ZAEHLZEITDEF'
  version: '202510'
  x-bpmn-source-sha: eaf359e3
  x-bo4e-schema-version: 1.7.1
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    '[NB] START_UEBERSICHT_ZAEHLZEITDEF':
      type: object
      required:
        - stammdaten
        - transaktionsdaten
        - zusatzdaten
      properties:
        stammdaten:
          oneOf:
            - $ref: ../../event-bauteil/202510/UTILTS/PI_25004.yaml#/components/schemas/PI_25004__stammdaten
        transaktionsdaten:
          type: object
          required:
            - absender
            - empfaenger
            - sparte
          properties:
            absender:
              $ref: ../../bo4e/fields/cdoc/Transaktionsdaten/absender.yaml#/components/schemas/absender
            empfaenger:
              $ref: ../../bo4e/fields/cdoc/Transaktionsdaten/empfaenger.yaml#/components/schemas/empfaenger
            sparte:
              $ref: ../../bo4e/fields/cdoc/Transaktionsdaten/sparte.yaml#/components/schemas/sparte
            pruefidentifikator:
              description: Wird dynamisch im Event-Prozess ermittelt (Sparte + Transaktionsgrund + Empfänger-Marktrolle). Ein vom Sender mitgegebener Wert wird ignoriert. Im Topic mögliche Prüfis — 25004.
              examples:
                - '25004'
        zusatzdaten:
          type: object
          required:
            - prozessId
            - eventname
          properties:
            prozessId:
              type: string
            eventname:
              type: string
              const: START_UEBERSICHT_ZAEHLZEITDEF
              default: START_UEBERSICHT_ZAEHLZEITDEF
