openapi: 3.1.0
info:
  title: '[NB] START_VERSAND_BESTANDSLISTE GAS'
  version: '202510'
  x-bpmn-source-sha: 6b115946
  x-bo4e-schema-version: 1.6.5
  x-templater-sha: 6e98aaa8818d7b01b16786b130d743ea57fa960a
components:
  schemas:
    '[NB] START_VERSAND_BESTANDSLISTE GAS':
      type: object
      required:
        - stammdaten
        - transaktionsdaten
        - zusatzdaten
      properties:
        transaktionsdaten:
          allOf:
            - $ref: ../../bo4e/cdoc/Transaktionsdaten.yaml#/components/schemas/Transaktionsdaten
            - type: object
              required:
                - absender
                - empfaenger
                - gueltigAb
                - sparte
              properties:
                pruefidentifikator:
                  description: Wird dynamisch im Event-Prozess ermittelt (Sparte + Transaktionsgrund + Empfänger-Marktrolle). Ein vom Sender mitgegebener Wert wird ignoriert. Im Topic mögliche Prüfis — 44019.
                  examples:
                    - '44019'
        zusatzdaten:
          type: object
          required:
            - prozessId
            - eventname
          properties:
            prozessId:
              type: string
            eventname:
              type: string
              const: START_VERSAND_BESTANDSLISTE
              default: START_VERSAND_BESTANDSLISTE
      x-pending-pruefis:
        - '44019'
