openapi: 3.1.0
info:
  title: PI_17001
  version: '202604'
  x-bo4e-schema-version: 1.6.8
  x-bo4e-schema-sha: b84d59c01638e348fe912e388cf7b7a25ab9937f
  x-templater-sha: ce089a840512efbac03c3b3e949ad6e8b7215947
components:
  schemas:
    PI_17001:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_17001__stammdaten'
      required:
        - stammdaten
    PI_17001__stammdaten:
      type: object
      properties:
        AUFTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_17001__stammdaten__AUFTRAG'
      required:
        - AUFTRAG
    PI_17001__stammdaten__AUFTRAG:
      type: object
      properties:
        ausfuehrungsdatum:
          $ref: '../../../bo4e/fields/bo/Auftrag/ausfuehrungsdatum.yaml#/components/schemas/ausfuehrungsdatum'
          x-edifact-segment:
            - DTM+203
        positionsdaten:
          type: array
          items:
            $ref: '#/components/schemas/PI_17001__stammdaten__AUFTRAG__positionsdaten'
      required:
        - ausfuehrungsdatum
        - positionsdaten
    PI_17001__stammdaten__AUFTRAG__positionsdaten:
      type: object
      properties:
        positionsnummer:
          $ref: '../../../bo4e/fields/com/AuftragPosition/positionsnummer.yaml#/components/schemas/positionsnummer'
          x-edifact-segment:
            - SG29.LIN
        positionsnummerAngebot:
          $ref: '../../../bo4e/fields/com/AuftragPosition/positionsnummerAngebot.yaml#/components/schemas/positionsnummerAngebot'
          x-edifact-segment:
            - SG29.LIN.SG34.RFF+Z03
      required:
        - positionsnummer
        - positionsnummerAngebot
