openapi: 3.1.0
info:
  title: PI_17005
  version: '202604'
  x-bo4e-schema-version: 1.6.8
  x-bo4e-schema-sha: b84d59c01638e348fe912e388cf7b7a25ab9937f
  x-templater-sha: ce089a840512efbac03c3b3e949ad6e8b7215947
components:
  schemas:
    PI_17005:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_17005__stammdaten'
      required:
        - stammdaten
    PI_17005__stammdaten:
      type: object
      properties:
        ANFRAGE:
          type: array
          items:
            $ref: '#/components/schemas/PI_17005__stammdaten__ANFRAGE'
        AUFTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_17005__stammdaten__AUFTRAG'
      required:
        - ANFRAGE
        - AUFTRAG
    PI_17005__stammdaten__ANFRAGE:
      type: object
      properties:
        abonnement:
          $ref: '../../../bo4e/fields/bo/Anfrage/abonnement.yaml#/components/schemas/abonnement'
          x-edifact-segment:
            - IMD++Z01
        lokationsId:
          $ref: '../../../bo4e/fields/bo/Anfrage/lokationsId.yaml#/components/schemas/lokationsId'
          x-edifact-segment:
            - SG2.NAD+DP.LOC+172
      required:
        - abonnement
        - lokationsId
    PI_17005__stammdaten__AUFTRAG:
      type: object
      properties:
        ausfuehrungsdatum:
          $ref: '../../../bo4e/fields/bo/Auftrag/ausfuehrungsdatum.yaml#/components/schemas/ausfuehrungsdatum'
          x-edifact-segment:
            - DTM+203
      required:
        - ausfuehrungsdatum
