openapi: 3.1.0
info:
  title: '[LF] START_STAMMDATENAENDERUNG_MALO_BILA_AN_NB GAS'
  version: '202610'
  x-bpmn-source-sha: '36717036'
components:
  schemas:
    '[LF] START_STAMMDATENAENDERUNG_MALO_BILA_AN_NB GAS':
      type: object
      required:
        - stammdaten
        - transaktionsdaten
        - zusatzdaten
      properties:
        transaktionsdaten:
          allOf:
            - $ref: ../../bo4e/cdoc/Transaktionsdaten.yaml#/components/schemas/Transaktionsdaten
            - type: object
              required:
                - absender
                - empfaenger
                - gueltigAb
                - kategorie
                - sparte
              properties:
                pruefidentifikator:
                  description: Wird dynamisch im Event-Prozess ermittelt (Sparte + Transaktionsgrund + Empfänger-Marktrolle). Ein vom Sender mitgegebener Wert wird ignoriert. Im Topic mögliche Prüfis — 44120.
                  examples:
                    - '44120'
        zusatzdaten:
          type: object
          required:
            - prozessId
            - eventname
          properties:
            prozessId:
              type: string
            eventname:
              type: string
              const: START_STAMMDATENAENDERUNG_MALO_BILA_AN_NB
              default: START_STAMMDATENAENDERUNG_MALO_BILA_AN_NB
      x-pending-pruefis:
        - '44120'
