openapi: 3.1.0
info:
  title: '[NB] START_AUFTRAGSSTATUS'
  version: '202610'
  x-bpmn-source-sha: 33b20645
  x-bo4e-schema-version: 1.7.0
  x-templater-sha: c7b88c733e93fe4ee423d52cffa2cd8f312574ea
components:
  schemas:
    '[NB] START_AUFTRAGSSTATUS':
      type: object
      required:
        - stammdaten
        - transaktionsdaten
        - zusatzdaten
      properties:
        transaktionsdaten:
          type: object
          required:
            - absender
            - antwortstatus
            - antwortstatusCodeliste
            - empfaenger
            - fertigstellungsdatum
            - sparte
          properties:
            absender:
              type: object
              properties:
                rollencodenummer:
                  $ref: ../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer
            antwortstatus:
              $ref: ../../bo4e/fields/cdoc/Transaktionsdaten/antwortstatus.yaml#/components/schemas/antwortstatus
            antwortstatusCodeliste:
              $ref: ../../bo4e/fields/cdoc/Transaktionsdaten/antwortstatusCodeliste.yaml#/components/schemas/antwortstatusCodeliste
            empfaenger:
              type: object
              properties:
                rollencodenummer:
                  $ref: ../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer
            fertigstellungsdatum:
              $ref: ../../bo4e/fields/cdoc/Transaktionsdaten/fertigstellungsdatum.yaml#/components/schemas/fertigstellungsdatum
            sparte:
              $ref: ../../bo4e/fields/cdoc/Transaktionsdaten/sparte.yaml#/components/schemas/sparte
            pruefidentifikator:
              description: Wird dynamisch im Event-Prozess ermittelt (Sparte + Transaktionsgrund + Empfänger-Marktrolle). Ein vom Sender mitgegebener Wert wird ignoriert. Im Topic mögliche Prüfis — 21039, 21040.
              examples:
                - '21039'
                - '21040'
        zusatzdaten:
          type: object
          required:
            - prozessId
            - eventname
          properties:
            prozessId:
              type: string
            eventname:
              type: string
              const: START_AUFTRAGSSTATUS
              default: START_AUFTRAGSSTATUS
      x-pending-pruefis:
        - '21039'
        - '21040'
