openapi: 3.1.0
info:
  title: '[NB] START_STAMMDATENAENDERUNG_LBS_AN_LF'
  version: '202610'
  x-bpmn-source-sha: 6b115946
components:
  schemas:
    '[NB] START_STAMMDATENAENDERUNG_LBS_AN_LF':
      type: object
      required:
        - stammdaten
        - transaktionsdaten
        - zusatzdaten
      properties:
        transaktionsdaten:
          allOf:
            - $ref: ../../bo4e/cdoc/Transaktionsdaten.yaml#/components/schemas/Transaktionsdaten
            - type: object
              required:
                - absender
                - empfaenger
                - gueltigAb
                - kategorie
                - sparte
              properties:
                pruefidentifikator:
                  description: Wird dynamisch im Event-Prozess ermittelt (Sparte + Transaktionsgrund + Empfänger-Marktrolle). Ein vom Sender mitgegebener Wert wird ignoriert. Im Topic mögliche Prüfis — 55175.
                  examples:
                    - '55175'
        zusatzdaten:
          type: object
          required:
            - prozessId
            - eventname
          properties:
            prozessId:
              type: string
            eventname:
              type: string
              const: START_STAMMDATENAENDERUNG_LBS_AN_LF
              default: START_STAMMDATENAENDERUNG_LBS_AN_LF
      x-pending-pruefis:
        - '55175'
