openapi: 3.1.0
info:
  title: '[NB] START_ERHEBUNG_MESSWERTE'
  version: '202610'
  x-bpmn-source-sha: eaf359e3
  x-bo4e-schema-version: 1.7.0
  x-templater-sha: 39ae45d481e5cc3d4d7aae328a23a9751236156a
components:
  schemas:
    '[NB] START_ERHEBUNG_MESSWERTE':
      type: object
      required:
        - stammdaten
        - transaktionsdaten
        - zusatzdaten
      properties:
        transaktionsdaten:
          type: object
          required:
            - absender
            - anfrageReferenz
            - empfaenger
            - kategorie
            - lokationsTyp
            - sparte
            - typ
          properties:
            absender:
              type: object
              properties:
                rollencodenummer:
                  $ref: ../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer
            anfrageReferenz:
              $ref: ../../bo4e/fields/cdoc/Transaktionsdaten/anfrageReferenz.yaml#/components/schemas/anfrageReferenz
            empfaenger:
              type: object
              properties:
                rollencodenummer:
                  $ref: ../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer
            kategorie:
              $ref: ../../bo4e/fields/cdoc/Transaktionsdaten/kategorie.yaml#/components/schemas/kategorie
            lokationsTyp:
              $ref: ../../bo4e/fields/cdoc/Transaktionsdaten/lokationsTyp.yaml#/components/schemas/lokationsTyp
            sparte:
              $ref: ../../bo4e/fields/cdoc/Transaktionsdaten/sparte.yaml#/components/schemas/sparte
            typ:
              $ref: ../../bo4e/fields/cdoc/Transaktionsdaten/typ.yaml#/components/schemas/typ
            pruefidentifikator:
              description: Wird dynamisch im Event-Prozess ermittelt (Sparte + Transaktionsgrund + Empfänger-Marktrolle). Ein vom Sender mitgegebener Wert wird ignoriert. Im Topic mögliche Prüfis — 13002, 13008, 13009, 13016, 13017, 13018, 13019, 13025, 13027.
              examples:
                - '13002'
                - '13008'
                - '13009'
                - '13016'
                - '13017'
                - '13018'
                - '13019'
                - '13025'
                - '13027'
        zusatzdaten:
          type: object
          required:
            - prozessId
            - eventname
          properties:
            prozessId:
              type: string
            eventname:
              type: string
              const: START_ERHEBUNG_MESSWERTE
              default: START_ERHEBUNG_MESSWERTE
      x-pending-pruefis:
        - '13002'
        - '13008'
        - '13009'
        - '13016'
        - '13017'
        - '13018'
        - '13019'
        - '13025'
        - '13027'
