openapi: 3.1.0
info:
  title: PI_66666
  version: '202510'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: 39ae45d481e5cc3d4d7aae328a23a9751236156a
components:
  schemas:
    PI_66666:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_66666__stammdaten'
        transaktionsdaten:
          $ref: '#/components/schemas/PI_66666__transaktionsdaten'
      required:
        - stammdaten
        - transaktionsdaten
    PI_66666__stammdaten:
      type: object
      properties:
        STATUSBERICHT:
          type: array
          items:
            $ref: '#/components/schemas/PI_66666__stammdaten__STATUSBERICHT'
      required:
        - STATUSBERICHT
    PI_66666__stammdaten__STATUSBERICHT:
      type: object
      properties:
        datumPruefung:
          $ref: '../../../bo4e/fields/bo/Statusbericht/datumPruefung.yaml#/components/schemas/datumPruefung'
          x-edifact-segment:
            - SG2.RFF+ACE.DTM+171
        pruefgegenstand:
          $ref: '../../../bo4e/fields/bo/Statusbericht/pruefgegenstand.yaml#/components/schemas/pruefgegenstand'
          x-edifact-segment:
            - SG2.RFF+ACE
      required:
        - datumPruefung
        - pruefgegenstand
    PI_66666__transaktionsdaten:
      type: object
      properties:
        absender:
          $ref: '#/components/schemas/PI_66666__transaktionsdaten__absender'
        dokumentennummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/dokumentennummer.yaml#/components/schemas/dokumentennummer'
          x-edifact-segment:
            - BGM
        empfaenger:
          $ref: '#/components/schemas/PI_66666__transaktionsdaten__empfaenger'
        kategorie:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/kategorie.yaml#/components/schemas/kategorie'
          x-edifact-segment:
            - BGM
        nachrichtendatum:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtendatum.yaml#/components/schemas/nachrichtendatum'
          x-edifact-segment:
            - DTM+137
        nachrichtenreferenznummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtenreferenznummer.yaml#/components/schemas/nachrichtenreferenznummer'
          x-edifact-segment:
            - UNH
      required:
        - absender
        - dokumentennummer
        - empfaenger
        - kategorie
        - nachrichtendatum
        - nachrichtenreferenznummer
    PI_66666__transaktionsdaten__absender:
      type: object
      properties:
        ansprechpartner:
          $ref: '#/components/schemas/PI_66666__transaktionsdaten__absender__ansprechpartner'
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG3.NAD+MS
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG3.NAD+MS
      required:
        - rollencodenummer
        - rollencodetyp
    PI_66666__transaktionsdaten__absender__ansprechpartner:
      type: object
      properties:
        eMailAdresse:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/eMailAdresse.yaml#/components/schemas/eMailAdresse'
          x-edifact-segment:
            - 'SG3.NAD+MS.COM+[EM|FX|TE|AJ|AL]'
        nachname:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/nachname.yaml#/components/schemas/nachname'
          x-edifact-segment:
            - SG3.NAD+MS.CTA+IC
        rufnummern:
          type: array
          items:
            $ref: '#/components/schemas/PI_66666__transaktionsdaten__absender__ansprechpartner__rufnummern'
    PI_66666__transaktionsdaten__absender__ansprechpartner__rufnummern:
      type: object
      properties:
        nummerntyp:
          $ref: '../../../bo4e/fields/com/Rufnummer/nummerntyp.yaml#/components/schemas/nummerntyp'
          x-edifact-segment:
            - 'SG3.NAD+MS.COM+[EM|FX|TE|AJ|AL]'
        rufnummer:
          $ref: '../../../bo4e/fields/com/Rufnummer/rufnummer.yaml#/components/schemas/rufnummer'
          x-edifact-segment:
            - 'SG3.NAD+MS.COM+[EM|FX|TE|AJ|AL]'
    PI_66666__transaktionsdaten__empfaenger:
      type: object
      properties:
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG3.NAD+MR
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG3.NAD+MR
      required:
        - rollencodenummer
        - rollencodetyp
