openapi: 3.1.0
info:
  title: PI_55194
  version: '202504'
  x-bo4e-schema-version: 1.6.5
  x-bo4e-schema-sha: 95f07d974cf2dc738ca248b258d6589025614cb0
  x-templater-sha: 6e98aaa8818d7b01b16786b130d743ea57fa960a
components:
  schemas:
    PI_55194:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55194__stammdaten'
      required:
        - stammdaten
    PI_55194__stammdaten:
      type: object
      properties:
        MESSLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_55194__stammdaten__MESSLOKATION'
        ZAEHLER:
          type: array
          items:
            $ref: '#/components/schemas/PI_55194__stammdaten__ZAEHLER'
      required:
        - MESSLOKATION
        - ZAEHLER
    PI_55194__stammdaten__MESSLOKATION:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Messlokation/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z64
        marktrollen:
          type: array
          items:
            $ref: '#/components/schemas/PI_55194__stammdaten__MESSLOKATION__marktrollen'
        messadresse:
          $ref: '#/components/schemas/PI_55194__stammdaten__MESSLOKATION__messadresse'
        messlokationsId:
          $ref: '../../../bo4e/fields/bo/Messlokation/messlokationsId.yaml#/components/schemas/messlokationsId'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z64.RFF+Z19
            - SG4.IDE+24.SG8.SEQ+ZF3.RFF+Z19
      required:
        - datenqualitaet
        - marktrollen
        - messadresse
        - messlokationsId
    PI_55194__stammdaten__MESSLOKATION__marktrollen:
      type: object
      properties:
        marktrolle:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/marktrolle.yaml#/components/schemas/marktrolle'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+ZF3.SG10.CCI+++ZB3.CAV+Z91
            - SG4.IDE+24.SG8.SEQ+ZF3.SG10.CCI+++ZB3.CAV+ZF0
        messstellenbetreiberEigenschaft:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/messstellenbetreiberEigenschaft.yaml#/components/schemas/messstellenbetreiberEigenschaft'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+ZF3.SG10.CCI+++ZB3.CAV+Z91
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+ZF3.SG10.CCI+++ZB3.CAV+Z91
            - SG4.IDE+24.SG8.SEQ+ZF3.SG10.CCI+++ZB3.CAV+ZF0
        weiterverpflichtet:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/weiterverpflichtet.yaml#/components/schemas/weiterverpflichtet'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+ZF3.SG10.CCI+++ZB3.CAV+Z91
      required:
        - marktrolle
        - messstellenbetreiberEigenschaft
        - rollencodenummer
        - weiterverpflichtet
    PI_55194__stammdaten__MESSLOKATION__messadresse:
      type: object
      properties:
        hausnummer:
          $ref: '../../../bo4e/fields/com/Adresse/hausnummer.yaml#/components/schemas/hausnummer'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z64
        landescode:
          $ref: '../../../bo4e/fields/com/Adresse/landescode.yaml#/components/schemas/landescode'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z64
        ort:
          $ref: '../../../bo4e/fields/com/Adresse/ort.yaml#/components/schemas/ort'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z64
        ortsteil:
          $ref: '../../../bo4e/fields/com/Adresse/ortsteil.yaml#/components/schemas/ortsteil'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z64
        postfach:
          $ref: '../../../bo4e/fields/com/Adresse/postfach.yaml#/components/schemas/postfach'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z64
        postleitzahl:
          $ref: '../../../bo4e/fields/com/Adresse/postleitzahl.yaml#/components/schemas/postleitzahl'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z64
        strasse:
          $ref: '../../../bo4e/fields/com/Adresse/strasse.yaml#/components/schemas/strasse'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z64
        zusatzInformation:
          $ref: '#/components/schemas/PI_55194__stammdaten__MESSLOKATION__messadresse__zusatzInformation'
      required:
        - hausnummer
        - landescode
        - ort
        - ortsteil
        - postfach
        - postleitzahl
        - strasse
        - zusatzInformation
    PI_55194__stammdaten__MESSLOKATION__messadresse__zusatzInformation:
      type: object
      properties:
        zusatz1:
          $ref: '../../../bo4e/fields/com/AdresszusatzInformation/zusatz1.yaml#/components/schemas/zusatz1'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z64
        zusatz2:
          $ref: '../../../bo4e/fields/com/AdresszusatzInformation/zusatz2.yaml#/components/schemas/zusatz2'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z64
        zusatz3:
          $ref: '../../../bo4e/fields/com/AdresszusatzInformation/zusatz3.yaml#/components/schemas/zusatz3'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z64
        zusatz4:
          $ref: '../../../bo4e/fields/com/AdresszusatzInformation/zusatz4.yaml#/components/schemas/zusatz4'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z64
        zusatz5:
          $ref: '../../../bo4e/fields/com/AdresszusatzInformation/zusatz5.yaml#/components/schemas/zusatz5'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z64
      required:
        - zusatz1
        - zusatz2
        - zusatz3
        - zusatz4
        - zusatz5
    PI_55194__stammdaten__ZAEHLER:
      type: object
      properties:
        geraete:
          type: array
          items:
            $ref: '#/components/schemas/PI_55194__stammdaten__ZAEHLER__geraete'
      required:
        - geraete
    PI_55194__stammdaten__ZAEHLER__geraete:
      type: object
      properties:
        geraetenummer:
          $ref: '../../../bo4e/fields/com/Geraet/geraetenummer.yaml#/components/schemas/geraetenummer'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+ZG0.SG10.CCI+++Z75.CAV+Z30
      required:
        - geraetenummer
