openapi: 3.1.0
info:
  title: PI_55619
  version: '202504'
  x-bo4e-schema-version: 1.6.5
  x-bo4e-schema-sha: 95f07d974cf2dc738ca248b258d6589025614cb0
  x-templater-sha: 6e98aaa8818d7b01b16786b130d743ea57fa960a
components:
  schemas:
    PI_55619:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55619__stammdaten'
      required:
        - stammdaten
    PI_55619__stammdaten:
      type: object
      properties:
        TRANCHE:
          type: array
          items:
            $ref: '#/components/schemas/PI_55619__stammdaten__TRANCHE'
        VERWENDUNGSZEITRAUM:
          type: array
          items:
            $ref: '#/components/schemas/PI_55619__stammdaten__VERWENDUNGSZEITRAUM'
      required:
        - TRANCHE
        - VERWENDUNGSZEITRAUM
    PI_55619__stammdaten__TRANCHE:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Tranche/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z15
        gueltigkeitszeitraum:
          $ref: '#/components/schemas/PI_55619__stammdaten__TRANCHE__gueltigkeitszeitraum'
        tranchenId:
          $ref: '../../../bo4e/fields/bo/Tranche/tranchenId.yaml#/components/schemas/tranchenId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z21
        verguetungEmpfaenger:
          $ref: '../../../bo4e/fields/bo/Tranche/verguetungEmpfaenger.yaml#/components/schemas/verguetungEmpfaenger'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z15.SG10.CCI+++Z89.CAV
      required:
        - datenqualitaet
        - gueltigkeitszeitraum
        - tranchenId
        - verguetungEmpfaenger
    PI_55619__stammdaten__TRANCHE__gueltigkeitszeitraum:
      type: object
      properties:
        zeitraumId:
          $ref: '../../../bo4e/fields/com/Zeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z15
      required:
        - zeitraumId
    PI_55619__stammdaten__VERWENDUNGSZEITRAUM:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53]'
        verwendungAb:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungAb.yaml#/components/schemas/verwendungAb'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53].DTM+Z25'
        verwendungBis:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungBis.yaml#/components/schemas/verwendungBis'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53].DTM+Z26'
        zeitraumId:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53]'
      required:
        - datenqualitaet
        - verwendungAb
        - zeitraumId
