openapi: 3.1.0
info:
  title: PI_17002
  version: '202610'
  x-bo4e-schema-version: 1.7.4
  x-bo4e-schema-sha: 1732e948753541a9b641ca98f3d8ff189d994263
  x-templater-sha: 20c434c98f1808f1b10ab64bdf7a7a96d42aa7ee
components:
  schemas:
    PI_17002:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_17002__masterData'
      required:
      - masterData
    PI_17002__masterData:
      type: object
      properties:
        REQUEST:
          type: array
          items:
            $ref: '#/components/schemas/PI_17002__masterData__REQUEST'
        ORDER:
          type: array
          items:
            $ref: '#/components/schemas/PI_17002__masterData__ORDER'
        MARKET_LOCATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_17002__masterData__MARKET_LOCATION'
      required:
      - REQUEST
      - ORDER
      - MARKET_LOCATION
    PI_17002__masterData__REQUEST:
      type: object
      properties:
        locationId:
          $ref: ../../../bo4e-en/fields/bo/Request/locationId.yaml#/components/schemas/locationId
          x-edifact-segment:
          - SG2.NAD+DP.LOC+172
      required:
      - locationId
    PI_17002__masterData__ORDER:
      type: object
      properties:
        postponedDeregistrationDate:
          $ref: ../../../bo4e-en/fields/bo/Order/postponedDeregistrationDate.yaml#/components/schemas/postponedDeregistrationDate
          x-edifact-segment:
          - DTM+Z02
      required:
      - postponedDeregistrationDate
    PI_17002__masterData__MARKET_LOCATION:
      type: object
      properties:
        marketLocationId:
          $ref: ../../../bo4e-en/fields/bo/MarketLocation/marketLocationId.yaml#/components/schemas/marketLocationId
          x-edifact-segment:
          - SG2.NAD+DP.SG3.RFF+Z18
      required:
      - marketLocationId
