openapi: 3.1.0
info:
  title: PI_17129
  version: '202610'
  x-bo4e-schema-version: 1.7.8
  x-bo4e-schema-sha: a4f202d62930c69acd327622abf92da121d3a12e
  x-templater-sha: 41b3eb8c66d69f8953cbfe2ce874d41618f10ca0
components:
  schemas:
    PI_17129:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_17129__masterData'
      required:
      - masterData
    PI_17129__masterData:
      type: object
      properties:
        ORDER:
          type: array
          items:
            $ref: '#/components/schemas/PI_17129__masterData__ORDER'
      required:
      - ORDER
    PI_17129__masterData__ORDER:
      type: object
      properties:
        executionDate:
          $ref: ../../../bo4e-en/fields/bo/Order/executionDate.yaml#/components/schemas/executionDate
          x-edifact-segment:
          - DTM+203
      required:
      - executionDate
