openapi: 3.1.0
info:
  title: PI_21012
  version: '202610'
  x-bo4e-schema-version: 1.7.8
  x-bo4e-schema-sha: a4f202d62930c69acd327622abf92da121d3a12e
  x-templater-sha: 41b3eb8c66d69f8953cbfe2ce874d41618f10ca0
components:
  schemas:
    PI_21012:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_21012__masterData'
      required:
      - masterData
    PI_21012__masterData:
      type: object
      properties:
        STATUS_NOTIFICATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_21012__masterData__STATUS_NOTIFICATION'
      required:
      - STATUS_NOTIFICATION
    PI_21012__masterData__STATUS_NOTIFICATION:
      type: object
      properties:
        positionData:
          type: array
          items:
            $ref: '#/components/schemas/PI_21012__masterData__STATUS_NOTIFICATION__positionData'
      required:
      - positionData
    PI_21012__masterData__STATUS_NOTIFICATION__positionData:
      type: object
      properties:
        orderStatus:
          $ref: ../../../bo4e-en/fields/com/StatusNotificationPosition/orderStatus.yaml#/components/schemas/orderStatus
          x-edifact-segment:
          - SG14.CNI.SG15.STS+Z10
        completionDate:
          $ref: ../../../bo4e-en/fields/com/StatusNotificationPosition/completionDate.yaml#/components/schemas/completionDate
          x-edifact-segment:
          - SG14.CNI.SG15.STS+Z10.DTM+293
        locationId:
          $ref: ../../../bo4e-en/fields/com/StatusNotificationPosition/locationId.yaml#/components/schemas/locationId
          x-edifact-segment:
          - SG14.CNI.LOC+172
        notificationNumber:
          $ref: ../../../bo4e-en/fields/com/StatusNotificationPosition/notificationNumber.yaml#/components/schemas/notificationNumber
          x-edifact-segment:
          - SG14.CNI.SG15.STS+Z10.RFF+ADY
        positionNumber:
          $ref: ../../../bo4e-en/fields/com/StatusNotificationPosition/positionNumber.yaml#/components/schemas/positionNumber
          x-edifact-segment:
          - SG14.CNI
        processReferenceNumber:
          $ref: ../../../bo4e-en/fields/com/StatusNotificationPosition/processReferenceNumber.yaml#/components/schemas/processReferenceNumber
          x-edifact-segment:
          - SG14.CNI.SG15.STS+Z10.RFF+ACW
      required:
      - orderStatus
      - completionDate
      - locationId
      - notificationNumber
      - positionNumber
      - processReferenceNumber
