openapi: 3.1.0
info:
  title: PI_55647
  version: '202510'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_55647:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_55647__masterData'
        transactionData:
          $ref: '#/components/schemas/PI_55647__transactionData'
      required:
      - masterData
      - transactionData
    PI_55647__masterData:
      type: object
      properties:
        TRANCHE:
          type: array
          items:
            $ref: '#/components/schemas/PI_55647__masterData__TRANCHE'
        USAGE_PERIOD:
          type: array
          items:
            $ref: '#/components/schemas/PI_55647__masterData__USAGE_PERIOD'
      required:
      - TRANCHE
      - USAGE_PERIOD
    PI_55647__masterData__TRANCHE:
      type: object
      properties:
        dataQuality:
          $ref: ../../../bo4e-en/fields/bo/Tranche/dataQuality.yaml#/components/schemas/dataQuality
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z99|ZA0]
        validityPeriod:
          $ref: '#/components/schemas/PI_55647__masterData__TRANCHE__validityPeriod'
        trancheId:
          $ref: ../../../bo4e-en/fields/bo/Tranche/trancheId.yaml#/components/schemas/trancheId
          x-edifact-segment:
          - SG4.IDE+24.SG5.LOC+Z21
        meterRegisters:
          type: array
          items:
            $ref: '#/components/schemas/PI_55647__masterData__TRANCHE__meterRegisters'
      required:
      - dataQuality
      - validityPeriod
      - trancheId
      - meterRegisters
    PI_55647__masterData__TRANCHE__validityPeriod:
      type: object
      properties:
        periodId:
          $ref: ../../../bo4e-en/fields/com/TimePeriod/periodId.yaml#/components/schemas/periodId
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z99|ZA0]
      required:
      - periodId
    PI_55647__masterData__TRANCHE__meterRegisters:
      type: object
      properties:
        obisCode:
          $ref: ../../../bo4e-en/fields/com/MeterRegister/obisCode.yaml#/components/schemas/obisCode
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z99|ZA0].PIA+5
        purposesOfUse:
          type: array
          items:
            $ref: '#/components/schemas/PI_55647__masterData__TRANCHE__meterRegisters__purposesOfUse'
      required:
      - obisCode
      - purposesOfUse
    PI_55647__masterData__TRANCHE__meterRegisters__purposesOfUse:
      type: object
      properties:
        marketRole:
          $ref: ../../../bo4e-en/fields/com/PurposeOfUse/marketRole.yaml#/components/schemas/marketRole
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z99|ZA0].SG10.CCI+++ZA8.CAV
        purpose:
          $ref: ../../../bo4e-en/fields/com/PurposeOfUse/purpose.yaml#/components/schemas/purpose
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z99|ZA0].SG10.CCI+++ZA8.CAV
      required:
      - marketRole
      - purpose
    PI_55647__masterData__USAGE_PERIOD:
      type: object
      properties:
        dataQuality:
          $ref: ../../../bo4e-en/fields/bo/UsagePeriod/dataQuality.yaml#/components/schemas/dataQuality
          x-edifact-segment:
          - SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55]
        usageFrom:
          $ref: ../../../bo4e-en/fields/bo/UsagePeriod/usageFrom.yaml#/components/schemas/usageFrom
          x-edifact-segment:
          - SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55].DTM+Z25
        usageTo:
          $ref: ../../../bo4e-en/fields/bo/UsagePeriod/usageTo.yaml#/components/schemas/usageTo
          x-edifact-segment:
          - SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55].DTM+Z26
        periodId:
          $ref: ../../../bo4e-en/fields/bo/UsagePeriod/periodId.yaml#/components/schemas/periodId
          x-edifact-segment:
          - SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55]
      required:
      - dataQuality
      - usageFrom
      - periodId
    PI_55647__transactionData:
      type: object
      properties:
        sender:
          $ref: '#/components/schemas/PI_55647__transactionData__sender'
        requestReferenceNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/requestReferenceNumber.yaml#/components/schemas/requestReferenceNumber
          x-edifact-segment:
          - SG4.IDE+24.SG6.RFF+TN
        responseStatusPeriod:
          type: array
          items:
            $ref: '#/components/schemas/PI_55647__transactionData__responseStatusPeriod'
        documentNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/documentNumber.yaml#/components/schemas/documentNumber
          x-edifact-segment:
          - BGM+[E03|Z88]
        receiver:
          $ref: '#/components/schemas/PI_55647__transactionData__receiver'
        category:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/category.yaml#/components/schemas/category
          x-edifact-segment:
          - BGM+[E03|Z88]
        messageDate:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/messageDate.yaml#/components/schemas/messageDate
          x-edifact-segment:
          - DTM+137
        messageReferenceNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/messageReferenceNumber.yaml#/components/schemas/messageReferenceNumber
          x-edifact-segment:
          - UNH
        verificationIdentifier:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/verificationIdentifier.yaml#/components/schemas/verificationIdentifier
          x-edifact-segment:
          - SG4.IDE+24.SG6.RFF+Z13
        transactionReason:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/transactionReason.yaml#/components/schemas/transactionReason
          x-edifact-segment:
          - SG4.IDE+24.STS+7
        processNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/processNumber.yaml#/components/schemas/processNumber
          x-edifact-segment:
          - SG4.IDE+24
      required:
      - sender
      - requestReferenceNumber
      - documentNumber
      - receiver
      - category
      - messageDate
      - messageReferenceNumber
      - verificationIdentifier
      - transactionReason
      - processNumber
    PI_55647__transactionData__sender:
      type: object
      properties:
        contactPerson:
          $ref: '#/components/schemas/PI_55647__transactionData__sender__contactPerson'
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG2.NAD+MS
        roleCodeType:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeType.yaml#/components/schemas/roleCodeType
          x-edifact-segment:
          - SG2.NAD+MS
      required:
      - contactPerson
      - roleCodeNumber
      - roleCodeType
    PI_55647__transactionData__sender__contactPerson:
      type: object
      properties:
        eMailAddress:
          $ref: ../../../bo4e-en/fields/bo/ContactPerson/eMailAddress.yaml#/components/schemas/eMailAddress
          x-edifact-segment:
          - SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]
        lastName:
          $ref: ../../../bo4e-en/fields/bo/ContactPerson/lastName.yaml#/components/schemas/lastName
          x-edifact-segment:
          - SG2.NAD+MS.SG3.CTA
        phoneNumbers:
          type: array
          items:
            $ref: '#/components/schemas/PI_55647__transactionData__sender__contactPerson__phoneNumbers'
      required:
      - eMailAddress
      - lastName
      - phoneNumbers
    PI_55647__transactionData__sender__contactPerson__phoneNumbers:
      type: object
      properties:
        numberType:
          $ref: ../../../bo4e-en/fields/com/PhoneNumber/numberType.yaml#/components/schemas/numberType
          x-edifact-segment:
          - SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]
        phoneNumber:
          $ref: ../../../bo4e-en/fields/com/PhoneNumber/phoneNumber.yaml#/components/schemas/phoneNumber
          x-edifact-segment:
          - SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]
      required:
      - numberType
      - phoneNumber
    PI_55647__transactionData__responseStatusPeriod:
      type: object
      properties:
        code:
          $ref: ../../../bo4e-en/fields/com/ResponseStatusPeriod/code.yaml#/components/schemas/code
          x-edifact-segment:
          - SG4.IDE+24.STS+E01
        list:
          $ref: ../../../bo4e-en/fields/com/ResponseStatusPeriod/list.yaml#/components/schemas/list
          x-edifact-segment:
          - SG4.IDE+24.STS+E01
        periodId:
          $ref: ../../../bo4e-en/fields/com/ResponseStatusPeriod/periodId.yaml#/components/schemas/periodId
          x-edifact-segment:
          - SG4.IDE+24.STS+E01
    PI_55647__transactionData__receiver:
      type: object
      properties:
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG2.NAD+MR
        roleCodeType:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeType.yaml#/components/schemas/roleCodeType
          x-edifact-segment:
          - SG2.NAD+MR
      required:
      - roleCodeNumber
      - roleCodeType
