openapi: 3.1.0
info:
  title: PI_55673
  version: '202510'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_55673:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_55673__masterData'
        transactionData:
          $ref: '#/components/schemas/PI_55673__transactionData'
      required:
      - masterData
      - transactionData
    PI_55673__masterData:
      type: object
      properties:
        BALANCING:
          type: array
          items:
            $ref: '#/components/schemas/PI_55673__masterData__BALANCING'
        MARKET_LOCATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_55673__masterData__MARKET_LOCATION'
        TRANCHE:
          type: array
          items:
            $ref: '#/components/schemas/PI_55673__masterData__TRANCHE'
        USAGE_PERIOD:
          type: array
          items:
            $ref: '#/components/schemas/PI_55673__masterData__USAGE_PERIOD'
      required:
      - BALANCING
      - MARKET_LOCATION
      - TRANCHE
      - USAGE_PERIOD
    PI_55673__masterData__BALANCING:
      type: object
      properties:
        aggregationResponsibility:
          $ref: ../../../bo4e-en/fields/bo/Balancing/aggregationResponsibility.yaml#/components/schemas/aggregationResponsibility
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z80|Z81].SG10.CCI+6
        balancingGroup:
          $ref: ../../../bo4e-en/fields/bo/Balancing/balancingGroup.yaml#/components/schemas/balancingGroup
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z80|Z81].SG10.CCI+Z19
        dataQuality:
          $ref: ../../../bo4e-en/fields/bo/Balancing/dataQuality.yaml#/components/schemas/dataQuality
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z85|Z86]
          - SG4.IDE+24.SG8.SEQ+[Z87|Z88]
          - SG4.IDE+24.SG8.SEQ+[Z89|Z90]
        forecastBasisDetails:
          $ref: ../../../bo4e-en/fields/bo/Balancing/forecastBasisDetails.yaml#/components/schemas/forecastBasisDetails
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z80|Z81].SG10.CCI.CAV+[E02|E14]
        validityPeriod:
          $ref: '#/components/schemas/PI_55673__masterData__BALANCING__validityPeriod'
        annualConsumptionForecast:
          $ref: '#/components/schemas/PI_55673__masterData__BALANCING__annualConsumptionForecast'
        loadProfiles:
          type: array
          items:
            $ref: '#/components/schemas/PI_55673__masterData__BALANCING__loadProfiles'
        forecastBasis:
          $ref: ../../../bo4e-en/fields/bo/Balancing/forecastBasis.yaml#/components/schemas/forecastBasis
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z80|Z81].SG10.CCI
        temperatureWork:
          $ref: '#/components/schemas/PI_55673__masterData__BALANCING__temperatureWork'
        timeSeriesType:
          $ref: ../../../bo4e-en/fields/bo/Balancing/timeSeriesType.yaml#/components/schemas/timeSeriesType
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z80|Z81].SG10.CCI+15++Z21.CAV
      required:
      - aggregationResponsibility
      - balancingGroup
      - dataQuality
      - validityPeriod
      - annualConsumptionForecast
      - loadProfiles
      - forecastBasis
      - temperatureWork
      - timeSeriesType
    PI_55673__masterData__BALANCING__validityPeriod:
      type: object
      properties:
        periodId:
          $ref: ../../../bo4e-en/fields/com/TimePeriod/periodId.yaml#/components/schemas/periodId
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z85|Z86]
          - SG4.IDE+24.SG8.SEQ+[Z87|Z88]
          - SG4.IDE+24.SG8.SEQ+[Z89|Z90]
      required:
      - periodId
    PI_55673__masterData__BALANCING__annualConsumptionForecast:
      type: object
      properties:
        unit:
          $ref: ../../../bo4e-en/fields/com/Quantity/unit.yaml#/components/schemas/unit
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z80|Z81].SG9.QTY+31
        value:
          $ref: ../../../bo4e-en/fields/com/Quantity/value.yaml#/components/schemas/value
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z80|Z81].SG9.QTY+31
      required:
      - unit
      - value
    PI_55673__masterData__BALANCING__loadProfiles:
      type: object
      properties:
        designation:
          $ref: ../../../bo4e-en/fields/com/LoadProfile/designation.yaml#/components/schemas/designation
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z85|Z86].SG10.CCI+Z02.CAV
          - SG4.IDE+24.SG8.SEQ+[Z87|Z88].SG10.CCI+Z03.CAV
        feedIn:
          $ref: ../../../bo4e-en/fields/com/LoadProfile/feedIn.yaml#/components/schemas/feedIn
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z85|Z86].SG10.CCI+Z02
          - SG4.IDE+24.SG8.SEQ+[Z87|Z88].SG10.CCI+Z03
        profileType:
          $ref: ../../../bo4e-en/fields/com/LoadProfile/profileType.yaml#/components/schemas/profileType
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z85|Z86].SG10.CCI+Z02
          - SG4.IDE+24.SG8.SEQ+[Z87|Z88].SG10.CCI+Z03
        profileFamily:
          $ref: ../../../bo4e-en/fields/com/LoadProfile/profileFamily.yaml#/components/schemas/profileFamily
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z87|Z88].SG10.CCI+++Z12.CAV
        referenceProfileDesignation:
          $ref: ../../../bo4e-en/fields/com/LoadProfile/referenceProfileDesignation.yaml#/components/schemas/referenceProfileDesignation
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z89|Z90].SG10.CCI+Z05.CAV
        dailyParameters:
          $ref: '#/components/schemas/PI_55673__masterData__BALANCING__loadProfiles__dailyParameters'
        procedure:
          $ref: ../../../bo4e-en/fields/com/LoadProfile/procedure.yaml#/components/schemas/procedure
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z85|Z86].SG10.CCI+Z02
          - SG4.IDE+24.SG8.SEQ+[Z87|Z88].SG10.CCI+Z03
      required:
      - designation
      - feedIn
      - profileType
      - profileFamily
      - referenceProfileDesignation
      - dailyParameters
      - procedure
    PI_55673__masterData__BALANCING__loadProfiles__dailyParameters:
      type: object
      properties:
        serviceProvider:
          $ref: ../../../bo4e-en/fields/com/DailyParameters/serviceProvider.yaml#/components/schemas/serviceProvider
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z87|Z88].SG10.CCI+[ZA0|Z99]
        publisher:
          $ref: ../../../bo4e-en/fields/com/DailyParameters/publisher.yaml#/components/schemas/publisher
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z87|Z88].SG10.CCI+[ZA0|Z99]
        climateZone:
          $ref: ../../../bo4e-en/fields/com/DailyParameters/climateZone.yaml#/components/schemas/climateZone
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z87|Z88].SG10.CCI+[ZA0|Z99]
        temperatureMeasuringPoint:
          $ref: ../../../bo4e-en/fields/com/DailyParameters/temperatureMeasuringPoint.yaml#/components/schemas/temperatureMeasuringPoint
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z87|Z88].SG10.CCI+[ZA0|Z99]
      required:
      - serviceProvider
      - publisher
      - climateZone
      - temperatureMeasuringPoint
    PI_55673__masterData__BALANCING__temperatureWork:
      type: object
      properties:
        unit:
          $ref: ../../../bo4e-en/fields/com/Quantity/unit.yaml#/components/schemas/unit
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z80|Z81].SG9.QTY+[Z10|265]
        value:
          $ref: ../../../bo4e-en/fields/com/Quantity/value.yaml#/components/schemas/value
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z80|Z81].SG9.QTY+[Z10|265]
      required:
      - unit
      - value
    PI_55673__masterData__MARKET_LOCATION:
      type: object
      properties:
        balancingArea:
          $ref: ../../../bo4e-en/fields/bo/MarketLocation/balancingArea.yaml#/components/schemas/balancingArea
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z80|Z81].SG10.CCI+Z20
        dataQuality:
          $ref: ../../../bo4e-en/fields/bo/MarketLocation/dataQuality.yaml#/components/schemas/dataQuality
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z80|Z81]
        validityPeriod:
          $ref: '#/components/schemas/PI_55673__masterData__MARKET_LOCATION__validityPeriod'
        marketLocationId:
          $ref: ../../../bo4e-en/fields/bo/MarketLocation/marketLocationId.yaml#/components/schemas/marketLocationId
          x-edifact-segment:
          - SG4.IDE+24.SG5.LOC+Z16
        marketRoles:
          type: array
          items:
            $ref: '#/components/schemas/PI_55673__masterData__MARKET_LOCATION__marketRoles'
        controlZone:
          $ref: ../../../bo4e-en/fields/bo/MarketLocation/controlZone.yaml#/components/schemas/controlZone
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z80|Z81].SG10.CCI+Z18
      required:
      - balancingArea
      - dataQuality
      - validityPeriod
      - marketLocationId
      - marketRoles
      - controlZone
    PI_55673__masterData__MARKET_LOCATION__validityPeriod:
      type: object
      properties:
        periodId:
          $ref: ../../../bo4e-en/fields/com/TimePeriod/periodId.yaml#/components/schemas/periodId
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z80|Z81]
      required:
      - periodId
    PI_55673__masterData__MARKET_LOCATION__marketRoles:
      type: object
      properties:
        marketRole:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/marketRole.yaml#/components/schemas/marketRole
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z80|Z81].SG10.CCI+++ZB3.CAV+Z90
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z80|Z81].SG10.CCI+++ZB3.CAV+Z90
      required:
      - marketRole
      - roleCodeNumber
    PI_55673__masterData__TRANCHE:
      type: object
      properties:
        balancingGroup:
          $ref: ../../../bo4e-en/fields/bo/Tranche/balancingGroup.yaml#/components/schemas/balancingGroup
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z94|Z95].SG10.CCI+Z19
        dataQuality:
          $ref: ../../../bo4e-en/fields/bo/Tranche/dataQuality.yaml#/components/schemas/dataQuality
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z94|Z95]
        validityPeriod:
          $ref: '#/components/schemas/PI_55673__masterData__TRANCHE__validityPeriod'
        trancheId:
          $ref: ../../../bo4e-en/fields/bo/Tranche/trancheId.yaml#/components/schemas/trancheId
          x-edifact-segment:
          - SG4.IDE+24.SG5.LOC+Z21
      required:
      - balancingGroup
      - dataQuality
      - validityPeriod
      - trancheId
    PI_55673__masterData__TRANCHE__validityPeriod:
      type: object
      properties:
        periodId:
          $ref: ../../../bo4e-en/fields/com/TimePeriod/periodId.yaml#/components/schemas/periodId
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+[Z94|Z95]
      required:
      - periodId
    PI_55673__masterData__USAGE_PERIOD:
      type: object
      properties:
        dataQuality:
          $ref: ../../../bo4e-en/fields/bo/UsagePeriod/dataQuality.yaml#/components/schemas/dataQuality
          x-edifact-segment:
          - SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55]
        usageFrom:
          $ref: ../../../bo4e-en/fields/bo/UsagePeriod/usageFrom.yaml#/components/schemas/usageFrom
          x-edifact-segment:
          - SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55].DTM+Z25
        usageTo:
          $ref: ../../../bo4e-en/fields/bo/UsagePeriod/usageTo.yaml#/components/schemas/usageTo
          x-edifact-segment:
          - SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55].DTM+Z26
        periodId:
          $ref: ../../../bo4e-en/fields/bo/UsagePeriod/periodId.yaml#/components/schemas/periodId
          x-edifact-segment:
          - SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55]
      required:
      - dataQuality
      - usageFrom
      - periodId
    PI_55673__transactionData:
      type: object
      properties:
        sender:
          $ref: '#/components/schemas/PI_55673__transactionData__sender'
        requestReferenceNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/requestReferenceNumber.yaml#/components/schemas/requestReferenceNumber
          x-edifact-segment:
          - SG4.IDE+24.SG6.RFF+TN
        responseStatusPeriod:
          type: array
          items:
            $ref: '#/components/schemas/PI_55673__transactionData__responseStatusPeriod'
        documentNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/documentNumber.yaml#/components/schemas/documentNumber
          x-edifact-segment:
          - BGM+[E03|Z88]
        receiver:
          $ref: '#/components/schemas/PI_55673__transactionData__receiver'
        category:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/category.yaml#/components/schemas/category
          x-edifact-segment:
          - BGM+[E03|Z88]
        messageDate:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/messageDate.yaml#/components/schemas/messageDate
          x-edifact-segment:
          - DTM+137
        messageReferenceNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/messageReferenceNumber.yaml#/components/schemas/messageReferenceNumber
          x-edifact-segment:
          - UNH
        verificationIdentifier:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/verificationIdentifier.yaml#/components/schemas/verificationIdentifier
          x-edifact-segment:
          - SG4.IDE+24.SG6.RFF+Z13
        transactionReason:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/transactionReason.yaml#/components/schemas/transactionReason
          x-edifact-segment:
          - SG4.IDE+24.STS+7
        transactionReasonSupplement:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/transactionReasonSupplement.yaml#/components/schemas/transactionReasonSupplement
          x-edifact-segment:
          - SG4.IDE+24.STS+7
        processNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/processNumber.yaml#/components/schemas/processNumber
          x-edifact-segment:
          - SG4.IDE+24
      required:
      - sender
      - requestReferenceNumber
      - documentNumber
      - receiver
      - category
      - messageDate
      - messageReferenceNumber
      - verificationIdentifier
      - transactionReason
      - transactionReasonSupplement
      - processNumber
    PI_55673__transactionData__sender:
      type: object
      properties:
        contactPerson:
          $ref: '#/components/schemas/PI_55673__transactionData__sender__contactPerson'
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG2.NAD+MS
        roleCodeType:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeType.yaml#/components/schemas/roleCodeType
          x-edifact-segment:
          - SG2.NAD+MS
      required:
      - contactPerson
      - roleCodeNumber
      - roleCodeType
    PI_55673__transactionData__sender__contactPerson:
      type: object
      properties:
        eMailAddress:
          $ref: ../../../bo4e-en/fields/bo/ContactPerson/eMailAddress.yaml#/components/schemas/eMailAddress
          x-edifact-segment:
          - SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]
        lastName:
          $ref: ../../../bo4e-en/fields/bo/ContactPerson/lastName.yaml#/components/schemas/lastName
          x-edifact-segment:
          - SG2.NAD+MS.SG3.CTA
        phoneNumbers:
          type: array
          items:
            $ref: '#/components/schemas/PI_55673__transactionData__sender__contactPerson__phoneNumbers'
      required:
      - eMailAddress
      - lastName
      - phoneNumbers
    PI_55673__transactionData__sender__contactPerson__phoneNumbers:
      type: object
      properties:
        numberType:
          $ref: ../../../bo4e-en/fields/com/PhoneNumber/numberType.yaml#/components/schemas/numberType
          x-edifact-segment:
          - SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]
        phoneNumber:
          $ref: ../../../bo4e-en/fields/com/PhoneNumber/phoneNumber.yaml#/components/schemas/phoneNumber
          x-edifact-segment:
          - SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]
      required:
      - numberType
      - phoneNumber
    PI_55673__transactionData__responseStatusPeriod:
      type: object
      properties:
        code:
          $ref: ../../../bo4e-en/fields/com/ResponseStatusPeriod/code.yaml#/components/schemas/code
          x-edifact-segment:
          - SG4.IDE+24.STS+E01
        list:
          $ref: ../../../bo4e-en/fields/com/ResponseStatusPeriod/list.yaml#/components/schemas/list
          x-edifact-segment:
          - SG4.IDE+24.STS+E01
        periodId:
          $ref: ../../../bo4e-en/fields/com/ResponseStatusPeriod/periodId.yaml#/components/schemas/periodId
          x-edifact-segment:
          - SG4.IDE+24.STS+E01
    PI_55673__transactionData__receiver:
      type: object
      properties:
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG2.NAD+MR
        roleCodeType:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeType.yaml#/components/schemas/roleCodeType
          x-edifact-segment:
          - SG2.NAD+MR
      required:
      - roleCodeNumber
      - roleCodeType
