openapi: 3.1.0
info:
  title: PI_33002
  version: '202510'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_33002:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_33002__masterData'
        transactionData:
          $ref: '#/components/schemas/PI_33002__transactionData'
      required:
      - masterData
      - transactionData
    PI_33002__masterData:
      type: object
      properties:
        ADVICE_NOTE:
          type: array
          items:
            $ref: '#/components/schemas/PI_33002__masterData__ADVICE_NOTE'
      required:
      - ADVICE_NOTE
    PI_33002__masterData__ADVICE_NOTE:
      type: object
      properties:
        adviceNoteNumber:
          $ref: ../../../bo4e-en/fields/bo/AdviceNote/adviceNoteNumber.yaml#/components/schemas/adviceNoteNumber
          x-edifact-segment:
          - BGM+239
        adviceNoteType:
          $ref: ../../../bo4e-en/fields/bo/AdviceNote/adviceNoteType.yaml#/components/schemas/adviceNoteType
          x-edifact-segment:
          - BGM+239
        positions:
          type: array
          items:
            $ref: '#/components/schemas/PI_33002__masterData__ADVICE_NOTE__positions'
        toPay:
          $ref: '#/components/schemas/PI_33002__masterData__ADVICE_NOTE__toPay'
      required:
      - adviceNoteNumber
      - adviceNoteType
      - positions
      - toPay
    PI_33002__masterData__ADVICE_NOTE__positions:
      type: object
      properties:
        discrepancy:
          type: array
          items:
            $ref: '#/components/schemas/PI_33002__masterData__ADVICE_NOTE__positions__discrepancy'
        totalGross:
          $ref: '#/components/schemas/PI_33002__masterData__ADVICE_NOTE__positions__totalGross'
        isSelfIssued:
          $ref: ../../../bo4e-en/fields/com/AdviceNotePosition/isSelfIssued.yaml#/components/schemas/isSelfIssued
          x-edifact-segment:
          - SG5.DOC
        isCancellation:
          $ref: ../../../bo4e-en/fields/com/AdviceNotePosition/isCancellation.yaml#/components/schemas/isCancellation
          x-edifact-segment:
          - SG5.DOC
        billingDate:
          $ref: ../../../bo4e-en/fields/com/AdviceNotePosition/billingDate.yaml#/components/schemas/billingDate
          x-edifact-segment:
          - SG5.DOC.DTM+137
        invoiceNumber:
          $ref: ../../../bo4e-en/fields/com/AdviceNotePosition/invoiceNumber.yaml#/components/schemas/invoiceNumber
          x-edifact-segment:
          - SG5.DOC
        reference:
          $ref: ../../../bo4e-en/fields/com/AdviceNotePosition/reference.yaml#/components/schemas/reference
          x-edifact-segment:
          - SG5.DOC.RFF+ACW
        toPay:
          $ref: '#/components/schemas/PI_33002__masterData__ADVICE_NOTE__positions__toPay'
      required:
      - discrepancy
      - totalGross
      - isSelfIssued
      - isCancellation
      - billingDate
      - invoiceNumber
      - toPay
    PI_33002__masterData__ADVICE_NOTE__positions__discrepancy:
      type: object
      properties:
        discrepancyReasonNote1:
          $ref: ../../../bo4e-en/fields/com/Discrepancy/discrepancyReasonNote1.yaml#/components/schemas/discrepancyReasonNote1
          x-edifact-segment:
          - SG5.DOC.SG7.AJT.FTX+ABO
        discrepancyReasonNote2:
          $ref: ../../../bo4e-en/fields/com/Discrepancy/discrepancyReasonNote2.yaml#/components/schemas/discrepancyReasonNote2
          x-edifact-segment:
          - SG5.DOC.SG7.AJT.FTX+ABO
        discrepancyReasonNote3:
          $ref: ../../../bo4e-en/fields/com/Discrepancy/discrepancyReasonNote3.yaml#/components/schemas/discrepancyReasonNote3
          x-edifact-segment:
          - SG5.DOC.SG7.AJT.FTX+ABO
        discrepancyReasonNote4:
          $ref: ../../../bo4e-en/fields/com/Discrepancy/discrepancyReasonNote4.yaml#/components/schemas/discrepancyReasonNote4
          x-edifact-segment:
          - SG5.DOC.SG7.AJT.FTX+ABO
        discrepancyReasonNote5:
          $ref: ../../../bo4e-en/fields/com/Discrepancy/discrepancyReasonNote5.yaml#/components/schemas/discrepancyReasonNote5
          x-edifact-segment:
          - SG5.DOC.SG7.AJT.FTX+ABO
        discrepancyReasonCode:
          $ref: ../../../bo4e-en/fields/com/Discrepancy/discrepancyReasonCode.yaml#/components/schemas/discrepancyReasonCode
          x-edifact-segment:
          - SG5.DOC.SG7.AJT
        discrepancyReasonCodeList:
          $ref: ../../../bo4e-en/fields/com/Discrepancy/discrepancyReasonCodeList.yaml#/components/schemas/discrepancyReasonCodeList
          x-edifact-segment:
          - SG5.DOC.SG7.AJT
      required:
      - discrepancyReasonCode
      - discrepancyReasonCodeList
    PI_33002__masterData__ADVICE_NOTE__positions__totalGross:
      type: object
      properties:
        value:
          $ref: ../../../bo4e-en/fields/com/Amount/value.yaml#/components/schemas/value
          x-edifact-segment:
          - SG5.DOC.MOA+12
      required:
      - value
    PI_33002__masterData__ADVICE_NOTE__positions__toPay:
      type: object
      properties:
        value:
          $ref: ../../../bo4e-en/fields/com/Amount/value.yaml#/components/schemas/value
          x-edifact-segment:
          - SG5.DOC.MOA+9
      required:
      - value
    PI_33002__masterData__ADVICE_NOTE__toPay:
      type: object
      properties:
        currency:
          $ref: ../../../bo4e-en/fields/com/Amount/currency.yaml#/components/schemas/currency
          x-edifact-segment:
          - SG4.CUX+2
        value:
          $ref: ../../../bo4e-en/fields/com/Amount/value.yaml#/components/schemas/value
          x-edifact-segment:
          - MOA+12
      required:
      - currency
      - value
    PI_33002__transactionData:
      type: object
      properties:
        sender:
          $ref: '#/components/schemas/PI_33002__transactionData__sender'
        receiver:
          $ref: '#/components/schemas/PI_33002__transactionData__receiver'
        messageDate:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/messageDate.yaml#/components/schemas/messageDate
          x-edifact-segment:
          - DTM+137
        messageReferenceNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/messageReferenceNumber.yaml#/components/schemas/messageReferenceNumber
          x-edifact-segment:
          - UNH
        verificationIdentifier:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/verificationIdentifier.yaml#/components/schemas/verificationIdentifier
          x-edifact-segment:
          - RFF+Z13
      required:
      - sender
      - receiver
      - messageDate
      - messageReferenceNumber
      - verificationIdentifier
    PI_33002__transactionData__sender:
      type: object
      properties:
        contactPerson:
          $ref: '#/components/schemas/PI_33002__transactionData__sender__contactPerson'
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG1.NAD+MS
        roleCodeType:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeType.yaml#/components/schemas/roleCodeType
          x-edifact-segment:
          - SG1.NAD+MS
      required:
      - contactPerson
      - roleCodeNumber
      - roleCodeType
    PI_33002__transactionData__sender__contactPerson:
      type: object
      properties:
        eMailAddress:
          $ref: ../../../bo4e-en/fields/bo/ContactPerson/eMailAddress.yaml#/components/schemas/eMailAddress
          x-edifact-segment:
          - SG1.NAD+MS.SG3.CTA+IC.COM+[EM|FX|TE|AJ|AL]
        lastName:
          $ref: ../../../bo4e-en/fields/bo/ContactPerson/lastName.yaml#/components/schemas/lastName
          x-edifact-segment:
          - SG1.NAD+MS.SG3.CTA+IC
        phoneNumbers:
          type: array
          items:
            $ref: '#/components/schemas/PI_33002__transactionData__sender__contactPerson__phoneNumbers'
      required:
      - eMailAddress
      - lastName
      - phoneNumbers
    PI_33002__transactionData__sender__contactPerson__phoneNumbers:
      type: object
      properties:
        numberType:
          $ref: ../../../bo4e-en/fields/com/PhoneNumber/numberType.yaml#/components/schemas/numberType
          x-edifact-segment:
          - SG1.NAD+MS.SG3.CTA+IC.COM+[EM|FX|TE|AJ|AL]
        phoneNumber:
          $ref: ../../../bo4e-en/fields/com/PhoneNumber/phoneNumber.yaml#/components/schemas/phoneNumber
          x-edifact-segment:
          - SG1.NAD+MS.SG3.CTA+IC.COM+[EM|FX|TE|AJ|AL]
      required:
      - numberType
      - phoneNumber
    PI_33002__transactionData__receiver:
      type: object
      properties:
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG1.NAD+MR
        roleCodeType:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeType.yaml#/components/schemas/roleCodeType
          x-edifact-segment:
          - SG1.NAD+MR
      required:
      - roleCodeNumber
      - roleCodeType
