openapi: 3.1.0
info:
  title: PI_27003
  version: '202604'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: 39ae45d481e5cc3d4d7aae328a23a9751236156a
components:
  schemas:
    PI_27003:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_27003__stammdaten'
        transaktionsdaten:
          $ref: '#/components/schemas/PI_27003__transaktionsdaten'
      required:
        - stammdaten
        - transaktionsdaten
    PI_27003__stammdaten:
      type: object
      properties:
        PREISBLATT:
          type: array
          items:
            $ref: '#/components/schemas/PI_27003__stammdaten__PREISBLATT'
      required:
        - PREISBLATT
    PI_27003__stammdaten__PREISBLATT:
      type: object
      properties:
        gueltigkeit:
          $ref: '#/components/schemas/PI_27003__stammdaten__PREISBLATT__gueltigkeit'
        preisNetzbetreiberCodenummer:
          $ref: '../../../bo4e/fields/bo/Preisblatt/preisNetzbetreiberCodenummer.yaml#/components/schemas/preisNetzbetreiberCodenummer'
          x-edifact-segment:
            - SG1.RFF+Z56
        preispositionen:
          type: array
          items:
            $ref: '#/components/schemas/PI_27003__stammdaten__PREISBLATT__preispositionen'
      required:
        - gueltigkeit
        - preisNetzbetreiberCodenummer
        - preispositionen
    PI_27003__stammdaten__PREISBLATT__gueltigkeit:
      type: object
      properties:
        startdatum:
          $ref: '../../../bo4e/fields/com/Zeitraum/startdatum.yaml#/components/schemas/startdatum'
          x-edifact-segment:
            - DTM+157
      required:
        - startdatum
    PI_27003__stammdaten__PREISBLATT__preispositionen:
      type: object
      properties:
        artikelId:
          $ref: '../../../bo4e/fields/com/Preisposition/artikelId.yaml#/components/schemas/artikelId'
          x-edifact-segment:
            - SG17.PGI+9.SG36.LIN
            - SG17.PGI+Z01.SG36.LIN
        positionsnummer:
          $ref: '../../../bo4e/fields/com/Preisposition/positionsnummer.yaml#/components/schemas/positionsnummer'
          x-edifact-segment:
            - SG17.PGI+9.SG36.LIN
            - SG17.PGI+Z01.SG36.LIN
        preisstaffeln:
          type: array
          items:
            $ref: '#/components/schemas/PI_27003__stammdaten__PREISBLATT__preispositionen__preisstaffeln'
        zeitbasis:
          $ref: '../../../bo4e/fields/com/Preisposition/zeitbasis.yaml#/components/schemas/zeitbasis'
          x-edifact-segment:
            - SG17.PGI+9.SG36.LIN.SG40.PRI+CAL
            - SG17.PGI+Z01.SG36.LIN.SG40.PRI+CAL
      required:
        - artikelId
        - positionsnummer
        - preisstaffeln
        - zeitbasis
    PI_27003__stammdaten__PREISBLATT__preispositionen__preisstaffeln:
      type: object
      properties:
        einheitspreis:
          $ref: '../../../bo4e/fields/com/Preisstaffel/einheitspreis.yaml#/components/schemas/einheitspreis'
          x-edifact-segment:
            - SG17.PGI+9.SG36.LIN.SG40.PRI+CAL
            - SG17.PGI+Z01.SG36.LIN.SG40.PRI+CAL
        staffelgrenzeBis:
          $ref: '../../../bo4e/fields/com/Preisstaffel/staffelgrenzeBis.yaml#/components/schemas/staffelgrenzeBis'
          x-edifact-segment:
            - SG17.PGI+Z01.SG36.LIN.SG40.PRI+CAL.RNG+10+KWH
        staffelgrenzeVon:
          $ref: '../../../bo4e/fields/com/Preisstaffel/staffelgrenzeVon.yaml#/components/schemas/staffelgrenzeVon'
          x-edifact-segment:
            - SG17.PGI+Z01.SG36.LIN.SG40.PRI+CAL.RNG+10+KWH
      required:
        - einheitspreis
    PI_27003__transaktionsdaten:
      type: object
      properties:
        absender:
          $ref: '#/components/schemas/PI_27003__transaktionsdaten__absender'
        dokumentennummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/dokumentennummer.yaml#/components/schemas/dokumentennummer'
          x-edifact-segment:
            - 'BGM+[Z54|Z64|Z67|Z70]'
        empfaenger:
          $ref: '#/components/schemas/PI_27003__transaktionsdaten__empfaenger'
        kategorie:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/kategorie.yaml#/components/schemas/kategorie'
          x-edifact-segment:
            - 'BGM+[Z54|Z64|Z67|Z70]'
        nachrichtendatum:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtendatum.yaml#/components/schemas/nachrichtendatum'
          x-edifact-segment:
            - DTM+137
        nachrichtenreferenznummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtenreferenznummer.yaml#/components/schemas/nachrichtenreferenznummer'
          x-edifact-segment:
            - UNH
        pruefidentifikator:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/pruefidentifikator.yaml#/components/schemas/pruefidentifikator'
          x-edifact-segment:
            - SG1.RFF+Z13
        vorgangsreferenznummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/vorgangsreferenznummer.yaml#/components/schemas/vorgangsreferenznummer'
          x-edifact-segment:
            - SG1.RFF+ACW
      required:
        - absender
        - dokumentennummer
        - empfaenger
        - kategorie
        - nachrichtendatum
        - nachrichtenreferenznummer
        - pruefidentifikator
        - vorgangsreferenznummer
    PI_27003__transaktionsdaten__absender:
      type: object
      properties:
        ansprechpartner:
          $ref: '#/components/schemas/PI_27003__transaktionsdaten__absender__ansprechpartner'
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+MS
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+MS
      required:
        - ansprechpartner
        - rollencodenummer
        - rollencodetyp
    PI_27003__transaktionsdaten__absender__ansprechpartner:
      type: object
      properties:
        eMailAdresse:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/eMailAdresse.yaml#/components/schemas/eMailAdresse'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG4.CTA+IC.COM+[EM|FX|TE|AJ|AL]'
        nachname:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/nachname.yaml#/components/schemas/nachname'
          x-edifact-segment:
            - SG2.NAD+MS.SG4.CTA+IC
        rufnummern:
          type: array
          items:
            $ref: '#/components/schemas/PI_27003__transaktionsdaten__absender__ansprechpartner__rufnummern'
      required:
        - eMailAdresse
        - nachname
        - rufnummern
    PI_27003__transaktionsdaten__absender__ansprechpartner__rufnummern:
      type: object
      properties:
        nummerntyp:
          $ref: '../../../bo4e/fields/com/Rufnummer/nummerntyp.yaml#/components/schemas/nummerntyp'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG4.CTA+IC.COM+[EM|FX|TE|AJ|AL]'
        rufnummer:
          $ref: '../../../bo4e/fields/com/Rufnummer/rufnummer.yaml#/components/schemas/rufnummer'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG4.CTA+IC.COM+[EM|FX|TE|AJ|AL]'
      required:
        - nummerntyp
        - rufnummer
    PI_27003__transaktionsdaten__empfaenger:
      type: object
      properties:
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+MR
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+MR
      required:
        - rollencodenummer
        - rollencodetyp
