openapi: 3.1.0
info:
  title: PI_44101
  version: '202604'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_44101:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_44101__masterData'
        transactionData:
          $ref: '#/components/schemas/PI_44101__transactionData'
      required:
      - masterData
      - transactionData
    PI_44101__masterData:
      type: object
      properties:
        METERING_LOCATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_44101__masterData__METERING_LOCATION'
        GRID_ACCESS_CONTRACT:
          type: array
          items:
            $ref: '#/components/schemas/PI_44101__masterData__GRID_ACCESS_CONTRACT'
      required:
      - METERING_LOCATION
      - GRID_ACCESS_CONTRACT
    PI_44101__masterData__METERING_LOCATION:
      type: object
      properties:
        meteringLocationId:
          $ref: ../../../bo4e-en/fields/bo/MeteringLocation/meteringLocationId.yaml#/components/schemas/meteringLocationId
          x-edifact-segment:
          - SG4.IDE+24.SG5.LOC+172
      required:
      - meteringLocationId
    PI_44101__masterData__GRID_ACCESS_CONTRACT:
      type: object
      properties:
        contractStart:
          $ref: ../../../bo4e-en/fields/bo/Contract/contractStart.yaml#/components/schemas/contractStart
          x-edifact-segment:
          - SG4.IDE+24.DTM+92
        contractEnd:
          $ref: ../../../bo4e-en/fields/bo/Contract/contractEnd.yaml#/components/schemas/contractEnd
          x-edifact-segment:
          - SG4.IDE+24.DTM+93
      required:
      - contractStart
    PI_44101__transactionData:
      type: object
      properties:
        sender:
          $ref: '#/components/schemas/PI_44101__transactionData__sender'
        involvedMarketPartner:
          $ref: '#/components/schemas/PI_44101__transactionData__involvedMarketPartner'
        documentNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/documentNumber.yaml#/components/schemas/documentNumber
          x-edifact-segment:
          - BGM+Z22
        receiver:
          $ref: '#/components/schemas/PI_44101__transactionData__receiver'
        validFrom:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/validFrom.yaml#/components/schemas/validFrom
          x-edifact-segment:
          - SG4.IDE+24.DTM+157
        category:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/category.yaml#/components/schemas/category
          x-edifact-segment:
          - BGM+Z22
        messageDate:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/messageDate.yaml#/components/schemas/messageDate
          x-edifact-segment:
          - DTM+137
        messageReferenceNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/messageReferenceNumber.yaml#/components/schemas/messageReferenceNumber
          x-edifact-segment:
          - UNH
        verificationIdentifier:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/verificationIdentifier.yaml#/components/schemas/verificationIdentifier
          x-edifact-segment:
          - SG4.IDE+24.SG6.RFF+Z13
        transactionReason:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/transactionReason.yaml#/components/schemas/transactionReason
          x-edifact-segment:
          - SG4.IDE+24.STS+7
        contractStart:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/contractStart.yaml#/components/schemas/contractStart
          x-edifact-segment:
          - SG4.IDE+24.DTM+92
        contractEnd:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/contractEnd.yaml#/components/schemas/contractEnd
          x-edifact-segment:
          - SG4.IDE+24.DTM+93
        processNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/processNumber.yaml#/components/schemas/processNumber
          x-edifact-segment:
          - SG4.IDE+24
      required:
      - sender
      - involvedMarketPartner
      - documentNumber
      - receiver
      - validFrom
      - category
      - messageDate
      - messageReferenceNumber
      - verificationIdentifier
      - transactionReason
      - contractStart
      - processNumber
    PI_44101__transactionData__sender:
      type: object
      properties:
        contactPerson:
          $ref: '#/components/schemas/PI_44101__transactionData__sender__contactPerson'
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG2.NAD+MS
        roleCodeType:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeType.yaml#/components/schemas/roleCodeType
          x-edifact-segment:
          - SG2.NAD+MS
      required:
      - contactPerson
      - roleCodeNumber
      - roleCodeType
    PI_44101__transactionData__sender__contactPerson:
      type: object
      properties:
        eMailAddress:
          $ref: ../../../bo4e-en/fields/bo/ContactPerson/eMailAddress.yaml#/components/schemas/eMailAddress
          x-edifact-segment:
          - SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]
        lastName:
          $ref: ../../../bo4e-en/fields/bo/ContactPerson/lastName.yaml#/components/schemas/lastName
          x-edifact-segment:
          - SG2.NAD+MS.SG3.CTA
        phoneNumbers:
          type: array
          items:
            $ref: '#/components/schemas/PI_44101__transactionData__sender__contactPerson__phoneNumbers'
      required:
      - eMailAddress
      - lastName
      - phoneNumbers
    PI_44101__transactionData__sender__contactPerson__phoneNumbers:
      type: object
      properties:
        numberType:
          $ref: ../../../bo4e-en/fields/com/PhoneNumber/numberType.yaml#/components/schemas/numberType
          x-edifact-segment:
          - SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]
        phoneNumber:
          $ref: ../../../bo4e-en/fields/com/PhoneNumber/phoneNumber.yaml#/components/schemas/phoneNumber
          x-edifact-segment:
          - SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]
      required:
      - numberType
      - phoneNumber
    PI_44101__transactionData__involvedMarketPartner:
      type: object
      properties:
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+VY
        roleCodeType:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeType.yaml#/components/schemas/roleCodeType
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+VY
      required:
      - roleCodeNumber
      - roleCodeType
    PI_44101__transactionData__receiver:
      type: object
      properties:
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG2.NAD+MR
        roleCodeType:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeType.yaml#/components/schemas/roleCodeType
          x-edifact-segment:
          - SG2.NAD+MR
      required:
      - roleCodeNumber
      - roleCodeType
