openapi: 3.1.0
info:
  title: PI_44021
  version: '202604'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_44021:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_44021__masterData'
        transactionData:
          $ref: '#/components/schemas/PI_44021__transactionData'
      required:
      - masterData
      - transactionData
    PI_44021__masterData:
      type: object
      properties:
        BALANCING:
          type: array
          items:
            $ref: '#/components/schemas/PI_44021__masterData__BALANCING'
        ENERGY_SUPPLY_CONTRACT:
          type: array
          items:
            $ref: '#/components/schemas/PI_44021__masterData__ENERGY_SUPPLY_CONTRACT'
        MARKET_LOCATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_44021__masterData__MARKET_LOCATION'
        GRID_ACCESS_CONTRACT:
          type: array
          items:
            $ref: '#/components/schemas/PI_44021__masterData__GRID_ACCESS_CONTRACT'
      required:
      - BALANCING
      - ENERGY_SUPPLY_CONTRACT
      - MARKET_LOCATION
      - GRID_ACCESS_CONTRACT
    PI_44021__masterData__BALANCING:
      type: object
      properties:
        balancingStart:
          $ref: ../../../bo4e-en/fields/bo/Balancing/balancingStart.yaml#/components/schemas/balancingStart
          x-edifact-segment:
          - SG4.IDE+24.DTM+158
        balancingEnd:
          $ref: ../../../bo4e-en/fields/bo/Balancing/balancingEnd.yaml#/components/schemas/balancingEnd
          x-edifact-segment:
          - SG4.IDE+24.DTM+159
        balancingGroups:
          type: array
          items:
            $ref: '#/components/schemas/PI_44021__masterData__BALANCING__balancingGroups'
        caseGroupAssignment:
          $ref: ../../../bo4e-en/fields/bo/Balancing/caseGroupAssignment.yaml#/components/schemas/caseGroupAssignment
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+++Z17
        annualConsumptionForecast:
          $ref: '#/components/schemas/PI_44021__masterData__BALANCING__annualConsumptionForecast'
        customerValue:
          $ref: '#/components/schemas/PI_44021__masterData__BALANCING__customerValue'
        loadProfiles:
          type: array
          items:
            $ref: '#/components/schemas/PI_44021__masterData__BALANCING__loadProfiles'
        forecastBasis:
          $ref: ../../../bo4e-en/fields/bo/Balancing/forecastBasis.yaml#/components/schemas/forecastBasis
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI
      required:
      - balancingGroups
      - caseGroupAssignment
      - annualConsumptionForecast
      - customerValue
      - loadProfiles
      - forecastBasis
    PI_44021__masterData__BALANCING__balancingGroups:
      type: object
      properties:
        designation:
          $ref: ../../../bo4e-en/fields/bo/BalancingGroup/designation.yaml#/components/schemas/designation
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+Z19
      required:
      - designation
    PI_44021__masterData__BALANCING__annualConsumptionForecast:
      type: object
      properties:
        unit:
          $ref: ../../../bo4e-en/fields/com/Quantity/unit.yaml#/components/schemas/unit
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01.SG9.QTY+31
        value:
          $ref: ../../../bo4e-en/fields/com/Quantity/value.yaml#/components/schemas/value
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01.SG9.QTY+31
      required:
      - unit
      - value
    PI_44021__masterData__BALANCING__customerValue:
      type: object
      properties:
        value:
          $ref: ../../../bo4e-en/fields/com/Quantity/value.yaml#/components/schemas/value
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01.SG9.QTY+Y02
      required:
      - value
    PI_44021__masterData__BALANCING__loadProfiles:
      type: object
      properties:
        designation:
          $ref: ../../../bo4e-en/fields/com/LoadProfile/designation.yaml#/components/schemas/designation
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z35.SG10.CCI+Z12.CAV
        publisher:
          $ref: ../../../bo4e-en/fields/com/LoadProfile/publisher.yaml#/components/schemas/publisher
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z35.SG10.CCI+Z12.CAV
        dailyParameters:
          $ref: '#/components/schemas/PI_44021__masterData__BALANCING__loadProfiles__dailyParameters'
        procedure:
          $ref: ../../../bo4e-en/fields/com/LoadProfile/procedure.yaml#/components/schemas/procedure
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z35.SG10.CCI+Z12
      required:
      - designation
      - publisher
      - dailyParameters
      - procedure
    PI_44021__masterData__BALANCING__loadProfiles__dailyParameters:
      type: object
      properties:
        serviceProvider:
          $ref: ../../../bo4e-en/fields/com/DailyParameters/serviceProvider.yaml#/components/schemas/serviceProvider
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z35.SG10.CCI
        publisher:
          $ref: ../../../bo4e-en/fields/com/DailyParameters/publisher.yaml#/components/schemas/publisher
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z35.SG10.CCI
        climateZone:
          $ref: ../../../bo4e-en/fields/com/DailyParameters/climateZone.yaml#/components/schemas/climateZone
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z35.SG10.CCI
        temperatureMeasuringPoint:
          $ref: ../../../bo4e-en/fields/com/DailyParameters/temperatureMeasuringPoint.yaml#/components/schemas/temperatureMeasuringPoint
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z35.SG10.CCI
      required:
      - serviceProvider
      - publisher
      - climateZone
      - temperatureMeasuringPoint
    PI_44021__masterData__ENERGY_SUPPLY_CONTRACT:
      type: object
      properties:
        contractPartner2:
          type: array
          items:
            $ref: '#/components/schemas/PI_44021__masterData__ENERGY_SUPPLY_CONTRACT__contractPartner2'
      required:
      - contractPartner2
    PI_44021__masterData__ENERGY_SUPPLY_CONTRACT__contractPartner2:
      type: object
      properties:
        salutation:
          $ref: ../../../bo4e-en/fields/bo/BusinessPartner/salutation.yaml#/components/schemas/salutation
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z09
        commercialClassification:
          $ref: ../../../bo4e-en/fields/bo/BusinessPartner/commercialClassification.yaml#/components/schemas/commercialClassification
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z09
        name1:
          $ref: ../../../bo4e-en/fields/bo/BusinessPartner/name1.yaml#/components/schemas/name1
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z09
        name2:
          $ref: ../../../bo4e-en/fields/bo/BusinessPartner/name2.yaml#/components/schemas/name2
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z09
        name3:
          $ref: ../../../bo4e-en/fields/bo/BusinessPartner/name3.yaml#/components/schemas/name3
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z09
        name4:
          $ref: ../../../bo4e-en/fields/bo/BusinessPartner/name4.yaml#/components/schemas/name4
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z09
      required:
      - salutation
      - commercialClassification
      - name1
      - name2
      - name3
      - name4
    PI_44021__masterData__MARKET_LOCATION:
      type: object
      properties:
        locationAddress:
          $ref: '#/components/schemas/PI_44021__masterData__MARKET_LOCATION__locationAddress'
        marketLocationId:
          $ref: ../../../bo4e-en/fields/bo/MarketLocation/marketLocationId.yaml#/components/schemas/marketLocationId
          x-edifact-segment:
          - SG4.IDE+24.SG5.LOC+172
      required:
      - locationAddress
      - marketLocationId
    PI_44021__masterData__MARKET_LOCATION__locationAddress:
      type: object
      properties:
        houseNumber:
          $ref: ../../../bo4e-en/fields/com/Address/houseNumber.yaml#/components/schemas/houseNumber
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+DP
        countryCode:
          $ref: ../../../bo4e-en/fields/com/Address/countryCode.yaml#/components/schemas/countryCode
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+DP
        city:
          $ref: ../../../bo4e-en/fields/com/Address/city.yaml#/components/schemas/city
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+DP
        district:
          $ref: ../../../bo4e-en/fields/com/Address/district.yaml#/components/schemas/district
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+DP
        poBox:
          $ref: ../../../bo4e-en/fields/com/Address/poBox.yaml#/components/schemas/poBox
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+DP
        postalCode:
          $ref: ../../../bo4e-en/fields/com/Address/postalCode.yaml#/components/schemas/postalCode
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+DP
        street:
          $ref: ../../../bo4e-en/fields/com/Address/street.yaml#/components/schemas/street
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+DP
        additionalInformation:
          $ref: '#/components/schemas/PI_44021__masterData__MARKET_LOCATION__locationAddress__additionalInformation'
      required:
      - houseNumber
      - countryCode
      - city
      - district
      - poBox
      - postalCode
      - street
      - additionalInformation
    PI_44021__masterData__MARKET_LOCATION__locationAddress__additionalInformation:
      type: object
      properties:
        supplement1:
          $ref: ../../../bo4e-en/fields/com/AddressSupplementInformation/supplement1.yaml#/components/schemas/supplement1
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+DP
        supplement2:
          $ref: ../../../bo4e-en/fields/com/AddressSupplementInformation/supplement2.yaml#/components/schemas/supplement2
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+DP
        supplement3:
          $ref: ../../../bo4e-en/fields/com/AddressSupplementInformation/supplement3.yaml#/components/schemas/supplement3
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+DP
        supplement4:
          $ref: ../../../bo4e-en/fields/com/AddressSupplementInformation/supplement4.yaml#/components/schemas/supplement4
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+DP
        supplement5:
          $ref: ../../../bo4e-en/fields/com/AddressSupplementInformation/supplement5.yaml#/components/schemas/supplement5
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+DP
      required:
      - supplement1
      - supplement2
      - supplement3
      - supplement4
      - supplement5
    PI_44021__masterData__GRID_ACCESS_CONTRACT:
      type: object
      properties:
        contractStart:
          $ref: ../../../bo4e-en/fields/bo/Contract/contractStart.yaml#/components/schemas/contractStart
          x-edifact-segment:
          - SG4.IDE+24.DTM+92
        contractEnd:
          $ref: ../../../bo4e-en/fields/bo/Contract/contractEnd.yaml#/components/schemas/contractEnd
          x-edifact-segment:
          - SG4.IDE+24.DTM+93
        contractConditions:
          $ref: '#/components/schemas/PI_44021__masterData__GRID_ACCESS_CONTRACT__contractConditions'
      required:
      - contractConditions
    PI_44021__masterData__GRID_ACCESS_CONTRACT__contractConditions:
      type: object
      properties:
        householdCustomer:
          $ref: ../../../bo4e-en/fields/com/ContractConditions/householdCustomer.yaml#/components/schemas/householdCustomer
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI
        gridAccessContract:
          $ref: ../../../bo4e-en/fields/com/ContractConditions/gridAccessContract.yaml#/components/schemas/gridAccessContract
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+++Z88.CAV+Z74
        gridAccessPayer:
          $ref: ../../../bo4e-en/fields/com/ContractConditions/gridAccessPayer.yaml#/components/schemas/gridAccessPayer
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+++Z88.CAV+Z73
      required:
      - householdCustomer
      - gridAccessPayer
    PI_44021__transactionData:
      type: object
      properties:
        sender:
          $ref: '#/components/schemas/PI_44021__transactionData__sender'
        requestReferenceNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/requestReferenceNumber.yaml#/components/schemas/requestReferenceNumber
          x-edifact-segment:
          - SG4.IDE+24.SG6.RFF+TN
        responseStatus:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/responseStatus.yaml#/components/schemas/responseStatus
          x-edifact-segment:
          - SG4.IDE+24.STS+E01
        responseStatusCodeList:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/responseStatusCodeList.yaml#/components/schemas/responseStatusCodeList
          x-edifact-segment:
          - SG4.IDE+24.STS+E01
        documentNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/documentNumber.yaml#/components/schemas/documentNumber
          x-edifact-segment:
          - BGM+E03
        receiver:
          $ref: '#/components/schemas/PI_44021__transactionData__receiver'
        category:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/category.yaml#/components/schemas/category
          x-edifact-segment:
          - BGM+E03
        messageDate:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/messageDate.yaml#/components/schemas/messageDate
          x-edifact-segment:
          - DTM+137
        messageReferenceNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/messageReferenceNumber.yaml#/components/schemas/messageReferenceNumber
          x-edifact-segment:
          - UNH
        verificationIdentifier:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/verificationIdentifier.yaml#/components/schemas/verificationIdentifier
          x-edifact-segment:
          - SG4.IDE+24.SG6.RFF+Z13
        transactionReason:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/transactionReason.yaml#/components/schemas/transactionReason
          x-edifact-segment:
          - SG4.IDE+24.STS+7
        contractStart:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/contractStart.yaml#/components/schemas/contractStart
          x-edifact-segment:
          - SG4.IDE+24.DTM+92
        contractEnd:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/contractEnd.yaml#/components/schemas/contractEnd
          x-edifact-segment:
          - SG4.IDE+24.DTM+93
        processNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/processNumber.yaml#/components/schemas/processNumber
          x-edifact-segment:
          - SG4.IDE+24
      required:
      - sender
      - requestReferenceNumber
      - responseStatus
      - responseStatusCodeList
      - documentNumber
      - receiver
      - category
      - messageDate
      - messageReferenceNumber
      - verificationIdentifier
      - transactionReason
      - processNumber
    PI_44021__transactionData__sender:
      type: object
      properties:
        contactPerson:
          $ref: '#/components/schemas/PI_44021__transactionData__sender__contactPerson'
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG2.NAD+MS
        roleCodeType:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeType.yaml#/components/schemas/roleCodeType
          x-edifact-segment:
          - SG2.NAD+MS
      required:
      - contactPerson
      - roleCodeNumber
      - roleCodeType
    PI_44021__transactionData__sender__contactPerson:
      type: object
      properties:
        eMailAddress:
          $ref: ../../../bo4e-en/fields/bo/ContactPerson/eMailAddress.yaml#/components/schemas/eMailAddress
          x-edifact-segment:
          - SG2.NAD+MS.SG3.CTA+IC.COM+[EM|FX|TE|AJ|AL]
        lastName:
          $ref: ../../../bo4e-en/fields/bo/ContactPerson/lastName.yaml#/components/schemas/lastName
          x-edifact-segment:
          - SG2.NAD+MS.SG3.CTA+IC
        phoneNumbers:
          type: array
          items:
            $ref: '#/components/schemas/PI_44021__transactionData__sender__contactPerson__phoneNumbers'
      required:
      - eMailAddress
      - lastName
      - phoneNumbers
    PI_44021__transactionData__sender__contactPerson__phoneNumbers:
      type: object
      properties:
        numberType:
          $ref: ../../../bo4e-en/fields/com/PhoneNumber/numberType.yaml#/components/schemas/numberType
          x-edifact-segment:
          - SG2.NAD+MS.SG3.CTA+IC.COM+[EM|FX|TE|AJ|AL]
        phoneNumber:
          $ref: ../../../bo4e-en/fields/com/PhoneNumber/phoneNumber.yaml#/components/schemas/phoneNumber
          x-edifact-segment:
          - SG2.NAD+MS.SG3.CTA+IC.COM+[EM|FX|TE|AJ|AL]
      required:
      - numberType
      - phoneNumber
    PI_44021__transactionData__receiver:
      type: object
      properties:
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG2.NAD+MR
        roleCodeType:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeType.yaml#/components/schemas/roleCodeType
          x-edifact-segment:
          - SG2.NAD+MR
      required:
      - roleCodeNumber
      - roleCodeType
