openapi: 3.1.0
info:
  title: PI_44104
  version: '202604'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_44104:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_44104__masterData'
        transactionData:
          $ref: '#/components/schemas/PI_44104__transactionData'
      required:
      - masterData
      - transactionData
    PI_44104__masterData:
      type: object
      properties:
        BALANCING:
          type: array
          items:
            $ref: '#/components/schemas/PI_44104__masterData__BALANCING'
        MARKET_LOCATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_44104__masterData__MARKET_LOCATION'
        GRID_ACCESS_CONTRACT:
          type: array
          items:
            $ref: '#/components/schemas/PI_44104__masterData__GRID_ACCESS_CONTRACT'
      required:
      - BALANCING
      - MARKET_LOCATION
    PI_44104__masterData__BALANCING:
      type: object
      properties:
        balancingStart:
          $ref: ../../../bo4e-en/fields/bo/Balancing/balancingStart.yaml#/components/schemas/balancingStart
          x-edifact-segment:
          - SG4.IDE+24.DTM+158
        balancingEnd:
          $ref: ../../../bo4e-en/fields/bo/Balancing/balancingEnd.yaml#/components/schemas/balancingEnd
          x-edifact-segment:
          - SG4.IDE+24.DTM+159
        caseGroupAssignment:
          $ref: ../../../bo4e-en/fields/bo/Balancing/caseGroupAssignment.yaml#/components/schemas/caseGroupAssignment
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+++Z17
        annualConsumptionForecast:
          $ref: '#/components/schemas/PI_44104__masterData__BALANCING__annualConsumptionForecast'
        customerValue:
          $ref: '#/components/schemas/PI_44104__masterData__BALANCING__customerValue'
        loadProfiles:
          type: array
          items:
            $ref: '#/components/schemas/PI_44104__masterData__BALANCING__loadProfiles'
        forecastBasis:
          $ref: ../../../bo4e-en/fields/bo/Balancing/forecastBasis.yaml#/components/schemas/forecastBasis
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI
      required:
      - caseGroupAssignment
      - annualConsumptionForecast
      - customerValue
      - loadProfiles
      - forecastBasis
    PI_44104__masterData__BALANCING__annualConsumptionForecast:
      type: object
      properties:
        unit:
          $ref: ../../../bo4e-en/fields/com/Quantity/unit.yaml#/components/schemas/unit
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01.SG9.QTY+31
        value:
          $ref: ../../../bo4e-en/fields/com/Quantity/value.yaml#/components/schemas/value
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01.SG9.QTY+31
      required:
      - unit
      - value
    PI_44104__masterData__BALANCING__customerValue:
      type: object
      properties:
        value:
          $ref: ../../../bo4e-en/fields/com/Quantity/value.yaml#/components/schemas/value
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01.SG9.QTY+Y02
      required:
      - value
    PI_44104__masterData__BALANCING__loadProfiles:
      type: object
      properties:
        designation:
          $ref: ../../../bo4e-en/fields/com/LoadProfile/designation.yaml#/components/schemas/designation
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z35.SG10.CCI+Z12.CAV
        publisher:
          $ref: ../../../bo4e-en/fields/com/LoadProfile/publisher.yaml#/components/schemas/publisher
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z35.SG10.CCI+Z12.CAV
        dailyParameters:
          $ref: '#/components/schemas/PI_44104__masterData__BALANCING__loadProfiles__dailyParameters'
        procedure:
          $ref: ../../../bo4e-en/fields/com/LoadProfile/procedure.yaml#/components/schemas/procedure
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z35.SG10.CCI+Z12
      required:
      - designation
      - publisher
      - dailyParameters
      - procedure
    PI_44104__masterData__BALANCING__loadProfiles__dailyParameters:
      type: object
      properties:
        serviceProvider:
          $ref: ../../../bo4e-en/fields/com/DailyParameters/serviceProvider.yaml#/components/schemas/serviceProvider
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z35.SG10.CCI
        publisher:
          $ref: ../../../bo4e-en/fields/com/DailyParameters/publisher.yaml#/components/schemas/publisher
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z35.SG10.CCI
        climateZone:
          $ref: ../../../bo4e-en/fields/com/DailyParameters/climateZone.yaml#/components/schemas/climateZone
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z35.SG10.CCI
        temperatureMeasuringPoint:
          $ref: ../../../bo4e-en/fields/com/DailyParameters/temperatureMeasuringPoint.yaml#/components/schemas/temperatureMeasuringPoint
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z35.SG10.CCI
      required:
      - serviceProvider
      - publisher
      - climateZone
      - temperatureMeasuringPoint
    PI_44104__masterData__MARKET_LOCATION:
      type: object
      properties:
        marketLocationId:
          $ref: ../../../bo4e-en/fields/bo/MarketLocation/marketLocationId.yaml#/components/schemas/marketLocationId
          x-edifact-segment:
          - SG4.IDE+24.SG5.LOC+172
      required:
      - marketLocationId
    PI_44104__masterData__GRID_ACCESS_CONTRACT:
      type: object
      properties:
        contractStart:
          $ref: ../../../bo4e-en/fields/bo/Contract/contractStart.yaml#/components/schemas/contractStart
          x-edifact-segment:
          - SG4.IDE+24.DTM+92
        contractEnd:
          $ref: ../../../bo4e-en/fields/bo/Contract/contractEnd.yaml#/components/schemas/contractEnd
          x-edifact-segment:
          - SG4.IDE+24.DTM+93
    PI_44104__transactionData:
      type: object
      properties:
        sender:
          $ref: '#/components/schemas/PI_44104__transactionData__sender'
        involvedMarketPartner:
          $ref: '#/components/schemas/PI_44104__transactionData__involvedMarketPartner'
        balancingGroupAssignment:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/balancingGroupAssignment.yaml#/components/schemas/balancingGroupAssignment
          x-edifact-segment:
          - SG4.IDE+24.STS+Z18
        documentNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/documentNumber.yaml#/components/schemas/documentNumber
          x-edifact-segment:
          - BGM+Z22
        receiver:
          $ref: '#/components/schemas/PI_44104__transactionData__receiver'
        validFrom:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/validFrom.yaml#/components/schemas/validFrom
          x-edifact-segment:
          - SG4.IDE+24.DTM+157
        category:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/category.yaml#/components/schemas/category
          x-edifact-segment:
          - BGM+Z22
        messageDate:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/messageDate.yaml#/components/schemas/messageDate
          x-edifact-segment:
          - DTM+137
        messageReferenceNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/messageReferenceNumber.yaml#/components/schemas/messageReferenceNumber
          x-edifact-segment:
          - UNH
        verificationIdentifier:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/verificationIdentifier.yaml#/components/schemas/verificationIdentifier
          x-edifact-segment:
          - SG4.IDE+24.SG6.RFF+Z13
        transactionReason:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/transactionReason.yaml#/components/schemas/transactionReason
          x-edifact-segment:
          - SG4.IDE+24.STS+7
        contractStart:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/contractStart.yaml#/components/schemas/contractStart
          x-edifact-segment:
          - SG4.IDE+24.DTM+92
        contractEnd:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/contractEnd.yaml#/components/schemas/contractEnd
          x-edifact-segment:
          - SG4.IDE+24.DTM+93
        processNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/processNumber.yaml#/components/schemas/processNumber
          x-edifact-segment:
          - SG4.IDE+24
      required:
      - sender
      - involvedMarketPartner
      - documentNumber
      - receiver
      - category
      - messageDate
      - messageReferenceNumber
      - verificationIdentifier
      - transactionReason
      - processNumber
    PI_44104__transactionData__sender:
      type: object
      properties:
        contactPerson:
          $ref: '#/components/schemas/PI_44104__transactionData__sender__contactPerson'
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG2.NAD+MS
        roleCodeType:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeType.yaml#/components/schemas/roleCodeType
          x-edifact-segment:
          - SG2.NAD+MS
      required:
      - contactPerson
      - roleCodeNumber
      - roleCodeType
    PI_44104__transactionData__sender__contactPerson:
      type: object
      properties:
        eMailAddress:
          $ref: ../../../bo4e-en/fields/bo/ContactPerson/eMailAddress.yaml#/components/schemas/eMailAddress
          x-edifact-segment:
          - SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]
        lastName:
          $ref: ../../../bo4e-en/fields/bo/ContactPerson/lastName.yaml#/components/schemas/lastName
          x-edifact-segment:
          - SG2.NAD+MS.SG3.CTA
        phoneNumbers:
          type: array
          items:
            $ref: '#/components/schemas/PI_44104__transactionData__sender__contactPerson__phoneNumbers'
      required:
      - eMailAddress
      - lastName
      - phoneNumbers
    PI_44104__transactionData__sender__contactPerson__phoneNumbers:
      type: object
      properties:
        numberType:
          $ref: ../../../bo4e-en/fields/com/PhoneNumber/numberType.yaml#/components/schemas/numberType
          x-edifact-segment:
          - SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]
        phoneNumber:
          $ref: ../../../bo4e-en/fields/com/PhoneNumber/phoneNumber.yaml#/components/schemas/phoneNumber
          x-edifact-segment:
          - SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]
      required:
      - numberType
      - phoneNumber
    PI_44104__transactionData__involvedMarketPartner:
      type: object
      properties:
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+VY
        roleCodeType:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeType.yaml#/components/schemas/roleCodeType
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+VY
      required:
      - roleCodeNumber
      - roleCodeType
    PI_44104__transactionData__receiver:
      type: object
      properties:
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG2.NAD+MR
        roleCodeType:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeType.yaml#/components/schemas/roleCodeType
          x-edifact-segment:
          - SG2.NAD+MR
      required:
      - roleCodeNumber
      - roleCodeType
