openapi: 3.1.0
info:
  title: PI_13008
  version: '202604'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_13008:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_13008__masterData'
        transactionData:
          $ref: '#/components/schemas/PI_13008__transactionData'
      required:
      - masterData
      - transactionData
    PI_13008__masterData:
      type: object
      properties:
        ENERGY_QUANTITY:
          type: array
          items:
            $ref: '#/components/schemas/PI_13008__masterData__ENERGY_QUANTITY'
      required:
      - ENERGY_QUANTITY
    PI_13008__masterData__ENERGY_QUANTITY:
      type: object
      properties:
        endDate:
          $ref: ../../../bo4e-en/fields/bo/EnergyQuantity/endDate.yaml#/components/schemas/endDate
          x-edifact-segment:
          - SG5.NAD+DP.SG6.LOC+172.DTM+164
        energyConsumption:
          type: array
          items:
            $ref: '#/components/schemas/PI_13008__masterData__ENERGY_QUANTITY__energyConsumption'
        configuration:
          $ref: ../../../bo4e-en/fields/bo/EnergyQuantity/configuration.yaml#/components/schemas/configuration
          x-edifact-segment:
          - SG5.NAD+DP.SG6.LOC+172
        locationId:
          $ref: ../../../bo4e-en/fields/bo/EnergyQuantity/locationId.yaml#/components/schemas/locationId
          x-edifact-segment:
          - SG5.NAD+DP.SG6.LOC+172
        startDate:
          $ref: ../../../bo4e-en/fields/bo/EnergyQuantity/startDate.yaml#/components/schemas/startDate
          x-edifact-segment:
          - SG5.NAD+DP.SG6.LOC+172.DTM+163
      required:
      - endDate
      - energyConsumption
      - configuration
      - locationId
      - startDate
    PI_13008__masterData__ENERGY_QUANTITY__energyConsumption:
      type: object
      properties:
        endDate:
          $ref: ../../../bo4e-en/fields/com/Consumption/endDate.yaml#/components/schemas/endDate
          x-edifact-segment:
          - SG5.NAD+DP.SG6.LOC+172.SG9.LIN.SG10.QTY.DTM+164
        measurementValueStatus:
          $ref: ../../../bo4e-en/fields/com/Consumption/measurementValueStatus.yaml#/components/schemas/measurementValueStatus
          x-edifact-segment:
          - SG5.NAD+DP.SG6.LOC+172.SG9.LIN.SG10.QTY
        obisNumber:
          $ref: ../../../bo4e-en/fields/com/Consumption/obisNumber.yaml#/components/schemas/obisNumber
          x-edifact-segment:
          - SG5.NAD+DP.SG6.LOC+172.SG9.LIN.PIA+5
        position:
          $ref: ../../../bo4e-en/fields/com/Consumption/position.yaml#/components/schemas/position
          x-edifact-segment:
          - SG5.NAD+DP.SG6.LOC+172.SG9.LIN
        startDate:
          $ref: ../../../bo4e-en/fields/com/Consumption/startDate.yaml#/components/schemas/startDate
          x-edifact-segment:
          - SG5.NAD+DP.SG6.LOC+172.SG9.LIN.SG10.QTY.DTM+163
        statusAdditionalInformation:
          type: array
          items:
            $ref: '#/components/schemas/PI_13008__masterData__ENERGY_QUANTITY__energyConsumption__statusAdditionalInformation'
        value:
          $ref: ../../../bo4e-en/fields/com/Consumption/value.yaml#/components/schemas/value
          x-edifact-segment:
          - SG5.NAD+DP.SG6.LOC+172.SG9.LIN.SG10.QTY
      required:
      - endDate
      - measurementValueStatus
      - obisNumber
      - position
      - startDate
      - value
    PI_13008__masterData__ENERGY_QUANTITY__energyConsumption__statusAdditionalInformation:
      type: object
      properties:
        kind:
          $ref: ../../../bo4e-en/fields/com/StatusAdditionalInformation/kind.yaml#/components/schemas/kind
          x-edifact-segment:
          - SG5.NAD+DP.SG6.LOC+172.SG9.LIN.SG10.QTY.STS+Z31
          - SG5.NAD+DP.SG6.LOC+172.SG9.LIN.SG10.QTY.STS+Z32
        status:
          $ref: ../../../bo4e-en/fields/com/StatusAdditionalInformation/status.yaml#/components/schemas/status
          x-edifact-segment:
          - SG5.NAD+DP.SG6.LOC+172.SG9.LIN.SG10.QTY.STS+Z31
          - SG5.NAD+DP.SG6.LOC+172.SG9.LIN.SG10.QTY.STS+Z32
    PI_13008__transactionData:
      type: object
      properties:
        sender:
          $ref: '#/components/schemas/PI_13008__transactionData__sender'
        inquiryReference:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/inquiryReference.yaml#/components/schemas/inquiryReference
          x-edifact-segment:
          - SG1.RFF+AGI
        documentNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/documentNumber.yaml#/components/schemas/documentNumber
          x-edifact-segment:
          - BGM+7
        receiver:
          $ref: '#/components/schemas/PI_13008__transactionData__receiver'
        category:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/category.yaml#/components/schemas/category
          x-edifact-segment:
          - BGM+7
        messageDate:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/messageDate.yaml#/components/schemas/messageDate
          x-edifact-segment:
          - DTM+137
        messageFunction:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/messageFunction.yaml#/components/schemas/messageFunction
          x-edifact-segment:
          - BGM+7
        messageReferenceNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/messageReferenceNumber.yaml#/components/schemas/messageReferenceNumber
          x-edifact-segment:
          - UNH
        verificationIdentifier:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/verificationIdentifier.yaml#/components/schemas/verificationIdentifier
          x-edifact-segment:
          - SG1.RFF+Z13
      required:
      - sender
      - inquiryReference
      - documentNumber
      - receiver
      - category
      - messageDate
      - messageFunction
      - messageReferenceNumber
      - verificationIdentifier
    PI_13008__transactionData__sender:
      type: object
      properties:
        contactPerson:
          $ref: '#/components/schemas/PI_13008__transactionData__sender__contactPerson'
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG2.NAD+MS
        roleCodeType:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeType.yaml#/components/schemas/roleCodeType
          x-edifact-segment:
          - SG2.NAD+MS
      required:
      - contactPerson
      - roleCodeNumber
      - roleCodeType
    PI_13008__transactionData__sender__contactPerson:
      type: object
      properties:
        eMailAddress:
          $ref: ../../../bo4e-en/fields/bo/ContactPerson/eMailAddress.yaml#/components/schemas/eMailAddress
          x-edifact-segment:
          - SG2.NAD+MS.SG4.CTA+IC.COM+[EM|FX|TE|AJ|AL]
        lastName:
          $ref: ../../../bo4e-en/fields/bo/ContactPerson/lastName.yaml#/components/schemas/lastName
          x-edifact-segment:
          - SG2.NAD+MS.SG4.CTA+IC
        phoneNumbers:
          type: array
          items:
            $ref: '#/components/schemas/PI_13008__transactionData__sender__contactPerson__phoneNumbers'
      required:
      - eMailAddress
      - lastName
      - phoneNumbers
    PI_13008__transactionData__sender__contactPerson__phoneNumbers:
      type: object
      properties:
        numberType:
          $ref: ../../../bo4e-en/fields/com/PhoneNumber/numberType.yaml#/components/schemas/numberType
          x-edifact-segment:
          - SG2.NAD+MS.SG4.CTA+IC.COM+[EM|FX|TE|AJ|AL]
        phoneNumber:
          $ref: ../../../bo4e-en/fields/com/PhoneNumber/phoneNumber.yaml#/components/schemas/phoneNumber
          x-edifact-segment:
          - SG2.NAD+MS.SG4.CTA+IC.COM+[EM|FX|TE|AJ|AL]
      required:
      - numberType
      - phoneNumber
    PI_13008__transactionData__receiver:
      type: object
      properties:
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG2.NAD+MR
        roleCodeType:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeType.yaml#/components/schemas/roleCodeType
          x-edifact-segment:
          - SG2.NAD+MR
      required:
      - roleCodeNumber
      - roleCodeType
