openapi: 3.1.0
info:
  title: PI_55014
  version: '202604'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_55014:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55014__stammdaten'
        transaktionsdaten:
          $ref: '#/components/schemas/PI_55014__transaktionsdaten'
      required:
        - stammdaten
        - transaktionsdaten
    PI_55014__stammdaten:
      type: object
      properties:
        ENERGIELIEFERVERTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_55014__stammdaten__ENERGIELIEFERVERTRAG'
        MARKTLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_55014__stammdaten__MARKTLOKATION'
        NETZNUTZUNGSVERTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_55014__stammdaten__NETZNUTZUNGSVERTRAG'
      required:
        - ENERGIELIEFERVERTRAG
        - MARKTLOKATION
        - NETZNUTZUNGSVERTRAG
    PI_55014__stammdaten__ENERGIELIEFERVERTRAG:
      type: object
      properties:
        enFG:
          type: array
          items:
            $ref: '#/components/schemas/PI_55014__stammdaten__ENERGIELIEFERVERTRAG__enFG'
        korrespondenzpartner:
          $ref: '#/components/schemas/PI_55014__stammdaten__ENERGIELIEFERVERTRAG__korrespondenzpartner'
        vertragspartner2:
          type: array
          items:
            $ref: '#/components/schemas/PI_55014__stammdaten__ENERGIELIEFERVERTRAG__vertragspartner2'
      required:
        - enFG
        - korrespondenzpartner
        - vertragspartner2
    PI_55014__stammdaten__ENERGIELIEFERVERTRAG__enFG:
      type: object
      properties:
        grund:
          $ref: '../../../bo4e/fields/com/EnFG/grund.yaml#/components/schemas/grund'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z75.SG10.CCI+Z61.CAV
        grundlageVerringerungUmlagen:
          $ref: '../../../bo4e/fields/com/EnFG/grundlageVerringerungUmlagen.yaml#/components/schemas/grundlageVerringerungUmlagen'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z75.SG10.CCI+Z61
      required:
        - grundlageVerringerungUmlagen
    PI_55014__stammdaten__ENERGIELIEFERVERTRAG__korrespondenzpartner:
      type: object
      properties:
        anrede:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/anrede.yaml#/components/schemas/anrede'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
        name1:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name1.yaml#/components/schemas/name1'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
        name2:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name2.yaml#/components/schemas/name2'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
        name3:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name3.yaml#/components/schemas/name3'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
        name4:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name4.yaml#/components/schemas/name4'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
        partneradresse:
          $ref: '#/components/schemas/PI_55014__stammdaten__ENERGIELIEFERVERTRAG__korrespondenzpartner__partneradresse'
      required:
        - anrede
        - name1
        - name2
        - name3
        - name4
        - partneradresse
    PI_55014__stammdaten__ENERGIELIEFERVERTRAG__korrespondenzpartner__partneradresse:
      type: object
      properties:
        hausnummer:
          $ref: '../../../bo4e/fields/com/Adresse/hausnummer.yaml#/components/schemas/hausnummer'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
        landescode:
          $ref: '../../../bo4e/fields/com/Adresse/landescode.yaml#/components/schemas/landescode'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
        ort:
          $ref: '../../../bo4e/fields/com/Adresse/ort.yaml#/components/schemas/ort'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
        ortsteil:
          $ref: '../../../bo4e/fields/com/Adresse/ortsteil.yaml#/components/schemas/ortsteil'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
        postfach:
          $ref: '../../../bo4e/fields/com/Adresse/postfach.yaml#/components/schemas/postfach'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
        postleitzahl:
          $ref: '../../../bo4e/fields/com/Adresse/postleitzahl.yaml#/components/schemas/postleitzahl'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
        strasse:
          $ref: '../../../bo4e/fields/com/Adresse/strasse.yaml#/components/schemas/strasse'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
      required:
        - hausnummer
        - landescode
        - ort
        - ortsteil
        - postfach
        - postleitzahl
        - strasse
    PI_55014__stammdaten__ENERGIELIEFERVERTRAG__vertragspartner2:
      type: object
      properties:
        anrede:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/anrede.yaml#/components/schemas/anrede'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z09
        geschaeftspartnerrolle:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/geschaeftspartnerrolle.yaml#/components/schemas/geschaeftspartnerrolle'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z09
        name1:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name1.yaml#/components/schemas/name1'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z09
        name2:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name2.yaml#/components/schemas/name2'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z09
        name3:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name3.yaml#/components/schemas/name3'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z09
        name4:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name4.yaml#/components/schemas/name4'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z09
      required:
        - anrede
        - geschaeftspartnerrolle
        - name1
        - name2
        - name3
        - name4
    PI_55014__stammdaten__MARKTLOKATION:
      type: object
      properties:
        erforderlichesProduktpaket:
          type: array
          items:
            $ref: '#/components/schemas/PI_55014__stammdaten__MARKTLOKATION__erforderlichesProduktpaket'
        versorgungsart:
          $ref: '../../../bo4e/fields/bo/Marktlokation/versorgungsart.yaml#/components/schemas/versorgungsart'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+Z36
      required:
        - erforderlichesProduktpaket
        - versorgungsart
    PI_55014__stammdaten__MARKTLOKATION__erforderlichesProduktpaket:
      type: object
      properties:
        priorisierung:
          $ref: '../../../bo4e/fields/com/Produktpaket/priorisierung.yaml#/components/schemas/priorisierung'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+ZH0.SG10.CCI+Z65.CAV
        produkt:
          type: array
          items:
            $ref: '#/components/schemas/PI_55014__stammdaten__MARKTLOKATION__erforderlichesProduktpaket__produkt'
        produktpaketId:
          $ref: '../../../bo4e/fields/com/Produktpaket/produktpaketId.yaml#/components/schemas/produktpaketId'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z79
            - SG4.IDE+24.SG8.SEQ+ZH0
        umsetzungsgradvorgabe:
          $ref: '../../../bo4e/fields/com/Produktpaket/umsetzungsgradvorgabe.yaml#/components/schemas/umsetzungsgradvorgabe'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+ZH0.SG10.CCI+Z65
      required:
        - produkt
        - produktpaketId
        - umsetzungsgradvorgabe
    PI_55014__stammdaten__MARKTLOKATION__erforderlichesProduktpaket__produkt:
      type: object
      properties:
        codeProdukteigenschaft:
          $ref: '../../../bo4e/fields/com/Produkt/codeProdukteigenschaft.yaml#/components/schemas/codeProdukteigenschaft'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z79.SG10.CCI+Z66.CAV+ZH9
        produktCode:
          $ref: '../../../bo4e/fields/com/Produkt/produktCode.yaml#/components/schemas/produktCode'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z79.PIA+5
        wertedetails:
          $ref: '../../../bo4e/fields/com/Produkt/wertedetails.yaml#/components/schemas/wertedetails'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z79.SG10.CCI+Z66.CAV+ZV4
      required:
        - produktCode
    PI_55014__stammdaten__NETZNUTZUNGSVERTRAG:
      type: object
      properties:
        vertragsbeginn:
          $ref: '../../../bo4e/fields/bo/Vertrag/vertragsbeginn.yaml#/components/schemas/vertragsbeginn'
          x-edifact-segment:
            - SG4.IDE+24.DTM+92
        vertragsende:
          $ref: '../../../bo4e/fields/bo/Vertrag/vertragsende.yaml#/components/schemas/vertragsende'
          x-edifact-segment:
            - SG4.IDE+24.DTM+93
        vertragskonditionen:
          $ref: '#/components/schemas/PI_55014__stammdaten__NETZNUTZUNGSVERTRAG__vertragskonditionen'
      required:
        - vertragsbeginn
        - vertragskonditionen
    PI_55014__stammdaten__NETZNUTZUNGSVERTRAG__vertragskonditionen:
      type: object
      properties:
        haushaltskunde:
          $ref: '../../../bo4e/fields/com/Vertragskonditionen/haushaltskunde.yaml#/components/schemas/haushaltskunde'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI
      required:
        - haushaltskunde
    PI_55014__transaktionsdaten:
      type: object
      properties:
        absender:
          $ref: '#/components/schemas/PI_55014__transaktionsdaten__absender'
        anfragereferenznummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/anfragereferenznummer.yaml#/components/schemas/anfragereferenznummer'
          x-edifact-segment:
            - SG4.IDE+24.SG6.RFF+TN
        antwortstatus:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/antwortstatus.yaml#/components/schemas/antwortstatus'
          x-edifact-segment:
            - SG4.IDE+24.STS+E01
        antwortstatusCodeliste:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/antwortstatusCodeliste.yaml#/components/schemas/antwortstatusCodeliste'
          x-edifact-segment:
            - SG4.IDE+24.STS+E01
        dokumentennummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/dokumentennummer.yaml#/components/schemas/dokumentennummer'
          x-edifact-segment:
            - BGM+E01
        empfaenger:
          $ref: '#/components/schemas/PI_55014__transaktionsdaten__empfaenger'
        kategorie:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/kategorie.yaml#/components/schemas/kategorie'
          x-edifact-segment:
            - BGM+E01
        nachrichtendatum:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtendatum.yaml#/components/schemas/nachrichtendatum'
          x-edifact-segment:
            - DTM+137
        nachrichtenreferenznummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtenreferenznummer.yaml#/components/schemas/nachrichtenreferenznummer'
          x-edifact-segment:
            - UNH
        pruefidentifikator:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/pruefidentifikator.yaml#/components/schemas/pruefidentifikator'
          x-edifact-segment:
            - SG4.IDE+24.SG6.RFF+Z13
        transaktionsgrund:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/transaktionsgrund.yaml#/components/schemas/transaktionsgrund'
          x-edifact-segment:
            - SG4.IDE+24.STS+7
        transaktionsgrundergaenzung:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/transaktionsgrundergaenzung.yaml#/components/schemas/transaktionsgrundergaenzung'
          x-edifact-segment:
            - SG4.IDE+24.STS+7
        transaktionsgrundergaenzungBefristeteAnmeldung:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/transaktionsgrundergaenzungBefristeteAnmeldung.yaml#/components/schemas/transaktionsgrundergaenzungBefristeteAnmeldung'
          x-edifact-segment:
            - SG4.IDE+24.STS+7
        vertragsbeginn:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/vertragsbeginn.yaml#/components/schemas/vertragsbeginn'
          x-edifact-segment:
            - SG4.IDE+24.DTM+92
        vertragsende:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/vertragsende.yaml#/components/schemas/vertragsende'
          x-edifact-segment:
            - SG4.IDE+24.DTM+93
        vorgangsnummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/vorgangsnummer.yaml#/components/schemas/vorgangsnummer'
          x-edifact-segment:
            - SG4.IDE+24
      required:
        - absender
        - anfragereferenznummer
        - antwortstatus
        - antwortstatusCodeliste
        - dokumentennummer
        - empfaenger
        - kategorie
        - nachrichtendatum
        - nachrichtenreferenznummer
        - pruefidentifikator
        - transaktionsgrund
        - transaktionsgrundergaenzung
        - transaktionsgrundergaenzungBefristeteAnmeldung
        - vertragsbeginn
        - vorgangsnummer
    PI_55014__transaktionsdaten__absender:
      type: object
      properties:
        ansprechpartner:
          $ref: '#/components/schemas/PI_55014__transaktionsdaten__absender__ansprechpartner'
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+MS
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+MS
      required:
        - ansprechpartner
        - rollencodenummer
        - rollencodetyp
    PI_55014__transaktionsdaten__absender__ansprechpartner:
      type: object
      properties:
        eMailAdresse:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/eMailAdresse.yaml#/components/schemas/eMailAdresse'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]'
        nachname:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/nachname.yaml#/components/schemas/nachname'
          x-edifact-segment:
            - SG2.NAD+MS.SG3.CTA
        rufnummern:
          type: array
          items:
            $ref: '#/components/schemas/PI_55014__transaktionsdaten__absender__ansprechpartner__rufnummern'
      required:
        - eMailAdresse
        - nachname
        - rufnummern
    PI_55014__transaktionsdaten__absender__ansprechpartner__rufnummern:
      type: object
      properties:
        nummerntyp:
          $ref: '../../../bo4e/fields/com/Rufnummer/nummerntyp.yaml#/components/schemas/nummerntyp'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]'
        rufnummer:
          $ref: '../../../bo4e/fields/com/Rufnummer/rufnummer.yaml#/components/schemas/rufnummer'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]'
      required:
        - nummerntyp
        - rufnummer
    PI_55014__transaktionsdaten__empfaenger:
      type: object
      properties:
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+MR
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+MR
      required:
        - rollencodenummer
        - rollencodetyp
