openapi: 3.1.0
info:
  title: PI_55077
  version: '202604'
  x-bo4e-schema-version: 1.6.8
  x-bo4e-schema-sha: b84d59c01638e348fe912e388cf7b7a25ab9937f
  x-templater-sha: ce089a840512efbac03c3b3e949ad6e8b7215947
components:
  schemas:
    PI_55077:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55077__stammdaten'
        transaktionsdaten:
          $ref: '#/components/schemas/PI_55077__transaktionsdaten'
      required:
        - stammdaten
        - transaktionsdaten
    PI_55077__stammdaten:
      type: object
      properties:
        MARKTLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_55077__stammdaten__MARKTLOKATION'
        NETZNUTZUNGSVERTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_55077__stammdaten__NETZNUTZUNGSVERTRAG'
        TRANCHE:
          type: array
          items:
            $ref: '#/components/schemas/PI_55077__stammdaten__TRANCHE'
      required:
        - MARKTLOKATION
        - NETZNUTZUNGSVERTRAG
        - TRANCHE
    PI_55077__stammdaten__MARKTLOKATION:
      type: object
      properties:
        erforderlichesProduktpaket:
          type: array
          items:
            $ref: '#/components/schemas/PI_55077__stammdaten__MARKTLOKATION__erforderlichesProduktpaket'
        foerderungsLand:
          $ref: '../../../bo4e/fields/bo/Marktlokation/foerderungsLand.yaml#/components/schemas/foerderungsLand'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+Z23
        marktlokationsId:
          $ref: '../../../bo4e/fields/bo/Marktlokation/marktlokationsId.yaml#/components/schemas/marktlokationsId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z16
      required:
        - erforderlichesProduktpaket
        - foerderungsLand
        - marktlokationsId
    PI_55077__stammdaten__MARKTLOKATION__erforderlichesProduktpaket:
      type: object
      properties:
        priorisierung:
          $ref: '../../../bo4e/fields/com/Produktpaket/priorisierung.yaml#/components/schemas/priorisierung'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+ZH0.SG10.CCI+Z65.CAV
        produkt:
          type: array
          items:
            $ref: '#/components/schemas/PI_55077__stammdaten__MARKTLOKATION__erforderlichesProduktpaket__produkt'
        produktpaketId:
          $ref: '../../../bo4e/fields/com/Produktpaket/produktpaketId.yaml#/components/schemas/produktpaketId'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z79
            - SG4.IDE+24.SG8.SEQ+ZH0
        umsetzungsgradvorgabe:
          $ref: '../../../bo4e/fields/com/Produktpaket/umsetzungsgradvorgabe.yaml#/components/schemas/umsetzungsgradvorgabe'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+ZH0.SG10.CCI+Z65
      required:
        - produkt
        - produktpaketId
        - umsetzungsgradvorgabe
    PI_55077__stammdaten__MARKTLOKATION__erforderlichesProduktpaket__produkt:
      type: object
      properties:
        codeProdukteigenschaft:
          $ref: '../../../bo4e/fields/com/Produkt/codeProdukteigenschaft.yaml#/components/schemas/codeProdukteigenschaft'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z79.SG10.CCI+Z66.CAV+ZH9
        produktCode:
          $ref: '../../../bo4e/fields/com/Produkt/produktCode.yaml#/components/schemas/produktCode'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z79.PIA+5
        wertedetails:
          $ref: '../../../bo4e/fields/com/Produkt/wertedetails.yaml#/components/schemas/wertedetails'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z79.SG10.CCI+Z66.CAV+ZV4
      required:
        - produktCode
    PI_55077__stammdaten__NETZNUTZUNGSVERTRAG:
      type: object
      properties:
        vertragsbeginn:
          $ref: '../../../bo4e/fields/bo/Vertrag/vertragsbeginn.yaml#/components/schemas/vertragsbeginn'
          x-edifact-segment:
            - SG4.IDE+24.DTM+92
      required:
        - vertragsbeginn
    PI_55077__stammdaten__TRANCHE:
      type: object
      properties:
        tranchenId:
          $ref: '../../../bo4e/fields/bo/Tranche/tranchenId.yaml#/components/schemas/tranchenId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z21
      required:
        - tranchenId
    PI_55077__transaktionsdaten:
      type: object
      properties:
        absender:
          $ref: '#/components/schemas/PI_55077__transaktionsdaten__absender'
        abtretungserklaerung:
          $ref: '#/components/schemas/PI_55077__transaktionsdaten__abtretungserklaerung'
        dokumentennummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/dokumentennummer.yaml#/components/schemas/dokumentennummer'
          x-edifact-segment:
            - BGM+E01
        empfaenger:
          $ref: '#/components/schemas/PI_55077__transaktionsdaten__empfaenger'
        kategorie:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/kategorie.yaml#/components/schemas/kategorie'
          x-edifact-segment:
            - BGM+E01
        nachrichtendatum:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtendatum.yaml#/components/schemas/nachrichtendatum'
          x-edifact-segment:
            - DTM+137
        nachrichtenreferenznummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtenreferenznummer.yaml#/components/schemas/nachrichtenreferenznummer'
          x-edifact-segment:
            - UNH
        pruefidentifikator:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/pruefidentifikator.yaml#/components/schemas/pruefidentifikator'
          x-edifact-segment:
            - SG4.IDE+24.SG6.RFF+Z13
        transaktionsgrund:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/transaktionsgrund.yaml#/components/schemas/transaktionsgrund'
          x-edifact-segment:
            - SG4.IDE+24.STS+7
        transaktionsgrundergaenzung:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/transaktionsgrundergaenzung.yaml#/components/schemas/transaktionsgrundergaenzung'
          x-edifact-segment:
            - SG4.IDE+24.STS+7
        vertragsbeginn:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/vertragsbeginn.yaml#/components/schemas/vertragsbeginn'
          x-edifact-segment:
            - SG4.IDE+24.DTM+92
        vorgangsnummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/vorgangsnummer.yaml#/components/schemas/vorgangsnummer'
          x-edifact-segment:
            - SG4.IDE+24
      required:
        - absender
        - dokumentennummer
        - empfaenger
        - kategorie
        - nachrichtendatum
        - nachrichtenreferenznummer
        - pruefidentifikator
        - transaktionsgrund
        - transaktionsgrundergaenzung
        - vertragsbeginn
        - vorgangsnummer
    PI_55077__transaktionsdaten__absender:
      type: object
      properties:
        ansprechpartner:
          $ref: '#/components/schemas/PI_55077__transaktionsdaten__absender__ansprechpartner'
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+MS
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+MS
      required:
        - ansprechpartner
        - rollencodenummer
        - rollencodetyp
    PI_55077__transaktionsdaten__absender__ansprechpartner:
      type: object
      properties:
        eMailAdresse:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/eMailAdresse.yaml#/components/schemas/eMailAdresse'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]'
        nachname:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/nachname.yaml#/components/schemas/nachname'
          x-edifact-segment:
            - SG2.NAD+MS.SG3.CTA
        rufnummern:
          type: array
          items:
            $ref: '#/components/schemas/PI_55077__transaktionsdaten__absender__ansprechpartner__rufnummern'
      required:
        - eMailAdresse
        - nachname
        - rufnummern
    PI_55077__transaktionsdaten__absender__ansprechpartner__rufnummern:
      type: object
      properties:
        nummerntyp:
          $ref: '../../../bo4e/fields/com/Rufnummer/nummerntyp.yaml#/components/schemas/nummerntyp'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]'
        rufnummer:
          $ref: '../../../bo4e/fields/com/Rufnummer/rufnummer.yaml#/components/schemas/rufnummer'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG3.CTA.COM+[EM|FX|TE|AJ|AL]'
      required:
        - nummerntyp
        - rufnummer
    PI_55077__transaktionsdaten__abtretungserklaerung:
      type: object
      properties:
        link1:
          $ref: '../../../bo4e/fields/com/Abtretungserklaerung/link1.yaml#/components/schemas/link1'
          x-edifact-segment:
            - SG4.IDE+24.FTX+Z13
        link2:
          $ref: '../../../bo4e/fields/com/Abtretungserklaerung/link2.yaml#/components/schemas/link2'
          x-edifact-segment:
            - SG4.IDE+24.FTX+Z13
        link3:
          $ref: '../../../bo4e/fields/com/Abtretungserklaerung/link3.yaml#/components/schemas/link3'
          x-edifact-segment:
            - SG4.IDE+24.FTX+Z13
        link4:
          $ref: '../../../bo4e/fields/com/Abtretungserklaerung/link4.yaml#/components/schemas/link4'
          x-edifact-segment:
            - SG4.IDE+24.FTX+Z13
        link5:
          $ref: '../../../bo4e/fields/com/Abtretungserklaerung/link5.yaml#/components/schemas/link5'
          x-edifact-segment:
            - SG4.IDE+24.FTX+Z13
        passwort:
          $ref: '../../../bo4e/fields/com/Abtretungserklaerung/passwort.yaml#/components/schemas/passwort'
          x-edifact-segment:
            - SG4.IDE+24.FTX+Z13
    PI_55077__transaktionsdaten__empfaenger:
      type: object
      properties:
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+MR
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+MR
      required:
        - rollencodenummer
        - rollencodetyp
