openapi: 3.1.0
info:
  title: PI_25009
  version: '202510'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_25009:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_25009__masterData'
      required:
      - masterData
    PI_25009__masterData:
      type: object
      properties:
        LOAD_CURVE_DEFINITION:
          type: array
          items:
            $ref: '#/components/schemas/PI_25009__masterData__LOAD_CURVE_DEFINITION'
      required:
      - LOAD_CURVE_DEFINITION
    PI_25009__masterData__LOAD_CURVE_DEFINITION:
      type: object
      properties:
        beginDate:
          $ref: ../../../bo4e-en/fields/bo/LoadCurveDefinition/beginDate.yaml#/components/schemas/beginDate
          x-edifact-segment:
          - SG5.IDE+24.DTM+Z34
        code:
          $ref: ../../../bo4e-en/fields/bo/LoadCurveDefinition/code.yaml#/components/schemas/code
          x-edifact-segment:
          - SG5.IDE+24.LOC+Z09
        closingDate:
          $ref: ../../../bo4e-en/fields/bo/LoadCurveDefinition/closingDate.yaml#/components/schemas/closingDate
          x-edifact-segment:
          - SG5.IDE+24.DTM+Z35
        loadCurves:
          type: array
          items:
            $ref: '#/components/schemas/PI_25009__masterData__LOAD_CURVE_DEFINITION__loadCurves'
        version:
          $ref: ../../../bo4e-en/fields/bo/LoadCurveDefinition/version.yaml#/components/schemas/version
          x-edifact-segment:
          - SG5.IDE+24.DTM+293
      required:
      - beginDate
      - code
      - loadCurves
      - version
    PI_25009__masterData__LOAD_CURVE_DEFINITION__loadCurves:
      type: object
      properties:
        changeTimestamp:
          $ref: ../../../bo4e-en/fields/com/LoadCurve/changeTimestamp.yaml#/components/schemas/changeTimestamp
          x-edifact-segment:
          - SG5.IDE+24.SG8.SEQ+Z74.DTM+Z45
        frequency:
          $ref: ../../../bo4e-en/fields/com/LoadCurve/frequency.yaml#/components/schemas/frequency
          x-edifact-segment:
          - SG5.IDE+24.SG8.SEQ+Z74.DTM+Z45
        threshold:
          $ref: '#/components/schemas/PI_25009__masterData__LOAD_CURVE_DEFINITION__loadCurves__threshold'
      required:
      - changeTimestamp
      - frequency
      - threshold
    PI_25009__masterData__LOAD_CURVE_DEFINITION__loadCurves__threshold:
      type: object
      properties:
        upperThreshold:
          $ref: ../../../bo4e-en/fields/com/Threshold/upperThreshold.yaml#/components/schemas/upperThreshold
          x-edifact-segment:
          - SG5.IDE+24.SG8.SEQ+Z74.SG11.QTY+Z40
      required:
      - upperThreshold
