openapi: 3.1.0
info:
  title: PI_23001
  version: '202510'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: 39ae45d481e5cc3d4d7aae328a23a9751236156a
components:
  schemas:
    PI_23001:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_23001__stammdaten'
      required:
        - stammdaten
    PI_23001__stammdaten:
      type: object
      properties:
        STATUSMITTEILUNG:
          type: array
          items:
            $ref: '#/components/schemas/PI_23001__stammdaten__STATUSMITTEILUNG'
      required:
        - STATUSMITTEILUNG
    PI_23001__stammdaten__STATUSMITTEILUNG:
      type: object
      properties:
        positionsdaten:
          type: array
          items:
            $ref: '#/components/schemas/PI_23001__stammdaten__STATUSMITTEILUNG__positionsdaten'
      required:
        - positionsdaten
    PI_23001__stammdaten__STATUSMITTEILUNG__positionsdaten:
      type: object
      properties:
        auftragsstatus:
          $ref: '../../../bo4e/fields/com/StatusmitteilungPosition/auftragsstatus.yaml#/components/schemas/auftragsstatus'
          x-edifact-segment:
            - SG3.DOC+21.SG7.LIN.STS+Z06
        begruendung:
          $ref: '#/components/schemas/PI_23001__stammdaten__STATUSMITTEILUNG__positionsdaten__begruendung'
        lokationsId:
          $ref: '../../../bo4e/fields/com/StatusmitteilungPosition/lokationsId.yaml#/components/schemas/lokationsId'
          x-edifact-segment:
            - SG3.DOC+21.SG7.LIN.SG8.NAD+DP.LOC+172
        positionsnummer:
          $ref: '../../../bo4e/fields/com/StatusmitteilungPosition/positionsnummer.yaml#/components/schemas/positionsnummer'
          x-edifact-segment:
            - SG3.DOC+21.SG7.LIN
        verwendungAb:
          $ref: '../../../bo4e/fields/com/StatusmitteilungPosition/verwendungAb.yaml#/components/schemas/verwendungAb'
          x-edifact-segment:
            - SG3.DOC+21.SG7.LIN.DTM+163
      required:
        - auftragsstatus
        - lokationsId
        - positionsnummer
    PI_23001__stammdaten__STATUSMITTEILUNG__positionsdaten__begruendung:
      type: object
      properties:
        begruendung1:
          $ref: '../../../bo4e/fields/com/Begruendung/begruendung1.yaml#/components/schemas/begruendung1'
          x-edifact-segment:
            - SG3.DOC+21.SG7.LIN.FTX+ACD
        begruendung2:
          $ref: '../../../bo4e/fields/com/Begruendung/begruendung2.yaml#/components/schemas/begruendung2'
          x-edifact-segment:
            - SG3.DOC+21.SG7.LIN.FTX+ACD
        begruendung3:
          $ref: '../../../bo4e/fields/com/Begruendung/begruendung3.yaml#/components/schemas/begruendung3'
          x-edifact-segment:
            - SG3.DOC+21.SG7.LIN.FTX+ACD
        begruendung4:
          $ref: '../../../bo4e/fields/com/Begruendung/begruendung4.yaml#/components/schemas/begruendung4'
          x-edifact-segment:
            - SG3.DOC+21.SG7.LIN.FTX+ACD
        begruendung5:
          $ref: '../../../bo4e/fields/com/Begruendung/begruendung5.yaml#/components/schemas/begruendung5'
          x-edifact-segment:
            - SG3.DOC+21.SG7.LIN.FTX+ACD
