openapi: 3.1.0
info:
  title: PI_39000
  version: '202604'
  x-bo4e-schema-version: 1.7.4
  x-bo4e-schema-sha: 1732e948753541a9b641ca98f3d8ff189d994263
  x-templater-sha: 392a2eb2993418f8a5be64578c22568416e2d551
components:
  schemas:
    PI_39000:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_39000__stammdaten'
      required:
        - stammdaten
    PI_39000__stammdaten:
      type: object
      properties:
        ANFRAGE:
          type: array
          items:
            $ref: '#/components/schemas/PI_39000__stammdaten__ANFRAGE'
      required:
        - ANFRAGE
    PI_39000__stammdaten__ANFRAGE:
      type: object
      properties:
        anfragekategorie:
          $ref: '../../../bo4e/fields/bo/Anfrage/anfragekategorie.yaml#/components/schemas/anfragekategorie'
          x-edifact-segment:
            - BGM
      required:
        - anfragekategorie
