openapi: 3.1.0
info:
  title: PI_21028
  version: '202610'
  x-bo4e-schema-version: 1.7.8
  x-bo4e-schema-sha: a4f202d62930c69acd327622abf92da121d3a12e
  x-templater-sha: 41b3eb8c66d69f8953cbfe2ce874d41618f10ca0
components:
  schemas:
    PI_21028:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_21028__stammdaten'
      required:
        - stammdaten
    PI_21028__stammdaten:
      type: object
      properties:
        STATUSMITTEILUNG:
          type: array
          items:
            $ref: '#/components/schemas/PI_21028__stammdaten__STATUSMITTEILUNG'
      required:
        - STATUSMITTEILUNG
    PI_21028__stammdaten__STATUSMITTEILUNG:
      type: object
      properties:
        positionsdaten:
          type: array
          items:
            $ref: '#/components/schemas/PI_21028__stammdaten__STATUSMITTEILUNG__positionsdaten'
      required:
        - positionsdaten
    PI_21028__stammdaten__STATUSMITTEILUNG__positionsdaten:
      type: object
      properties:
        antwortstatus:
          $ref: '../../../bo4e/fields/com/StatusmitteilungPosition/antwortstatus.yaml#/components/schemas/antwortstatus'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z12
        antwortstatusCodeliste:
          $ref: '../../../bo4e/fields/com/StatusmitteilungPosition/antwortstatusCodeliste.yaml#/components/schemas/antwortstatusCodeliste'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z12
        auftragsstatus:
          $ref: '../../../bo4e/fields/com/StatusmitteilungPosition/auftragsstatus.yaml#/components/schemas/auftragsstatus'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z12
        gueltigAb:
          $ref: '../../../bo4e/fields/com/StatusmitteilungPosition/gueltigAb.yaml#/components/schemas/gueltigAb'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z12.DTM+7
        lokationsId:
          $ref: '../../../bo4e/fields/com/StatusmitteilungPosition/lokationsId.yaml#/components/schemas/lokationsId'
          x-edifact-segment:
            - SG14.CNI.LOC+172
        positionsnummer:
          $ref: '../../../bo4e/fields/com/StatusmitteilungPosition/positionsnummer.yaml#/components/schemas/positionsnummer'
          x-edifact-segment:
            - SG14.CNI
        statusObjekt:
          $ref: '../../../bo4e/fields/com/StatusmitteilungPosition/statusObjekt.yaml#/components/schemas/statusObjekt'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z12
      required:
        - antwortstatus
        - antwortstatusCodeliste
        - auftragsstatus
        - gueltigAb
        - lokationsId
        - positionsnummer
        - statusObjekt
