openapi: 3.1.0
info:
  title: PI_15003
  version: '202510'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: 39ae45d481e5cc3d4d7aae328a23a9751236156a
components:
  schemas:
    PI_15003:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_15003__stammdaten'
        transaktionsdaten:
          $ref: '#/components/schemas/PI_15003__transaktionsdaten'
      required:
        - stammdaten
        - transaktionsdaten
    PI_15003__stammdaten:
      type: object
      properties:
        ANGEBOT:
          type: array
          items:
            $ref: '#/components/schemas/PI_15003__stammdaten__ANGEBOT'
        MARKTLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_15003__stammdaten__MARKTLOKATION'
        MESSLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_15003__stammdaten__MESSLOKATION'
        NETZLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_15003__stammdaten__NETZLOKATION'
        STEUERBARE_RESSOURCE:
          type: array
          items:
            $ref: '#/components/schemas/PI_15003__stammdaten__STEUERBARE_RESSOURCE'
        TRANCHE:
          type: array
          items:
            $ref: '#/components/schemas/PI_15003__stammdaten__TRANCHE'
        WERTE_NACH_TYP2:
          type: array
          items:
            $ref: '#/components/schemas/PI_15003__stammdaten__WERTE_NACH_TYP2'
      required:
        - ANGEBOT
        - MARKTLOKATION
        - MESSLOKATION
        - NETZLOKATION
        - STEUERBARE_RESSOURCE
        - TRANCHE
        - WERTE_NACH_TYP2
    PI_15003__stammdaten__ANGEBOT:
      type: object
      properties:
        anfragereferenz:
          $ref: '../../../bo4e/fields/bo/Angebot/anfragereferenz.yaml#/components/schemas/anfragereferenz'
          x-edifact-segment:
            - SG1.RFF+AAV
        bindefristAngebot:
          $ref: '#/components/schemas/PI_15003__stammdaten__ANGEBOT__bindefristAngebot'
        positionsdaten:
          type: array
          items:
            $ref: '#/components/schemas/PI_15003__stammdaten__ANGEBOT__positionsdaten'
        zeitspanneEinrichtungUebermittlungWerte:
          $ref: '#/components/schemas/PI_15003__stammdaten__ANGEBOT__zeitspanneEinrichtungUebermittlungWerte'
      required:
        - anfragereferenz
        - bindefristAngebot
        - positionsdaten
    PI_15003__stammdaten__ANGEBOT__bindefristAngebot:
      type: object
      properties:
        dauer:
          $ref: '../../../bo4e/fields/com/Zeitraum/dauer.yaml#/components/schemas/dauer'
          x-edifact-segment:
            - DTM+273
        einheit:
          $ref: '../../../bo4e/fields/com/Zeitraum/einheit.yaml#/components/schemas/einheit'
          x-edifact-segment:
            - DTM+273
      required:
        - dauer
        - einheit
    PI_15003__stammdaten__ANGEBOT__positionsdaten:
      type: object
      properties:
        artikelId:
          $ref: '../../../bo4e/fields/com/Angebotsposition/artikelId.yaml#/components/schemas/artikelId'
          x-edifact-segment:
            - SG27.LIN+Z67.PIA+Z02
            - SG27.LIN+Z68.PIA+Z02
        positionsbezeichnung:
          $ref: '../../../bo4e/fields/com/Angebotsposition/positionsbezeichnung.yaml#/components/schemas/positionsbezeichnung'
          x-edifact-segment:
            - SG27.LIN+Z67
            - SG27.LIN+Z68
        positionspreis:
          type: array
          items:
            $ref: '#/components/schemas/PI_15003__stammdaten__ANGEBOT__positionsdaten__positionspreis'
      required:
        - artikelId
        - positionsbezeichnung
        - positionspreis
    PI_15003__stammdaten__ANGEBOT__positionsdaten__positionspreis:
      type: object
      properties:
        bezugswert:
          $ref: '../../../bo4e/fields/com/Preis/bezugswert.yaml#/components/schemas/bezugswert'
          x-edifact-segment:
            - SG27.LIN+Z67.SG31.PRI+CAL
            - SG27.LIN+Z68.SG31.PRI+CAL
        menge:
          $ref: '../../../bo4e/fields/com/Preis/menge.yaml#/components/schemas/menge'
          x-edifact-segment:
            - SG27.LIN+Z67.SG31.PRI+CAL
            - SG27.LIN+Z68.SG31.PRI+CAL
        preisart:
          $ref: '../../../bo4e/fields/com/Preis/preisart.yaml#/components/schemas/preisart'
          x-edifact-segment:
            - SG27.LIN+Z67.SG31.PRI+CAL
            - SG27.LIN+Z68.SG31.PRI+CAL
        wert:
          $ref: '../../../bo4e/fields/com/Preis/wert.yaml#/components/schemas/wert'
          x-edifact-segment:
            - SG27.LIN+Z67.SG31.PRI+CAL
            - SG27.LIN+Z68.SG31.PRI+CAL
      required:
        - bezugswert
        - menge
        - preisart
        - wert
    PI_15003__stammdaten__ANGEBOT__zeitspanneEinrichtungUebermittlungWerte:
      type: object
      properties:
        dauer:
          $ref: '../../../bo4e/fields/com/Zeitraum/dauer.yaml#/components/schemas/dauer'
          x-edifact-segment:
            - DTM+279
        einheit:
          $ref: '../../../bo4e/fields/com/Zeitraum/einheit.yaml#/components/schemas/einheit'
          x-edifact-segment:
            - DTM+279
    PI_15003__stammdaten__MARKTLOKATION:
      type: object
      properties:
        marktlokationsId:
          $ref: '../../../bo4e/fields/bo/Marktlokation/marktlokationsId.yaml#/components/schemas/marktlokationsId'
          x-edifact-segment:
            - SG11.NAD+DP.LOC+172
      required:
        - marktlokationsId
    PI_15003__stammdaten__MESSLOKATION:
      type: object
      properties:
        messlokationsId:
          $ref: '../../../bo4e/fields/bo/Messlokation/messlokationsId.yaml#/components/schemas/messlokationsId'
          x-edifact-segment:
            - SG11.NAD+DP.LOC+172
      required:
        - messlokationsId
    PI_15003__stammdaten__NETZLOKATION:
      type: object
      properties:
        netzlokationsId:
          $ref: '../../../bo4e/fields/bo/Netzlokation/netzlokationsId.yaml#/components/schemas/netzlokationsId'
          x-edifact-segment:
            - SG11.NAD+DP.LOC+172
      required:
        - netzlokationsId
    PI_15003__stammdaten__STEUERBARE_RESSOURCE:
      type: object
      properties:
        ressourcenId:
          $ref: '../../../bo4e/fields/bo/SteuerbareRessource/ressourcenId.yaml#/components/schemas/ressourcenId'
          x-edifact-segment:
            - SG11.NAD+DP.LOC+172
      required:
        - ressourcenId
    PI_15003__stammdaten__TRANCHE:
      type: object
      properties:
        tranchenId:
          $ref: '../../../bo4e/fields/bo/Tranche/tranchenId.yaml#/components/schemas/tranchenId'
          x-edifact-segment:
            - SG11.NAD+DP.LOC+172
      required:
        - tranchenId
    PI_15003__stammdaten__WERTE_NACH_TYP2:
      type: object
      properties:
        konfigurationsprodukt:
          $ref: '../../../bo4e/fields/bo/WerteNachTyp2/konfigurationsprodukt.yaml#/components/schemas/konfigurationsprodukt'
          x-edifact-segment:
            - SG27.LIN+Z68.PIA+5
        messprodukt:
          $ref: '../../../bo4e/fields/bo/WerteNachTyp2/messprodukt.yaml#/components/schemas/messprodukt'
          x-edifact-segment:
            - SG27.LIN+Z67.PIA+5
        zaehlwerke:
          type: array
          items:
            $ref: '#/components/schemas/PI_15003__stammdaten__WERTE_NACH_TYP2__zaehlwerke'
      required:
        - konfigurationsprodukt
        - messprodukt
        - zaehlwerke
    PI_15003__stammdaten__WERTE_NACH_TYP2__zaehlwerke:
      type: object
      properties:
        obisKennzahl:
          $ref: '../../../bo4e/fields/com/Zaehlwerk/obisKennzahl.yaml#/components/schemas/obisKennzahl'
          x-edifact-segment:
            - SG27.LIN+Z67.PIA+5
      required:
        - obisKennzahl
    PI_15003__transaktionsdaten:
      type: object
      properties:
        absender:
          $ref: '#/components/schemas/PI_15003__transaktionsdaten__absender'
        dokumentennummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/dokumentennummer.yaml#/components/schemas/dokumentennummer'
          x-edifact-segment:
            - BGM+Z57
        empfaenger:
          $ref: '#/components/schemas/PI_15003__transaktionsdaten__empfaenger'
        freitext:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/freitext.yaml#/components/schemas/freitext'
          x-edifact-segment:
            - FTX+ACB
        kategorie:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/kategorie.yaml#/components/schemas/kategorie'
          x-edifact-segment:
            - BGM+Z57
        nachrichtendatum:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtendatum.yaml#/components/schemas/nachrichtendatum'
          x-edifact-segment:
            - DTM+137
        nachrichtenreferenznummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtenreferenznummer.yaml#/components/schemas/nachrichtenreferenznummer'
          x-edifact-segment:
            - UNH
        pruefidentifikator:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/pruefidentifikator.yaml#/components/schemas/pruefidentifikator'
          x-edifact-segment:
            - SG1.RFF+Z13
        startdatum:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/startdatum.yaml#/components/schemas/startdatum'
          x-edifact-segment:
            - DTM+469
      required:
        - absender
        - dokumentennummer
        - empfaenger
        - kategorie
        - nachrichtendatum
        - nachrichtenreferenznummer
        - pruefidentifikator
        - startdatum
    PI_15003__transaktionsdaten__absender:
      type: object
      properties:
        ansprechpartner:
          $ref: '#/components/schemas/PI_15003__transaktionsdaten__absender__ansprechpartner'
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG11.NAD+MS
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG11.NAD+MS
      required:
        - ansprechpartner
        - rollencodenummer
        - rollencodetyp
    PI_15003__transaktionsdaten__absender__ansprechpartner:
      type: object
      properties:
        eMailAdresse:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/eMailAdresse.yaml#/components/schemas/eMailAdresse'
          x-edifact-segment:
            - 'SG11.NAD+MS.SG14.CTA.COM+[EM|FX|TE|AJ|AL]'
        nachname:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/nachname.yaml#/components/schemas/nachname'
          x-edifact-segment:
            - SG11.NAD+MS.SG14.CTA
        rufnummern:
          type: array
          items:
            $ref: '#/components/schemas/PI_15003__transaktionsdaten__absender__ansprechpartner__rufnummern'
      required:
        - eMailAdresse
        - nachname
        - rufnummern
    PI_15003__transaktionsdaten__absender__ansprechpartner__rufnummern:
      type: object
      properties:
        nummerntyp:
          $ref: '../../../bo4e/fields/com/Rufnummer/nummerntyp.yaml#/components/schemas/nummerntyp'
          x-edifact-segment:
            - 'SG11.NAD+MS.SG14.CTA.COM+[EM|FX|TE|AJ|AL]'
        rufnummer:
          $ref: '../../../bo4e/fields/com/Rufnummer/rufnummer.yaml#/components/schemas/rufnummer'
          x-edifact-segment:
            - 'SG11.NAD+MS.SG14.CTA.COM+[EM|FX|TE|AJ|AL]'
      required:
        - nummerntyp
        - rufnummer
    PI_15003__transaktionsdaten__empfaenger:
      type: object
      properties:
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG11.NAD+MR
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG11.NAD+MR
      required:
        - rollencodenummer
        - rollencodetyp
