openapi: 3.1.0
info:
  title: PI_29002
  version: '202510'
  x-bo4e-schema-version: 1.6.5
  x-bo4e-schema-sha: 95f07d974cf2dc738ca248b258d6589025614cb0
  x-templater-sha: 6e98aaa8818d7b01b16786b130d743ea57fa960a
components:
  schemas:
    PI_29002:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_29002__stammdaten'
      required:
        - stammdaten
    PI_29002__stammdaten:
      type: object
      properties:
        HANDELSUNSTIMMIGKEIT:
          type: array
          items:
            $ref: '#/components/schemas/PI_29002__stammdaten__HANDELSUNSTIMMIGKEIT'
      required:
        - HANDELSUNSTIMMIGKEIT
    PI_29002__stammdaten__HANDELSUNSTIMMIGKEIT:
      type: object
      properties:
        begruendung:
          $ref: '#/components/schemas/PI_29002__stammdaten__HANDELSUNSTIMMIGKEIT__begruendung'
        nummer:
          $ref: '../../../bo4e/fields/bo/Handelsunstimmigkeit/nummer.yaml#/components/schemas/nummer'
          x-edifact-segment:
            - 'SG2.DOC+[Z41|Z42]'
        typ:
          $ref: '../../../bo4e/fields/bo/Handelsunstimmigkeit/typ.yaml#/components/schemas/typ'
          x-edifact-segment:
            - 'SG2.DOC+[Z41|Z42]'
      required:
        - begruendung
        - nummer
        - typ
    PI_29002__stammdaten__HANDELSUNSTIMMIGKEIT__begruendung:
      type: object
      properties:
        grund:
          $ref: '../../../bo4e/fields/com/Handelsunstimmigkeitsbegruendung/grund.yaml#/components/schemas/grund'
          x-edifact-segment:
            - 'SG2.DOC+[Z41|Z42].SG3.AJT'
        hinweis:
          $ref: '../../../bo4e/fields/com/Handelsunstimmigkeitsbegruendung/hinweis.yaml#/components/schemas/hinweis'
          x-edifact-segment:
            - 'SG2.DOC+[Z41|Z42].SG3.AJT.FTX+ACB'
      required:
        - grund
        - hinweis
