openapi: 3.1.0
info:
  title: PI_55040
  version: '202510'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_55040:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_55040__masterData'
      required:
      - masterData
    PI_55040__masterData:
      type: object
      properties:
        METERING_LOCATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_55040__masterData__METERING_LOCATION'
        METERING_POINT_OPERATION_CONTRACT:
          type: array
          items:
            $ref: '#/components/schemas/PI_55040__masterData__METERING_POINT_OPERATION_CONTRACT'
        GRID_ACCESS_CONTRACT:
          type: array
          items:
            $ref: '#/components/schemas/PI_55040__masterData__GRID_ACCESS_CONTRACT'
        METER:
          type: array
          items:
            $ref: '#/components/schemas/PI_55040__masterData__METER'
      required:
      - METERING_LOCATION
      - METERING_POINT_OPERATION_CONTRACT
      - METER
    PI_55040__masterData__METERING_LOCATION:
      type: object
      properties:
        meteringAddress:
          $ref: '#/components/schemas/PI_55040__masterData__METERING_LOCATION__meteringAddress'
        meteringLocationId:
          $ref: ../../../bo4e-en/fields/bo/MeteringLocation/meteringLocationId.yaml#/components/schemas/meteringLocationId
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z03.RFF+Z19
          - SG4.IDE+24.SG12.NAD+Z07.RFF+Z19
          - SG4.IDE+24.SG5.LOC+Z17
      required:
      - meteringAddress
      - meteringLocationId
    PI_55040__masterData__METERING_LOCATION__meteringAddress:
      type: object
      properties:
        houseNumber:
          $ref: ../../../bo4e-en/fields/com/Address/houseNumber.yaml#/components/schemas/houseNumber
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z03
        countryCode:
          $ref: ../../../bo4e-en/fields/com/Address/countryCode.yaml#/components/schemas/countryCode
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z03
        city:
          $ref: ../../../bo4e-en/fields/com/Address/city.yaml#/components/schemas/city
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z03
        district:
          $ref: ../../../bo4e-en/fields/com/Address/district.yaml#/components/schemas/district
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z03
        poBox:
          $ref: ../../../bo4e-en/fields/com/Address/poBox.yaml#/components/schemas/poBox
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z03
        postalCode:
          $ref: ../../../bo4e-en/fields/com/Address/postalCode.yaml#/components/schemas/postalCode
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z03
        street:
          $ref: ../../../bo4e-en/fields/com/Address/street.yaml#/components/schemas/street
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z03
        additionalInformation:
          $ref: '#/components/schemas/PI_55040__masterData__METERING_LOCATION__meteringAddress__additionalInformation'
      required:
      - houseNumber
      - countryCode
      - city
      - district
      - poBox
      - postalCode
      - street
      - additionalInformation
    PI_55040__masterData__METERING_LOCATION__meteringAddress__additionalInformation:
      type: object
      properties:
        supplement1:
          $ref: ../../../bo4e-en/fields/com/AddressSupplementInformation/supplement1.yaml#/components/schemas/supplement1
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z03
        supplement2:
          $ref: ../../../bo4e-en/fields/com/AddressSupplementInformation/supplement2.yaml#/components/schemas/supplement2
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z03
        supplement3:
          $ref: ../../../bo4e-en/fields/com/AddressSupplementInformation/supplement3.yaml#/components/schemas/supplement3
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z03
        supplement4:
          $ref: ../../../bo4e-en/fields/com/AddressSupplementInformation/supplement4.yaml#/components/schemas/supplement4
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z03
        supplement5:
          $ref: ../../../bo4e-en/fields/com/AddressSupplementInformation/supplement5.yaml#/components/schemas/supplement5
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z03
      required:
      - supplement1
      - supplement2
      - supplement3
      - supplement4
      - supplement5
    PI_55040__masterData__METERING_POINT_OPERATION_CONTRACT:
      type: object
      properties:
        contractPartner2:
          type: array
          items:
            $ref: '#/components/schemas/PI_55040__masterData__METERING_POINT_OPERATION_CONTRACT__contractPartner2'
      required:
      - contractPartner2
    PI_55040__masterData__METERING_POINT_OPERATION_CONTRACT__contractPartner2:
      type: object
      properties:
        salutation:
          $ref: ../../../bo4e-en/fields/bo/BusinessPartner/salutation.yaml#/components/schemas/salutation
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z07
        businessPartnerRole:
          $ref: ../../../bo4e-en/fields/bo/BusinessPartner/businessPartnerRole.yaml#/components/schemas/businessPartnerRole
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z07
        name1:
          $ref: ../../../bo4e-en/fields/bo/BusinessPartner/name1.yaml#/components/schemas/name1
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z07
        name2:
          $ref: ../../../bo4e-en/fields/bo/BusinessPartner/name2.yaml#/components/schemas/name2
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z07
        name3:
          $ref: ../../../bo4e-en/fields/bo/BusinessPartner/name3.yaml#/components/schemas/name3
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z07
        name4:
          $ref: ../../../bo4e-en/fields/bo/BusinessPartner/name4.yaml#/components/schemas/name4
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z07
      required:
      - salutation
      - businessPartnerRole
      - name1
      - name2
      - name3
      - name4
    PI_55040__masterData__GRID_ACCESS_CONTRACT:
      type: object
      properties:
        contractEnd:
          $ref: ../../../bo4e-en/fields/bo/Contract/contractEnd.yaml#/components/schemas/contractEnd
          x-edifact-segment:
          - SG4.IDE+24.DTM+93
    PI_55040__masterData__METER:
      type: object
      properties:
        meteringLocationId:
          $ref: ../../../bo4e-en/fields/bo/Meter/meteringLocationId.yaml#/components/schemas/meteringLocationId
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z03.RFF+Z19
        meterNumber:
          $ref: ../../../bo4e-en/fields/bo/Meter/meterNumber.yaml#/components/schemas/meterNumber
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z03.SG10.CCI+++E13.CAV+Z30
      required:
      - meteringLocationId
      - meterNumber
