openapi: 3.1.0
info:
  title: PI_55170
  version: '202510'
  x-bo4e-schema-version: 1.7.4
  x-bo4e-schema-sha: 1732e948753541a9b641ca98f3d8ff189d994263
  x-templater-sha: 20c434c98f1808f1b10ab64bdf7a7a96d42aa7ee
components:
  schemas:
    PI_55170:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_55170__masterData'
      required:
      - masterData
    PI_55170__masterData:
      type: object
      properties:
        METERING_LOCATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_55170__masterData__METERING_LOCATION'
      required:
      - METERING_LOCATION
    PI_55170__masterData__METERING_LOCATION:
      type: object
      properties:
        meteringLocationId:
          $ref: ../../../bo4e-en/fields/bo/MeteringLocation/meteringLocationId.yaml#/components/schemas/meteringLocationId
          x-edifact-segment:
          - SG4.IDE+24.SG5.LOC+Z17
      required:
      - meteringLocationId
