openapi: 3.1.0
info:
  title: PI_55674
  version: '202510'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_55674:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_55674__masterData'
      required:
      - masterData
    PI_55674__masterData:
      type: object
      properties:
        BALANCING:
          type: array
          items:
            $ref: '#/components/schemas/PI_55674__masterData__BALANCING'
        MARKET_LOCATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_55674__masterData__MARKET_LOCATION'
        TRANCHE:
          type: array
          items:
            $ref: '#/components/schemas/PI_55674__masterData__TRANCHE'
        USAGE_PERIOD:
          type: array
          items:
            $ref: '#/components/schemas/PI_55674__masterData__USAGE_PERIOD'
      required:
      - BALANCING
      - MARKET_LOCATION
      - TRANCHE
      - USAGE_PERIOD
    PI_55674__masterData__BALANCING:
      type: object
      properties:
        balancingGroup:
          $ref: ../../../bo4e-en/fields/bo/Balancing/balancingGroup.yaml#/components/schemas/balancingGroup
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+Z19
          - SG4.IDE+24.SG8.SEQ+Z98.SG10.CCI+Z19
        forecastBasis:
          $ref: ../../../bo4e-en/fields/bo/Balancing/forecastBasis.yaml#/components/schemas/forecastBasis
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+++ZC0
          - SG4.IDE+24.SG8.SEQ+Z98.SG10.CCI+++ZC0
        timeSeriesType:
          $ref: ../../../bo4e-en/fields/bo/Balancing/timeSeriesType.yaml#/components/schemas/timeSeriesType
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+15++Z21.CAV
          - SG4.IDE+24.SG8.SEQ+Z98.SG10.CCI+15++Z21.CAV
      required:
      - balancingGroup
      - forecastBasis
      - timeSeriesType
    PI_55674__masterData__MARKET_LOCATION:
      type: object
      properties:
        balancingArea:
          $ref: ../../../bo4e-en/fields/bo/MarketLocation/balancingArea.yaml#/components/schemas/balancingArea
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+Z20
          - SG4.IDE+24.SG8.SEQ+Z98.SG10.CCI+Z20
        dataQuality:
          $ref: ../../../bo4e-en/fields/bo/MarketLocation/dataQuality.yaml#/components/schemas/dataQuality
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01
          - SG4.IDE+24.SG8.SEQ+Z98
        validityPeriod:
          $ref: '#/components/schemas/PI_55674__masterData__MARKET_LOCATION__validityPeriod'
        marketLocationId:
          $ref: ../../../bo4e-en/fields/bo/MarketLocation/marketLocationId.yaml#/components/schemas/marketLocationId
          x-edifact-segment:
          - SG4.IDE+24.SG5.LOC+Z16
        marketRoles:
          type: array
          items:
            $ref: '#/components/schemas/PI_55674__masterData__MARKET_LOCATION__marketRoles'
        gridLevel:
          $ref: ../../../bo4e-en/fields/bo/MarketLocation/gridLevel.yaml#/components/schemas/gridLevel
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+++E03.CAV
          - SG4.IDE+24.SG8.SEQ+Z98.SG10.CCI+++E03.CAV
        transformation:
          $ref: ../../../bo4e-en/fields/bo/MarketLocation/transformation.yaml#/components/schemas/transformation
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+++E03.CAV
          - SG4.IDE+24.SG8.SEQ+Z98.SG10.CCI+++E03.CAV
      required:
      - balancingArea
      - dataQuality
      - validityPeriod
      - marketLocationId
      - gridLevel
    PI_55674__masterData__MARKET_LOCATION__validityPeriod:
      type: object
      properties:
        periodId:
          $ref: ../../../bo4e-en/fields/com/TimePeriod/periodId.yaml#/components/schemas/periodId
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01
      required:
      - periodId
    PI_55674__masterData__MARKET_LOCATION__marketRoles:
      type: object
      properties:
        marketRole:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/marketRole.yaml#/components/schemas/marketRole
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+++ZB3.CAV+Z89
          - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+++ZB3.CAV+Z91
          - SG4.IDE+24.SG8.SEQ+Z98.SG10.CCI+++ZB3.CAV+Z89
          - SG4.IDE+24.SG8.SEQ+Z98.SG10.CCI+++ZB3.CAV+Z91
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+++ZB3.CAV+Z89
          - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+++ZB3.CAV+Z91
          - SG4.IDE+24.SG8.SEQ+Z98.SG10.CCI+++ZB3.CAV+Z89
          - SG4.IDE+24.SG8.SEQ+Z98.SG10.CCI+++ZB3.CAV+Z91
    PI_55674__masterData__TRANCHE:
      type: object
      properties:
        balancingGroup:
          $ref: ../../../bo4e-en/fields/bo/Tranche/balancingGroup.yaml#/components/schemas/balancingGroup
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z15.SG10.CCI+Z19
        dataQuality:
          $ref: ../../../bo4e-en/fields/bo/Tranche/dataQuality.yaml#/components/schemas/dataQuality
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z15
        validityPeriod:
          $ref: '#/components/schemas/PI_55674__masterData__TRANCHE__validityPeriod'
        marketRoles:
          type: array
          items:
            $ref: '#/components/schemas/PI_55674__masterData__TRANCHE__marketRoles'
        trancheId:
          $ref: ../../../bo4e-en/fields/bo/Tranche/trancheId.yaml#/components/schemas/trancheId
          x-edifact-segment:
          - SG4.IDE+24.SG5.LOC+Z21
      required:
      - balancingGroup
      - dataQuality
      - validityPeriod
      - marketRoles
      - trancheId
    PI_55674__masterData__TRANCHE__validityPeriod:
      type: object
      properties:
        periodId:
          $ref: ../../../bo4e-en/fields/com/TimePeriod/periodId.yaml#/components/schemas/periodId
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z15
      required:
      - periodId
    PI_55674__masterData__TRANCHE__marketRoles:
      type: object
      properties:
        marketRole:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/marketRole.yaml#/components/schemas/marketRole
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z15.SG10.CCI+++ZB3.CAV+Z89
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+Z15.SG10.CCI+++ZB3.CAV+Z89
      required:
      - marketRole
      - roleCodeNumber
    PI_55674__masterData__USAGE_PERIOD:
      type: object
      properties:
        dataQuality:
          $ref: ../../../bo4e-en/fields/bo/UsagePeriod/dataQuality.yaml#/components/schemas/dataQuality
          x-edifact-segment:
          - SG4.IDE+24.SG6.RFF+[Z49|Z53]
        usageFrom:
          $ref: ../../../bo4e-en/fields/bo/UsagePeriod/usageFrom.yaml#/components/schemas/usageFrom
          x-edifact-segment:
          - SG4.IDE+24.SG6.RFF+[Z49|Z53].DTM+Z25
        usageTo:
          $ref: ../../../bo4e-en/fields/bo/UsagePeriod/usageTo.yaml#/components/schemas/usageTo
          x-edifact-segment:
          - SG4.IDE+24.SG6.RFF+[Z49|Z53].DTM+Z26
        periodId:
          $ref: ../../../bo4e-en/fields/bo/UsagePeriod/periodId.yaml#/components/schemas/periodId
          x-edifact-segment:
          - SG4.IDE+24.SG6.RFF+[Z49|Z53]
      required:
      - dataQuality
      - usageFrom
      - periodId
