openapi: 3.1.0
info:
  title: PI_55194
  version: '202510'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_55194:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_55194__masterData'
      required:
      - masterData
    PI_55194__masterData:
      type: object
      properties:
        METERING_LOCATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_55194__masterData__METERING_LOCATION'
        METER:
          type: array
          items:
            $ref: '#/components/schemas/PI_55194__masterData__METER'
      required:
      - METERING_LOCATION
      - METER
    PI_55194__masterData__METERING_LOCATION:
      type: object
      properties:
        dataQuality:
          $ref: ../../../bo4e-en/fields/bo/MeteringLocation/dataQuality.yaml#/components/schemas/dataQuality
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z64
        marketRoles:
          type: array
          items:
            $ref: '#/components/schemas/PI_55194__masterData__METERING_LOCATION__marketRoles'
        meteringAddress:
          $ref: '#/components/schemas/PI_55194__masterData__METERING_LOCATION__meteringAddress'
        meteringLocationId:
          $ref: ../../../bo4e-en/fields/bo/MeteringLocation/meteringLocationId.yaml#/components/schemas/meteringLocationId
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z64.RFF+Z19
          - SG4.IDE+24.SG8.SEQ+ZF3.RFF+Z19
      required:
      - dataQuality
      - marketRoles
      - meteringAddress
      - meteringLocationId
    PI_55194__masterData__METERING_LOCATION__marketRoles:
      type: object
      properties:
        marketRole:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/marketRole.yaml#/components/schemas/marketRole
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+ZF3.SG10.CCI+++ZB3.CAV+Z91
          - SG4.IDE+24.SG8.SEQ+ZF3.SG10.CCI+++ZB3.CAV+ZF0
        meteringPointOperatorAttribute:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/meteringPointOperatorAttribute.yaml#/components/schemas/meteringPointOperatorAttribute
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+ZF3.SG10.CCI+++ZB3.CAV+Z91
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+ZF3.SG10.CCI+++ZB3.CAV+Z91
          - SG4.IDE+24.SG8.SEQ+ZF3.SG10.CCI+++ZB3.CAV+ZF0
        subContracted:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/subContracted.yaml#/components/schemas/subContracted
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+ZF3.SG10.CCI+++ZB3.CAV+Z91
      required:
      - marketRole
      - meteringPointOperatorAttribute
      - roleCodeNumber
      - subContracted
    PI_55194__masterData__METERING_LOCATION__meteringAddress:
      type: object
      properties:
        houseNumber:
          $ref: ../../../bo4e-en/fields/com/Address/houseNumber.yaml#/components/schemas/houseNumber
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z64
        countryCode:
          $ref: ../../../bo4e-en/fields/com/Address/countryCode.yaml#/components/schemas/countryCode
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z64
        city:
          $ref: ../../../bo4e-en/fields/com/Address/city.yaml#/components/schemas/city
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z64
        district:
          $ref: ../../../bo4e-en/fields/com/Address/district.yaml#/components/schemas/district
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z64
        poBox:
          $ref: ../../../bo4e-en/fields/com/Address/poBox.yaml#/components/schemas/poBox
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z64
        postalCode:
          $ref: ../../../bo4e-en/fields/com/Address/postalCode.yaml#/components/schemas/postalCode
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z64
        street:
          $ref: ../../../bo4e-en/fields/com/Address/street.yaml#/components/schemas/street
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z64
        additionalInformation:
          $ref: '#/components/schemas/PI_55194__masterData__METERING_LOCATION__meteringAddress__additionalInformation'
      required:
      - houseNumber
      - countryCode
      - city
      - district
      - poBox
      - postalCode
      - street
      - additionalInformation
    PI_55194__masterData__METERING_LOCATION__meteringAddress__additionalInformation:
      type: object
      properties:
        supplement1:
          $ref: ../../../bo4e-en/fields/com/AddressSupplementInformation/supplement1.yaml#/components/schemas/supplement1
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z64
        supplement2:
          $ref: ../../../bo4e-en/fields/com/AddressSupplementInformation/supplement2.yaml#/components/schemas/supplement2
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z64
        supplement3:
          $ref: ../../../bo4e-en/fields/com/AddressSupplementInformation/supplement3.yaml#/components/schemas/supplement3
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z64
        supplement4:
          $ref: ../../../bo4e-en/fields/com/AddressSupplementInformation/supplement4.yaml#/components/schemas/supplement4
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z64
        supplement5:
          $ref: ../../../bo4e-en/fields/com/AddressSupplementInformation/supplement5.yaml#/components/schemas/supplement5
          x-edifact-segment:
          - SG4.IDE+24.SG12.NAD+Z64
      required:
      - supplement1
      - supplement2
      - supplement3
      - supplement4
      - supplement5
    PI_55194__masterData__METER:
      type: object
      properties:
        devices:
          type: array
          items:
            $ref: '#/components/schemas/PI_55194__masterData__METER__devices'
      required:
      - devices
    PI_55194__masterData__METER__devices:
      type: object
      properties:
        deviceNumber:
          $ref: ../../../bo4e-en/fields/com/Device/deviceNumber.yaml#/components/schemas/deviceNumber
          x-edifact-segment:
          - SG4.IDE+24.SG8.SEQ+ZG0.SG10.CCI+++Z75.CAV+Z30
      required:
      - deviceNumber
