openapi: 3.1.0
info:
  title: PI_21026
  version: '202510'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_21026:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_21026__masterData'
        transactionData:
          $ref: '#/components/schemas/PI_21026__transactionData'
      required:
      - masterData
      - transactionData
    PI_21026__masterData:
      type: object
      properties:
        METERING_LOCATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_21026__masterData__METERING_LOCATION'
        STATUS_NOTIFICATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_21026__masterData__STATUS_NOTIFICATION'
      required:
      - METERING_LOCATION
      - STATUS_NOTIFICATION
    PI_21026__masterData__METERING_LOCATION:
      type: object
      properties:
        meteringLocationId:
          $ref: ../../../bo4e-en/fields/bo/MeteringLocation/meteringLocationId.yaml#/components/schemas/meteringLocationId
          x-edifact-segment:
          - SG14.CNI.LOC+172
      required:
      - meteringLocationId
    PI_21026__masterData__STATUS_NOTIFICATION:
      type: object
      properties:
        orderStatus:
          $ref: ../../../bo4e-en/fields/bo/StatusNotification/orderStatus.yaml#/components/schemas/orderStatus
          x-edifact-segment:
          - SG14.CNI.SG15.STS+Z15
        positionData:
          type: array
          items:
            $ref: '#/components/schemas/PI_21026__masterData__STATUS_NOTIFICATION__positionData'
        statusObject:
          $ref: ../../../bo4e-en/fields/bo/StatusNotification/statusObject.yaml#/components/schemas/statusObject
          x-edifact-segment:
          - SG14.CNI.SG15.STS+Z15
      required:
      - orderStatus
      - positionData
      - statusObject
    PI_21026__masterData__STATUS_NOTIFICATION__positionData:
      type: object
      properties:
        positionNumber:
          $ref: ../../../bo4e-en/fields/com/StatusNotificationPosition/positionNumber.yaml#/components/schemas/positionNumber
          x-edifact-segment:
          - SG14.CNI
      required:
      - positionNumber
    PI_21026__transactionData:
      type: object
      properties:
        sender:
          $ref: '#/components/schemas/PI_21026__transactionData__sender'
        documentNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/documentNumber.yaml#/components/schemas/documentNumber
          x-edifact-segment:
          - BGM+Z09
        receiver:
          $ref: '#/components/schemas/PI_21026__transactionData__receiver'
        completionDate:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/completionDate.yaml#/components/schemas/completionDate
          x-edifact-segment:
          - SG14.CNI.SG15.STS+Z15.DTM+293
        messageDate:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/messageDate.yaml#/components/schemas/messageDate
          x-edifact-segment:
          - DTM+137
        messageReferenceNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/messageReferenceNumber.yaml#/components/schemas/messageReferenceNumber
          x-edifact-segment:
          - UNH
        verificationIdentifier:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/verificationIdentifier.yaml#/components/schemas/verificationIdentifier
          x-edifact-segment:
          - SG14.CNI.SG15.STS+Z15.RFF+Z13
      required:
      - sender
      - documentNumber
      - receiver
      - completionDate
      - messageDate
      - messageReferenceNumber
      - verificationIdentifier
    PI_21026__transactionData__sender:
      type: object
      properties:
        contactPerson:
          $ref: '#/components/schemas/PI_21026__transactionData__sender__contactPerson'
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG1.NAD+MS
        roleCodeType:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeType.yaml#/components/schemas/roleCodeType
          x-edifact-segment:
          - SG1.NAD+MS
      required:
      - contactPerson
      - roleCodeNumber
      - roleCodeType
    PI_21026__transactionData__sender__contactPerson:
      type: object
      properties:
        eMailAddress:
          $ref: ../../../bo4e-en/fields/bo/ContactPerson/eMailAddress.yaml#/components/schemas/eMailAddress
          x-edifact-segment:
          - SG1.NAD+MS.SG2.CTA+IC.COM+[EM|FX|TE|AJ|AL]
        lastName:
          $ref: ../../../bo4e-en/fields/bo/ContactPerson/lastName.yaml#/components/schemas/lastName
          x-edifact-segment:
          - SG1.NAD+MS.SG2.CTA+IC
        phoneNumbers:
          type: array
          items:
            $ref: '#/components/schemas/PI_21026__transactionData__sender__contactPerson__phoneNumbers'
      required:
      - eMailAddress
      - lastName
      - phoneNumbers
    PI_21026__transactionData__sender__contactPerson__phoneNumbers:
      type: object
      properties:
        numberType:
          $ref: ../../../bo4e-en/fields/com/PhoneNumber/numberType.yaml#/components/schemas/numberType
          x-edifact-segment:
          - SG1.NAD+MS.SG2.CTA+IC.COM+[EM|FX|TE|AJ|AL]
        phoneNumber:
          $ref: ../../../bo4e-en/fields/com/PhoneNumber/phoneNumber.yaml#/components/schemas/phoneNumber
          x-edifact-segment:
          - SG1.NAD+MS.SG2.CTA+IC.COM+[EM|FX|TE|AJ|AL]
      required:
      - numberType
      - phoneNumber
    PI_21026__transactionData__receiver:
      type: object
      properties:
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG1.NAD+MR
        roleCodeType:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeType.yaml#/components/schemas/roleCodeType
          x-edifact-segment:
          - SG1.NAD+MR
      required:
      - roleCodeNumber
      - roleCodeType
