openapi: 3.1.0
info:
  title: PI_25009
  version: '202510'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: c7b88c733e93fe4ee423d52cffa2cd8f312574ea
components:
  schemas:
    PI_25009:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_25009__stammdaten'
      required:
        - stammdaten
    PI_25009__stammdaten:
      type: object
      properties:
        LEISTUNGSKURVENDEFINITION:
          type: array
          items:
            $ref: '#/components/schemas/PI_25009__stammdaten__LEISTUNGSKURVENDEFINITION'
      required:
        - LEISTUNGSKURVENDEFINITION
    PI_25009__stammdaten__LEISTUNGSKURVENDEFINITION:
      type: object
      properties:
        beginndatum:
          $ref: '../../../bo4e/fields/bo/Leistungskurvendefinition/beginndatum.yaml#/components/schemas/beginndatum'
          x-edifact-segment:
            - SG5.IDE+24.DTM+Z34
        code:
          $ref: '../../../bo4e/fields/bo/Leistungskurvendefinition/code.yaml#/components/schemas/code'
          x-edifact-segment:
            - SG5.IDE+24.LOC+Z09
        endedatum:
          $ref: '../../../bo4e/fields/bo/Leistungskurvendefinition/endedatum.yaml#/components/schemas/endedatum'
          x-edifact-segment:
            - SG5.IDE+24.DTM+Z35
        leistungskurven:
          type: array
          items:
            $ref: '#/components/schemas/PI_25009__stammdaten__LEISTUNGSKURVENDEFINITION__leistungskurven'
        version:
          $ref: '../../../bo4e/fields/bo/Leistungskurvendefinition/version.yaml#/components/schemas/version'
          x-edifact-segment:
            - SG5.IDE+24.DTM+293
      required:
        - beginndatum
        - code
        - leistungskurven
        - version
    PI_25009__stammdaten__LEISTUNGSKURVENDEFINITION__leistungskurven:
      type: object
      properties:
        aenderungszeitpunkt:
          $ref: '../../../bo4e/fields/com/Leistungskurve/aenderungszeitpunkt.yaml#/components/schemas/aenderungszeitpunkt'
          x-edifact-segment:
            - SG5.IDE+24.SG8.SEQ+Z74.DTM+Z45
        haeufigkeit:
          $ref: '../../../bo4e/fields/com/Leistungskurve/haeufigkeit.yaml#/components/schemas/haeufigkeit'
          x-edifact-segment:
            - SG5.IDE+24.SG8.SEQ+Z74.DTM+Z45
        schwellwert:
          $ref: '#/components/schemas/PI_25009__stammdaten__LEISTUNGSKURVENDEFINITION__leistungskurven__schwellwert'
      required:
        - aenderungszeitpunkt
        - haeufigkeit
        - schwellwert
    PI_25009__stammdaten__LEISTUNGSKURVENDEFINITION__leistungskurven__schwellwert:
      type: object
      properties:
        obererSchwellwert:
          $ref: '../../../bo4e/fields/com/Schwellwert/obererSchwellwert.yaml#/components/schemas/obererSchwellwert'
          x-edifact-segment:
            - SG5.IDE+24.SG8.SEQ+Z74.SG11.QTY+Z40
      required:
        - obererSchwellwert
