openapi: 3.1.0
info:
  title: PI_21047
  version: '202604'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_21047:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_21047__masterData'
      required:
      - masterData
    PI_21047__masterData:
      type: object
      properties:
        STATUS_NOTIFICATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_21047__masterData__STATUS_NOTIFICATION'
      required:
      - STATUS_NOTIFICATION
    PI_21047__masterData__STATUS_NOTIFICATION:
      type: object
      properties:
        orderStatus:
          $ref: ../../../bo4e-en/fields/bo/StatusNotification/orderStatus.yaml#/components/schemas/orderStatus
          x-edifact-segment:
          - SG14.CNI.SG15.STS+Z43
        positionData:
          type: array
          items:
            $ref: '#/components/schemas/PI_21047__masterData__STATUS_NOTIFICATION__positionData'
        statusObject:
          $ref: ../../../bo4e-en/fields/bo/StatusNotification/statusObject.yaml#/components/schemas/statusObject
          x-edifact-segment:
          - SG14.CNI.SG15.STS+Z43
      required:
      - orderStatus
      - positionData
      - statusObject
    PI_21047__masterData__STATUS_NOTIFICATION__positionData:
      type: object
      properties:
        generalInformation:
          $ref: '#/components/schemas/PI_21047__masterData__STATUS_NOTIFICATION__positionData__generalInformation'
        positionNumber:
          $ref: ../../../bo4e-en/fields/com/StatusNotificationPosition/positionNumber.yaml#/components/schemas/positionNumber
          x-edifact-segment:
          - SG14.CNI
      required:
      - generalInformation
      - positionNumber
    PI_21047__masterData__STATUS_NOTIFICATION__positionData__generalInformation:
      type: object
      properties:
        info1:
          $ref: ../../../bo4e-en/fields/com/GeneralInformation/info1.yaml#/components/schemas/info1
          x-edifact-segment:
          - SG14.CNI.SG15.STS+Z43.SG25.GID.FTX+ACB
        info2:
          $ref: ../../../bo4e-en/fields/com/GeneralInformation/info2.yaml#/components/schemas/info2
          x-edifact-segment:
          - SG14.CNI.SG15.STS+Z43.SG25.GID.FTX+ACB
        info3:
          $ref: ../../../bo4e-en/fields/com/GeneralInformation/info3.yaml#/components/schemas/info3
          x-edifact-segment:
          - SG14.CNI.SG15.STS+Z43.SG25.GID.FTX+ACB
        info4:
          $ref: ../../../bo4e-en/fields/com/GeneralInformation/info4.yaml#/components/schemas/info4
          x-edifact-segment:
          - SG14.CNI.SG15.STS+Z43.SG25.GID.FTX+ACB
        info5:
          $ref: ../../../bo4e-en/fields/com/GeneralInformation/info5.yaml#/components/schemas/info5
          x-edifact-segment:
          - SG14.CNI.SG15.STS+Z43.SG25.GID.FTX+ACB
      required:
      - info1
      - info2
      - info3
      - info4
      - info5
