openapi: 3.1.0
info:
  title: PI_21035
  version: '202604'
  x-bo4e-schema-version: 1.7.4
  x-bo4e-schema-sha: 1732e948753541a9b641ca98f3d8ff189d994263
  x-templater-sha: 392a2eb2993418f8a5be64578c22568416e2d551
components:
  schemas:
    PI_21035:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_21035__masterData'
      required:
      - masterData
    PI_21035__masterData:
      type: object
      properties:
        STATUS_NOTIFICATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_21035__masterData__STATUS_NOTIFICATION'
      required:
      - STATUS_NOTIFICATION
    PI_21035__masterData__STATUS_NOTIFICATION:
      type: object
      properties:
        orderStatus:
          $ref: ../../../bo4e-en/fields/bo/StatusNotification/orderStatus.yaml#/components/schemas/orderStatus
          x-edifact-segment:
          - SG14.CNI.SG15.STS+Z25
        positionData:
          type: array
          items:
            $ref: '#/components/schemas/PI_21035__masterData__STATUS_NOTIFICATION__positionData'
      required:
      - orderStatus
      - positionData
    PI_21035__masterData__STATUS_NOTIFICATION__positionData:
      type: object
      properties:
        positionNumber:
          $ref: ../../../bo4e-en/fields/com/StatusNotificationPosition/positionNumber.yaml#/components/schemas/positionNumber
          x-edifact-segment:
          - SG14.CNI
      required:
      - positionNumber
