openapi: 3.1.0
info:
  title: PI_29001
  version: '202510'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: 39ae45d481e5cc3d4d7aae328a23a9751236156a
components:
  schemas:
    PI_29001:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_29001__stammdaten'
        transaktionsdaten:
          $ref: '#/components/schemas/PI_29001__transaktionsdaten'
      required:
        - stammdaten
        - transaktionsdaten
    PI_29001__stammdaten:
      type: object
      properties:
        HANDELSUNSTIMMIGKEIT:
          type: array
          items:
            $ref: '#/components/schemas/PI_29001__stammdaten__HANDELSUNSTIMMIGKEIT'
      required:
        - HANDELSUNSTIMMIGKEIT
    PI_29001__stammdaten__HANDELSUNSTIMMIGKEIT:
      type: object
      properties:
        begruendung:
          $ref: '#/components/schemas/PI_29001__stammdaten__HANDELSUNSTIMMIGKEIT__begruendung'
        nummer:
          $ref: '../../../bo4e/fields/bo/Handelsunstimmigkeit/nummer.yaml#/components/schemas/nummer'
          x-edifact-segment:
            - SG2.DOC+380
        typ:
          $ref: '../../../bo4e/fields/bo/Handelsunstimmigkeit/typ.yaml#/components/schemas/typ'
          x-edifact-segment:
            - SG2.DOC+380
        zuZahlen:
          $ref: '#/components/schemas/PI_29001__stammdaten__HANDELSUNSTIMMIGKEIT__zuZahlen'
      required:
        - begruendung
        - nummer
        - typ
        - zuZahlen
    PI_29001__stammdaten__HANDELSUNSTIMMIGKEIT__begruendung:
      type: object
      properties:
        anerkennungsmeldung:
          $ref: '../../../bo4e/fields/com/Handelsunstimmigkeitsbegruendung/anerkennungsmeldung.yaml#/components/schemas/anerkennungsmeldung'
          x-edifact-segment:
            - SG2.DOC+380.SG3.AJT.FTX+ACD
        bestaetigungDar:
          $ref: '../../../bo4e/fields/com/Handelsunstimmigkeitsbegruendung/bestaetigungDar.yaml#/components/schemas/bestaetigungDar'
          x-edifact-segment:
            - SG2.DOC+380.SG3.AJT.FTX+ACD
        grund:
          $ref: '../../../bo4e/fields/com/Handelsunstimmigkeitsbegruendung/grund.yaml#/components/schemas/grund'
          x-edifact-segment:
            - SG2.DOC+380.SG3.AJT
        hinweis:
          $ref: '../../../bo4e/fields/com/Handelsunstimmigkeitsbegruendung/hinweis.yaml#/components/schemas/hinweis'
          x-edifact-segment:
            - SG2.DOC+380.SG3.AJT.FTX+ACB
        referenzDar:
          $ref: '../../../bo4e/fields/com/Handelsunstimmigkeitsbegruendung/referenzDar.yaml#/components/schemas/referenzDar'
          x-edifact-segment:
            - SG2.DOC+380.SG3.AJT.FTX+ACD
        referenznummer:
          $ref: '../../../bo4e/fields/com/Handelsunstimmigkeitsbegruendung/referenznummer.yaml#/components/schemas/referenznummer'
          x-edifact-segment:
            - SG2.DOC+380.SG3.AJT.FTX+ACD
        richtigkeit:
          $ref: '../../../bo4e/fields/com/Handelsunstimmigkeitsbegruendung/richtigkeit.yaml#/components/schemas/richtigkeit'
          x-edifact-segment:
            - SG2.DOC+380.SG3.AJT.FTX+ACD
      required:
        - grund
    PI_29001__stammdaten__HANDELSUNSTIMMIGKEIT__zuZahlen:
      type: object
      properties:
        wert:
          $ref: '../../../bo4e/fields/com/Betrag/wert.yaml#/components/schemas/wert'
          x-edifact-segment:
            - SG2.DOC+380.MOA+9
      required:
        - wert
    PI_29001__transaktionsdaten:
      type: object
      properties:
        absender:
          $ref: '#/components/schemas/PI_29001__transaktionsdaten__absender'
        antwortstatusCodeliste:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/antwortstatusCodeliste.yaml#/components/schemas/antwortstatusCodeliste'
          x-edifact-segment:
            - SG2.DOC+380.SG3.AJT
        dokumentennummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/dokumentennummer.yaml#/components/schemas/dokumentennummer'
          x-edifact-segment:
            - BGM+456
        empfaenger:
          $ref: '#/components/schemas/PI_29001__transaktionsdaten__empfaenger'
        kategorie:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/kategorie.yaml#/components/schemas/kategorie'
          x-edifact-segment:
            - BGM+456
        nachrichtendatum:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtendatum.yaml#/components/schemas/nachrichtendatum'
          x-edifact-segment:
            - DTM+137
        nachrichtenreferenznummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtenreferenznummer.yaml#/components/schemas/nachrichtenreferenznummer'
          x-edifact-segment:
            - UNH
        pruefidentifikator:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/pruefidentifikator.yaml#/components/schemas/pruefidentifikator'
          x-edifact-segment:
            - RFF+Z13
      required:
        - absender
        - antwortstatusCodeliste
        - dokumentennummer
        - empfaenger
        - kategorie
        - nachrichtendatum
        - nachrichtenreferenznummer
        - pruefidentifikator
    PI_29001__transaktionsdaten__absender:
      type: object
      properties:
        ansprechpartner:
          $ref: '#/components/schemas/PI_29001__transaktionsdaten__absender__ansprechpartner'
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG1.NAD+MS
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG1.NAD+MS
      required:
        - ansprechpartner
        - rollencodenummer
        - rollencodetyp
    PI_29001__transaktionsdaten__absender__ansprechpartner:
      type: object
      properties:
        eMailAdresse:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/eMailAdresse.yaml#/components/schemas/eMailAdresse'
          x-edifact-segment:
            - 'SG1.NAD+MS.COM+[EM|FX|TE|AJ|AL]'
        nachname:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/nachname.yaml#/components/schemas/nachname'
          x-edifact-segment:
            - SG1.NAD+MS.CTA+IC
        rufnummern:
          type: array
          items:
            $ref: '#/components/schemas/PI_29001__transaktionsdaten__absender__ansprechpartner__rufnummern'
      required:
        - eMailAdresse
        - nachname
        - rufnummern
    PI_29001__transaktionsdaten__absender__ansprechpartner__rufnummern:
      type: object
      properties:
        nummerntyp:
          $ref: '../../../bo4e/fields/com/Rufnummer/nummerntyp.yaml#/components/schemas/nummerntyp'
          x-edifact-segment:
            - 'SG1.NAD+MS.COM+[EM|FX|TE|AJ|AL]'
        rufnummer:
          $ref: '../../../bo4e/fields/com/Rufnummer/rufnummer.yaml#/components/schemas/rufnummer'
          x-edifact-segment:
            - 'SG1.NAD+MS.COM+[EM|FX|TE|AJ|AL]'
      required:
        - nummerntyp
        - rufnummer
    PI_29001__transaktionsdaten__empfaenger:
      type: object
      properties:
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG1.NAD+MR
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG1.NAD+MR
      required:
        - rollencodenummer
        - rollencodetyp
