openapi: 3.1.0
info:
  title: PI_13025
  version: '202504'
  x-bo4e-schema-version: 1.6.5
  x-bo4e-schema-sha: 95f07d974cf2dc738ca248b258d6589025614cb0
  x-templater-sha: 6e98aaa8818d7b01b16786b130d743ea57fa960a
components:
  schemas:
    PI_13025:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_13025__stammdaten'
        transaktionsdaten:
          $ref: '#/components/schemas/PI_13025__transaktionsdaten'
      required:
        - stammdaten
        - transaktionsdaten
    PI_13025__stammdaten:
      type: object
      properties:
        ENERGIEMENGE:
          type: array
          items:
            $ref: '#/components/schemas/PI_13025__stammdaten__ENERGIEMENGE'
      required:
        - ENERGIEMENGE
    PI_13025__stammdaten__ENERGIEMENGE:
      type: object
      properties:
        enddatum:
          $ref: '../../../bo4e/fields/bo/Energiemenge/enddatum.yaml#/components/schemas/enddatum'
          x-edifact-segment:
            - SG5.NAD+DP.SG6.LOC+172.DTM+164
        konfiguration:
          $ref: '../../../bo4e/fields/bo/Energiemenge/konfiguration.yaml#/components/schemas/konfiguration'
          x-edifact-segment:
            - SG5.NAD+DP.SG6.LOC+172
        lokationsId:
          $ref: '../../../bo4e/fields/bo/Energiemenge/lokationsId.yaml#/components/schemas/lokationsId'
          x-edifact-segment:
            - SG5.NAD+DP.SG6.LOC+172
        startdatum:
          $ref: '../../../bo4e/fields/bo/Energiemenge/startdatum.yaml#/components/schemas/startdatum'
          x-edifact-segment:
            - SG5.NAD+DP.SG6.LOC+172.DTM+163
      required:
        - enddatum
        - konfiguration
        - lokationsId
        - startdatum
    PI_13025__transaktionsdaten:
      type: object
      properties:
        absender:
          $ref: '#/components/schemas/PI_13025__transaktionsdaten__absender'
        anfrageReferenz:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/anfrageReferenz.yaml#/components/schemas/anfrageReferenz'
          x-edifact-segment:
            - SG1.RFF+AGI
        dokumentennummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/dokumentennummer.yaml#/components/schemas/dokumentennummer'
          x-edifact-segment:
            - 'BGM+[7|Z48]'
        empfaenger:
          $ref: '#/components/schemas/PI_13025__transaktionsdaten__empfaenger'
        kategorie:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/kategorie.yaml#/components/schemas/kategorie'
          x-edifact-segment:
            - 'BGM+[7|Z48]'
        nachrichtendatum:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtendatum.yaml#/components/schemas/nachrichtendatum'
          x-edifact-segment:
            - DTM+137
        nachrichtenfunktion:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtenfunktion.yaml#/components/schemas/nachrichtenfunktion'
          x-edifact-segment:
            - 'BGM+[7|Z48]'
        nachrichtenreferenznummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtenreferenznummer.yaml#/components/schemas/nachrichtenreferenznummer'
          x-edifact-segment:
            - UNH
        pruefidentifikator:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/pruefidentifikator.yaml#/components/schemas/pruefidentifikator'
          x-edifact-segment:
            - SG1.RFF+Z13
      required:
        - absender
        - anfrageReferenz
        - dokumentennummer
        - kategorie
        - nachrichtendatum
        - nachrichtenfunktion
        - nachrichtenreferenznummer
        - pruefidentifikator
    PI_13025__transaktionsdaten__absender:
      type: object
      properties:
        ansprechpartner:
          $ref: '#/components/schemas/PI_13025__transaktionsdaten__absender__ansprechpartner'
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+MS
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+MS
      required:
        - ansprechpartner
    PI_13025__transaktionsdaten__absender__ansprechpartner:
      type: object
      properties:
        eMailAdresse:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/eMailAdresse.yaml#/components/schemas/eMailAdresse'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG4.CTA+IC.COM+[EM|FX|TE|AJ|AL]'
        nachname:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/nachname.yaml#/components/schemas/nachname'
          x-edifact-segment:
            - SG2.NAD+MS.SG4.CTA+IC
        rufnummern:
          type: array
          items:
            $ref: '#/components/schemas/PI_13025__transaktionsdaten__absender__ansprechpartner__rufnummern'
      required:
        - eMailAdresse
        - nachname
        - rufnummern
    PI_13025__transaktionsdaten__absender__ansprechpartner__rufnummern:
      type: object
      properties:
        nummerntyp:
          $ref: '../../../bo4e/fields/com/Rufnummer/nummerntyp.yaml#/components/schemas/nummerntyp'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG4.CTA+IC.COM+[EM|FX|TE|AJ|AL]'
        rufnummer:
          $ref: '../../../bo4e/fields/com/Rufnummer/rufnummer.yaml#/components/schemas/rufnummer'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG4.CTA+IC.COM+[EM|FX|TE|AJ|AL]'
      required:
        - nummerntyp
        - rufnummer
    PI_13025__transaktionsdaten__empfaenger:
      type: object
      properties:
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+MR
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+MR
