openapi: 3.1.0
info:
  title: '[NB] START_LIEFERENDE'
  version: '202604'
  x-bpmn-source-sha: eaf359e3
  x-bo4e-schema-version: 1.7.1
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    '[NB] START_LIEFERENDE':
      type: object
      required:
      - masterData
      - transactionData
      - additionalData
      properties:
        masterData:
          oneOf:
          - $ref: ../../event-bauteil-en/202604/UTILMD_GAS/PI_44007.yaml#/components/schemas/PI_44007__masterData
          - $ref: ../../event-bauteil-en/202604/UTILMD/PI_55007.yaml#/components/schemas/PI_55007__masterData
        transactionData:
          type: object
          required:
          - sender
          - receiver
          - freeText
          - category
          - sector
          - transactionReason
          - transactionReasonSupplement
          properties:
            sender:
              type: object
              properties:
                roleCodeNumber:
                  $ref: ../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
            receiver:
              type: object
              properties:
                roleCodeNumber:
                  $ref: ../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
            freeText:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/freeText.yaml#/components/schemas/freeText
            category:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/category.yaml#/components/schemas/category
            sector:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/sector.yaml#/components/schemas/sector
            transactionReason:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/transactionReason.yaml#/components/schemas/transactionReason
            transactionReasonSupplement:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/transactionReasonSupplement.yaml#/components/schemas/transactionReasonSupplement
            verificationIdentifier:
              description: Wird dynamisch im Event-Prozess ermittelt (Sparte + Transaktionsgrund + Empfänger-Marktrolle). Ein vom Sender mitgegebener Wert wird ignoriert. Im Topic mögliche Prüfis — 44007, 55007.
              examples:
              - '44007'
              - '55007'
        additionalData:
          type: object
          required:
          - processId
          - eventname
          properties:
            processId:
              type: string
            eventname:
              type: string
              const: START_LIEFERENDE
              default: START_DELIVERY_END
