openapi: 3.1.0
info:
  title: '[NB] START_ERHEBUNG_MESSWERTE'
  version: '202604'
  x-bpmn-source-sha: eaf359e3
  x-bo4e-schema-version: 1.7.1
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    '[NB] START_ERHEBUNG_MESSWERTE':
      type: object
      required:
      - masterData
      - transactionData
      - additionalData
      properties:
        masterData:
          oneOf:
          - $ref: ../../event-bauteil-en/202604/MSCONS/PI_13002.yaml#/components/schemas/PI_13002__masterData
          - $ref: ../../event-bauteil-en/202604/MSCONS/PI_13008.yaml#/components/schemas/PI_13008__masterData
          - $ref: ../../event-bauteil-en/202604/MSCONS/PI_13009.yaml#/components/schemas/PI_13009__masterData
          - $ref: ../../event-bauteil-en/202604/MSCONS/PI_13016.yaml#/components/schemas/PI_13016__masterData
          - $ref: ../../event-bauteil-en/202604/MSCONS/PI_13017.yaml#/components/schemas/PI_13017__masterData
          - $ref: ../../event-bauteil-en/202604/MSCONS/PI_13018.yaml#/components/schemas/PI_13018__masterData
          - $ref: ../../event-bauteil-en/202604/MSCONS/PI_13019.yaml#/components/schemas/PI_13019__masterData
          - $ref: ../../event-bauteil-en/202604/MSCONS/PI_13025.yaml#/components/schemas/PI_13025__masterData
          - $ref: ../../event-bauteil-en/202604/MSCONS/PI_13027.yaml#/components/schemas/PI_13027__masterData
        transactionData:
          type: object
          required:
          - sender
          - inquiryReference
          - receiver
          - category
          - locationType
          - sector
          - typeValue
          properties:
            sender:
              type: object
              properties:
                roleCodeNumber:
                  $ref: ../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
            inquiryReference:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/inquiryReference.yaml#/components/schemas/inquiryReference
            receiver:
              type: object
              properties:
                roleCodeNumber:
                  $ref: ../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
            category:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/category.yaml#/components/schemas/category
            locationType:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/locationType.yaml#/components/schemas/locationType
            sector:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/sector.yaml#/components/schemas/sector
            typeValue:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/typeValue.yaml#/components/schemas/typeValue
            verificationIdentifier:
              description: Wird dynamisch im Event-Prozess ermittelt (Sparte + Transaktionsgrund + Empfänger-Marktrolle). Ein vom Sender mitgegebener Wert wird ignoriert. Im Topic mögliche Prüfis — 13002, 13008, 13009, 13016, 13017, 13018, 13019, 13025, 13027.
              examples:
              - '13002'
              - '13008'
              - '13009'
              - '13016'
              - '13017'
              - '13018'
              - '13019'
              - '13025'
              - '13027'
        additionalData:
          type: object
          required:
          - processId
          - eventname
          properties:
            processId:
              type: string
            eventname:
              type: string
              const: START_ERHEBUNG_MESSWERTE
              default: START_COLLECTION_MEASURED_VALUES
