openapi: 3.1.0
info:
  title: PI_25007
  version: '202604'
  x-bo4e-schema-version: 1.6.5
  x-bo4e-schema-sha: 95f07d974cf2dc738ca248b258d6589025614cb0
  x-templater-sha: 6e98aaa8818d7b01b16786b130d743ea57fa960a
components:
  schemas:
    PI_25007:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_25007__stammdaten'
      required:
        - stammdaten
    PI_25007__stammdaten:
      type: object
      properties:
        LEISTUNGSKURVENDEFINITION:
          type: array
          items:
            $ref: '#/components/schemas/PI_25007__stammdaten__LEISTUNGSKURVENDEFINITION'
      required:
        - LEISTUNGSKURVENDEFINITION
    PI_25007__stammdaten__LEISTUNGSKURVENDEFINITION:
      type: object
      properties:
        beginndatum:
          $ref: '../../../bo4e/fields/bo/Leistungskurvendefinition/beginndatum.yaml#/components/schemas/beginndatum'
          x-edifact-segment:
            - SG5.IDE+24.DTM+157
        leistungskurven:
          type: array
          items:
            $ref: '#/components/schemas/PI_25007__stammdaten__LEISTUNGSKURVENDEFINITION__leistungskurven'
        notwendigkeit:
          $ref: '../../../bo4e/fields/bo/Leistungskurvendefinition/notwendigkeit.yaml#/components/schemas/notwendigkeit'
          x-edifact-segment:
            - SG5.IDE+24.STS+Z36
        version:
          $ref: '../../../bo4e/fields/bo/Leistungskurvendefinition/version.yaml#/components/schemas/version'
          x-edifact-segment:
            - SG5.IDE+24.DTM+293
      required:
        - beginndatum
        - leistungskurven
        - notwendigkeit
        - version
    PI_25007__stammdaten__LEISTUNGSKURVENDEFINITION__leistungskurven:
      type: object
      properties:
        code:
          $ref: '../../../bo4e/fields/com/Leistungskurve/code.yaml#/components/schemas/code'
          x-edifact-segment:
            - SG5.IDE+24.SG8.SEQ+Z70.SG9.CCI+Z53
        haeufigkeit:
          $ref: '../../../bo4e/fields/com/Leistungskurve/haeufigkeit.yaml#/components/schemas/haeufigkeit'
          x-edifact-segment:
            - SG5.IDE+24.SG8.SEQ+Z70.SG9.CCI+Z53.CAV+ZE0
        uebermittelbarkeit:
          $ref: '../../../bo4e/fields/com/Leistungskurve/uebermittelbarkeit.yaml#/components/schemas/uebermittelbarkeit'
          x-edifact-segment:
            - SG5.IDE+24.SG8.SEQ+Z70.SG9.CCI+Z53.CAV+ZD5
      required:
        - code
        - haeufigkeit
        - uebermittelbarkeit
