openapi: 3.1.0
info:
  title: PI_27002
  version: '202604'
  x-bo4e-schema-version: 1.6.5
  x-bo4e-schema-sha: 95f07d974cf2dc738ca248b258d6589025614cb0
  x-templater-sha: 6e98aaa8818d7b01b16786b130d743ea57fa960a
components:
  schemas:
    PI_27002:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_27002__stammdaten'
      required:
        - stammdaten
    PI_27002__stammdaten:
      type: object
      properties:
        PREISBLATT:
          type: array
          items:
            $ref: '#/components/schemas/PI_27002__stammdaten__PREISBLATT'
      required:
        - PREISBLATT
    PI_27002__stammdaten__PREISBLATT:
      type: object
      properties:
        gueltigkeit:
          $ref: '#/components/schemas/PI_27002__stammdaten__PREISBLATT__gueltigkeit'
        preispositionen:
          type: array
          items:
            $ref: '#/components/schemas/PI_27002__stammdaten__PREISBLATT__preispositionen'
      required:
        - gueltigkeit
        - preispositionen
    PI_27002__stammdaten__PREISBLATT__gueltigkeit:
      type: object
      properties:
        startdatum:
          $ref: '../../../bo4e/fields/com/Zeitraum/startdatum.yaml#/components/schemas/startdatum'
          x-edifact-segment:
            - DTM+157
      required:
        - startdatum
    PI_27002__stammdaten__PREISBLATT__preispositionen:
      type: object
      properties:
        artikelId:
          $ref: '../../../bo4e/fields/com/Preisposition/artikelId.yaml#/components/schemas/artikelId'
          x-edifact-segment:
            - SG17.PGI+9.SG36.LIN
        bdewArtikelnummer:
          $ref: '../../../bo4e/fields/com/Preisposition/bdewArtikelnummer.yaml#/components/schemas/bdewArtikelnummer'
          x-edifact-segment:
            - SG17.PGI+9.SG36.LIN
            - 'SG17.PGI+9.SG36.LIN.IMD+[C|F|X]'
        beschreibung:
          $ref: '../../../bo4e/fields/com/Preisposition/beschreibung.yaml#/components/schemas/beschreibung'
          x-edifact-segment:
            - 'SG17.PGI+9.SG36.LIN.IMD+[C|F|X]'
        beschreibungsformat:
          $ref: '../../../bo4e/fields/com/Preisposition/beschreibungsformat.yaml#/components/schemas/beschreibungsformat'
          x-edifact-segment:
            - 'SG17.PGI+9.SG36.LIN.IMD+[C|F|X]'
        leistungsbezeichnung:
          $ref: '../../../bo4e/fields/com/Preisposition/leistungsbezeichnung.yaml#/components/schemas/leistungsbezeichnung'
          x-edifact-segment:
            - 'SG17.PGI+9.SG36.LIN.IMD+[C|F|X]'
        messebene:
          $ref: '../../../bo4e/fields/com/Preisposition/messebene.yaml#/components/schemas/messebene'
          x-edifact-segment:
            - 'SG17.PGI+9.SG36.LIN.IMD+[C|F|X]'
        positionsnummer:
          $ref: '../../../bo4e/fields/com/Preisposition/positionsnummer.yaml#/components/schemas/positionsnummer'
          x-edifact-segment:
            - SG17.PGI+9.SG36.LIN
        preisschluesselstamm:
          $ref: '../../../bo4e/fields/com/Preisposition/preisschluesselstamm.yaml#/components/schemas/preisschluesselstamm'
          x-edifact-segment:
            - SG17.PGI+9.SG36.LIN.PIA+1
        preisstaffeln:
          type: array
          items:
            $ref: '#/components/schemas/PI_27002__stammdaten__PREISBLATT__preispositionen__preisstaffeln'
        zeitbasis:
          $ref: '../../../bo4e/fields/com/Preisposition/zeitbasis.yaml#/components/schemas/zeitbasis'
          x-edifact-segment:
            - SG17.PGI+9.SG36.LIN.SG40.PRI+CAL
      required:
        - artikelId
        - bdewArtikelnummer
        - positionsnummer
        - preisstaffeln
        - zeitbasis
    PI_27002__stammdaten__PREISBLATT__preispositionen__preisstaffeln:
      type: object
      properties:
        einheit:
          $ref: '../../../bo4e/fields/com/Preisstaffel/einheit.yaml#/components/schemas/einheit'
          x-edifact-segment:
            - SG17.PGI+9.SG36.LIN.SG40.PRI+CAL.RNG+10+KWH
        einheitspreis:
          $ref: '../../../bo4e/fields/com/Preisstaffel/einheitspreis.yaml#/components/schemas/einheitspreis'
          x-edifact-segment:
            - SG17.PGI+9.SG36.LIN.SG40.PRI+CAL
        staffelgrenzeBis:
          $ref: '../../../bo4e/fields/com/Preisstaffel/staffelgrenzeBis.yaml#/components/schemas/staffelgrenzeBis'
          x-edifact-segment:
            - SG17.PGI+9.SG36.LIN.SG40.PRI+CAL.RNG+10+KWH
        staffelgrenzeVon:
          $ref: '../../../bo4e/fields/com/Preisstaffel/staffelgrenzeVon.yaml#/components/schemas/staffelgrenzeVon'
          x-edifact-segment:
            - SG17.PGI+9.SG36.LIN.SG40.PRI+CAL.RNG+10+KWH
      required:
        - einheitspreis
