openapi: 3.1.0
info:
  title: PI_21039
  version: '202610'
  x-bo4e-schema-version: 1.7.8
  x-bo4e-schema-sha: a4f202d62930c69acd327622abf92da121d3a12e
  x-templater-sha: 41b3eb8c66d69f8953cbfe2ce874d41618f10ca0
components:
  schemas:
    PI_21039:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_21039__stammdaten'
        transaktionsdaten:
          $ref: '#/components/schemas/PI_21039__transaktionsdaten'
      required:
        - stammdaten
        - transaktionsdaten
    PI_21039__stammdaten:
      type: object
      properties:
        STATUSMITTEILUNG:
          type: array
          items:
            $ref: '#/components/schemas/PI_21039__stammdaten__STATUSMITTEILUNG'
      required:
        - STATUSMITTEILUNG
    PI_21039__stammdaten__STATUSMITTEILUNG:
      type: object
      properties:
        positionsdaten:
          type: array
          items:
            $ref: '#/components/schemas/PI_21039__stammdaten__STATUSMITTEILUNG__positionsdaten'
      required:
        - positionsdaten
    PI_21039__stammdaten__STATUSMITTEILUNG__positionsdaten:
      type: object
      properties:
        allgemeineInformationenText:
          $ref: '../../../bo4e/fields/com/StatusmitteilungPosition/allgemeineInformationenText.yaml#/components/schemas/allgemeineInformationenText'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z37.SG25.GID.FTX+ACB
            - SG14.CNI.SG15.STS+Z38.SG25.GID.FTX+ACB
        antwortstatus:
          $ref: '../../../bo4e/fields/com/StatusmitteilungPosition/antwortstatus.yaml#/components/schemas/antwortstatus'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z37
            - SG14.CNI.SG15.STS+Z38
        antwortstatusCodeliste:
          $ref: '../../../bo4e/fields/com/StatusmitteilungPosition/antwortstatusCodeliste.yaml#/components/schemas/antwortstatusCodeliste'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z37
            - SG14.CNI.SG15.STS+Z38
        auftragsstatus:
          $ref: '../../../bo4e/fields/com/StatusmitteilungPosition/auftragsstatus.yaml#/components/schemas/auftragsstatus'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z37
            - SG14.CNI.SG15.STS+Z38
        fertigstellungsdatum:
          $ref: '../../../bo4e/fields/com/StatusmitteilungPosition/fertigstellungsdatum.yaml#/components/schemas/fertigstellungsdatum'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z37.DTM+293
            - SG14.CNI.SG15.STS+Z38.DTM+293
        lokationsId:
          $ref: '../../../bo4e/fields/com/StatusmitteilungPosition/lokationsId.yaml#/components/schemas/lokationsId'
          x-edifact-segment:
            - SG14.CNI.LOC+172
        positionsnummer:
          $ref: '../../../bo4e/fields/com/StatusmitteilungPosition/positionsnummer.yaml#/components/schemas/positionsnummer'
          x-edifact-segment:
            - SG14.CNI
        sendungsposition:
          $ref: '../../../bo4e/fields/com/StatusmitteilungPosition/sendungsposition.yaml#/components/schemas/sendungsposition'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z37.SG25.GID
            - SG14.CNI.SG15.STS+Z38.SG25.GID
        statusObjekt:
          $ref: '../../../bo4e/fields/com/StatusmitteilungPosition/statusObjekt.yaml#/components/schemas/statusObjekt'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z37
            - SG14.CNI.SG15.STS+Z38
      required:
        - lokationsId
        - positionsnummer
    PI_21039__transaktionsdaten:
      type: object
      properties:
        absender:
          $ref: '#/components/schemas/PI_21039__transaktionsdaten__absender'
        dokumentennummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/dokumentennummer.yaml#/components/schemas/dokumentennummer'
          x-edifact-segment:
            - BGM+Z33
        empfaenger:
          $ref: '#/components/schemas/PI_21039__transaktionsdaten__empfaenger'
        nachrichtendatum:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtendatum.yaml#/components/schemas/nachrichtendatum'
          x-edifact-segment:
            - DTM+137
        nachrichtenreferenznummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtenreferenznummer.yaml#/components/schemas/nachrichtenreferenznummer'
          x-edifact-segment:
            - UNH
        pruefidentifikator:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/pruefidentifikator.yaml#/components/schemas/pruefidentifikator'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z37.RFF+Z13
            - SG14.CNI.SG15.STS+Z38.RFF+Z13
      required:
        - absender
        - dokumentennummer
        - empfaenger
        - nachrichtendatum
        - nachrichtenreferenznummer
    PI_21039__transaktionsdaten__absender:
      type: object
      properties:
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG1.NAD+MS
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG1.NAD+MS
      required:
        - rollencodenummer
        - rollencodetyp
    PI_21039__transaktionsdaten__empfaenger:
      type: object
      properties:
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG1.NAD+MR
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG1.NAD+MR
      required:
        - rollencodenummer
        - rollencodetyp
