openapi: 3.1.0
info:
  title: PI_55011
  version: '202604'
  x-bo4e-schema-version: 1.7.4
  x-bo4e-schema-sha: 1732e948753541a9b641ca98f3d8ff189d994263
  x-templater-sha: 20c434c98f1808f1b10ab64bdf7a7a96d42aa7ee
components:
  schemas:
    PI_55011:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_55011__masterData'
      required:
      - masterData
    PI_55011__masterData:
      type: object
      properties:
        GRID_ACCESS_CONTRACT:
          type: array
          items:
            $ref: '#/components/schemas/PI_55011__masterData__GRID_ACCESS_CONTRACT'
      required:
      - GRID_ACCESS_CONTRACT
    PI_55011__masterData__GRID_ACCESS_CONTRACT:
      type: object
      properties:
        contractEnd:
          $ref: ../../../bo4e-en/fields/bo/Contract/contractEnd.yaml#/components/schemas/contractEnd
          x-edifact-segment:
          - SG4.IDE+24.DTM+93
      required:
      - contractEnd
