openapi: 3.1.0
info:
  title: PI_55077
  version: '202610'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_55077:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55077__stammdaten'
      required:
        - stammdaten
    PI_55077__stammdaten:
      type: object
      properties:
        MARKTLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_55077__stammdaten__MARKTLOKATION'
        NETZNUTZUNGSVERTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_55077__stammdaten__NETZNUTZUNGSVERTRAG'
        TRANCHE:
          type: array
          items:
            $ref: '#/components/schemas/PI_55077__stammdaten__TRANCHE'
      required:
        - MARKTLOKATION
        - NETZNUTZUNGSVERTRAG
        - TRANCHE
    PI_55077__stammdaten__MARKTLOKATION:
      type: object
      properties:
        erforderlichesProduktpaket:
          type: array
          items:
            $ref: '#/components/schemas/PI_55077__stammdaten__MARKTLOKATION__erforderlichesProduktpaket'
        foerderungsLand:
          $ref: '../../../bo4e/fields/bo/Marktlokation/foerderungsLand.yaml#/components/schemas/foerderungsLand'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z01.SG10.CCI+Z23
        marktlokationsId:
          $ref: '../../../bo4e/fields/bo/Marktlokation/marktlokationsId.yaml#/components/schemas/marktlokationsId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z16
      required:
        - erforderlichesProduktpaket
        - foerderungsLand
        - marktlokationsId
    PI_55077__stammdaten__MARKTLOKATION__erforderlichesProduktpaket:
      type: object
      properties:
        priorisierung:
          $ref: '../../../bo4e/fields/com/Produktpaket/priorisierung.yaml#/components/schemas/priorisierung'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+ZH0.SG10.CCI+Z65.CAV
        produkt:
          type: array
          items:
            $ref: '#/components/schemas/PI_55077__stammdaten__MARKTLOKATION__erforderlichesProduktpaket__produkt'
        produktpaketId:
          $ref: '../../../bo4e/fields/com/Produktpaket/produktpaketId.yaml#/components/schemas/produktpaketId'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z79
            - SG4.IDE+24.SG8.SEQ+ZH0
        umsetzungsgradvorgabe:
          $ref: '../../../bo4e/fields/com/Produktpaket/umsetzungsgradvorgabe.yaml#/components/schemas/umsetzungsgradvorgabe'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+ZH0.SG10.CCI+Z65
      required:
        - produkt
        - produktpaketId
        - umsetzungsgradvorgabe
    PI_55077__stammdaten__MARKTLOKATION__erforderlichesProduktpaket__produkt:
      type: object
      properties:
        codeProdukteigenschaft:
          $ref: '../../../bo4e/fields/com/Produkt/codeProdukteigenschaft.yaml#/components/schemas/codeProdukteigenschaft'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z79.SG10.CCI+Z66.CAV+ZH9
        produktCode:
          $ref: '../../../bo4e/fields/com/Produkt/produktCode.yaml#/components/schemas/produktCode'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z79.PIA+5
        wertedetails:
          $ref: '../../../bo4e/fields/com/Produkt/wertedetails.yaml#/components/schemas/wertedetails'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z79.SG10.CCI+Z66.CAV+ZV4
      required:
        - produktCode
    PI_55077__stammdaten__NETZNUTZUNGSVERTRAG:
      type: object
      properties:
        vertragsbeginn:
          $ref: '../../../bo4e/fields/bo/Vertrag/vertragsbeginn.yaml#/components/schemas/vertragsbeginn'
          x-edifact-segment:
            - SG4.IDE+24.DTM+92
      required:
        - vertragsbeginn
    PI_55077__stammdaten__TRANCHE:
      type: object
      properties:
        tranchenId:
          $ref: '../../../bo4e/fields/bo/Tranche/tranchenId.yaml#/components/schemas/tranchenId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z21
      required:
        - tranchenId
