openapi: 3.1.0
info:
  title: PI_55693
  version: '202610'
  x-bo4e-schema-version: 1.7.4
  x-bo4e-schema-sha: 1732e948753541a9b641ca98f3d8ff189d994263
  x-templater-sha: 392a2eb2993418f8a5be64578c22568416e2d551
components:
  schemas:
    PI_55693:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55693__stammdaten'
      required:
        - stammdaten
    PI_55693__stammdaten:
      type: object
      properties:
        TECHNISCHE_RESSOURCE:
          type: array
          items:
            $ref: '#/components/schemas/PI_55693__stammdaten__TECHNISCHE_RESSOURCE'
        VERWENDUNGSZEITRAUM:
          type: array
          items:
            $ref: '#/components/schemas/PI_55693__stammdaten__VERWENDUNGSZEITRAUM'
      required:
        - TECHNISCHE_RESSOURCE
        - VERWENDUNGSZEITRAUM
    PI_55693__stammdaten__TECHNISCHE_RESSOURCE:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/TechnischeRessource/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z52
        fernsteuerbarkeit:
          $ref: '../../../bo4e/fields/bo/TechnischeRessource/fernsteuerbarkeit.yaml#/components/schemas/fernsteuerbarkeit'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+Z52.SG10.CCI+Z24.CAV+[ZW5|ZW6]'
        gueltigkeitszeitraum:
          $ref: '#/components/schemas/PI_55693__stammdaten__TECHNISCHE_RESSOURCE__gueltigkeitszeitraum'
        ressourcenId:
          $ref: '../../../bo4e/fields/bo/TechnischeRessource/ressourcenId.yaml#/components/schemas/ressourcenId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z20
      required:
        - datenqualitaet
        - gueltigkeitszeitraum
        - ressourcenId
    PI_55693__stammdaten__TECHNISCHE_RESSOURCE__gueltigkeitszeitraum:
      type: object
      properties:
        zeitraumId:
          $ref: '../../../bo4e/fields/com/Zeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z52
      required:
        - zeitraumId
    PI_55693__stammdaten__VERWENDUNGSZEITRAUM:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53]'
        verwendungAb:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungAb.yaml#/components/schemas/verwendungAb'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53].DTM+Z25'
        verwendungBis:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungBis.yaml#/components/schemas/verwendungBis'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53].DTM+Z26'
        zeitraumId:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53]'
      required:
        - datenqualitaet
        - verwendungAb
        - zeitraumId
