openapi: 3.1.0
info:
  title: PI_55623
  version: '202610'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_55623:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55623__stammdaten'
      required:
        - stammdaten
    PI_55623__stammdaten:
      type: object
      properties:
        TECHNISCHE_RESSOURCE:
          type: array
          items:
            $ref: '#/components/schemas/PI_55623__stammdaten__TECHNISCHE_RESSOURCE'
        VERWENDUNGSZEITRAUM:
          type: array
          items:
            $ref: '#/components/schemas/PI_55623__stammdaten__VERWENDUNGSZEITRAUM'
      required:
        - TECHNISCHE_RESSOURCE
        - VERWENDUNGSZEITRAUM
    PI_55623__stammdaten__TECHNISCHE_RESSOURCE:
      type: object
      properties:
        art:
          $ref: '../../../bo4e/fields/bo/TechnischeRessource/art.yaml#/components/schemas/art'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZG4|ZG5].SG10.CCI+[Z17|Z50|Z56]'
        artEMobilitaet:
          $ref: '../../../bo4e/fields/bo/TechnischeRessource/artEMobilitaet.yaml#/components/schemas/artEMobilitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZG4|ZG5].SG10.CCI+[Z17|Z50|Z56].CAV'
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/TechnischeRessource/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZG4|ZG5]'
        einordnung:
          $ref: '../../../bo4e/fields/bo/TechnischeRessource/einordnung.yaml#/components/schemas/einordnung'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZG4|ZG5].SG10.CCI+[Z17|Z50|Z56].CAV+[ZH2|ZH3|ZH4|ZH5]'
        enwg:
          $ref: '../../../bo4e/fields/bo/TechnischeRessource/enwg.yaml#/components/schemas/enwg'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZG4|ZG5].SG10.CCI+[Z17|Z50|Z56].CAV+[ZG8|ZG9]'
        erzeugungsart:
          $ref: '../../../bo4e/fields/bo/TechnischeRessource/erzeugungsart.yaml#/components/schemas/erzeugungsart'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZG4|ZG5].SG10.CCI+[Z17|Z50|Z56].CAV+[ZF5|ZF6|ZG0|ZG1|ZG5]'
        gueltigkeitszeitraum:
          $ref: '#/components/schemas/PI_55623__stammdaten__TECHNISCHE_RESSOURCE__gueltigkeitszeitraum'
        inbetriebsetzungsdatum:
          $ref: '../../../bo4e/fields/bo/TechnischeRessource/inbetriebsetzungsdatum.yaml#/components/schemas/inbetriebsetzungsdatum'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZG4|ZG5].SG10.CCI+[Z17|Z50|Z56].CAV+[ZH0|ZH1]'
        nennleistung:
          $ref: '#/components/schemas/PI_55623__stammdaten__TECHNISCHE_RESSOURCE__nennleistung'
        referenzNetzlokation:
          $ref: '../../../bo4e/fields/bo/TechnischeRessource/referenzNetzlokation.yaml#/components/schemas/referenzNetzlokation'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZG4|ZG5].RFF+Z32'
        referenzSteuerbareRessource:
          $ref: '../../../bo4e/fields/bo/TechnischeRessource/referenzSteuerbareRessource.yaml#/components/schemas/referenzSteuerbareRessource'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZG4|ZG5].RFF+Z38'
        ressourcenId:
          $ref: '../../../bo4e/fields/bo/TechnischeRessource/ressourcenId.yaml#/components/schemas/ressourcenId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z20
        speicherart:
          $ref: '../../../bo4e/fields/bo/TechnischeRessource/speicherart.yaml#/components/schemas/speicherart'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZG4|ZG5].SG10.CCI+[Z17|Z50|Z56].CAV+[ZF7|ZF8|ZF9|ZG6]'
        speicherkapazitaet:
          $ref: '../../../bo4e/fields/bo/TechnischeRessource/speicherkapazitaet.yaml#/components/schemas/speicherkapazitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZG4|ZG5].SG9.QTY+Z42'
        verbrauchsart:
          $ref: '../../../bo4e/fields/bo/TechnischeRessource/verbrauchsart.yaml#/components/schemas/verbrauchsart'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZG4|ZG5].SG10.CCI+[Z17|Z50|Z56].CAV+[Z64|Z65|ZE5|ZA8]'
        verguetungsverpflichtung:
          $ref: '../../../bo4e/fields/bo/TechnischeRessource/verguetungsverpflichtung.yaml#/components/schemas/verguetungsverpflichtung'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZG4|ZG5].SG10.CCI+Z68'
        waermenutzung:
          $ref: '../../../bo4e/fields/bo/TechnischeRessource/waermenutzung.yaml#/components/schemas/waermenutzung'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZG4|ZG5].SG10.CCI+[Z17|Z50|Z56].CAV'
      required:
        - art
        - datenqualitaet
        - gueltigkeitszeitraum
        - nennleistung
        - ressourcenId
        - speicherkapazitaet
    PI_55623__stammdaten__TECHNISCHE_RESSOURCE__gueltigkeitszeitraum:
      type: object
      properties:
        zeitraumId:
          $ref: '../../../bo4e/fields/com/Zeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZG4|ZG5]'
      required:
        - zeitraumId
    PI_55623__stammdaten__TECHNISCHE_RESSOURCE__nennleistung:
      type: object
      properties:
        abgabe:
          $ref: '../../../bo4e/fields/com/Nennleistung/abgabe.yaml#/components/schemas/abgabe'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZG4|ZG5].SG9.QTY+Z44'
        aufnahme:
          $ref: '../../../bo4e/fields/com/Nennleistung/aufnahme.yaml#/components/schemas/aufnahme'
          x-edifact-segment:
            - 'SG4.IDE+24.SG8.SEQ+[ZG4|ZG5].SG9.QTY+Z43'
      required:
        - abgabe
        - aufnahme
    PI_55623__stammdaten__VERWENDUNGSZEITRAUM:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55]'
        verwendungAb:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungAb.yaml#/components/schemas/verwendungAb'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55].DTM+Z25'
        verwendungBis:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungBis.yaml#/components/schemas/verwendungBis'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55].DTM+Z26'
        zeitraumId:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55]'
      required:
        - datenqualitaet
        - verwendungAb
        - zeitraumId
