openapi: 3.1.0
info:
  title: PI_55136
  version: '202610'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: 39ae45d481e5cc3d4d7aae328a23a9751236156a
components:
  schemas:
    PI_55136:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55136__stammdaten'
      required:
        - stammdaten
    PI_55136__stammdaten:
      type: object
      properties:
        ENERGIELIEFERVERTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_55136__stammdaten__ENERGIELIEFERVERTRAG'
        MARKTLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_55136__stammdaten__MARKTLOKATION'
        VERWENDUNGSZEITRAUM:
          type: array
          items:
            $ref: '#/components/schemas/PI_55136__stammdaten__VERWENDUNGSZEITRAUM'
      required:
        - ENERGIELIEFERVERTRAG
        - MARKTLOKATION
        - VERWENDUNGSZEITRAUM
    PI_55136__stammdaten__ENERGIELIEFERVERTRAG:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Vertrag/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG12.NAD+[Z47|Z48]'
            - 'SG4.IDE+24.SG12.NAD+[Z49|Z50]'
        gueltigkeitszeitraum:
          $ref: '#/components/schemas/PI_55136__stammdaten__ENERGIELIEFERVERTRAG__gueltigkeitszeitraum'
        korrespondenzpartner:
          $ref: '#/components/schemas/PI_55136__stammdaten__ENERGIELIEFERVERTRAG__korrespondenzpartner'
        vertragspartner2:
          type: array
          items:
            $ref: '#/components/schemas/PI_55136__stammdaten__ENERGIELIEFERVERTRAG__vertragspartner2'
      required:
        - datenqualitaet
        - gueltigkeitszeitraum
        - korrespondenzpartner
        - vertragspartner2
    PI_55136__stammdaten__ENERGIELIEFERVERTRAG__gueltigkeitszeitraum:
      type: object
      properties:
        zeitraumId:
          $ref: '../../../bo4e/fields/com/Zeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG12.NAD+[Z47|Z48].RFF+Z46'
            - 'SG4.IDE+24.SG12.NAD+[Z49|Z50].RFF+Z46'
      required:
        - zeitraumId
    PI_55136__stammdaten__ENERGIELIEFERVERTRAG__korrespondenzpartner:
      type: object
      properties:
        anrede:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/anrede.yaml#/components/schemas/anrede'
          x-edifact-segment:
            - 'SG4.IDE+24.SG12.NAD+[Z49|Z50]'
        ansprechpartner:
          $ref: '#/components/schemas/PI_55136__stammdaten__ENERGIELIEFERVERTRAG__korrespondenzpartner__ansprechpartner'
        name1:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name1.yaml#/components/schemas/name1'
          x-edifact-segment:
            - 'SG4.IDE+24.SG12.NAD+[Z49|Z50]'
        name2:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name2.yaml#/components/schemas/name2'
          x-edifact-segment:
            - 'SG4.IDE+24.SG12.NAD+[Z49|Z50]'
        name3:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name3.yaml#/components/schemas/name3'
          x-edifact-segment:
            - 'SG4.IDE+24.SG12.NAD+[Z49|Z50]'
        name4:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name4.yaml#/components/schemas/name4'
          x-edifact-segment:
            - 'SG4.IDE+24.SG12.NAD+[Z49|Z50]'
        partneradresse:
          $ref: '#/components/schemas/PI_55136__stammdaten__ENERGIELIEFERVERTRAG__korrespondenzpartner__partneradresse'
      required:
        - anrede
        - ansprechpartner
        - name1
        - name2
        - name3
        - name4
        - partneradresse
    PI_55136__stammdaten__ENERGIELIEFERVERTRAG__korrespondenzpartner__ansprechpartner:
      type: object
      properties:
        eMailAdresse:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/eMailAdresse.yaml#/components/schemas/eMailAdresse'
          x-edifact-segment:
            - 'SG4.IDE+24.SG12.NAD+[Z49|Z50].SG13.CTA.COM+[TE|EM]'
        rufnummern:
          type: array
          items:
            $ref: '#/components/schemas/PI_55136__stammdaten__ENERGIELIEFERVERTRAG__korrespondenzpartner__ansprechpartner__rufnummern'
      required:
        - eMailAdresse
        - rufnummern
    PI_55136__stammdaten__ENERGIELIEFERVERTRAG__korrespondenzpartner__ansprechpartner__rufnummern:
      type: object
      properties:
        nummerntyp:
          $ref: '../../../bo4e/fields/com/Rufnummer/nummerntyp.yaml#/components/schemas/nummerntyp'
          x-edifact-segment:
            - 'SG4.IDE+24.SG12.NAD+[Z49|Z50].SG13.CTA.COM+[TE|EM]'
        rufnummer:
          $ref: '../../../bo4e/fields/com/Rufnummer/rufnummer.yaml#/components/schemas/rufnummer'
          x-edifact-segment:
            - 'SG4.IDE+24.SG12.NAD+[Z49|Z50].SG13.CTA.COM+[TE|EM]'
      required:
        - nummerntyp
        - rufnummer
    PI_55136__stammdaten__ENERGIELIEFERVERTRAG__korrespondenzpartner__partneradresse:
      type: object
      properties:
        hausnummer:
          $ref: '../../../bo4e/fields/com/Adresse/hausnummer.yaml#/components/schemas/hausnummer'
          x-edifact-segment:
            - 'SG4.IDE+24.SG12.NAD+[Z49|Z50]'
        landescode:
          $ref: '../../../bo4e/fields/com/Adresse/landescode.yaml#/components/schemas/landescode'
          x-edifact-segment:
            - 'SG4.IDE+24.SG12.NAD+[Z49|Z50]'
        ort:
          $ref: '../../../bo4e/fields/com/Adresse/ort.yaml#/components/schemas/ort'
          x-edifact-segment:
            - 'SG4.IDE+24.SG12.NAD+[Z49|Z50]'
        ortsteil:
          $ref: '../../../bo4e/fields/com/Adresse/ortsteil.yaml#/components/schemas/ortsteil'
          x-edifact-segment:
            - 'SG4.IDE+24.SG12.NAD+[Z49|Z50]'
        postfach:
          $ref: '../../../bo4e/fields/com/Adresse/postfach.yaml#/components/schemas/postfach'
          x-edifact-segment:
            - 'SG4.IDE+24.SG12.NAD+[Z49|Z50]'
        postleitzahl:
          $ref: '../../../bo4e/fields/com/Adresse/postleitzahl.yaml#/components/schemas/postleitzahl'
          x-edifact-segment:
            - 'SG4.IDE+24.SG12.NAD+[Z49|Z50]'
        strasse:
          $ref: '../../../bo4e/fields/com/Adresse/strasse.yaml#/components/schemas/strasse'
          x-edifact-segment:
            - 'SG4.IDE+24.SG12.NAD+[Z49|Z50]'
      required:
        - hausnummer
        - landescode
        - ort
        - ortsteil
        - postfach
        - postleitzahl
        - strasse
    PI_55136__stammdaten__ENERGIELIEFERVERTRAG__vertragspartner2:
      type: object
      properties:
        anrede:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/anrede.yaml#/components/schemas/anrede'
          x-edifact-segment:
            - 'SG4.IDE+24.SG12.NAD+[Z47|Z48]'
        geschaeftspartnerrolle:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/geschaeftspartnerrolle.yaml#/components/schemas/geschaeftspartnerrolle'
          x-edifact-segment:
            - 'SG4.IDE+24.SG12.NAD+[Z47|Z48]'
        name1:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name1.yaml#/components/schemas/name1'
          x-edifact-segment:
            - 'SG4.IDE+24.SG12.NAD+[Z47|Z48]'
        name2:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name2.yaml#/components/schemas/name2'
          x-edifact-segment:
            - 'SG4.IDE+24.SG12.NAD+[Z47|Z48]'
        name3:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name3.yaml#/components/schemas/name3'
          x-edifact-segment:
            - 'SG4.IDE+24.SG12.NAD+[Z47|Z48]'
        name4:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name4.yaml#/components/schemas/name4'
          x-edifact-segment:
            - 'SG4.IDE+24.SG12.NAD+[Z47|Z48]'
      required:
        - anrede
        - geschaeftspartnerrolle
        - name1
        - name2
        - name3
        - name4
    PI_55136__stammdaten__MARKTLOKATION:
      type: object
      properties:
        marktlokationsId:
          $ref: '../../../bo4e/fields/bo/Marktlokation/marktlokationsId.yaml#/components/schemas/marktlokationsId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z16
      required:
        - marktlokationsId
    PI_55136__stammdaten__VERWENDUNGSZEITRAUM:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55]'
        verwendungAb:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungAb.yaml#/components/schemas/verwendungAb'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55].DTM+Z25'
        verwendungBis:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungBis.yaml#/components/schemas/verwendungBis'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55].DTM+Z26'
        zeitraumId:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z47|Z48|Z54|Z55]'
      required:
        - datenqualitaet
        - verwendungAb
        - zeitraumId
