openapi: 3.1.0
info:
  title: PI_55008
  version: '202610'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: c7b88c733e93fe4ee423d52cffa2cd8f312574ea
components:
  schemas:
    PI_55008:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55008__stammdaten'
      required:
        - stammdaten
    PI_55008__stammdaten:
      type: object
      properties:
        NETZNUTZUNGSVERTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_55008__stammdaten__NETZNUTZUNGSVERTRAG'
      required:
        - NETZNUTZUNGSVERTRAG
    PI_55008__stammdaten__NETZNUTZUNGSVERTRAG:
      type: object
      properties:
        vertragsende:
          $ref: '../../../bo4e/fields/bo/Vertrag/vertragsende.yaml#/components/schemas/vertragsende'
          x-edifact-segment:
            - SG4.IDE+24.DTM+93
      required:
        - vertragsende
