openapi: 3.1.0
info:
  title: PI_55044
  version: '202610'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: c7b88c733e93fe4ee423d52cffa2cd8f312574ea
components:
  schemas:
    PI_55044:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55044__stammdaten'
      required:
        - stammdaten
    PI_55044__stammdaten:
      type: object
      properties:
        MESSLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_55044__stammdaten__MESSLOKATION'
      required:
        - MESSLOKATION
    PI_55044__stammdaten__MESSLOKATION:
      type: object
      properties:
        messlokationsId:
          $ref: '../../../bo4e/fields/bo/Messlokation/messlokationsId.yaml#/components/schemas/messlokationsId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z17
      required:
        - messlokationsId
