openapi: 3.1.0
info:
  title: PI_21013
  version: '202604'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_21013:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_21013__stammdaten'
      required:
        - stammdaten
    PI_21013__stammdaten:
      type: object
      properties:
        MESSLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_21013__stammdaten__MESSLOKATION'
        STATUSMITTEILUNG:
          type: array
          items:
            $ref: '#/components/schemas/PI_21013__stammdaten__STATUSMITTEILUNG'
      required:
        - MESSLOKATION
        - STATUSMITTEILUNG
    PI_21013__stammdaten__MESSLOKATION:
      type: object
      properties:
        messlokationsId:
          $ref: '../../../bo4e/fields/bo/Messlokation/messlokationsId.yaml#/components/schemas/messlokationsId'
          x-edifact-segment:
            - SG14.CNI.LOC+172
      required:
        - messlokationsId
    PI_21013__stammdaten__STATUSMITTEILUNG:
      type: object
      properties:
        auftragsstatus:
          $ref: '../../../bo4e/fields/bo/Statusmitteilung/auftragsstatus.yaml#/components/schemas/auftragsstatus'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z10
        positionsdaten:
          type: array
          items:
            $ref: '#/components/schemas/PI_21013__stammdaten__STATUSMITTEILUNG__positionsdaten'
      required:
        - auftragsstatus
        - positionsdaten
    PI_21013__stammdaten__STATUSMITTEILUNG__positionsdaten:
      type: object
      properties:
        positionsnummer:
          $ref: '../../../bo4e/fields/com/StatusmitteilungPosition/positionsnummer.yaml#/components/schemas/positionsnummer'
          x-edifact-segment:
            - SG14.CNI
      required:
        - positionsnummer
