openapi: 3.1.0
info:
  title: PI_21027
  version: '202604'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: c7b88c733e93fe4ee423d52cffa2cd8f312574ea
components:
  schemas:
    PI_21027:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_21027__stammdaten'
      required:
        - stammdaten
    PI_21027__stammdaten:
      type: object
      properties:
        MARKTLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_21027__stammdaten__MARKTLOKATION'
        MESSLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_21027__stammdaten__MESSLOKATION'
        NETZLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_21027__stammdaten__NETZLOKATION'
        STATUSMITTEILUNG:
          type: array
          items:
            $ref: '#/components/schemas/PI_21027__stammdaten__STATUSMITTEILUNG'
        STEUERBARE_RESSOURCE:
          type: array
          items:
            $ref: '#/components/schemas/PI_21027__stammdaten__STEUERBARE_RESSOURCE'
      required:
        - MARKTLOKATION
        - MESSLOKATION
        - NETZLOKATION
        - STATUSMITTEILUNG
        - STEUERBARE_RESSOURCE
    PI_21027__stammdaten__MARKTLOKATION:
      type: object
      properties:
        marktlokationsId:
          $ref: '../../../bo4e/fields/bo/Marktlokation/marktlokationsId.yaml#/components/schemas/marktlokationsId'
          x-edifact-segment:
            - SG14.CNI.LOC+172
      required:
        - marktlokationsId
    PI_21027__stammdaten__MESSLOKATION:
      type: object
      properties:
        messlokationsId:
          $ref: '../../../bo4e/fields/bo/Messlokation/messlokationsId.yaml#/components/schemas/messlokationsId'
          x-edifact-segment:
            - SG14.CNI.LOC+172
      required:
        - messlokationsId
    PI_21027__stammdaten__NETZLOKATION:
      type: object
      properties:
        netzlokationsId:
          $ref: '../../../bo4e/fields/bo/Netzlokation/netzlokationsId.yaml#/components/schemas/netzlokationsId'
          x-edifact-segment:
            - SG14.CNI.LOC+172
      required:
        - netzlokationsId
    PI_21027__stammdaten__STATUSMITTEILUNG:
      type: object
      properties:
        auftragsstatus:
          $ref: '../../../bo4e/fields/bo/Statusmitteilung/auftragsstatus.yaml#/components/schemas/auftragsstatus'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z15
        positionsdaten:
          type: array
          items:
            $ref: '#/components/schemas/PI_21027__stammdaten__STATUSMITTEILUNG__positionsdaten'
      required:
        - auftragsstatus
        - positionsdaten
    PI_21027__stammdaten__STATUSMITTEILUNG__positionsdaten:
      type: object
      properties:
        allgemeineInformationen:
          $ref: '#/components/schemas/PI_21027__stammdaten__STATUSMITTEILUNG__positionsdaten__allgemeineInformationen'
        positionsnummer:
          $ref: '../../../bo4e/fields/com/StatusmitteilungPosition/positionsnummer.yaml#/components/schemas/positionsnummer'
          x-edifact-segment:
            - SG14.CNI
      required:
        - allgemeineInformationen
        - positionsnummer
    PI_21027__stammdaten__STATUSMITTEILUNG__positionsdaten__allgemeineInformationen:
      type: object
      properties:
        info1:
          $ref: '../../../bo4e/fields/com/AllgemeineInformationen/info1.yaml#/components/schemas/info1'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z15.SG25.GID.FTX+ACB
        info2:
          $ref: '../../../bo4e/fields/com/AllgemeineInformationen/info2.yaml#/components/schemas/info2'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z15.SG25.GID.FTX+ACB
        info3:
          $ref: '../../../bo4e/fields/com/AllgemeineInformationen/info3.yaml#/components/schemas/info3'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z15.SG25.GID.FTX+ACB
        info4:
          $ref: '../../../bo4e/fields/com/AllgemeineInformationen/info4.yaml#/components/schemas/info4'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z15.SG25.GID.FTX+ACB
        info5:
          $ref: '../../../bo4e/fields/com/AllgemeineInformationen/info5.yaml#/components/schemas/info5'
          x-edifact-segment:
            - SG14.CNI.SG15.STS+Z15.SG25.GID.FTX+ACB
      required:
        - info1
        - info2
        - info3
        - info4
        - info5
    PI_21027__stammdaten__STEUERBARE_RESSOURCE:
      type: object
      properties:
        ressourcenId:
          $ref: '../../../bo4e/fields/bo/SteuerbareRessource/ressourcenId.yaml#/components/schemas/ressourcenId'
          x-edifact-segment:
            - SG14.CNI.LOC+172
      required:
        - ressourcenId
