openapi: 3.1.0
info:
  title: PI_44147
  version: '202604'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: 39ae45d481e5cc3d4d7aae328a23a9751236156a
components:
  schemas:
    PI_44147:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_44147__stammdaten'
      required:
        - stammdaten
    PI_44147__stammdaten:
      type: object
      properties:
        MESSLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_44147__stammdaten__MESSLOKATION'
        NETZNUTZUNGSVERTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_44147__stammdaten__NETZNUTZUNGSVERTRAG'
        ZAEHLER:
          type: array
          items:
            $ref: '#/components/schemas/PI_44147__stammdaten__ZAEHLER'
      required:
        - MESSLOKATION
        - NETZNUTZUNGSVERTRAG
        - ZAEHLER
    PI_44147__stammdaten__MESSLOKATION:
      type: object
      properties:
        messlokationsId:
          $ref: '../../../bo4e/fields/bo/Messlokation/messlokationsId.yaml#/components/schemas/messlokationsId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+172
      required:
        - messlokationsId
    PI_44147__stammdaten__NETZNUTZUNGSVERTRAG:
      type: object
      properties:
        vertragsbeginn:
          $ref: '../../../bo4e/fields/bo/Vertrag/vertragsbeginn.yaml#/components/schemas/vertragsbeginn'
          x-edifact-segment:
            - SG4.IDE+24.DTM+92
      required:
        - vertragsbeginn
    PI_44147__stammdaten__ZAEHLER:
      type: object
      properties:
        geraete:
          type: array
          items:
            $ref: '#/components/schemas/PI_44147__stammdaten__ZAEHLER__geraete'
        messlokationsId:
          $ref: '../../../bo4e/fields/bo/Zaehler/messlokationsId.yaml#/components/schemas/messlokationsId'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z03.RFF+Z19
            - SG4.IDE+24.SG8.SEQ+Z20.RFF+Z19
        messwerterfassung:
          $ref: '../../../bo4e/fields/bo/Zaehler/messwerterfassung.yaml#/components/schemas/messwerterfassung'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z03.SG10.CCI+++E12.CAV
        zaehlergroesse:
          $ref: '../../../bo4e/fields/bo/Zaehler/zaehlergroesse.yaml#/components/schemas/zaehlergroesse'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z03.SG10.CCI+++E13.CAV
        zaehlernummer:
          $ref: '../../../bo4e/fields/bo/Zaehler/zaehlernummer.yaml#/components/schemas/zaehlernummer'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z03.SG10.CCI+++E13.CAV+Z30
            - SG4.IDE+24.SG8.SEQ+Z05.RFF+MG
            - SG4.IDE+24.SG8.SEQ+Z09.RFF+MG
            - 'SG4.IDE+24.SG8.SEQ+Z20.RFF+[MG|Z11]'
        zaehlertyp:
          $ref: '../../../bo4e/fields/bo/Zaehler/zaehlertyp.yaml#/components/schemas/zaehlertyp'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z03.SG10.CCI+++E13.CAV
        zaehlertypspezifikation:
          $ref: '../../../bo4e/fields/bo/Zaehler/zaehlertypspezifikation.yaml#/components/schemas/zaehlertypspezifikation'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z03.SG10.CCI+++E13.CAV
        zaehlwerke:
          type: array
          items:
            $ref: '#/components/schemas/PI_44147__stammdaten__ZAEHLER__zaehlwerke'
      required:
        - geraete
        - messlokationsId
        - messwerterfassung
        - zaehlergroesse
        - zaehlernummer
        - zaehlertyp
        - zaehlertypspezifikation
        - zaehlwerke
    PI_44147__stammdaten__ZAEHLER__geraete:
      type: object
      properties:
        geraeteeigenschaften:
          $ref: '#/components/schemas/PI_44147__stammdaten__ZAEHLER__geraete__geraeteeigenschaften'
        geraetenummer:
          $ref: '../../../bo4e/fields/com/Geraet/geraetenummer.yaml#/components/schemas/geraetenummer'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z05.SG10.CCI+++Z26.CAV+Z30
            - SG4.IDE+24.SG8.SEQ+Z09.SG10.CCI+++Z64.CAV+Z30
            - SG4.IDE+24.SG8.SEQ+Z13.SG10.CCI+++Z75.CAV+Z30
            - SG4.IDE+24.SG8.SEQ+Z50.SG10.CCI+++E13.CAV+Z30
      required:
        - geraeteeigenschaften
        - geraetenummer
    PI_44147__stammdaten__ZAEHLER__geraete__geraeteeigenschaften:
      type: object
      properties:
        geraetemerkmal:
          $ref: '../../../bo4e/fields/com/Geraeteeigenschaften/geraetemerkmal.yaml#/components/schemas/geraetemerkmal'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z05.SG10.CCI+++Z26.CAV
            - SG4.IDE+24.SG8.SEQ+Z09.SG10.CCI+++Z64.CAV
      required:
        - geraetemerkmal
    PI_44147__stammdaten__ZAEHLER__zaehlwerke:
      type: object
      properties:
        bezeichnung:
          $ref: '../../../bo4e/fields/com/Zaehlwerk/bezeichnung.yaml#/components/schemas/bezeichnung'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z20.SG10.CCI+++Z63
        nachkommastelle:
          $ref: '../../../bo4e/fields/com/Zaehlwerk/nachkommastelle.yaml#/components/schemas/nachkommastelle'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z20.SG10.CCI+11++Z33.CAV
        obisKennzahl:
          $ref: '../../../bo4e/fields/com/Zaehlwerk/obisKennzahl.yaml#/components/schemas/obisKennzahl'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z20.PIA+5
        vorkommastelle:
          $ref: '../../../bo4e/fields/com/Zaehlwerk/vorkommastelle.yaml#/components/schemas/vorkommastelle'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z20.SG10.CCI+11++Z33.CAV
        wertegranularitaet:
          $ref: '../../../bo4e/fields/com/Zaehlwerk/wertegranularitaet.yaml#/components/schemas/wertegranularitaet'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z20.SG10.CCI+++ZE4.CAV
      required:
        - bezeichnung
        - nachkommastelle
        - obisKennzahl
        - vorkommastelle
        - wertegranularitaet
