openapi: 3.1.0
info:
  title: PI_44176
  version: '202604'
  x-bo4e-schema-version: 1.6.8
  x-bo4e-schema-sha: b84d59c01638e348fe912e388cf7b7a25ab9937f
  x-templater-sha: ce089a840512efbac03c3b3e949ad6e8b7215947
components:
  schemas:
    PI_44176:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_44176__stammdaten'
      required:
        - stammdaten
    PI_44176__stammdaten:
      type: object
      properties:
        MARKTLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_44176__stammdaten__MARKTLOKATION'
        MESSLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_44176__stammdaten__MESSLOKATION'
        NETZNUTZUNGSVERTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_44176__stammdaten__NETZNUTZUNGSVERTRAG'
      required:
        - MARKTLOKATION
        - MESSLOKATION
        - NETZNUTZUNGSVERTRAG
    PI_44176__stammdaten__MARKTLOKATION:
      type: object
      properties:
        marktlokationsId:
          $ref: '../../../bo4e/fields/bo/Marktlokation/marktlokationsId.yaml#/components/schemas/marktlokationsId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+172
      required:
        - marktlokationsId
    PI_44176__stammdaten__MESSLOKATION:
      type: object
      properties:
        messlokationsId:
          $ref: '../../../bo4e/fields/bo/Messlokation/messlokationsId.yaml#/components/schemas/messlokationsId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+172
      required:
        - messlokationsId
    PI_44176__stammdaten__NETZNUTZUNGSVERTRAG:
      type: object
      properties:
        vertragsbeginn:
          $ref: '../../../bo4e/fields/bo/Vertrag/vertragsbeginn.yaml#/components/schemas/vertragsbeginn'
          x-edifact-segment:
            - SG4.IDE+24.DTM+92
      required:
        - vertragsbeginn
