openapi: 3.1.0
info:
  title: PI_23001
  version: '202510'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_23001:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_23001__masterData'
      required:
      - masterData
    PI_23001__masterData:
      type: object
      properties:
        STATUS_NOTIFICATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_23001__masterData__STATUS_NOTIFICATION'
      required:
      - STATUS_NOTIFICATION
    PI_23001__masterData__STATUS_NOTIFICATION:
      type: object
      properties:
        positionData:
          type: array
          items:
            $ref: '#/components/schemas/PI_23001__masterData__STATUS_NOTIFICATION__positionData'
      required:
      - positionData
    PI_23001__masterData__STATUS_NOTIFICATION__positionData:
      type: object
      properties:
        orderStatus:
          $ref: ../../../bo4e-en/fields/com/StatusNotificationPosition/orderStatus.yaml#/components/schemas/orderStatus
          x-edifact-segment:
          - SG3.DOC+21.SG7.LIN.STS+Z06
        justification:
          $ref: '#/components/schemas/PI_23001__masterData__STATUS_NOTIFICATION__positionData__justification'
        locationId:
          $ref: ../../../bo4e-en/fields/com/StatusNotificationPosition/locationId.yaml#/components/schemas/locationId
          x-edifact-segment:
          - SG3.DOC+21.SG7.LIN.SG8.NAD+DP.LOC+172
        positionNumber:
          $ref: ../../../bo4e-en/fields/com/StatusNotificationPosition/positionNumber.yaml#/components/schemas/positionNumber
          x-edifact-segment:
          - SG3.DOC+21.SG7.LIN
        usageFrom:
          $ref: ../../../bo4e-en/fields/com/StatusNotificationPosition/usageFrom.yaml#/components/schemas/usageFrom
          x-edifact-segment:
          - SG3.DOC+21.SG7.LIN.DTM+163
      required:
      - orderStatus
      - locationId
      - positionNumber
    PI_23001__masterData__STATUS_NOTIFICATION__positionData__justification:
      type: object
      properties:
        justification1:
          $ref: ../../../bo4e-en/fields/com/Justification/justification1.yaml#/components/schemas/justification1
          x-edifact-segment:
          - SG3.DOC+21.SG7.LIN.FTX+ACD
        justification2:
          $ref: ../../../bo4e-en/fields/com/Justification/justification2.yaml#/components/schemas/justification2
          x-edifact-segment:
          - SG3.DOC+21.SG7.LIN.FTX+ACD
        justification3:
          $ref: ../../../bo4e-en/fields/com/Justification/justification3.yaml#/components/schemas/justification3
          x-edifact-segment:
          - SG3.DOC+21.SG7.LIN.FTX+ACD
        justification4:
          $ref: ../../../bo4e-en/fields/com/Justification/justification4.yaml#/components/schemas/justification4
          x-edifact-segment:
          - SG3.DOC+21.SG7.LIN.FTX+ACD
        justification5:
          $ref: ../../../bo4e-en/fields/com/Justification/justification5.yaml#/components/schemas/justification5
          x-edifact-segment:
          - SG3.DOC+21.SG7.LIN.FTX+ACD
