openapi: 3.1.0
info:
  title: PI_31004
  version: '202510'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_31004:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_31004__masterData'
        transactionData:
          $ref: '#/components/schemas/PI_31004__transactionData'
      required:
      - masterData
      - transactionData
    PI_31004__masterData:
      type: object
      properties:
        MARKET_LOCATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_31004__masterData__MARKET_LOCATION'
        METERING_LOCATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_31004__masterData__METERING_LOCATION'
        GRID_LOCATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_31004__masterData__GRID_LOCATION'
        INVOICE:
          type: array
          items:
            $ref: '#/components/schemas/PI_31004__masterData__INVOICE'
        CONTROLLABLE_RESOURCE:
          type: array
          items:
            $ref: '#/components/schemas/PI_31004__masterData__CONTROLLABLE_RESOURCE'
        TECHNICAL_RESOURCE:
          type: array
          items:
            $ref: '#/components/schemas/PI_31004__masterData__TECHNICAL_RESOURCE'
      required:
      - MARKET_LOCATION
      - METERING_LOCATION
      - GRID_LOCATION
      - INVOICE
      - CONTROLLABLE_RESOURCE
      - TECHNICAL_RESOURCE
    PI_31004__masterData__MARKET_LOCATION:
      type: object
      properties:
        locationAddress:
          $ref: ../../../bo4e-en/fields/bo/MarketLocation/locationAddress.yaml#/components/schemas/locationAddress
          x-edifact-segment:
          - SG2.NAD+DP
        marketLocationId:
          $ref: ../../../bo4e-en/fields/bo/MarketLocation/marketLocationId.yaml#/components/schemas/marketLocationId
          x-edifact-segment:
          - SG2.NAD+DP.LOC+172
      required:
      - locationAddress
      - marketLocationId
    PI_31004__masterData__METERING_LOCATION:
      type: object
      properties:
        meteringLocationId:
          $ref: ../../../bo4e-en/fields/bo/MeteringLocation/meteringLocationId.yaml#/components/schemas/meteringLocationId
          x-edifact-segment:
          - SG2.NAD+DP.LOC+172
      required:
      - meteringLocationId
    PI_31004__masterData__GRID_LOCATION:
      type: object
      properties:
        gridLocationId:
          $ref: ../../../bo4e-en/fields/bo/GridLocation/gridLocationId.yaml#/components/schemas/gridLocationId
          x-edifact-segment:
          - SG2.NAD+DP.LOC+172
      required:
      - gridLocationId
    PI_31004__masterData__INVOICE:
      type: object
      properties:
        executionDate:
          $ref: ../../../bo4e-en/fields/bo/Invoice/executionDate.yaml#/components/schemas/executionDate
          x-edifact-segment:
          - DTM+203
        processingDate:
          $ref: ../../../bo4e-en/fields/bo/Invoice/processingDate.yaml#/components/schemas/processingDate
          x-edifact-segment:
          - DTM+9
        dueDate:
          $ref: ../../../bo4e-en/fields/bo/Invoice/dueDate.yaml#/components/schemas/dueDate
          x-edifact-segment:
          - SG8.PYT.DTM+265
        municipalDiscount:
          $ref: '#/components/schemas/PI_31004__masterData__INVOICE__municipalDiscount'
        totalGrossAmount:
          $ref: '#/components/schemas/PI_31004__masterData__INVOICE__totalGrossAmount'
        isReverseCharge:
          $ref: ../../../bo4e-en/fields/bo/Invoice/isReverseCharge.yaml#/components/schemas/isReverseCharge
          x-edifact-segment:
          - FTX+REG++RCH
        isSelfIssued:
          $ref: ../../../bo4e-en/fields/bo/Invoice/isSelfIssued.yaml#/components/schemas/isSelfIssued
          x-edifact-segment:
          - BGM+[457|Z25]
        gridAccount:
          $ref: ../../../bo4e-en/fields/bo/Invoice/gridAccount.yaml#/components/schemas/gridAccount
          x-edifact-segment:
          - SG2.NAD+ZSH
        originalInvoiceNumber:
          $ref: ../../../bo4e-en/fields/bo/Invoice/originalInvoiceNumber.yaml#/components/schemas/originalInvoiceNumber
          x-edifact-segment:
          - SG1.RFF+OI
        invoiceDate:
          $ref: ../../../bo4e-en/fields/bo/Invoice/invoiceDate.yaml#/components/schemas/invoiceDate
          x-edifact-segment:
          - DTM+137
        invoicePeriod:
          $ref: '#/components/schemas/PI_31004__masterData__INVOICE__invoicePeriod'
        invoiceStatus:
          $ref: ../../../bo4e-en/fields/bo/Invoice/invoiceStatus.yaml#/components/schemas/invoiceStatus
          x-edifact-segment:
          - BGM+[457|Z25]
        invoiceType:
          $ref: ../../../bo4e-en/fields/bo/Invoice/invoiceType.yaml#/components/schemas/invoiceType
          x-edifact-segment:
          - IMD
        referenceMessageDate:
          $ref: ../../../bo4e-en/fields/bo/Invoice/referenceMessageDate.yaml#/components/schemas/referenceMessageDate
          x-edifact-segment:
          - SG1.RFF+OI.DTM+171
        taxAmounts:
          type: array
          items:
            $ref: '#/components/schemas/PI_31004__masterData__INVOICE__taxAmounts'
        prepaid:
          $ref: '#/components/schemas/PI_31004__masterData__INVOICE__prepaid'
        provisionalBillingPeriod:
          $ref: '#/components/schemas/PI_31004__masterData__INVOICE__provisionalBillingPeriod'
        toPay:
          $ref: '#/components/schemas/PI_31004__masterData__INVOICE__toPay'
      required:
      - processingDate
      - dueDate
      - municipalDiscount
      - totalGrossAmount
      - isSelfIssued
      - gridAccount
      - originalInvoiceNumber
      - invoiceDate
      - invoiceStatus
      - invoiceType
      - referenceMessageDate
      - taxAmounts
      - toPay
    PI_31004__masterData__INVOICE__municipalDiscount:
      type: object
      properties:
        value:
          $ref: ../../../bo4e-en/fields/com/MunicipalDiscount/value.yaml#/components/schemas/value
          x-edifact-segment:
          - SG50.MOA+Z01
      required:
      - value
    PI_31004__masterData__INVOICE__totalGrossAmount:
      type: object
      properties:
        value:
          $ref: ../../../bo4e-en/fields/com/Amount/value.yaml#/components/schemas/value
          x-edifact-segment:
          - SG50.MOA+77
      required:
      - value
    PI_31004__masterData__INVOICE__invoicePeriod:
      type: object
      properties:
        endDate:
          $ref: ../../../bo4e-en/fields/com/TimePeriod/endDate.yaml#/components/schemas/endDate
          x-edifact-segment:
          - DTM+156
        startDate:
          $ref: ../../../bo4e-en/fields/com/TimePeriod/startDate.yaml#/components/schemas/startDate
          x-edifact-segment:
          - DTM+155
    PI_31004__masterData__INVOICE__taxAmounts:
      type: object
      properties:
        baseValue:
          $ref: ../../../bo4e-en/fields/com/TaxAmount/baseValue.yaml#/components/schemas/baseValue
          x-edifact-segment:
          - SG52.TAX+7+VAT.MOA+125
        baseValuePrepaid:
          $ref: ../../../bo4e-en/fields/com/TaxAmount/baseValuePrepaid.yaml#/components/schemas/baseValuePrepaid
          x-edifact-segment:
          - SG52.TAX+7+VAT.MOA+113
        taxCode:
          $ref: ../../../bo4e-en/fields/com/TaxAmount/taxCode.yaml#/components/schemas/taxCode
          x-edifact-segment:
          - SG52.TAX+7+VAT
        taxValue:
          $ref: ../../../bo4e-en/fields/com/TaxAmount/taxValue.yaml#/components/schemas/taxValue
          x-edifact-segment:
          - SG52.TAX+7+VAT.MOA+161
        taxValuePrepaid:
          $ref: ../../../bo4e-en/fields/com/TaxAmount/taxValuePrepaid.yaml#/components/schemas/taxValuePrepaid
          x-edifact-segment:
          - SG52.TAX+7+VAT.MOA+115
      required:
      - baseValue
      - taxCode
      - taxValue
    PI_31004__masterData__INVOICE__prepaid:
      type: object
      properties:
        value:
          $ref: ../../../bo4e-en/fields/com/Amount/value.yaml#/components/schemas/value
          x-edifact-segment:
          - SG50.MOA+113
    PI_31004__masterData__INVOICE__provisionalBillingPeriod:
      type: object
      properties:
        endDate:
          $ref: ../../../bo4e-en/fields/com/TimePeriod/endDate.yaml#/components/schemas/endDate
          x-edifact-segment:
          - DTM+Z43
        startDate:
          $ref: ../../../bo4e-en/fields/com/TimePeriod/startDate.yaml#/components/schemas/startDate
          x-edifact-segment:
          - DTM+Z42
    PI_31004__masterData__INVOICE__toPay:
      type: object
      properties:
        value:
          $ref: ../../../bo4e-en/fields/com/Amount/value.yaml#/components/schemas/value
          x-edifact-segment:
          - SG50.MOA+9
      required:
      - value
    PI_31004__masterData__CONTROLLABLE_RESOURCE:
      type: object
      properties:
        resourceId:
          $ref: ../../../bo4e-en/fields/bo/ControllableResource/resourceId.yaml#/components/schemas/resourceId
          x-edifact-segment:
          - SG2.NAD+DP.LOC+172
      required:
      - resourceId
    PI_31004__masterData__TECHNICAL_RESOURCE:
      type: object
      properties:
        resourceId:
          $ref: ../../../bo4e-en/fields/bo/TechnicalResource/resourceId.yaml#/components/schemas/resourceId
          x-edifact-segment:
          - SG2.NAD+DP.LOC+172
      required:
      - resourceId
    PI_31004__transactionData:
      type: object
      properties:
        sender:
          $ref: '#/components/schemas/PI_31004__transactionData__sender'
        documentNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/documentNumber.yaml#/components/schemas/documentNumber
          x-edifact-segment:
          - BGM+[457|Z25]
        receiver:
          $ref: '#/components/schemas/PI_31004__transactionData__receiver'
        messageReferenceNumber:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/messageReferenceNumber.yaml#/components/schemas/messageReferenceNumber
          x-edifact-segment:
          - UNH
        verificationIdentifier:
          $ref: ../../../bo4e-en/fields/cdoc/TransactionData/verificationIdentifier.yaml#/components/schemas/verificationIdentifier
          x-edifact-segment:
          - SG1.RFF+Z13
      required:
      - sender
      - documentNumber
      - receiver
      - messageReferenceNumber
      - verificationIdentifier
    PI_31004__transactionData__sender:
      type: object
      properties:
        contactPerson:
          $ref: '#/components/schemas/PI_31004__transactionData__sender__contactPerson'
        name1:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/name1.yaml#/components/schemas/name1
          x-edifact-segment:
          - SG2.NAD+MS
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG2.NAD+MS
        roleCodeType:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeType.yaml#/components/schemas/roleCodeType
          x-edifact-segment:
          - SG2.NAD+MS
        taxNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/taxNumber.yaml#/components/schemas/taxNumber
          x-edifact-segment:
          - SG2.NAD+MS.SG3.RFF
        vatId:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/vatId.yaml#/components/schemas/vatId
          x-edifact-segment:
          - SG2.NAD+MS.SG3.RFF
      required:
      - contactPerson
      - name1
      - roleCodeNumber
      - roleCodeType
      - taxNumber
      - vatId
    PI_31004__transactionData__sender__contactPerson:
      type: object
      properties:
        lastName:
          $ref: ../../../bo4e-en/fields/bo/ContactPerson/lastName.yaml#/components/schemas/lastName
          x-edifact-segment:
          - SG2.NAD+MS.SG5.CTA+IC
      required:
      - lastName
    PI_31004__transactionData__receiver:
      type: object
      properties:
        name1:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/name1.yaml#/components/schemas/name1
          x-edifact-segment:
          - SG2.NAD+MR
        roleCodeNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
          x-edifact-segment:
          - SG2.NAD+MR
        roleCodeType:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/roleCodeType.yaml#/components/schemas/roleCodeType
          x-edifact-segment:
          - SG2.NAD+MR
        taxNumber:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/taxNumber.yaml#/components/schemas/taxNumber
          x-edifact-segment:
          - SG2.NAD+MR.SG3.RFF
        vatId:
          $ref: ../../../bo4e-en/fields/bo/MarketParticipant/vatId.yaml#/components/schemas/vatId
          x-edifact-segment:
          - SG2.NAD+MR.SG3.RFF
      required:
      - name1
      - roleCodeNumber
      - roleCodeType
      - taxNumber
      - vatId
