openapi: 3.1.0
info:
  title: PI_17135
  version: '202604'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: c7b88c733e93fe4ee423d52cffa2cd8f312574ea
components:
  schemas:
    PI_17135:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_17135__stammdaten'
        transaktionsdaten:
          $ref: '#/components/schemas/PI_17135__transaktionsdaten'
      required:
        - stammdaten
        - transaktionsdaten
    PI_17135__stammdaten:
      type: object
      properties:
        ANFRAGE:
          type: array
          items:
            $ref: '#/components/schemas/PI_17135__stammdaten__ANFRAGE'
        AUFTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_17135__stammdaten__AUFTRAG'
        MARKTLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_17135__stammdaten__MARKTLOKATION'
        MESSLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_17135__stammdaten__MESSLOKATION'
        TRANCHE:
          type: array
          items:
            $ref: '#/components/schemas/PI_17135__stammdaten__TRANCHE'
      required:
        - ANFRAGE
        - AUFTRAG
        - MARKTLOKATION
        - MESSLOKATION
        - TRANCHE
    PI_17135__stammdaten__ANFRAGE:
      type: object
      properties:
        anfragetyp:
          $ref: '../../../bo4e/fields/bo/Anfrage/anfragetyp.yaml#/components/schemas/anfragetyp'
          x-edifact-segment:
            - 'IMD++[Z66|Z67]'
        lokationsId:
          $ref: '../../../bo4e/fields/bo/Anfrage/lokationsId.yaml#/components/schemas/lokationsId'
          x-edifact-segment:
            - SG2.NAD+DP.LOC+172
      required:
        - lokationsId
    PI_17135__stammdaten__AUFTRAG:
      type: object
      properties:
        ausfuehrungsdatum:
          $ref: '../../../bo4e/fields/bo/Auftrag/ausfuehrungsdatum.yaml#/components/schemas/ausfuehrungsdatum'
          x-edifact-segment:
            - DTM+203
        positionsdaten:
          type: array
          items:
            $ref: '#/components/schemas/PI_17135__stammdaten__AUFTRAG__positionsdaten'
      required:
        - ausfuehrungsdatum
        - positionsdaten
    PI_17135__stammdaten__AUFTRAG__positionsdaten:
      type: object
      properties:
        positionsnummer:
          $ref: '../../../bo4e/fields/com/AuftragPosition/positionsnummer.yaml#/components/schemas/positionsnummer'
          x-edifact-segment:
            - SG29.LIN++Z19
      required:
        - positionsnummer
    PI_17135__stammdaten__MARKTLOKATION:
      type: object
      properties:
        marktlokationsId:
          $ref: '../../../bo4e/fields/bo/Marktlokation/marktlokationsId.yaml#/components/schemas/marktlokationsId'
          x-edifact-segment:
            - SG2.NAD+DEB.SG3.RFF+Z59
            - SG2.NAD+DP.SG3.RFF+Z18
            - SG2.NAD+DP.SG3.RFF+Z59
            - SG2.NAD+SU.SG3.RFF+Z18
            - SG2.NAD+SU.SG3.RFF+Z59
        marktrollen:
          type: array
          items:
            $ref: '#/components/schemas/PI_17135__stammdaten__MARKTLOKATION__marktrollen'
      required:
        - marktlokationsId
        - marktrollen
    PI_17135__stammdaten__MARKTLOKATION__marktrollen:
      type: object
      properties:
        marktrolle:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/marktrolle.yaml#/components/schemas/marktrolle'
          x-edifact-segment:
            - SG2.NAD+DEB
            - SG2.NAD+SU
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+DEB
            - SG2.NAD+SU
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+DEB
            - SG2.NAD+SU
        weiterverpflichtet:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/weiterverpflichtet.yaml#/components/schemas/weiterverpflichtet'
          x-edifact-segment:
            - SG2.NAD+DEB
            - SG2.NAD+SU
      required:
        - marktrolle
        - rollencodenummer
        - rollencodetyp
        - weiterverpflichtet
    PI_17135__stammdaten__MESSLOKATION:
      type: object
      properties:
        zaehlwerke:
          type: array
          items:
            $ref: '#/components/schemas/PI_17135__stammdaten__MESSLOKATION__zaehlwerke'
      required:
        - zaehlwerke
    PI_17135__stammdaten__MESSLOKATION__zaehlwerke:
      type: object
      properties:
        messprodukt:
          $ref: '../../../bo4e/fields/com/Zaehlwerk/messprodukt.yaml#/components/schemas/messprodukt'
          x-edifact-segment:
            - SG29.LIN++Z19.PIA+5
        zaehlzeiten:
          $ref: '#/components/schemas/PI_17135__stammdaten__MESSLOKATION__zaehlwerke__zaehlzeiten'
      required:
        - messprodukt
        - zaehlzeiten
    PI_17135__stammdaten__MESSLOKATION__zaehlwerke__zaehlzeiten:
      type: object
      properties:
        zaehlzeitDefinition:
          $ref: '../../../bo4e/fields/com/Zaehlzeitregister/zaehlzeitDefinition.yaml#/components/schemas/zaehlzeitDefinition'
          x-edifact-segment:
            - 'SG29.LIN++Z19.SG30.CCI+[Z39|Z41]'
      required:
        - zaehlzeitDefinition
    PI_17135__stammdaten__TRANCHE:
      type: object
      properties:
        marktrollen:
          type: array
          items:
            $ref: '#/components/schemas/PI_17135__stammdaten__TRANCHE__marktrollen'
        tranchenId:
          $ref: '../../../bo4e/fields/bo/Tranche/tranchenId.yaml#/components/schemas/tranchenId'
          x-edifact-segment:
            - SG2.NAD+DP.SG3.RFF+Z20
            - SG2.NAD+SU.SG3.RFF+Z20
      required:
        - marktrollen
        - tranchenId
    PI_17135__stammdaten__TRANCHE__marktrollen:
      type: object
      properties:
        marktrolle:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/marktrolle.yaml#/components/schemas/marktrolle'
          x-edifact-segment:
            - SG2.NAD+SU
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+SU
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+SU
      required:
        - marktrolle
        - rollencodenummer
        - rollencodetyp
    PI_17135__transaktionsdaten:
      type: object
      properties:
        absender:
          $ref: '#/components/schemas/PI_17135__transaktionsdaten__absender'
        beteiligterMarktpartner:
          $ref: '#/components/schemas/PI_17135__transaktionsdaten__beteiligterMarktpartner'
        dokumentennummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/dokumentennummer.yaml#/components/schemas/dokumentennummer'
          x-edifact-segment:
            - BGM+Z92
        empfaenger:
          $ref: '#/components/schemas/PI_17135__transaktionsdaten__empfaenger'
        nachrichtendatum:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtendatum.yaml#/components/schemas/nachrichtendatum'
          x-edifact-segment:
            - DTM+137
        nachrichtenreferenznummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtenreferenznummer.yaml#/components/schemas/nachrichtenreferenznummer'
          x-edifact-segment:
            - UNH
        pruefidentifikator:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/pruefidentifikator.yaml#/components/schemas/pruefidentifikator'
          x-edifact-segment:
            - SG1.RFF+Z13
      required:
        - absender
        - beteiligterMarktpartner
        - dokumentennummer
        - empfaenger
        - nachrichtendatum
        - nachrichtenreferenznummer
        - pruefidentifikator
    PI_17135__transaktionsdaten__absender:
      type: object
      properties:
        ansprechpartner:
          $ref: '#/components/schemas/PI_17135__transaktionsdaten__absender__ansprechpartner'
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+MS
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+MS
      required:
        - ansprechpartner
        - rollencodenummer
        - rollencodetyp
    PI_17135__transaktionsdaten__absender__ansprechpartner:
      type: object
      properties:
        eMailAdresse:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/eMailAdresse.yaml#/components/schemas/eMailAdresse'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG5.CTA+IC.COM+[EM|FX|TE|AJ|AL]'
        nachname:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/nachname.yaml#/components/schemas/nachname'
          x-edifact-segment:
            - SG2.NAD+MS.SG5.CTA+IC
        rufnummern:
          type: array
          items:
            $ref: '#/components/schemas/PI_17135__transaktionsdaten__absender__ansprechpartner__rufnummern'
      required:
        - eMailAdresse
        - nachname
        - rufnummern
    PI_17135__transaktionsdaten__absender__ansprechpartner__rufnummern:
      type: object
      properties:
        nummerntyp:
          $ref: '../../../bo4e/fields/com/Rufnummer/nummerntyp.yaml#/components/schemas/nummerntyp'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG5.CTA+IC.COM+[EM|FX|TE|AJ|AL]'
        rufnummer:
          $ref: '../../../bo4e/fields/com/Rufnummer/rufnummer.yaml#/components/schemas/rufnummer'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG5.CTA+IC.COM+[EM|FX|TE|AJ|AL]'
      required:
        - nummerntyp
        - rufnummer
    PI_17135__transaktionsdaten__beteiligterMarktpartner:
      type: object
      properties:
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+VY
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+VY
      required:
        - rollencodenummer
        - rollencodetyp
    PI_17135__transaktionsdaten__empfaenger:
      type: object
      properties:
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+MR
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+MR
      required:
        - rollencodenummer
        - rollencodetyp
