openapi: 3.1.0
info:
  title: PI_19301
  version: '202510'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_19301:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_19301__masterData'
      required:
      - masterData
    PI_19301__masterData:
      type: object
      properties:
        REQUEST:
          type: array
          items:
            $ref: '#/components/schemas/PI_19301__masterData__REQUEST'
      required:
      - REQUEST
    PI_19301__masterData__REQUEST:
      type: object
      properties:
        subscription:
          $ref: ../../../bo4e-en/fields/bo/Request/subscription.yaml#/components/schemas/subscription
          x-edifact-segment:
          - IMD++[Z01|Z02]
        requestCategory:
          $ref: ../../../bo4e-en/fields/bo/Request/requestCategory.yaml#/components/schemas/requestCategory
          x-edifact-segment:
          - BGM+[7|Z14]
        requestType:
          $ref: ../../../bo4e-en/fields/bo/Request/requestType.yaml#/components/schemas/requestType
          x-edifact-segment:
          - IMD++[Z11|Z12]
      required:
      - subscription
      - requestCategory
