openapi: 3.1.0
info:
  title: PI_19009
  version: '202510'
  x-bo4e-schema-version: 1.7.8
  x-bo4e-schema-sha: a4f202d62930c69acd327622abf92da121d3a12e
  x-templater-sha: 41b3eb8c66d69f8953cbfe2ce874d41618f10ca0
components:
  schemas:
    PI_19009:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_19009__masterData'
      required:
      - masterData
    PI_19009__masterData:
      type: object
      properties:
        REQUEST:
          type: array
          items:
            $ref: '#/components/schemas/PI_19009__masterData__REQUEST'
        ORDER:
          type: array
          items:
            $ref: '#/components/schemas/PI_19009__masterData__ORDER'
      required:
      - REQUEST
      - ORDER
    PI_19009__masterData__REQUEST:
      type: object
      properties:
        subscription:
          $ref: ../../../bo4e-en/fields/bo/Request/subscription.yaml#/components/schemas/subscription
          x-edifact-segment:
          - IMD++Z02
        requestCategory:
          $ref: ../../../bo4e-en/fields/bo/Request/requestCategory.yaml#/components/schemas/requestCategory
          x-edifact-segment:
          - BGM+Z29
      required:
      - subscription
      - requestCategory
    PI_19009__masterData__ORDER:
      type: object
      properties:
        executionDate:
          $ref: ../../../bo4e-en/fields/bo/Order/executionDate.yaml#/components/schemas/executionDate
          x-edifact-segment:
          - DTM+203
      required:
      - executionDate
