openapi: 3.1.0
info:
  title: PI_31004
  version: '202510'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_31004:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_31004__stammdaten'
        transaktionsdaten:
          $ref: '#/components/schemas/PI_31004__transaktionsdaten'
      required:
        - stammdaten
        - transaktionsdaten
    PI_31004__stammdaten:
      type: object
      properties:
        MARKTLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_31004__stammdaten__MARKTLOKATION'
        MESSLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_31004__stammdaten__MESSLOKATION'
        NETZLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_31004__stammdaten__NETZLOKATION'
        RECHNUNG:
          type: array
          items:
            $ref: '#/components/schemas/PI_31004__stammdaten__RECHNUNG'
        STEUERBARE_RESSOURCE:
          type: array
          items:
            $ref: '#/components/schemas/PI_31004__stammdaten__STEUERBARE_RESSOURCE'
        TECHNISCHE_RESSOURCE:
          type: array
          items:
            $ref: '#/components/schemas/PI_31004__stammdaten__TECHNISCHE_RESSOURCE'
      required:
        - MARKTLOKATION
        - MESSLOKATION
        - NETZLOKATION
        - RECHNUNG
        - STEUERBARE_RESSOURCE
        - TECHNISCHE_RESSOURCE
    PI_31004__stammdaten__MARKTLOKATION:
      type: object
      properties:
        lokationsadresse:
          $ref: '../../../bo4e/fields/bo/Marktlokation/lokationsadresse.yaml#/components/schemas/lokationsadresse'
          x-edifact-segment:
            - SG2.NAD+DP
        marktlokationsId:
          $ref: '../../../bo4e/fields/bo/Marktlokation/marktlokationsId.yaml#/components/schemas/marktlokationsId'
          x-edifact-segment:
            - SG2.NAD+DP.LOC+172
      required:
        - lokationsadresse
        - marktlokationsId
    PI_31004__stammdaten__MESSLOKATION:
      type: object
      properties:
        messlokationsId:
          $ref: '../../../bo4e/fields/bo/Messlokation/messlokationsId.yaml#/components/schemas/messlokationsId'
          x-edifact-segment:
            - SG2.NAD+DP.LOC+172
      required:
        - messlokationsId
    PI_31004__stammdaten__NETZLOKATION:
      type: object
      properties:
        netzlokationsId:
          $ref: '../../../bo4e/fields/bo/Netzlokation/netzlokationsId.yaml#/components/schemas/netzlokationsId'
          x-edifact-segment:
            - SG2.NAD+DP.LOC+172
      required:
        - netzlokationsId
    PI_31004__stammdaten__RECHNUNG:
      type: object
      properties:
        ausfuehrungsdatum:
          $ref: '../../../bo4e/fields/bo/Rechnung/ausfuehrungsdatum.yaml#/components/schemas/ausfuehrungsdatum'
          x-edifact-segment:
            - DTM+203
        bearbeitungsdatum:
          $ref: '../../../bo4e/fields/bo/Rechnung/bearbeitungsdatum.yaml#/components/schemas/bearbeitungsdatum'
          x-edifact-segment:
            - DTM+9
        faelligkeitsdatum:
          $ref: '../../../bo4e/fields/bo/Rechnung/faelligkeitsdatum.yaml#/components/schemas/faelligkeitsdatum'
          x-edifact-segment:
            - SG8.PYT.DTM+265
        gemeinderabatt:
          $ref: '#/components/schemas/PI_31004__stammdaten__RECHNUNG__gemeinderabatt'
        gesamtbrutto:
          $ref: '#/components/schemas/PI_31004__stammdaten__RECHNUNG__gesamtbrutto'
        istReverseCharge:
          $ref: '../../../bo4e/fields/bo/Rechnung/istReverseCharge.yaml#/components/schemas/istReverseCharge'
          x-edifact-segment:
            - FTX+REG++RCH
        istSelbstausgestellt:
          $ref: '../../../bo4e/fields/bo/Rechnung/istSelbstausgestellt.yaml#/components/schemas/istSelbstausgestellt'
          x-edifact-segment:
            - 'BGM+[457|Z25]'
        netzkonto:
          $ref: '../../../bo4e/fields/bo/Rechnung/netzkonto.yaml#/components/schemas/netzkonto'
          x-edifact-segment:
            - SG2.NAD+ZSH
        originalRechnungsnummer:
          $ref: '../../../bo4e/fields/bo/Rechnung/originalRechnungsnummer.yaml#/components/schemas/originalRechnungsnummer'
          x-edifact-segment:
            - SG1.RFF+OI
        rechnungsdatum:
          $ref: '../../../bo4e/fields/bo/Rechnung/rechnungsdatum.yaml#/components/schemas/rechnungsdatum'
          x-edifact-segment:
            - DTM+137
        rechnungsperiode:
          $ref: '#/components/schemas/PI_31004__stammdaten__RECHNUNG__rechnungsperiode'
        rechnungsstatus:
          $ref: '../../../bo4e/fields/bo/Rechnung/rechnungsstatus.yaml#/components/schemas/rechnungsstatus'
          x-edifact-segment:
            - 'BGM+[457|Z25]'
        rechnungstyp:
          $ref: '../../../bo4e/fields/bo/Rechnung/rechnungstyp.yaml#/components/schemas/rechnungstyp'
          x-edifact-segment:
            - IMD
        referenzNachrichtendatum:
          $ref: '../../../bo4e/fields/bo/Rechnung/referenzNachrichtendatum.yaml#/components/schemas/referenzNachrichtendatum'
          x-edifact-segment:
            - SG1.RFF+OI.DTM+171
        steuerbetraege:
          type: array
          items:
            $ref: '#/components/schemas/PI_31004__stammdaten__RECHNUNG__steuerbetraege'
        vorausgezahlt:
          $ref: '#/components/schemas/PI_31004__stammdaten__RECHNUNG__vorausgezahlt'
        vorlaeufigerAbrechnungszeitraum:
          $ref: '#/components/schemas/PI_31004__stammdaten__RECHNUNG__vorlaeufigerAbrechnungszeitraum'
        zuZahlen:
          $ref: '#/components/schemas/PI_31004__stammdaten__RECHNUNG__zuZahlen'
      required:
        - bearbeitungsdatum
        - faelligkeitsdatum
        - gemeinderabatt
        - gesamtbrutto
        - istSelbstausgestellt
        - netzkonto
        - originalRechnungsnummer
        - rechnungsdatum
        - rechnungsstatus
        - rechnungstyp
        - referenzNachrichtendatum
        - steuerbetraege
        - zuZahlen
    PI_31004__stammdaten__RECHNUNG__gemeinderabatt:
      type: object
      properties:
        wert:
          $ref: '../../../bo4e/fields/com/Gemeinderabatt/wert.yaml#/components/schemas/wert'
          x-edifact-segment:
            - SG50.MOA+Z01
      required:
        - wert
    PI_31004__stammdaten__RECHNUNG__gesamtbrutto:
      type: object
      properties:
        wert:
          $ref: '../../../bo4e/fields/com/Betrag/wert.yaml#/components/schemas/wert'
          x-edifact-segment:
            - SG50.MOA+77
      required:
        - wert
    PI_31004__stammdaten__RECHNUNG__rechnungsperiode:
      type: object
      properties:
        enddatum:
          $ref: '../../../bo4e/fields/com/Zeitraum/enddatum.yaml#/components/schemas/enddatum'
          x-edifact-segment:
            - DTM+156
        startdatum:
          $ref: '../../../bo4e/fields/com/Zeitraum/startdatum.yaml#/components/schemas/startdatum'
          x-edifact-segment:
            - DTM+155
    PI_31004__stammdaten__RECHNUNG__steuerbetraege:
      type: object
      properties:
        basiswert:
          $ref: '../../../bo4e/fields/com/Steuerbetrag/basiswert.yaml#/components/schemas/basiswert'
          x-edifact-segment:
            - SG52.TAX+7+VAT.MOA+125
        basiswertVorausbezahlt:
          $ref: '../../../bo4e/fields/com/Steuerbetrag/basiswertVorausbezahlt.yaml#/components/schemas/basiswertVorausbezahlt'
          x-edifact-segment:
            - SG52.TAX+7+VAT.MOA+113
        steuerkennzeichen:
          $ref: '../../../bo4e/fields/com/Steuerbetrag/steuerkennzeichen.yaml#/components/schemas/steuerkennzeichen'
          x-edifact-segment:
            - SG52.TAX+7+VAT
        steuerwert:
          $ref: '../../../bo4e/fields/com/Steuerbetrag/steuerwert.yaml#/components/schemas/steuerwert'
          x-edifact-segment:
            - SG52.TAX+7+VAT.MOA+161
        steuerwertVorausbezahlt:
          $ref: '../../../bo4e/fields/com/Steuerbetrag/steuerwertVorausbezahlt.yaml#/components/schemas/steuerwertVorausbezahlt'
          x-edifact-segment:
            - SG52.TAX+7+VAT.MOA+115
      required:
        - basiswert
        - steuerkennzeichen
        - steuerwert
    PI_31004__stammdaten__RECHNUNG__vorausgezahlt:
      type: object
      properties:
        wert:
          $ref: '../../../bo4e/fields/com/Betrag/wert.yaml#/components/schemas/wert'
          x-edifact-segment:
            - SG50.MOA+113
    PI_31004__stammdaten__RECHNUNG__vorlaeufigerAbrechnungszeitraum:
      type: object
      properties:
        enddatum:
          $ref: '../../../bo4e/fields/com/Zeitraum/enddatum.yaml#/components/schemas/enddatum'
          x-edifact-segment:
            - DTM+Z43
        startdatum:
          $ref: '../../../bo4e/fields/com/Zeitraum/startdatum.yaml#/components/schemas/startdatum'
          x-edifact-segment:
            - DTM+Z42
    PI_31004__stammdaten__RECHNUNG__zuZahlen:
      type: object
      properties:
        wert:
          $ref: '../../../bo4e/fields/com/Betrag/wert.yaml#/components/schemas/wert'
          x-edifact-segment:
            - SG50.MOA+9
      required:
        - wert
    PI_31004__stammdaten__STEUERBARE_RESSOURCE:
      type: object
      properties:
        ressourcenId:
          $ref: '../../../bo4e/fields/bo/SteuerbareRessource/ressourcenId.yaml#/components/schemas/ressourcenId'
          x-edifact-segment:
            - SG2.NAD+DP.LOC+172
      required:
        - ressourcenId
    PI_31004__stammdaten__TECHNISCHE_RESSOURCE:
      type: object
      properties:
        ressourcenId:
          $ref: '../../../bo4e/fields/bo/TechnischeRessource/ressourcenId.yaml#/components/schemas/ressourcenId'
          x-edifact-segment:
            - SG2.NAD+DP.LOC+172
      required:
        - ressourcenId
    PI_31004__transaktionsdaten:
      type: object
      properties:
        absender:
          $ref: '#/components/schemas/PI_31004__transaktionsdaten__absender'
        dokumentennummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/dokumentennummer.yaml#/components/schemas/dokumentennummer'
          x-edifact-segment:
            - 'BGM+[457|Z25]'
        empfaenger:
          $ref: '#/components/schemas/PI_31004__transaktionsdaten__empfaenger'
        nachrichtenreferenznummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtenreferenznummer.yaml#/components/schemas/nachrichtenreferenznummer'
          x-edifact-segment:
            - UNH
        pruefidentifikator:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/pruefidentifikator.yaml#/components/schemas/pruefidentifikator'
          x-edifact-segment:
            - SG1.RFF+Z13
      required:
        - absender
        - dokumentennummer
        - empfaenger
        - nachrichtenreferenznummer
        - pruefidentifikator
    PI_31004__transaktionsdaten__absender:
      type: object
      properties:
        ansprechpartner:
          $ref: '#/components/schemas/PI_31004__transaktionsdaten__absender__ansprechpartner'
        name1:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/name1.yaml#/components/schemas/name1'
          x-edifact-segment:
            - SG2.NAD+MS
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+MS
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+MS
        steuernummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/steuernummer.yaml#/components/schemas/steuernummer'
          x-edifact-segment:
            - SG2.NAD+MS.SG3.RFF
        umsatzsteuerId:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/umsatzsteuerId.yaml#/components/schemas/umsatzsteuerId'
          x-edifact-segment:
            - SG2.NAD+MS.SG3.RFF
      required:
        - ansprechpartner
        - name1
        - rollencodenummer
        - rollencodetyp
        - steuernummer
        - umsatzsteuerId
    PI_31004__transaktionsdaten__absender__ansprechpartner:
      type: object
      properties:
        nachname:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/nachname.yaml#/components/schemas/nachname'
          x-edifact-segment:
            - SG2.NAD+MS.SG5.CTA+IC
      required:
        - nachname
    PI_31004__transaktionsdaten__empfaenger:
      type: object
      properties:
        name1:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/name1.yaml#/components/schemas/name1'
          x-edifact-segment:
            - SG2.NAD+MR
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+MR
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+MR
        steuernummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/steuernummer.yaml#/components/schemas/steuernummer'
          x-edifact-segment:
            - SG2.NAD+MR.SG3.RFF
        umsatzsteuerId:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/umsatzsteuerId.yaml#/components/schemas/umsatzsteuerId'
          x-edifact-segment:
            - SG2.NAD+MR.SG3.RFF
      required:
        - name1
        - rollencodenummer
        - rollencodetyp
        - steuernummer
        - umsatzsteuerId
