openapi: 3.1.0
info:
  title: PI_33001
  version: '202510'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_33001:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_33001__stammdaten'
      required:
        - stammdaten
    PI_33001__stammdaten:
      type: object
      properties:
        AVIS:
          type: array
          items:
            $ref: '#/components/schemas/PI_33001__stammdaten__AVIS'
      required:
        - AVIS
    PI_33001__stammdaten__AVIS:
      type: object
      properties:
        avisNummer:
          $ref: '../../../bo4e/fields/bo/Avis/avisNummer.yaml#/components/schemas/avisNummer'
          x-edifact-segment:
            - BGM+481
        avisTyp:
          $ref: '../../../bo4e/fields/bo/Avis/avisTyp.yaml#/components/schemas/avisTyp'
          x-edifact-segment:
            - BGM+481
        positionen:
          type: array
          items:
            $ref: '#/components/schemas/PI_33001__stammdaten__AVIS__positionen'
        zuZahlen:
          $ref: '#/components/schemas/PI_33001__stammdaten__AVIS__zuZahlen'
      required:
        - avisNummer
        - avisTyp
        - positionen
        - zuZahlen
    PI_33001__stammdaten__AVIS__positionen:
      type: object
      properties:
        gesamtBrutto:
          $ref: '#/components/schemas/PI_33001__stammdaten__AVIS__positionen__gesamtBrutto'
        istSelbstausgestellt:
          $ref: '../../../bo4e/fields/com/Avisposition/istSelbstausgestellt.yaml#/components/schemas/istSelbstausgestellt'
          x-edifact-segment:
            - SG5.DOC
        istStorno:
          $ref: '../../../bo4e/fields/com/Avisposition/istStorno.yaml#/components/schemas/istStorno'
          x-edifact-segment:
            - SG5.DOC
        rechnungsDatum:
          $ref: '../../../bo4e/fields/com/Avisposition/rechnungsDatum.yaml#/components/schemas/rechnungsDatum'
          x-edifact-segment:
            - SG5.DOC.DTM+137
        rechnungsNummer:
          $ref: '../../../bo4e/fields/com/Avisposition/rechnungsNummer.yaml#/components/schemas/rechnungsNummer'
          x-edifact-segment:
            - SG5.DOC
        zuZahlen:
          $ref: '#/components/schemas/PI_33001__stammdaten__AVIS__positionen__zuZahlen'
      required:
        - gesamtBrutto
        - istSelbstausgestellt
        - istStorno
        - rechnungsDatum
        - rechnungsNummer
        - zuZahlen
    PI_33001__stammdaten__AVIS__positionen__gesamtBrutto:
      type: object
      properties:
        wert:
          $ref: '../../../bo4e/fields/com/Betrag/wert.yaml#/components/schemas/wert'
          x-edifact-segment:
            - SG5.DOC.MOA+12
      required:
        - wert
    PI_33001__stammdaten__AVIS__positionen__zuZahlen:
      type: object
      properties:
        wert:
          $ref: '../../../bo4e/fields/com/Betrag/wert.yaml#/components/schemas/wert'
          x-edifact-segment:
            - SG5.DOC.MOA+9
      required:
        - wert
    PI_33001__stammdaten__AVIS__zuZahlen:
      type: object
      properties:
        waehrung:
          $ref: '../../../bo4e/fields/com/Betrag/waehrung.yaml#/components/schemas/waehrung'
          x-edifact-segment:
            - SG4.CUX+2
        wert:
          $ref: '../../../bo4e/fields/com/Betrag/wert.yaml#/components/schemas/wert'
          x-edifact-segment:
            - MOA+12
      required:
        - waehrung
        - wert
