openapi: 3.1.0
info:
  title: PI_99999
  version: '202604'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_99999:
      type: object
      properties:
        masterData:
          $ref: '#/components/schemas/PI_99999__masterData'
      required:
      - masterData
    PI_99999__masterData:
      type: object
      properties:
        STATUS_REPORT:
          type: array
          items:
            $ref: '#/components/schemas/PI_99999__masterData__STATUS_REPORT'
      required:
      - STATUS_REPORT
    PI_99999__masterData__STATUS_REPORT:
      type: object
      properties:
        reviewDate:
          $ref: ../../../bo4e-en/fields/bo/StatusReport/reviewDate.yaml#/components/schemas/reviewDate
          x-edifact-segment:
          - SG2.RFF+ACE.DTM+171
        auditObject:
          $ref: ../../../bo4e-en/fields/bo/StatusReport/auditObject.yaml#/components/schemas/auditObject
          x-edifact-segment:
          - SG2.RFF+ACE
      required:
      - reviewDate
      - auditObject
