openapi: 3.1.0
info:
  title: PI_35004
  version: '202604'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: 39ae45d481e5cc3d4d7aae328a23a9751236156a
components:
  schemas:
    PI_35004:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_35004__stammdaten'
        transaktionsdaten:
          $ref: '#/components/schemas/PI_35004__transaktionsdaten'
      required:
        - stammdaten
        - transaktionsdaten
    PI_35004__stammdaten:
      type: object
      properties:
        AD_HOC_STEUERKANAL:
          type: array
          items:
            $ref: '#/components/schemas/PI_35004__stammdaten__AD_HOC_STEUERKANAL'
        ANFRAGE:
          type: array
          items:
            $ref: '#/components/schemas/PI_35004__stammdaten__ANFRAGE'
        LEISTUNGSKURVENDEFINITION:
          type: array
          items:
            $ref: '#/components/schemas/PI_35004__stammdaten__LEISTUNGSKURVENDEFINITION'
        MARKTLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_35004__stammdaten__MARKTLOKATION'
        MESSLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_35004__stammdaten__MESSLOKATION'
        NETZLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_35004__stammdaten__NETZLOKATION'
        SCHALTZEITDEFINITION:
          type: array
          items:
            $ref: '#/components/schemas/PI_35004__stammdaten__SCHALTZEITDEFINITION'
        STEUERBARE_RESSOURCE:
          type: array
          items:
            $ref: '#/components/schemas/PI_35004__stammdaten__STEUERBARE_RESSOURCE'
        TECHNISCHE_RESSOURCE:
          type: array
          items:
            $ref: '#/components/schemas/PI_35004__stammdaten__TECHNISCHE_RESSOURCE'
        WERTE_NACH_TYP2:
          type: array
          items:
            $ref: '#/components/schemas/PI_35004__stammdaten__WERTE_NACH_TYP2'
      required:
        - AD_HOC_STEUERKANAL
        - ANFRAGE
        - LEISTUNGSKURVENDEFINITION
        - MARKTLOKATION
        - MESSLOKATION
        - NETZLOKATION
        - SCHALTZEITDEFINITION
        - STEUERBARE_RESSOURCE
        - TECHNISCHE_RESSOURCE
        - WERTE_NACH_TYP2
    PI_35004__stammdaten__AD_HOC_STEUERKANAL:
      type: object
      properties:
        konfigurationsprodukt:
          $ref: '../../../bo4e/fields/bo/AdHocSteuerkanal/konfigurationsprodukt.yaml#/components/schemas/konfigurationsprodukt'
          x-edifact-segment:
            - SG27.LIN+Z66.PIA+5
      required:
        - konfigurationsprodukt
    PI_35004__stammdaten__ANFRAGE:
      type: object
      properties:
        anfragetyp:
          $ref: '../../../bo4e/fields/bo/Anfrage/anfragetyp.yaml#/components/schemas/anfragetyp'
          x-edifact-segment:
            - 'IMD++[Z55|Z64]'
      required:
        - anfragetyp
    PI_35004__stammdaten__LEISTUNGSKURVENDEFINITION:
      type: object
      properties:
        leistungskurven:
          type: array
          items:
            $ref: '#/components/schemas/PI_35004__stammdaten__LEISTUNGSKURVENDEFINITION__leistungskurven'
      required:
        - leistungskurven
    PI_35004__stammdaten__LEISTUNGSKURVENDEFINITION__leistungskurven:
      type: object
      properties:
        code:
          $ref: '../../../bo4e/fields/com/Leistungskurve/code.yaml#/components/schemas/code'
          x-edifact-segment:
            - SG27.LIN+Z65.SG28.CCI+Z53
        konfigurationsprodukt:
          $ref: '../../../bo4e/fields/com/Leistungskurve/konfigurationsprodukt.yaml#/components/schemas/konfigurationsprodukt'
          x-edifact-segment:
            - SG27.LIN+Z65.PIA+5
      required:
        - code
        - konfigurationsprodukt
    PI_35004__stammdaten__MARKTLOKATION:
      type: object
      properties:
        marktlokationsId:
          $ref: '../../../bo4e/fields/bo/Marktlokation/marktlokationsId.yaml#/components/schemas/marktlokationsId'
          x-edifact-segment:
            - SG11.NAD+DP.LOC+172
      required:
        - marktlokationsId
    PI_35004__stammdaten__MESSLOKATION:
      type: object
      properties:
        messlokationsId:
          $ref: '../../../bo4e/fields/bo/Messlokation/messlokationsId.yaml#/components/schemas/messlokationsId'
          x-edifact-segment:
            - SG11.NAD+DP.LOC+172
      required:
        - messlokationsId
    PI_35004__stammdaten__NETZLOKATION:
      type: object
      properties:
        netzlokationsId:
          $ref: '../../../bo4e/fields/bo/Netzlokation/netzlokationsId.yaml#/components/schemas/netzlokationsId'
          x-edifact-segment:
            - SG11.NAD+DP.LOC+172
      required:
        - netzlokationsId
    PI_35004__stammdaten__SCHALTZEITDEFINITION:
      type: object
      properties:
        schaltzeiten:
          type: array
          items:
            $ref: '#/components/schemas/PI_35004__stammdaten__SCHALTZEITDEFINITION__schaltzeiten'
      required:
        - schaltzeiten
    PI_35004__stammdaten__SCHALTZEITDEFINITION__schaltzeiten:
      type: object
      properties:
        code:
          $ref: '../../../bo4e/fields/com/Schaltzeit/code.yaml#/components/schemas/code'
          x-edifact-segment:
            - SG27.LIN+Z64.SG28.CCI+Z52
        konfigurationsprodukt:
          $ref: '../../../bo4e/fields/com/Schaltzeit/konfigurationsprodukt.yaml#/components/schemas/konfigurationsprodukt'
          x-edifact-segment:
            - SG27.LIN+Z64.PIA+5
      required:
        - code
        - konfigurationsprodukt
    PI_35004__stammdaten__STEUERBARE_RESSOURCE:
      type: object
      properties:
        ressourcenId:
          $ref: '../../../bo4e/fields/bo/SteuerbareRessource/ressourcenId.yaml#/components/schemas/ressourcenId'
          x-edifact-segment:
            - SG11.NAD+DP.LOC+172
      required:
        - ressourcenId
    PI_35004__stammdaten__TECHNISCHE_RESSOURCE:
      type: object
      properties:
        ressourcenId:
          $ref: '../../../bo4e/fields/bo/TechnischeRessource/ressourcenId.yaml#/components/schemas/ressourcenId'
          x-edifact-segment:
            - SG11.NAD+DP.LOC+172
      required:
        - ressourcenId
    PI_35004__stammdaten__WERTE_NACH_TYP2:
      type: object
      properties:
        aenderungsmoeglichkeitKonfiguration:
          $ref: '../../../bo4e/fields/bo/WerteNachTyp2/aenderungsmoeglichkeitKonfiguration.yaml#/components/schemas/aenderungsmoeglichkeitKonfiguration'
          x-edifact-segment:
            - SG27.LIN+Z68.SG28.CCI+Z54
        aussteller:
          $ref: '#/components/schemas/PI_35004__stammdaten__WERTE_NACH_TYP2__aussteller'
        konfigurationsprodukt:
          $ref: '../../../bo4e/fields/bo/WerteNachTyp2/konfigurationsprodukt.yaml#/components/schemas/konfigurationsprodukt'
          x-edifact-segment:
            - SG27.LIN+Z68.PIA+5
        messprodukt:
          $ref: '../../../bo4e/fields/bo/WerteNachTyp2/messprodukt.yaml#/components/schemas/messprodukt'
          x-edifact-segment:
            - SG27.LIN+Z67.PIA+5
        schwellwerte:
          type: array
          items:
            $ref: '#/components/schemas/PI_35004__stammdaten__WERTE_NACH_TYP2__schwellwerte'
        zertifikatsNutzer:
          $ref: '#/components/schemas/PI_35004__stammdaten__WERTE_NACH_TYP2__zertifikatsNutzer'
        zieladresse:
          $ref: '#/components/schemas/PI_35004__stammdaten__WERTE_NACH_TYP2__zieladresse'
      required:
        - aenderungsmoeglichkeitKonfiguration
        - aussteller
        - konfigurationsprodukt
        - messprodukt
        - schwellwerte
        - zertifikatsNutzer
        - zieladresse
    PI_35004__stammdaten__WERTE_NACH_TYP2__aussteller:
      type: object
      properties:
        aussteller1:
          $ref: '../../../bo4e/fields/com/Aussteller/aussteller1.yaml#/components/schemas/aussteller1'
          x-edifact-segment:
            - SG27.LIN+Z68.FTX+Z24
        aussteller2:
          $ref: '../../../bo4e/fields/com/Aussteller/aussteller2.yaml#/components/schemas/aussteller2'
          x-edifact-segment:
            - SG27.LIN+Z68.FTX+Z24
        aussteller3:
          $ref: '../../../bo4e/fields/com/Aussteller/aussteller3.yaml#/components/schemas/aussteller3'
          x-edifact-segment:
            - SG27.LIN+Z68.FTX+Z24
        aussteller4:
          $ref: '../../../bo4e/fields/com/Aussteller/aussteller4.yaml#/components/schemas/aussteller4'
          x-edifact-segment:
            - SG27.LIN+Z68.FTX+Z24
        aussteller5:
          $ref: '../../../bo4e/fields/com/Aussteller/aussteller5.yaml#/components/schemas/aussteller5'
          x-edifact-segment:
            - SG27.LIN+Z68.FTX+Z24
      required:
        - aussteller1
        - aussteller2
        - aussteller3
        - aussteller4
        - aussteller5
    PI_35004__stammdaten__WERTE_NACH_TYP2__schwellwerte:
      type: object
      properties:
        konfigurationsprodukt:
          $ref: '../../../bo4e/fields/com/Schwellwert/konfigurationsprodukt.yaml#/components/schemas/konfigurationsprodukt'
          x-edifact-segment:
            - SG27.LIN+Z68.SG28.CCI+Z60
        obererSchwellwert:
          $ref: '../../../bo4e/fields/com/Schwellwert/obererSchwellwert.yaml#/components/schemas/obererSchwellwert'
          x-edifact-segment:
            - SG27.LIN+Z68.SG28.CCI+Z60
        untererSchwellwert:
          $ref: '../../../bo4e/fields/com/Schwellwert/untererSchwellwert.yaml#/components/schemas/untererSchwellwert'
          x-edifact-segment:
            - SG27.LIN+Z68.SG28.CCI+Z60
      required:
        - konfigurationsprodukt
        - obererSchwellwert
        - untererSchwellwert
    PI_35004__stammdaten__WERTE_NACH_TYP2__zertifikatsNutzer:
      type: object
      properties:
        zertifikatsNutzer1:
          $ref: '../../../bo4e/fields/com/ZertifikatsNutzer/zertifikatsNutzer1.yaml#/components/schemas/zertifikatsNutzer1'
          x-edifact-segment:
            - SG27.LIN+Z68.FTX+Z23
        zertifikatsNutzer2:
          $ref: '../../../bo4e/fields/com/ZertifikatsNutzer/zertifikatsNutzer2.yaml#/components/schemas/zertifikatsNutzer2'
          x-edifact-segment:
            - SG27.LIN+Z68.FTX+Z23
        zertifikatsNutzer3:
          $ref: '../../../bo4e/fields/com/ZertifikatsNutzer/zertifikatsNutzer3.yaml#/components/schemas/zertifikatsNutzer3'
          x-edifact-segment:
            - SG27.LIN+Z68.FTX+Z23
        zertifikatsNutzer4:
          $ref: '../../../bo4e/fields/com/ZertifikatsNutzer/zertifikatsNutzer4.yaml#/components/schemas/zertifikatsNutzer4'
          x-edifact-segment:
            - SG27.LIN+Z68.FTX+Z23
        zertifikatsNutzer5:
          $ref: '../../../bo4e/fields/com/ZertifikatsNutzer/zertifikatsNutzer5.yaml#/components/schemas/zertifikatsNutzer5'
          x-edifact-segment:
            - SG27.LIN+Z68.FTX+Z23
      required:
        - zertifikatsNutzer1
        - zertifikatsNutzer2
        - zertifikatsNutzer3
        - zertifikatsNutzer4
        - zertifikatsNutzer5
    PI_35004__stammdaten__WERTE_NACH_TYP2__zieladresse:
      type: object
      properties:
        zieladresse1:
          $ref: '../../../bo4e/fields/com/Zieladresse/zieladresse1.yaml#/components/schemas/zieladresse1'
          x-edifact-segment:
            - SG27.LIN+Z68.FTX+Z17
        zieladresse2:
          $ref: '../../../bo4e/fields/com/Zieladresse/zieladresse2.yaml#/components/schemas/zieladresse2'
          x-edifact-segment:
            - SG27.LIN+Z68.FTX+Z17
        zieladresse3:
          $ref: '../../../bo4e/fields/com/Zieladresse/zieladresse3.yaml#/components/schemas/zieladresse3'
          x-edifact-segment:
            - SG27.LIN+Z68.FTX+Z17
        zieladresse4:
          $ref: '../../../bo4e/fields/com/Zieladresse/zieladresse4.yaml#/components/schemas/zieladresse4'
          x-edifact-segment:
            - SG27.LIN+Z68.FTX+Z17
        zieladresse5:
          $ref: '../../../bo4e/fields/com/Zieladresse/zieladresse5.yaml#/components/schemas/zieladresse5'
          x-edifact-segment:
            - SG27.LIN+Z68.FTX+Z17
      required:
        - zieladresse1
        - zieladresse2
        - zieladresse3
        - zieladresse4
        - zieladresse5
    PI_35004__transaktionsdaten:
      type: object
      properties:
        absender:
          $ref: '#/components/schemas/PI_35004__transaktionsdaten__absender'
        beteiligterMarktpartner:
          $ref: '#/components/schemas/PI_35004__transaktionsdaten__beteiligterMarktpartner'
        dokumentennummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/dokumentennummer.yaml#/components/schemas/dokumentennummer'
          x-edifact-segment:
            - 'BGM+[Z74|Z82]'
        empfaenger:
          $ref: '#/components/schemas/PI_35004__transaktionsdaten__empfaenger'
        kategorie:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/kategorie.yaml#/components/schemas/kategorie'
          x-edifact-segment:
            - 'BGM+[Z74|Z82]'
        lieferdatum:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/lieferdatum.yaml#/components/schemas/lieferdatum'
          x-edifact-segment:
            - DTM+76
        nachrichtenReferenzBestellbestaetigung:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtenReferenzBestellbestaetigung.yaml#/components/schemas/nachrichtenReferenzBestellbestaetigung'
          x-edifact-segment:
            - SG1.RFF+Z42
        nachrichtendatum:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtendatum.yaml#/components/schemas/nachrichtendatum'
          x-edifact-segment:
            - DTM+137
        nachrichtenreferenznummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtenreferenznummer.yaml#/components/schemas/nachrichtenreferenznummer'
          x-edifact-segment:
            - UNH
        positionsnummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/positionsnummer.yaml#/components/schemas/positionsnummer'
          x-edifact-segment:
            - SG27.LIN+Z64
            - SG27.LIN+Z65
            - SG27.LIN+Z66
            - SG27.LIN+Z67
            - SG27.LIN+Z68
        pruefidentifikator:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/pruefidentifikator.yaml#/components/schemas/pruefidentifikator'
          x-edifact-segment:
            - SG1.RFF+Z13
        vorgangsReferenzBestellbestaetigung:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/vorgangsReferenzBestellbestaetigung.yaml#/components/schemas/vorgangsReferenzBestellbestaetigung'
          x-edifact-segment:
            - SG1.RFF+Z43
        vorgangsreferenznummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/vorgangsreferenznummer.yaml#/components/schemas/vorgangsreferenznummer'
          x-edifact-segment:
            - SG1.RFF+Z41
      required:
        - absender
        - beteiligterMarktpartner
        - dokumentennummer
        - empfaenger
        - kategorie
        - nachrichtenReferenzBestellbestaetigung
        - nachrichtendatum
        - nachrichtenreferenznummer
        - positionsnummer
        - pruefidentifikator
        - vorgangsReferenzBestellbestaetigung
        - vorgangsreferenznummer
    PI_35004__transaktionsdaten__absender:
      type: object
      properties:
        ansprechpartner:
          $ref: '#/components/schemas/PI_35004__transaktionsdaten__absender__ansprechpartner'
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG11.NAD+MS
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG11.NAD+MS
      required:
        - ansprechpartner
        - rollencodenummer
        - rollencodetyp
    PI_35004__transaktionsdaten__absender__ansprechpartner:
      type: object
      properties:
        eMailAdresse:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/eMailAdresse.yaml#/components/schemas/eMailAdresse'
          x-edifact-segment:
            - 'SG11.NAD+MS.SG14.CTA.COM+[EM|FX|TE|AJ|AL]'
        nachname:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/nachname.yaml#/components/schemas/nachname'
          x-edifact-segment:
            - SG11.NAD+MS.SG14.CTA
        rufnummern:
          type: array
          items:
            $ref: '#/components/schemas/PI_35004__transaktionsdaten__absender__ansprechpartner__rufnummern'
      required:
        - eMailAdresse
        - nachname
        - rufnummern
    PI_35004__transaktionsdaten__absender__ansprechpartner__rufnummern:
      type: object
      properties:
        nummerntyp:
          $ref: '../../../bo4e/fields/com/Rufnummer/nummerntyp.yaml#/components/schemas/nummerntyp'
          x-edifact-segment:
            - 'SG11.NAD+MS.SG14.CTA.COM+[EM|FX|TE|AJ|AL]'
        rufnummer:
          $ref: '../../../bo4e/fields/com/Rufnummer/rufnummer.yaml#/components/schemas/rufnummer'
          x-edifact-segment:
            - 'SG11.NAD+MS.SG14.CTA.COM+[EM|FX|TE|AJ|AL]'
      required:
        - nummerntyp
        - rufnummer
    PI_35004__transaktionsdaten__beteiligterMarktpartner:
      type: object
      properties:
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG11.NAD+DDM
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG11.NAD+DDM
      required:
        - rollencodenummer
        - rollencodetyp
    PI_35004__transaktionsdaten__empfaenger:
      type: object
      properties:
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG11.NAD+MR
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG11.NAD+MR
      required:
        - rollencodenummer
        - rollencodetyp
