openapi: 3.1.0
info:
  title: PI_25004
  version: '202604'
  x-bo4e-schema-version: 1.6.5
  x-bo4e-schema-sha: 95f07d974cf2dc738ca248b258d6589025614cb0
  x-templater-sha: 6e98aaa8818d7b01b16786b130d743ea57fa960a
components:
  schemas:
    PI_25004:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_25004__stammdaten'
        transaktionsdaten:
          $ref: '#/components/schemas/PI_25004__transaktionsdaten'
      required:
        - stammdaten
        - transaktionsdaten
    PI_25004__stammdaten:
      type: object
      properties:
        ZAEHLZEITDEFINITION:
          type: array
          items:
            $ref: '#/components/schemas/PI_25004__stammdaten__ZAEHLZEITDEFINITION'
      required:
        - ZAEHLZEITDEFINITION
    PI_25004__stammdaten__ZAEHLZEITDEFINITION:
      type: object
      properties:
        beginndatum:
          $ref: '../../../bo4e/fields/bo/Zaehlzeitdefinition/beginndatum.yaml#/components/schemas/beginndatum'
          x-edifact-segment:
            - SG5.IDE+24.DTM+157
        notwendigkeit:
          $ref: '../../../bo4e/fields/bo/Zaehlzeitdefinition/notwendigkeit.yaml#/components/schemas/notwendigkeit'
          x-edifact-segment:
            - SG5.IDE+24.STS+Z36
        version:
          $ref: '../../../bo4e/fields/bo/Zaehlzeitdefinition/version.yaml#/components/schemas/version'
          x-edifact-segment:
            - SG5.IDE+24.DTM+293
        zaehlzeiten:
          type: array
          items:
            $ref: '#/components/schemas/PI_25004__stammdaten__ZAEHLZEITDEFINITION__zaehlzeiten'
        zaehlzeitregister:
          type: array
          items:
            $ref: '#/components/schemas/PI_25004__stammdaten__ZAEHLZEITDEFINITION__zaehlzeitregister'
      required:
        - beginndatum
        - notwendigkeit
        - version
        - zaehlzeiten
        - zaehlzeitregister
    PI_25004__stammdaten__ZAEHLZEITDEFINITION__zaehlzeiten:
      type: object
      properties:
        beschreibungTyp:
          $ref: '../../../bo4e/fields/com/Zaehlzeit/beschreibungTyp.yaml#/components/schemas/beschreibungTyp'
          x-edifact-segment:
            - SG5.IDE+24.SG8.SEQ+Z42.SG9.CCI+Z39.CAV+ZD3
        code:
          $ref: '../../../bo4e/fields/com/Zaehlzeit/code.yaml#/components/schemas/code'
          x-edifact-segment:
            - SG5.IDE+24.SG8.SEQ+Z42.SG9.CCI+Z39
        ermittlungLeistungsmaximum:
          $ref: '../../../bo4e/fields/com/Zaehlzeit/ermittlungLeistungsmaximum.yaml#/components/schemas/ermittlungLeistungsmaximum'
          x-edifact-segment:
            - SG5.IDE+24.SG8.SEQ+Z42.SG9.CCI+Z39.CAV+ZD4
        haeufigkeit:
          $ref: '../../../bo4e/fields/com/Zaehlzeit/haeufigkeit.yaml#/components/schemas/haeufigkeit'
          x-edifact-segment:
            - SG5.IDE+24.SG8.SEQ+Z42.SG9.CCI+Z39.CAV+ZE0
        istBestellbar:
          $ref: '../../../bo4e/fields/com/Zaehlzeit/istBestellbar.yaml#/components/schemas/istBestellbar'
          x-edifact-segment:
            - SG5.IDE+24.SG8.SEQ+Z42.SG9.CCI+Z39.CAV+ZD7
        typ:
          $ref: '../../../bo4e/fields/com/Zaehlzeit/typ.yaml#/components/schemas/typ'
          x-edifact-segment:
            - SG5.IDE+24.SG8.SEQ+Z42.SG9.CCI+Z39.CAV+ZD3
        uebermittelbarkeit:
          $ref: '../../../bo4e/fields/com/Zaehlzeit/uebermittelbarkeit.yaml#/components/schemas/uebermittelbarkeit'
          x-edifact-segment:
            - SG5.IDE+24.SG8.SEQ+Z42.SG9.CCI+Z39.CAV+ZD5
      required:
        - code
        - haeufigkeit
        - uebermittelbarkeit
    PI_25004__stammdaten__ZAEHLZEITDEFINITION__zaehlzeitregister:
      type: object
      properties:
        register:
          $ref: '../../../bo4e/fields/com/Zaehlzeitregister/register.yaml#/components/schemas/register'
          x-edifact-segment:
            - SG5.IDE+24.SG8.SEQ+Z41.SG9.CCI+Z38
        schwachlastfaehig:
          $ref: '../../../bo4e/fields/com/Zaehlzeitregister/schwachlastfaehig.yaml#/components/schemas/schwachlastfaehig'
          x-edifact-segment:
            - SG5.IDE+24.SG8.SEQ+Z41.SG9.CCI+Z10
        zaehlzeitDefinition:
          $ref: '../../../bo4e/fields/com/Zaehlzeitregister/zaehlzeitDefinition.yaml#/components/schemas/zaehlzeitDefinition'
          x-edifact-segment:
            - SG5.IDE+24.SG8.SEQ+Z41.RFF+Z27
      required:
        - register
        - schwachlastfaehig
        - zaehlzeitDefinition
    PI_25004__transaktionsdaten:
      type: object
      properties:
        absender:
          $ref: '#/components/schemas/PI_25004__transaktionsdaten__absender'
        anfrageReferenz:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/anfrageReferenz.yaml#/components/schemas/anfrageReferenz'
          x-edifact-segment:
            - SG5.IDE+24.SG6.RFF+AGI
        dokumentennummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/dokumentennummer.yaml#/components/schemas/dokumentennummer'
          x-edifact-segment:
            - BGM+Z60
        empfaenger:
          $ref: '#/components/schemas/PI_25004__transaktionsdaten__empfaenger'
        nachrichtendatum:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtendatum.yaml#/components/schemas/nachrichtendatum'
          x-edifact-segment:
            - DTM+137
        nachrichtenreferenznummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/nachrichtenreferenznummer.yaml#/components/schemas/nachrichtenreferenznummer'
          x-edifact-segment:
            - UNH
        pruefidentifikator:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/pruefidentifikator.yaml#/components/schemas/pruefidentifikator'
          x-edifact-segment:
            - SG5.IDE+24.SG6.RFF+Z13
        vorgangsnummer:
          $ref: '../../../bo4e/fields/cdoc/Transaktionsdaten/vorgangsnummer.yaml#/components/schemas/vorgangsnummer'
          x-edifact-segment:
            - SG5.IDE+24
      required:
        - absender
        - anfrageReferenz
        - dokumentennummer
        - empfaenger
        - nachrichtendatum
        - nachrichtenreferenznummer
        - pruefidentifikator
        - vorgangsnummer
    PI_25004__transaktionsdaten__absender:
      type: object
      properties:
        ansprechpartner:
          $ref: '#/components/schemas/PI_25004__transaktionsdaten__absender__ansprechpartner'
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+MS
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+MS
      required:
        - ansprechpartner
        - rollencodenummer
        - rollencodetyp
    PI_25004__transaktionsdaten__absender__ansprechpartner:
      type: object
      properties:
        eMailAdresse:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/eMailAdresse.yaml#/components/schemas/eMailAdresse'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG3.CTA+IC.COM+[EM|FX|TE|AJ|AL]'
        nachname:
          $ref: '../../../bo4e/fields/bo/Ansprechpartner/nachname.yaml#/components/schemas/nachname'
          x-edifact-segment:
            - SG2.NAD+MS.SG3.CTA+IC
        rufnummern:
          type: array
          items:
            $ref: '#/components/schemas/PI_25004__transaktionsdaten__absender__ansprechpartner__rufnummern'
      required:
        - eMailAdresse
        - nachname
        - rufnummern
    PI_25004__transaktionsdaten__absender__ansprechpartner__rufnummern:
      type: object
      properties:
        nummerntyp:
          $ref: '../../../bo4e/fields/com/Rufnummer/nummerntyp.yaml#/components/schemas/nummerntyp'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG3.CTA+IC.COM+[EM|FX|TE|AJ|AL]'
        rufnummer:
          $ref: '../../../bo4e/fields/com/Rufnummer/rufnummer.yaml#/components/schemas/rufnummer'
          x-edifact-segment:
            - 'SG2.NAD+MS.SG3.CTA+IC.COM+[EM|FX|TE|AJ|AL]'
      required:
        - nummerntyp
        - rufnummer
    PI_25004__transaktionsdaten__empfaenger:
      type: object
      properties:
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG2.NAD+MR
        rollencodetyp:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodetyp.yaml#/components/schemas/rollencodetyp'
          x-edifact-segment:
            - SG2.NAD+MR
      required:
        - rollencodenummer
        - rollencodetyp
