openapi: 3.1.0
info:
  title: '[LF] START_VERSAND_ANTWORT_NNA'
  version: '202510'
  x-bpmn-source-sha: 3a7c8fc1
  x-bo4e-schema-version: 1.7.1
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    '[LF] START_VERSAND_ANTWORT_NNA':
      type: object
      required:
      - masterData
      - transactionData
      - additionalData
      properties:
        masterData:
          oneOf:
          - $ref: ../../event-bauteil-en/202510/REMADV/PI_33001.yaml#/components/schemas/PI_33001__masterData
          - $ref: ../../event-bauteil-en/202510/REMADV/PI_33002.yaml#/components/schemas/PI_33002__masterData
          - $ref: ../../event-bauteil-en/202510/REMADV/PI_33003.yaml#/components/schemas/PI_33003__masterData
          - $ref: ../../event-bauteil-en/202510/REMADV/PI_33004.yaml#/components/schemas/PI_33004__masterData
        transactionData:
          type: object
          required:
          - sender
          - receiver
          - category
          - messageDate
          - verificationIdentifier
          - sector
          properties:
            sender:
              type: object
              properties:
                roleCodeNumber:
                  $ref: ../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
            receiver:
              type: object
              properties:
                marketRole:
                  $ref: ../../bo4e-en/fields/bo/MarketParticipant/marketRole.yaml#/components/schemas/marketRole
                roleCodeNumber:
                  $ref: ../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
            category:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/category.yaml#/components/schemas/category
            messageDate:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/messageDate.yaml#/components/schemas/messageDate
            verificationIdentifier:
              enum:
              - '33001'
              - '33002'
              - '33003'
              - '33004'
              description: Pflichtfeld — bestimmt direkt die Antwort-Variante. Der Body-Wert routet den Versand-Prozess (T_-Gateway über ${pruefidentifikator}).
            sector:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/sector.yaml#/components/schemas/sector
        additionalData:
          type: object
          required:
          - processId
          - eventname
          properties:
            processId:
              type: string
            eventname:
              type: string
              const: START_VERSAND_ANTWORT_NNA
              default: START_DISPATCH_RESPONSE_NNA
