openapi: 3.1.0
info:
  title: '[MSB] START_BESTELLUNG_SDAE GAS'
  version: '202510'
  x-bpmn-source-sha: aa74db2c
  x-bo4e-schema-version: 1.7.1
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    '[MSB] START_BESTELLUNG_SDAE GAS':
      type: object
      required:
      - masterData
      - transactionData
      - additionalData
      properties:
        transactionData:
          type: object
          required:
          - sender
          - receiver
          - validFrom
          - category
          - sector
          - transactionReason
          - transactionReasonSupplement
          properties:
            sender:
              type: object
              properties:
                marketRole:
                  $ref: ../../bo4e-en/fields/bo/MarketParticipant/marketRole.yaml#/components/schemas/marketRole
                roleCodeNumber:
                  $ref: ../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
            receiver:
              type: object
              properties:
                marketRole:
                  $ref: ../../bo4e-en/fields/bo/MarketParticipant/marketRole.yaml#/components/schemas/marketRole
                roleCodeNumber:
                  $ref: ../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
            validFrom:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/validFrom.yaml#/components/schemas/validFrom
            category:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/category.yaml#/components/schemas/category
            sector:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/sector.yaml#/components/schemas/sector
            transactionReason:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/transactionReason.yaml#/components/schemas/transactionReason
            transactionReasonSupplement:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/transactionReasonSupplement.yaml#/components/schemas/transactionReasonSupplement
            verificationIdentifier:
              description: Wird dynamisch im Event-Prozess ermittelt (Sparte + Transaktionsgrund + Empfänger-Marktrolle). Ein vom Sender mitgegebener Wert wird ignoriert. Im Topic mögliche Prüfis — 44140.
              examples:
              - '44140'
        additionalData:
          type: object
          required:
          - processId
          - eventname
          properties:
            processId:
              type: string
            eventname:
              type: string
              const: START_BESTELLUNG_SDAE
              default: START_ORDER_SDAE
      x-pending-pruefis:
      - '44140'
