openapi: 3.1.0
info:
  title: '[NB] START_PREISBLATT'
  version: '202510'
  x-bpmn-source-sha: '72378213'
  x-bo4e-schema-version: 1.7.4
  x-templater-sha: 392a2eb2993418f8a5be64578c22568416e2d551
components:
  schemas:
    '[NB] START_PREISBLATT':
      type: object
      required:
      - masterData
      - transactionData
      - additionalData
      properties:
        masterData:
          oneOf:
          - $ref: ../../event-bauteil-en/202510/PRICAT/PI_27003.yaml#/components/schemas/PI_27003__masterData
        transactionData:
          type: object
          required:
          - sender
          - receiver
          - category
          - sector
          properties:
            sender:
              type: object
              properties:
                roleCodeNumber:
                  $ref: ../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
            receiver:
              type: object
              properties:
                roleCodeNumber:
                  $ref: ../../bo4e-en/fields/bo/MarketParticipant/roleCodeNumber.yaml#/components/schemas/roleCodeNumber
            category:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/category.yaml#/components/schemas/category
            sector:
              $ref: ../../bo4e-en/fields/cdoc/TransactionData/sector.yaml#/components/schemas/sector
            verificationIdentifier:
              description: Wird dynamisch im Event-Prozess ermittelt. Ein vom Sender mitgegebener Wert wird ignoriert. Im Topic mögliche Prüfis — 27003.
              examples:
              - '27003'
        additionalData:
          type: object
          required:
          - processId
          - eventname
          properties:
            processId:
              type: string
            eventname:
              type: string
              const: START_PREISBLATT
              default: START_PREISBLATT
