openapi: 3.1.0
info:
  title: PI_55630
  version: '202510'
  x-bo4e-schema-version: 1.6.5
  x-bo4e-schema-sha: 95f07d974cf2dc738ca248b258d6589025614cb0
  x-templater-sha: 6e98aaa8818d7b01b16786b130d743ea57fa960a
components:
  schemas:
    PI_55630:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55630__stammdaten'
      required:
        - stammdaten
    PI_55630__stammdaten:
      type: object
      properties:
        STEUERBARE_RESSOURCE:
          type: array
          items:
            $ref: '#/components/schemas/PI_55630__stammdaten__STEUERBARE_RESSOURCE'
        VERWENDUNGSZEITRAUM:
          type: array
          items:
            $ref: '#/components/schemas/PI_55630__stammdaten__VERWENDUNGSZEITRAUM'
      required:
        - STEUERBARE_RESSOURCE
        - VERWENDUNGSZEITRAUM
    PI_55630__stammdaten__STEUERBARE_RESSOURCE:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/SteuerbareRessource/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z62
        gueltigkeitszeitraum:
          $ref: '#/components/schemas/PI_55630__stammdaten__STEUERBARE_RESSOURCE__gueltigkeitszeitraum'
        marktrollen:
          type: array
          items:
            $ref: '#/components/schemas/PI_55630__stammdaten__STEUERBARE_RESSOURCE__marktrollen'
        ressourcenId:
          $ref: '../../../bo4e/fields/bo/SteuerbareRessource/ressourcenId.yaml#/components/schemas/ressourcenId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z19
      required:
        - datenqualitaet
        - gueltigkeitszeitraum
        - marktrollen
        - ressourcenId
    PI_55630__stammdaten__STEUERBARE_RESSOURCE__gueltigkeitszeitraum:
      type: object
      properties:
        zeitraumId:
          $ref: '../../../bo4e/fields/com/Zeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z62
      required:
        - zeitraumId
    PI_55630__stammdaten__STEUERBARE_RESSOURCE__marktrollen:
      type: object
      properties:
        marktrolle:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/marktrolle.yaml#/components/schemas/marktrolle'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z62.SG10.CCI+++ZB3.CAV+Z91
        messstellenbetreiberEigenschaft:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/messstellenbetreiberEigenschaft.yaml#/components/schemas/messstellenbetreiberEigenschaft'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z62.SG10.CCI+++ZB3.CAV+Z91
        rollencodenummer:
          $ref: '../../../bo4e/fields/bo/Marktteilnehmer/rollencodenummer.yaml#/components/schemas/rollencodenummer'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z62.SG10.CCI+++ZB3.CAV+Z91
      required:
        - marktrolle
        - messstellenbetreiberEigenschaft
        - rollencodenummer
    PI_55630__stammdaten__VERWENDUNGSZEITRAUM:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53]'
        verwendungAb:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungAb.yaml#/components/schemas/verwendungAb'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53].DTM+Z25'
        verwendungBis:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungBis.yaml#/components/schemas/verwendungBis'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53].DTM+Z26'
        zeitraumId:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53]'
      required:
        - datenqualitaet
        - verwendungAb
        - zeitraumId
