openapi: 3.1.0
info:
  title: PI_55110
  version: '202510'
  x-bo4e-schema-version: 1.6.5
  x-bo4e-schema-sha: 95f07d974cf2dc738ca248b258d6589025614cb0
  x-templater-sha: 6e98aaa8818d7b01b16786b130d743ea57fa960a
components:
  schemas:
    PI_55110:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55110__stammdaten'
      required:
        - stammdaten
    PI_55110__stammdaten:
      type: object
      properties:
        ENERGIELIEFERVERTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_55110__stammdaten__ENERGIELIEFERVERTRAG'
        MARKTLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_55110__stammdaten__MARKTLOKATION'
        VERWENDUNGSZEITRAUM:
          type: array
          items:
            $ref: '#/components/schemas/PI_55110__stammdaten__VERWENDUNGSZEITRAUM'
      required:
        - ENERGIELIEFERVERTRAG
        - MARKTLOKATION
        - VERWENDUNGSZEITRAUM
    PI_55110__stammdaten__ENERGIELIEFERVERTRAG:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Vertrag/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
            - SG4.IDE+24.SG12.NAD+Z09
        gueltigkeitszeitraum:
          $ref: '#/components/schemas/PI_55110__stammdaten__ENERGIELIEFERVERTRAG__gueltigkeitszeitraum'
        korrespondenzpartner:
          $ref: '#/components/schemas/PI_55110__stammdaten__ENERGIELIEFERVERTRAG__korrespondenzpartner'
        vertragspartner2:
          type: array
          items:
            $ref: '#/components/schemas/PI_55110__stammdaten__ENERGIELIEFERVERTRAG__vertragspartner2'
      required:
        - datenqualitaet
        - gueltigkeitszeitraum
        - korrespondenzpartner
        - vertragspartner2
    PI_55110__stammdaten__ENERGIELIEFERVERTRAG__gueltigkeitszeitraum:
      type: object
      properties:
        zeitraumId:
          $ref: '../../../bo4e/fields/com/Zeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04.RFF+Z46
            - SG4.IDE+24.SG12.NAD+Z09.RFF+Z46
      required:
        - zeitraumId
    PI_55110__stammdaten__ENERGIELIEFERVERTRAG__korrespondenzpartner:
      type: object
      properties:
        anrede:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/anrede.yaml#/components/schemas/anrede'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
        name1:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name1.yaml#/components/schemas/name1'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
        name2:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name2.yaml#/components/schemas/name2'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
        name3:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name3.yaml#/components/schemas/name3'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
        name4:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name4.yaml#/components/schemas/name4'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
        partneradresse:
          $ref: '#/components/schemas/PI_55110__stammdaten__ENERGIELIEFERVERTRAG__korrespondenzpartner__partneradresse'
      required:
        - anrede
        - name1
        - name2
        - name3
        - name4
        - partneradresse
    PI_55110__stammdaten__ENERGIELIEFERVERTRAG__korrespondenzpartner__partneradresse:
      type: object
      properties:
        hausnummer:
          $ref: '../../../bo4e/fields/com/Adresse/hausnummer.yaml#/components/schemas/hausnummer'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
        landescode:
          $ref: '../../../bo4e/fields/com/Adresse/landescode.yaml#/components/schemas/landescode'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
        ort:
          $ref: '../../../bo4e/fields/com/Adresse/ort.yaml#/components/schemas/ort'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
        ortsteil:
          $ref: '../../../bo4e/fields/com/Adresse/ortsteil.yaml#/components/schemas/ortsteil'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
        postfach:
          $ref: '../../../bo4e/fields/com/Adresse/postfach.yaml#/components/schemas/postfach'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
        postleitzahl:
          $ref: '../../../bo4e/fields/com/Adresse/postleitzahl.yaml#/components/schemas/postleitzahl'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
        strasse:
          $ref: '../../../bo4e/fields/com/Adresse/strasse.yaml#/components/schemas/strasse'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z04
      required:
        - hausnummer
        - landescode
        - ort
        - ortsteil
        - postfach
        - postleitzahl
        - strasse
    PI_55110__stammdaten__ENERGIELIEFERVERTRAG__vertragspartner2:
      type: object
      properties:
        anrede:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/anrede.yaml#/components/schemas/anrede'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z09
        geschaeftspartnerrolle:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/geschaeftspartnerrolle.yaml#/components/schemas/geschaeftspartnerrolle'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z09
        name1:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name1.yaml#/components/schemas/name1'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z09
        name2:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name2.yaml#/components/schemas/name2'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z09
        name3:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name3.yaml#/components/schemas/name3'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z09
        name4:
          $ref: '../../../bo4e/fields/bo/Geschaeftspartner/name4.yaml#/components/schemas/name4'
          x-edifact-segment:
            - SG4.IDE+24.SG12.NAD+Z09
      required:
        - anrede
        - geschaeftspartnerrolle
        - name1
        - name2
        - name3
        - name4
    PI_55110__stammdaten__MARKTLOKATION:
      type: object
      properties:
        marktlokationsId:
          $ref: '../../../bo4e/fields/bo/Marktlokation/marktlokationsId.yaml#/components/schemas/marktlokationsId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z16
      required:
        - marktlokationsId
    PI_55110__stammdaten__VERWENDUNGSZEITRAUM:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53]'
        verwendungAb:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungAb.yaml#/components/schemas/verwendungAb'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53].DTM+Z25'
        verwendungBis:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungBis.yaml#/components/schemas/verwendungBis'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53].DTM+Z26'
        zeitraumId:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53]'
      required:
        - datenqualitaet
        - verwendungAb
        - zeitraumId
