openapi: 3.1.0
info:
  title: PI_55051
  version: '202510'
  x-bo4e-schema-version: 1.6.5
  x-bo4e-schema-sha: 95f07d974cf2dc738ca248b258d6589025614cb0
  x-templater-sha: 6e98aaa8818d7b01b16786b130d743ea57fa960a
components:
  schemas:
    PI_55051:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55051__stammdaten'
      required:
        - stammdaten
    PI_55051__stammdaten:
      type: object
      properties:
        MESSLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_55051__stammdaten__MESSLOKATION'
        NETZNUTZUNGSVERTRAG:
          type: array
          items:
            $ref: '#/components/schemas/PI_55051__stammdaten__NETZNUTZUNGSVERTRAG'
      required:
        - MESSLOKATION
    PI_55051__stammdaten__MESSLOKATION:
      type: object
      properties:
        messlokationsId:
          $ref: '../../../bo4e/fields/bo/Messlokation/messlokationsId.yaml#/components/schemas/messlokationsId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z17
      required:
        - messlokationsId
    PI_55051__stammdaten__NETZNUTZUNGSVERTRAG:
      type: object
      properties:
        vertragsbeginn:
          $ref: '../../../bo4e/fields/bo/Vertrag/vertragsbeginn.yaml#/components/schemas/vertragsbeginn'
          x-edifact-segment:
            - SG4.IDE+24.DTM+92
        vertragsende:
          $ref: '../../../bo4e/fields/bo/Vertrag/vertragsende.yaml#/components/schemas/vertragsende'
          x-edifact-segment:
            - SG4.IDE+24.DTM+93
