openapi: 3.1.0
info:
  title: PI_55230
  version: '202510'
  x-bo4e-schema-version: 1.7.1
  x-bo4e-schema-sha: 559c00569530c9ff74ef104e035eadd88c5d4a54
  x-templater-sha: 3cf4d8497849ad9ec9ef89f2454ebe6f1f2f008f
components:
  schemas:
    PI_55230:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_55230__stammdaten'
      required:
        - stammdaten
    PI_55230__stammdaten:
      type: object
      properties:
        NETZLOKATION:
          type: array
          items:
            $ref: '#/components/schemas/PI_55230__stammdaten__NETZLOKATION'
        VERWENDUNGSZEITRAUM:
          type: array
          items:
            $ref: '#/components/schemas/PI_55230__stammdaten__VERWENDUNGSZEITRAUM'
      required:
        - NETZLOKATION
        - VERWENDUNGSZEITRAUM
    PI_55230__stammdaten__NETZLOKATION:
      type: object
      properties:
        abrechnungsdaten:
          type: array
          items:
            $ref: '#/components/schemas/PI_55230__stammdaten__NETZLOKATION__abrechnungsdaten'
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Netzlokation/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z71
        gueltigkeitszeitraum:
          $ref: '#/components/schemas/PI_55230__stammdaten__NETZLOKATION__gueltigkeitszeitraum'
        netzlokationsId:
          $ref: '../../../bo4e/fields/bo/Netzlokation/netzlokationsId.yaml#/components/schemas/netzlokationsId'
          x-edifact-segment:
            - SG4.IDE+24.SG5.LOC+Z18
      required:
        - abrechnungsdaten
        - datenqualitaet
        - gueltigkeitszeitraum
        - netzlokationsId
    PI_55230__stammdaten__NETZLOKATION__abrechnungsdaten:
      type: object
      properties:
        zahlerBlindarbeitLf:
          $ref: '../../../bo4e/fields/com/Netznutzungsabrechnungsdaten/zahlerBlindarbeitLf.yaml#/components/schemas/zahlerBlindarbeitLf'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z71.SG10.CCI+Z46
      required:
        - zahlerBlindarbeitLf
    PI_55230__stammdaten__NETZLOKATION__gueltigkeitszeitraum:
      type: object
      properties:
        zeitraumId:
          $ref: '../../../bo4e/fields/com/Zeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - SG4.IDE+24.SG8.SEQ+Z71
      required:
        - zeitraumId
    PI_55230__stammdaten__VERWENDUNGSZEITRAUM:
      type: object
      properties:
        datenqualitaet:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/datenqualitaet.yaml#/components/schemas/datenqualitaet'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53]'
        verwendungAb:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungAb.yaml#/components/schemas/verwendungAb'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53].DTM+Z25'
        verwendungBis:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/verwendungBis.yaml#/components/schemas/verwendungBis'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53].DTM+Z26'
        zeitraumId:
          $ref: '../../../bo4e/fields/bo/Verwendungszeitraum/zeitraumId.yaml#/components/schemas/zeitraumId'
          x-edifact-segment:
            - 'SG4.IDE+24.SG6.RFF+[Z49|Z53]'
      required:
        - datenqualitaet
        - verwendungAb
        - zeitraumId
