openapi: 3.1.0
info:
  title: PI_13028
  version: '202604'
  x-bo4e-schema-version: 1.7.0
  x-bo4e-schema-sha: 142c432f893bfc68216d5491b012102c2b879bc5
  x-templater-sha: c7b88c733e93fe4ee423d52cffa2cd8f312574ea
components:
  schemas:
    PI_13028:
      type: object
      properties:
        stammdaten:
          $ref: '#/components/schemas/PI_13028__stammdaten'
      required:
        - stammdaten
    PI_13028__stammdaten:
      type: object
      properties:
        ENERGIEMENGE:
          type: array
          items:
            $ref: '#/components/schemas/PI_13028__stammdaten__ENERGIEMENGE'
      required:
        - ENERGIEMENGE
    PI_13028__stammdaten__ENERGIEMENGE:
      type: object
      properties:
        energieverbrauch:
          type: array
          items:
            $ref: '#/components/schemas/PI_13028__stammdaten__ENERGIEMENGE__energieverbrauch'
        konfiguration:
          $ref: '../../../bo4e/fields/bo/Energiemenge/konfiguration.yaml#/components/schemas/konfiguration'
          x-edifact-segment:
            - SG5.NAD+DP.SG6.LOC+172
        lokationsId:
          $ref: '../../../bo4e/fields/bo/Energiemenge/lokationsId.yaml#/components/schemas/lokationsId'
          x-edifact-segment:
            - SG5.NAD+DP.SG6.LOC+172
      required:
        - energieverbrauch
        - konfiguration
        - lokationsId
    PI_13028__stammdaten__ENERGIEMENGE__energieverbrauch:
      type: object
      properties:
        enddatum:
          $ref: '../../../bo4e/fields/com/Verbrauch/enddatum.yaml#/components/schemas/enddatum'
          x-edifact-segment:
            - SG5.NAD+DP.SG6.LOC+172.SG9.LIN.SG10.QTY.DTM+164
        messwertstatus:
          $ref: '../../../bo4e/fields/com/Verbrauch/messwertstatus.yaml#/components/schemas/messwertstatus'
          x-edifact-segment:
            - SG5.NAD+DP.SG6.LOC+172.SG9.LIN.SG10.QTY
        obiskennzahl:
          $ref: '../../../bo4e/fields/com/Verbrauch/obiskennzahl.yaml#/components/schemas/obiskennzahl'
          x-edifact-segment:
            - SG5.NAD+DP.SG6.LOC+172.SG9.LIN.PIA+5
        position:
          $ref: '../../../bo4e/fields/com/Verbrauch/position.yaml#/components/schemas/position'
          x-edifact-segment:
            - SG5.NAD+DP.SG6.LOC+172.SG9.LIN
        startdatum:
          $ref: '../../../bo4e/fields/com/Verbrauch/startdatum.yaml#/components/schemas/startdatum'
          x-edifact-segment:
            - SG5.NAD+DP.SG6.LOC+172.SG9.LIN.SG10.QTY.DTM+163
        wert:
          $ref: '../../../bo4e/fields/com/Verbrauch/wert.yaml#/components/schemas/wert'
          x-edifact-segment:
            - SG5.NAD+DP.SG6.LOC+172.SG9.LIN.SG10.QTY
      required:
        - enddatum
        - messwertstatus
        - obiskennzahl
        - position
        - startdatum
        - wert
